# XDF Analyzer

Converts multi-stream XDF recordings into merged, analysis-ready CSVs. Two EmotiBit devices (Commander `_C`, Intelligence Support `_IS`) and a Neon eye tracker are exported from each XDF file, aligned by timestamp, labelled with video-reliability blocks, then joined with per-block survey scores.

## 1. Imports

In [28]:
import pyxdf
import pandas as pd
import numpy as np
from datetime import datetime
import os
import glob
import re

---

## 2. Core Functions

### Stream Export

Reads an XDF file and writes each stream to a separate CSV. Device source IDs determine the filename suffix: `_C` for Commander (`MD-V5-0001023`), `_I` for Intelligence Support (`MD-V6-0000405`).

In [29]:
def export_streams_to_csv(streams, output_dir="exported_streams"):

    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    exported_files = []
    for idx, stream in enumerate(streams):
        # Get stream metadata
        stream_name = stream['info']['name'][0]
        if stream_name == 'Keyboard':
            continue
        source_id = stream['info'].get('source_id', ['Unknown'])[0]
        if source_id is None:
            source_id = "Unknown"

        if source_id == "MD-V5-0001023":
            filename = f"{stream_name}_C.csv"
        elif source_id == "MD-V6-0000405":
            filename = f"{stream_name}_I.csv"
        else:
            filename = f"{stream_name}.csv"
        filepath = os.path.join(output_dir, filename)

        # Get data and timestamps
        data = stream['time_series']
        timestamps = stream['time_stamps']

        # Skip streams with no data
        if len(data) == 0:
            print(f"Skipping stream {idx} ({stream_name}): No data")
            continue

        # Convert data to numpy array if it's not already
        if not isinstance(data, np.ndarray):
            data = np.array(data)

        # Special handling for Neon Companion stream - export all channels with proper labels
        if "Neon" in stream_name and "Companion" in stream_name:
            # Build channel labels using label + eye suffix to disambiguate left/right duplicates
            channel_labels = []
            try:
                desc = stream['info'].get('desc')
                if desc and len(desc) > 0 and desc[0] is not None and isinstance(desc[0], dict):
                    channels_info = desc[0].get('channels')
                    if channels_info and len(channels_info) > 0 and channels_info[0] is not None:
                        channel_list = channels_info[0].get('channel', [])
                        for i, ch in enumerate(channel_list):
                            if isinstance(ch, dict) and 'label' in ch:
                                label = ch['label'][0] if isinstance(ch['label'], list) else ch['label']
                                eye = ch.get('eye')
                                if isinstance(eye, list):
                                    eye = eye[0] if eye else None
                                # Append eye suffix for per-eye channels to avoid duplicate column names
                                if eye and eye in ('left', 'right'):
                                    label = f"{label}_{eye}"
                                channel_labels.append(label)
                            else:
                                channel_labels.append(f'channel_{i}')
            except (AttributeError, KeyError, TypeError):
                pass

            # Pad with generic names if metadata doesn't cover all data channels
            while len(channel_labels) < data.shape[1]:
                channel_labels.append(f'channel_{len(channel_labels)}')

            # Create DataFrame with all channels
            df_dict = {'timestamp': timestamps}
            for i, label in enumerate(channel_labels):
                df_dict[label] = data[:, i]

            df = pd.DataFrame(df_dict)
            print(f"Exported Neon stream with {len(channel_labels)} channels: {', '.join(channel_labels)}")

        # Regular handling for other streams
        elif data.ndim == 1:
            # Single channel data
            df = pd.DataFrame({
                'timestamp': timestamps,
                'value': data
            })
        else:
            # Multi-channel data
            channel_count = data.shape[1] if len(data.shape) > 1 else 1
            df_dict = {'timestamp': timestamps}

            if channel_count == 1:
                # Treat as single channel even if it's 2D with 1 column
                df_dict['value'] = data.flatten()
            else:
                # Get channel labels if available (with safer handling)
                channel_labels = []
                try:
                    desc = stream['info'].get('desc')
                    if desc and len(desc) > 0 and desc[0] is not None and isinstance(desc[0], dict):
                        channels_info = desc[0].get('channels')
                        if channels_info and len(channels_info) > 0 and channels_info[0] is not None:
                            channel_list = channels_info[0].get('channel', [])
                            if channel_list:
                                for i in range(channel_count):
                                    if i < len(channel_list):
                                        label = channel_list[i].get('label', [f'channel_{i}'])
                                        if isinstance(label, list):
                                            label = label[0] if label else f'channel_{i}'
                                        channel_labels.append(label)
                                    else:
                                        channel_labels.append(f'channel_{i}')
                            else:
                                channel_labels = [f'channel_{i}' for i in range(channel_count)]
                        else:
                            channel_labels = [f'channel_{i}' for i in range(channel_count)]
                    else:
                        channel_labels = [f'channel_{i}' for i in range(channel_count)]
                except (AttributeError, KeyError, TypeError):
                    channel_labels = [f'channel_{i}' for i in range(channel_count)]

                # Add channel data to DataFrame
                for i in range(channel_count):
                    df_dict[channel_labels[i]] = data[:, i]

            df = pd.DataFrame(df_dict)

        # Export to CSV
        df.to_csv(filepath, index=False)
        exported_files.append(filepath)

        print(f"Exported stream {idx} ({stream_name}) to {filepath}")
        print(f"  Source ID: {source_id}")
        print(f"  Data shape: {data.shape}")
        print(f"  Sample count: {len(timestamps)}")
        if "Neon" in stream_name:
            print(f"  First timestamp: {timestamps[0]}")
        print()

    print(f"Successfully exported {len(exported_files)} streams to {output_dir}/")
    return exported_files

### Data Merging

`merge_csv_files` uses `PPG_GRN_C.csv` as the time base and nearest-timestamp joins (±21 ms) all other streams. Neon eye-tracking data is aggregated from 200 Hz → 25 Hz before merging. `_label_video_condition` is a standalone helper that applies the same video-segment labelling logic used inline by `merge_csv_files`.

In [30]:
def merge_csv_files(input_dir, output_path="merged_data.csv", use_ffill=True, tolerance=0.021, participant_id=None, condition=None, video_condition=None):
    """
    Merge CSV files using PPG_GRN_C as base, with nearest timestamp matching.

    Parameters:
    - input_dir: Directory containing CSV files
    - output_path: Path for the merged output file
    - use_ffill: Whether to forward fill missing values
    - tolerance: Maximum time difference for matching (seconds, default 0.021 = 21ms)
    - participant_id: ID to add as the first column in the output (optional)
    - condition: Condition to add as the second column in the output (optional)
    - video_condition: Video condition (1-6) for labeling Reliability sequences (optional)
    """
    import glob

    VIDEO_ORDERS = {
        1: ('LL', 'HH', 'M'),
        2: ('LL', 'M', 'HH'),
        3: ('HH', 'LL', 'M'),
        4: ('HH', 'M', 'LL'),
        5: ('M', 'LL', 'HH'),
        6: ('M', 'HH', 'LL')
    }

    csv_files = glob.glob(os.path.join(input_dir, "*.csv"))
    if not csv_files:
        print(f"No CSV files found in {input_dir}")
        return None
    print(f"Found {len(csv_files)} CSV files to merge")

    ppg_base = None
    other_files = []
    datasync_file = None

    for file_path in csv_files:
        filename = os.path.basename(file_path)
        if "PPG_GRN" in filename and "_C.csv" in filename:
            ppg_base = file_path
            print(f"Found PPG_GRN base file: {filename}")
        elif "DataSyncMarker" in filename:
            datasync_file = file_path
        elif "Keyboard" in filename:
            pass
        else:
            other_files.append(file_path)

    if ppg_base is None:
        print("No PPG_GRN_C.csv file found to use as base!")
        return None

    try:
        base_df = pd.read_csv(ppg_base)
        base_filename = os.path.basename(ppg_base)
        print(f"Base file: {base_filename} ({len(base_df)} rows)")
        base_df['timestamp'] = base_df['timestamp'].round(3)

        merged_df = pd.DataFrame()
        if participant_id is not None:
            merged_df['ID'] = [participant_id] * len(base_df)
        if condition is not None:
            merged_df['Condition'] = [condition] * len(base_df)
        merged_df['timestamp'] = base_df['timestamp']

        if datasync_file is not None:
            try:
                datasync_df = pd.read_csv(datasync_file)
                datasync_filename = os.path.basename(datasync_file)

                if 'timestamp' in datasync_df.columns:
                    print(f"\nProcessing {datasync_filename} (adding after timestamp)...")
                    datasync_df['timestamp'] = datasync_df['timestamp'].round(3)
                    print(f"  File timestamps: {datasync_df['timestamp'].min():.3f} to {datasync_df['timestamp'].max():.3f}")
                    data_columns = [col for col in datasync_df.columns if col != 'timestamp']
                    datasync_df = datasync_df.sort_values('timestamp').reset_index(drop=True)

                    if 'channel_0' in data_columns:
                        print(f"  Expanding DataSyncMarker events into time ranges...")
                        print(f"  Original DataSyncMarker events: {len(datasync_df)} events")
                        marker_events = datasync_df[['timestamp', 'channel_0']].sort_values('timestamp').copy()
                        print(f"  DataSyncMarker events:")
                        for idx, row in marker_events.iterrows():
                            print(f"    t={row['timestamp']:.3f}, value={row['channel_0']}")

                        merged_df = pd.merge_asof(merged_df,
                                                  marker_events[['timestamp', 'channel_0']],
                                                  on='timestamp',
                                                  direction='backward')

                        # Compute Reliability labels from raw channel_0 (1=video, 2=no video)
                        if video_condition is not None and video_condition in VIDEO_ORDERS:
                            video_order = VIDEO_ORDERS[video_condition]
                            reliability_labels = []
                            video_segment_num = 0
                            prev_state = None
                            for state in merged_df['channel_0']:
                                state_int = int(state) if pd.notna(state) else None
                                if state_int != prev_state:
                                    if state_int == 1:
                                        video_segment_num += 1
                                    prev_state = state_int
                                if state_int == 1 and 1 <= video_segment_num <= len(video_order):
                                    reliability_labels.append(video_order[video_segment_num - 1])
                                elif state_int == 2:
                                    reliability_labels.append("No Video")
                                else:
                                    reliability_labels.append(None)
                            merged_df['Reliability'] = reliability_labels
                            print(f"  Added Reliability column using video condition {video_condition}: {video_order}")

                        # Keep DataSyncMarker as original binary values (1=video, 2=no video)
                        merged_df = merged_df.rename(columns={'channel_0': 'DataSyncMarker'})

                        print(f"  Added DataSyncMarker column after timestamp")
                        matched_count = merged_df['DataSyncMarker'].notna().sum()
                        print(f"    DataSyncMarker: {matched_count}/{len(merged_df)} matches ({100*matched_count/len(merged_df):.1f}%)")

                        value_counts = merged_df['DataSyncMarker'].value_counts()
                        print(f"  DataSyncMarker value distribution:")
                        for value, count in value_counts.items():
                            print(f"    {value}: {count} rows ({100*count/len(merged_df):.1f}%)")

                    remaining_columns = [col for col in data_columns if col != 'channel_0']
                    if remaining_columns:
                        remaining_df = datasync_df[['timestamp'] + remaining_columns].copy()
                        file_prefix = datasync_filename.replace('.csv', '').replace('stream_', '')
                        for col in remaining_columns:
                            remaining_df = remaining_df.rename(columns={col: f"{file_prefix}_{col}"})
                        temp_path = "temp_datasync_remaining.csv"
                        remaining_df.to_csv(temp_path, index=False)
                        other_files.append(temp_path)

            except Exception as e:
                print(f"Error processing DataSyncMarker file {datasync_file}: {str(e)}")

        base_prefix = base_filename.replace('.csv', '').replace('stream_', '')
        data_columns = [col for col in base_df.columns if col != 'timestamp']
        for col in data_columns:
            merged_df[f"{base_prefix}_{col}"] = base_df[col]
        merged_df = merged_df.sort_values('timestamp').reset_index(drop=True)

    except Exception as e:
        print(f"Error reading base file {ppg_base}: {str(e)}")
        return None

    print(f"Base PPG timestamps: {merged_df['timestamp'].min():.3f} to {merged_df['timestamp'].max():.3f}")

    for i, file_path in enumerate(other_files):
        try:
            filename = os.path.basename(file_path)
            if filename == "temp_datasync_remaining.csv":
                df = pd.read_csv(file_path)
                if os.path.exists(file_path):
                    os.remove(file_path)
            else:
                df = pd.read_csv(file_path)

            if 'timestamp' not in df.columns:
                print(f"Skipping {filename}: No 'timestamp' column found")
                continue

            df['timestamp'] = df['timestamp'].round(3)
            print(f"\nProcessing {filename}...")
            print(f"  File timestamps: {df['timestamp'].min():.3f} to {df['timestamp'].max():.3f}")

            if "Neon" in filename:
                neon_columns = [col for col in df.columns if col != 'timestamp']
                if not neon_columns:
                    print(f"Skipping {filename}: No data columns found")
                    continue
                print(f"  Downsampling {len(neon_columns)} Neon eye-tracking channels from 200Hz to 25Hz using aggregation...")
                min_time = df['timestamp'].min()
                max_time = df['timestamp'].max()
                bin_size = 0.04
                time_bins = np.round(np.arange(min_time, max_time + bin_size, bin_size), 3)
                df['time_bin'] = pd.cut(df['timestamp'], bins=time_bins, labels=time_bins[:-1], include_lowest=True)
                aggregated_data = []
                for bin_center in time_bins[:-1]:
                    bin_data = df[df['time_bin'] == bin_center]
                    if len(bin_data) > 0:
                        row_data = {'timestamp': bin_center}
                        for col in neon_columns:
                            valid_values = bin_data[col].dropna()
                            row_data[col] = valid_values.mean() if len(valid_values) > 0 else np.nan
                        aggregated_data.append(row_data)
                df = pd.DataFrame(aggregated_data)
                print(f"  After aggregation: {len(df)} samples ({len(neon_columns)} channels)")
                for col in neon_columns:
                    valid_count = df[col].notna().sum()
                    print(f"    {col}: {valid_count}/{len(df)} valid aggregated values ({100*valid_count/len(df):.1f}%)")

            data_columns = [col for col in df.columns if col != 'timestamp' and col != 'time_bin']
            df = df.sort_values('timestamp').reset_index(drop=True)
            df_for_merge = df.copy()

            if filename != "temp_datasync_remaining.csv":
                file_prefix = filename.replace('.csv', '').replace('stream_', '')
                for col in data_columns:
                    df_for_merge = df_for_merge.rename(columns={col: f"{file_prefix}_{col}"})

            # Track which columns are new after this merge
            cols_before = set(merged_df.columns)

            if filename == "temp_datasync_remaining.csv":
                print(f"  Expanding DataSyncMarker_channel_1 events into time ranges...")
                merged_df = pd.merge_asof(merged_df, df_for_merge, on='timestamp', direction='backward')
            else:
                merged_df = pd.merge_asof(merged_df, df_for_merge, on='timestamp', direction='nearest', tolerance=tolerance)

            new_cols = [col for col in merged_df.columns if col not in cols_before]
            print(f"  Added {len(new_cols)} column(s) from {filename}")
            for col in new_cols:
                matched_count = merged_df[col].notna().sum()
                print(f"    {col}: {matched_count}/{len(merged_df)} matches ({100*matched_count/len(merged_df):.1f}%)")

        except Exception as e:
            print(f"Error processing {filename}: {str(e)}")
            continue

    # Convert DataSyncMarker_channel_1 from UNIX time to Date and Time columns
    if 'DataSyncMarker_channel_1' in merged_df.columns:
        print(f"\nCalculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...")
        valid_sync_timestamps = merged_df['DataSyncMarker_channel_1'].notna()

        if valid_sync_timestamps.any():
            try:
                first_sync_idx = merged_df[valid_sync_timestamps].index[0]
                first_sync_unix = merged_df.loc[first_sync_idx, 'DataSyncMarker_channel_1']
                sync_emotibit_time = merged_df.loc[first_sync_idx, 'timestamp']

                if 1577836800 <= first_sync_unix <= 1893456000:
                    import pytz
                    utc_datetime = pd.to_datetime(first_sync_unix, unit='s', utc=True)
                    est_tz = pytz.timezone('US/Eastern')
                    initial_datetime_est = utc_datetime.tz_convert(est_tz)

                    print(f"Initial sync point at row {first_sync_idx}:")
                    print(f"  UNIX timestamp: {first_sync_unix}")
                    print(f"  EST time: {initial_datetime_est}")
                    print(f"  Corresponding EmotiBit timestamp: {sync_emotibit_time}")

                    time_diffs = merged_df['timestamp'] - sync_emotibit_time
                    calculated_datetimes = initial_datetime_est.tz_localize(None) + pd.to_timedelta(time_diffs, unit='s')

                    date_col = calculated_datetimes.dt.strftime('%Y-%m-%d')
                    time_col = calculated_datetimes.dt.strftime('%H:%M:%S.%f').str[:-3]

                    columns = list(merged_df.columns)
                    if 'Condition' in columns:
                        insert_pos = columns.index('Condition') + 1
                    elif 'ID' in columns:
                        insert_pos = columns.index('ID') + 1
                    else:
                        insert_pos = 0

                    columns.insert(insert_pos, 'Date')
                    columns.insert(insert_pos + 1, 'Time')
                    merged_df['Date'] = date_col
                    merged_df['Time'] = time_col
                    merged_df = merged_df[columns]

                    print(f"Successfully created Date and Time columns for all {len(merged_df)} rows (EST timezone)")
                    print(f"Duration: {(calculated_datetimes.max() - calculated_datetimes.min()).total_seconds():.2f} seconds")

                    start_idx = max(0, first_sync_idx - 2)
                    end_idx = min(len(merged_df), first_sync_idx + 3)
                    print(f"\nExample rows around sync point (row {first_sync_idx}):")
                    for i in range(start_idx, end_idx):
                        marker = " <- SYNC POINT" if i == first_sync_idx else ""
                        time_diff = merged_df.loc[i, 'timestamp'] - sync_emotibit_time
                        print(f"  Row {i}: EmotiBit={merged_df.loc[i, 'timestamp']:.3f}, diff={time_diff:+.3f}s, Time={time_col.iloc[i]}{marker}")
                else:
                    print(f"First DataSyncMarker value {first_sync_unix} is outside expected range (2020-2030)")

            except Exception as e:
                print(f"Error calculating Date and Time columns: {str(e)}")
        else:
            print("No valid DataSyncMarker_channel_1 values found")

    # Apply forward fill
    if use_ffill:
        print(f"\nApplying forward fill to missing values...")
        missing_before = merged_df.isnull().sum().sum()

        exclude_cols = ['timestamp', 'ID', 'Condition', 'Date', 'Time']
        data_columns = [col for col in merged_df.columns if col not in exclude_cols]
        merged_df[data_columns] = merged_df[data_columns].ffill()

        missing_after = merged_df.isnull().sum().sum()
        print(f"Missing values before ffill: {missing_before}")
        print(f"Missing values after ffill: {missing_after}")
        print(f"Filled {missing_before - missing_after} missing values")

    # Rename columns:
    #   - strip _value suffix
    #   - TEMP1_X -> TEMP_X
    #   - _I suffix -> _IS
    rename_map = {}
    for col in merged_df.columns:
        new_col = col
        if new_col.endswith('_value'):
            new_col = new_col[:-6]
        new_col = new_col.replace('TEMP1_', 'TEMP_')
        if new_col.endswith('_I'):
            new_col = new_col + 'S'
        if new_col != col:
            rename_map[col] = new_col
    merged_df = merged_df.rename(columns=rename_map)
    print(f"\nRenamed {len(rename_map)} columns: {rename_map}")

    # Reorder columns — Neon columns are detected dynamically and placed after EmotiBit columns
    neon_cols = [col for col in merged_df.columns if 'Neon' in col]
    desired_order = [
        'ID', 'Condition', 'Date', 'Time', 'timestamp',
        'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability',
        'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C',
    ] + neon_cols + [
        'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS'
    ]
    ordered_cols = [col for col in desired_order if col in merged_df.columns]
    remaining_cols = [col for col in merged_df.columns if col not in desired_order]
    if remaining_cols:
        print(f"Note: extra columns appended at end: {remaining_cols}")
    merged_df = merged_df[ordered_cols + remaining_cols]

    merged_df.to_csv(output_path, index=False)

    print(f"\n=== MERGE SUMMARY ===")
    print(f"Final dataset: {len(merged_df)} rows, {len(merged_df.columns)} columns")
    print(f"Columns: {list(merged_df.columns)}")
    print(f"Time range: {merged_df['timestamp'].min():.3f} to {merged_df['timestamp'].max():.3f}")
    print(f"Duration: {merged_df['timestamp'].max() - merged_df['timestamp'].min():.2f} seconds")
    if participant_id is not None:
        print(f"Participant ID: {participant_id}")
    if condition is not None:
        print(f"Condition: {condition}")
    if video_condition is not None:
        print(f"Video condition: {video_condition}")

    print(f"\n=== FINAL DATA COMPLETENESS ===")
    for col in merged_df.columns:
        if col not in ['timestamp', 'ID', 'Condition', 'Date', 'Time']:
            non_null_count = merged_df[col].notna().sum()
            completeness = (non_null_count / len(merged_df)) * 100
            print(f"{col}: {non_null_count}/{len(merged_df)} ({completeness:.1f}% complete)")

    return merged_df

In [31]:
def _label_video_condition(binary_sequence, video_condition):
    """
    Label binary sequence based on video condition and playback order.
    
    Parameters:
    - binary_sequence: Series of 1s and 2s (1=video playback, 2=no video)
    - video_condition: Integer 1-6 indicating which of the 6 video orders from ExperimentPlayer
    
    Returns:
    - Series with labels: "HH", "LL", "M", "No Video", or original binary values
    """

    video_orders = {
        1: ('LL', 'HH', 'M'),
        2: ('LL', 'M', 'HH'),
        3: ('HH', 'LL', 'M'),
        4: ('HH', 'M', 'LL'),
        5: ('M', 'LL', 'HH'),
        6: ('M', 'HH', 'LL')
    }

    if video_condition not in video_orders:
        return binary_sequence

    order = video_orders[video_condition]
    seq_array = binary_sequence.values
    labels = seq_array.astype(object)

    # Identify which video block each index belongs to by counting transitions into state 1
    video_segment_num = 0
    prev_state = None

    for i in range(len(seq_array)):
        val = seq_array[i]
        val_int = int(val) if pd.notna(val) else None

        # Detect transition into a new video block
        if val_int != prev_state:
            if val_int == 1:
                video_segment_num += 1
            prev_state = val_int

        if val_int == 2:
            labels[i] = "No Video"
        elif val_int == 1:
            if 1 <= video_segment_num <= len(order):
                labels[i] = order[video_segment_num - 1]
            else:
                labels[i] = val  # more segments than expected, leave as-is
        else:
            # Forward fill for NaN or unexpected values
            if i > 0:
                labels[i] = labels[i - 1]

    return pd.Series(labels, index=binary_sequence.index)

### Restart Fix (ID25, ID46)

Two participants' sessions were restarted partway through a block: the experiment
player always restarts from block 1, so the `DataSyncMarker` stream gets extra `==1`
runs (junk replays of earlier blocks) plus one `==3` "skip" marker per replayed block,
sandwiched between the aborted attempt at the restarted block and its real continuation.

`label_restart_participant` keeps every row — unlike the row-dropping approach used
earlier, the restart window is labeled `Reliability == "Restart"` in place. Block
numbering for the surviving runs is derived by counting only the *kept* `==1` runs;
junk runs inside the window never advance the counter, so the real block lands on the
correct `video_order` entry regardless of how many junk attempts preceded it.

`RESTART_FIXES` maps `participant_id -> restarted block number K` (1-indexed) and is
the single source of truth for which participants get this treatment.

In [32]:
VIDEO_ORDERS = {
    1: ('LL', 'HH', 'M'),
    2: ('LL', 'M', 'HH'),
    3: ('HH', 'LL', 'M'),
    4: ('HH', 'M', 'LL'),
    5: ('M', 'LL', 'HH'),
    6: ('M', 'HH', 'LL')
}

RESTART_FIXES = {25: 2, 46: 3}   # participant_id -> restarted block number K


def label_restart_participant(df, restart_block, video_condition):
    """
    Relabel Reliability for a participant whose session was restarted partway
    through block `restart_block` (1-indexed). Keeps every row: the aborted
    attempt, replay(s), and skip marker(s) are tagged "Restart"; block numbers
    for the surviving runs come from counting only the KEPT DataSyncMarker==1
    runs (junk runs inside the restart window never advance the counter).
    """
    df = df.reset_index(drop=True)

    if video_condition not in VIDEO_ORDERS:
        print(f"WARNING: unknown video_condition {video_condition}; cannot determine video order")
        return df
    order = VIDEO_ORDERS[video_condition]

    def _state(v):
        if pd.isna(v):
            return None
        if v != 0 and abs(v) < 1e-6:
            return 'err'
        return int(round(v))

    states = df['DataSyncMarker'].map(_state)

    # Contiguous runs as (state, start_pos, end_pos)
    runs = []
    run_state, run_start = states.iloc[0], 0
    for i in range(1, len(states)):
        s = states.iloc[i]
        if s != run_state:
            runs.append((run_state, run_start, i - 1))
            run_state, run_start = s, i
    runs.append((run_state, run_start, len(states) - 1))

    one_runs = [r for r in runs if r[0] == 1]
    three_runs = [r for r in runs if r[0] == 3]

    print(f"DataSyncMarker==1 runs: {len(one_runs)}")
    for idx, (s, start, end) in enumerate(one_runs, 1):
        print(f"  run {idx}: rows {start}-{end} (n={end - start + 1})")
    print(f"DataSyncMarker==3 runs: {len(three_runs)}")
    for idx, (s, start, end) in enumerate(three_runs, 1):
        print(f"  run {idx}: rows {start}-{end} (n={end - start + 1})")

    if len(one_runs) < restart_block:
        print(f"WARNING: expected at least {restart_block} DataSyncMarker==1 run(s), found {len(one_runs)} -- returning df unchanged")
        return df
    if not three_runs:
        print("WARNING: no DataSyncMarker==3 run found -- cannot determine restart window; returning df unchanged")
        return df

    delete_start = one_runs[restart_block - 1][1]
    delete_end = three_runs[-1][2]
    if delete_end <= delete_start:
        print(f"WARNING: delete_end ({delete_end}) <= delete_start ({delete_start}); restart window invalid -- returning df unchanged")
        return df
    print(f"Restart window: rows {delete_start}-{delete_end} (n={delete_end - delete_start + 1})")

    window = set(range(delete_start, delete_end + 1))
    labels = [None] * len(df)
    block_segment = 0
    prev_kept_state = None
    none_outside_window = 0
    other_outside_window = 0

    for i, s in enumerate(states):
        if i in window:
            labels[i] = "Restart"
            continue
        if s == 1:
            if prev_kept_state != 1:
                block_segment += 1
            labels[i] = order[block_segment - 1] if 1 <= block_segment <= len(order) else None
        elif s == 2:
            labels[i] = "No Video"
        else:
            labels[i] = None
            if s is None:
                none_outside_window += 1
            else:
                other_outside_window += 1
        prev_kept_state = s

    if block_segment != len(order):
        print(f"WARNING: counted {block_segment} kept DataSyncMarker==1 run(s) outside the window, expected {len(order)}")
    if none_outside_window:
        print(f"  ({none_outside_window} row(s) outside the window had no marker yet -- expected before the first block starts)")
    if other_outside_window:
        print(f"WARNING: {other_outside_window} row(s) outside the restart window had an unexpected non-1/2 DataSyncMarker state")

    df['Reliability'] = labels

    n_restart = sum(1 for l in labels if l == "Restart")
    print(f"Tagged {n_restart} row(s) as 'Restart'")

    return df

---

## 3. Configuration

Paths for input XDF files, metadata, survey scores, and output CSVs. Update these before running the pipeline below.

In [33]:
# --- Batch Configuration ---
xdf_folder        = "/Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data"   # directory containing [number]_C.xdf files
metadata_csv      = "/Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Metadata.csv" # CSV with columns: Team_ID, condition, video_condition
survey_csv        = "/Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/mdmt_physio.csv"   # CSV with columns: Team_ID, Role, Condition, Block, ...
physio_output_path = "all_participants_physio.csv"   # raw physiological data (no survey columns)
output_path       = "all_participants_combined.csv"  # final output with survey columns merged in

---

## 4. Pipeline Functions

### Batch Processing

Discovers all `[ID]_C.xdf` files, reads per-participant metadata, and orchestrates the full export → merge pipeline.

In [34]:
def process_batch(xdf_folder, metadata_csv, output_path="all_participants_combined.csv"):
    """
    Process all [number]_C.xdf files in xdf_folder in ascending ID order.

    For each file the matching row in metadata_csv (keyed on Team_ID) supplies
    condition and video_condition.  use_ffill=True and tolerance=0.021 are
    fixed and not read from the metadata.

    Intermediate outputs written to xdf_folder:
      <ID>_Data/             — per-participant stream CSVs
      merged_data_<ID>.csv   — per-participant merged CSV

    Parameters
    ----------
    xdf_folder   : str  — directory containing [number]_C.xdf files
    metadata_csv : str  — CSV with at least columns Team_ID, condition, video_condition
    output_path  : str  — path for the combined output CSV
    """
    meta = pd.read_csv(metadata_csv)
    meta['Team_ID'] = meta['Team_ID'].astype(int)
    meta = meta.set_index('Team_ID')
    dupes = meta.index[meta.index.duplicated()].unique().tolist()
    if dupes:
        print(f'WARNING: duplicate Team_IDs in metadata (keeping first): {dupes}')
        meta = meta[~meta.index.duplicated(keep='first')]

    # Discover [number]_C.xdf files and sort by numeric ID
    xdf_files = []
    for fname in os.listdir(xdf_folder):
        m = re.match(r'^(\d+)_C\.xdf$', fname)
        if m:
            xdf_files.append((int(m.group(1)), os.path.join(xdf_folder, fname)))
    xdf_files.sort()

    if not xdf_files:
        print(f"No [number]_C.xdf files found in {xdf_folder}")
        return None

    print(f"Found {len(xdf_files)} file(s): IDs {[pid for pid, _ in xdf_files]}")

    all_dfs = []

    for participant_id, xdf_path in xdf_files:
        if participant_id not in meta.index:
            print(f"\nWARNING: No metadata row for ID {participant_id} — skipping")
            continue

        row             = meta.loc[participant_id]
        condition       = row['condition']
        video_condition = int(row['video_condition'])

        print(f"\n{'='*60}")
        print(f"Processing ID {participant_id}  ({os.path.basename(xdf_path)})")
        print(f"  condition={condition}  video_condition={video_condition}")
        print('='*60)

        temp_dir     = os.path.join(xdf_folder, f"{participant_id}_Data")
        per_part_csv = os.path.join(xdf_folder, f"merged_data_{participant_id}.csv")

        try:
            streams, _ = pyxdf.load_xdf(xdf_path)
            export_streams_to_csv(streams, output_dir=temp_dir)
            df = merge_csv_files(
                input_dir       = temp_dir,
                output_path     = per_part_csv,
                use_ffill       = True,
                tolerance       = 0.021,
                participant_id  = participant_id,
                condition       = condition,
                video_condition = video_condition,
            )
            if df is not None:
                if participant_id in RESTART_FIXES:
                    restart_block = RESTART_FIXES[participant_id]
                    print(f"\nApplying restart fix for ID {participant_id} (restarted at block {restart_block})...")
                    df = label_restart_participant(df, restart_block, video_condition)
                    df.to_csv(per_part_csv, index=False)
                    print(f"Re-saved relabeled CSV: {per_part_csv}")
                all_dfs.append(df)
        except Exception as e:
            print(f"ERROR: participant {participant_id}: {e}")
            continue

    if not all_dfs:
        print("No data to combine.")
        return None

    combined = pd.concat(all_dfs, ignore_index=True)
    combined.to_csv(output_path, index=False)

    processed_ids = [int(df['ID'].iloc[0]) for df in all_dfs]
    print(f"\n{'='*60}")
    print(f"BATCH COMPLETE — {len(all_dfs)} participant(s): {processed_ids}")
    print(f"Total rows : {len(combined)}")
    print(f"Output     : {output_path}")
    print('='*60)

    return combined

### Reprocess a Single Participant

For fixing one participant (e.g. ID25) without re-running the whole batch. Reuses the
already-exported `<ID>_Data/` stream CSVs unless `force_reexport=True`. Patches the
result into `physio_output_path` by replacing that participant's old rows — you still
need to re-run Step 2 (`merge_survey_data`) afterward since block/survey data depends
on the corrected rows.

In [35]:
def reprocess_participant(participant_id, xdf_folder, metadata_csv, physio_output_path, force_reexport=False):
    """
    Re-run export+merge for a single participant and patch the result into
    the existing physio_output_path CSV (replacing that participant's old rows).
    """
    meta = pd.read_csv(metadata_csv)
    meta['Team_ID'] = meta['Team_ID'].astype(int)
    meta = meta.set_index('Team_ID')
    row             = meta.loc[participant_id]
    condition       = row['condition']
    video_condition = int(row['video_condition'])

    xdf_path     = os.path.join(xdf_folder, f"{participant_id}_C.xdf")
    temp_dir     = os.path.join(xdf_folder, f"{participant_id}_Data")
    per_part_csv = os.path.join(xdf_folder, f"merged_data_{participant_id}.csv")

    if force_reexport or not os.path.isdir(temp_dir):
        print(f"Exporting streams from {xdf_path}...")
        streams, _ = pyxdf.load_xdf(xdf_path)
        export_streams_to_csv(streams, output_dir=temp_dir)
    else:
        print(f"Using existing exported streams in {temp_dir} (force_reexport=False)")

    df = merge_csv_files(
        input_dir       = temp_dir,
        output_path     = per_part_csv,
        use_ffill       = True,
        tolerance       = 0.021,
        participant_id  = participant_id,
        condition       = condition,
        video_condition = video_condition,
    )
    if df is None:
        print(f"ERROR: merge_csv_files returned None for participant {participant_id}")
        return None

    if participant_id in RESTART_FIXES:
        restart_block = RESTART_FIXES[participant_id]
        print(f"\nApplying restart fix for ID {participant_id} (restarted at block {restart_block})...")
        df = label_restart_participant(df, restart_block, video_condition)
        df.to_csv(per_part_csv, index=False)
        print(f"Re-saved relabeled CSV: {per_part_csv}")

    physio = pd.read_csv(physio_output_path, low_memory=False)
    before = len(physio)
    physio = physio[physio['ID'] != participant_id]
    combined = pd.concat([physio, df], ignore_index=True)
    combined.to_csv(physio_output_path, index=False)
    print(f"\nPatched ID {participant_id} into {physio_output_path}: "
          f"{before} -> {len(combined)} total rows ({len(df)} rows for this participant)")

    return combined

### Survey Integration

Left-merges per-block survey scores into the physiological time-series. Block boundaries are detected from `DataSyncMarker` transitions; Commander scores get suffix `_C`, Intelligence Support scores get `_IS`.

In [50]:
def merge_survey_data(combined_df, survey_df):
    """
    Merge per-block survey scores into the physiological time-series DataFrame.

    Block derivation (per ID × Condition group):
      Scan DataSyncMarker in row order; each transition into 1.0 starts the
      next block. Block counter starts at 1; rows before the first 1.0 marker
      belong to Block 1.  Rows where Reliability == "Restart" (see
      label_restart_participant) are skipped entirely -- they neither count as
      a transition nor advance the "last seen state," and are tagged with
      Block = -1 so they never match a real survey block. This keeps block
      numbering correct for the surviving rows of a restarted participant
      (e.g. ID25, ID46) without needing any participant-specific branching
      here.  The temporary Block column is dropped from the output.

    Survey roles and column suffixes:
      "Commander"            → non-key columns suffixed _C
      "Intelligence Support" → non-key columns suffixed _IS

    Key columns (not suffixed): Team_ID, Role, Condition, Block, Participant_ID
    Join: combined_df[ID, Condition, Block] ↔ survey[Team_ID, Condition, Block]

    Video_Condition is coalesced from _C / _IS into a single column placed
    between DataSyncMarker_channel_1 and Reliability.

    The function is idempotent: any survey columns already present in
    combined_df (from a prior run) are dropped before merging, including
    _x/_y duplicates from previous bad runs.
    """
    KEY_COLS = {'Team_ID', 'Role', 'Condition', 'Block', 'Participant_ID'}
    ROLE_MAP = {'Commander': '_C', 'Intelligence Support': '_IS'}
    survey_val_cols = [c for c in survey_df.columns if c not in KEY_COLS]

    # Drop ALL variants of pre-existing survey columns (exact, _x, _y) so
    # re-runs on a previously-merged CSV don't cause MergeError duplicates.
    stale_present = [
        col for col in combined_df.columns
        if any(
            col in (f"{c}{sfx}", f"{c}{sfx}_x", f"{c}{sfx}_y")
            for c in survey_val_cols for sfx in ('_C', '_IS')
        ) or col == 'Video_Condition'
    ]
    if stale_present:
        print(f"  Dropping {len(stale_present)} pre-existing survey column(s): {stale_present}")
        combined_df = combined_df.drop(columns=stale_present)

    # --- Derive Block per (ID, Condition) group so the counter resets for each participant ---
    def _derive_blocks(grp):
        nums, b, prev, first = [], 1, None, False
        has_reliability = 'Reliability' in grp.columns
        for i in range(len(grp)):
            m = grp['DataSyncMarker'].iloc[i]
            if has_reliability and grp['Reliability'].iloc[i] == 'Restart':
                nums.append(-1)
                continue
            if pd.notna(m) and float(m) == 1.0 and prev != 1.0:
                if first:
                    b += 1
                else:
                    first = True
            if pd.notna(m):
                prev = float(m)
            nums.append(b)
        return pd.Series(nums, index=grp.index, dtype=int)

    result = combined_df.copy()
    result['Block'] = (
        result.groupby(['ID', 'Condition'], sort=False, group_keys=False)
              .apply(_derive_blocks, include_groups=False)
    )

    # --- Build and left-merge one suffixed table per role ---
    for role, suffix in ROLE_MAP.items():
        role_rows = survey_df[survey_df['Role'] == role].copy()
        if role_rows.empty:
            print(f"  WARNING: no survey rows for role '{role}'")
            continue

        role_rows = role_rows.rename(columns={c: f"{c}{suffix}" for c in survey_val_cols})
        role_rows = role_rows.rename(columns={'Team_ID': 'ID'})
        role_rows = role_rows.drop(columns=[c for c in ('Role', 'Participant_ID') if c in role_rows.columns])

        suffixed = [f"{c}{suffix}" for c in survey_val_cols if f"{c}{suffix}" in role_rows.columns]
        role_rows = role_rows[['ID', 'Condition', 'Block'] + suffixed]

        result = result.merge(role_rows, on=['ID', 'Condition', 'Block'], how='left')

    result = result.drop(columns=['Block'])

    # Coalesce Video_Condition_C / Video_Condition_IS into one column placed
    # between DataSyncMarker_channel_1 and Reliability.
    vc_cols = [c for c in ('Video_Condition_C', 'Video_Condition_IS') if c in result.columns]
    if vc_cols:
        result['Video_Condition'] = result[vc_cols[0]]
        for c in vc_cols[1:]:
            result['Video_Condition'] = result['Video_Condition'].combine_first(result[c])
        result = result.drop(columns=vc_cols)

        cols = list(result.columns)
        cols.remove('Video_Condition')
        if 'DataSyncMarker_channel_1' in cols:
            insert_pos = cols.index('DataSyncMarker_channel_1') + 1
        elif 'Reliability' in cols:
            insert_pos = cols.index('Reliability')
        else:
            insert_pos = len(cols)
        cols.insert(insert_pos, 'Video_Condition')
        result = result[cols]

    # --- Summary ---
    tmp = combined_df.copy()
    tmp['Block'] = (
        tmp.groupby(['ID', 'Condition'], sort=False, group_keys=False)
           .apply(_derive_blocks, include_groups=False)
    )
    print("\n=== SURVEY MERGE SUMMARY ===")
    for (uid, cond), grp in tmp.groupby(['ID', 'Condition']):
        n_blocks = grp.loc[grp['Block'] != -1, 'Block'].nunique()
        n_restart = (grp['Block'] == -1).sum()
        extra = f"  ({n_restart:,} row(s) tagged Restart, excluded)" if n_restart else ""
        print(f"  ID {int(uid)} ({cond}): {n_blocks} block(s) detected{extra}")
    for role, suffix in ROLE_MAP.items():
        sample = next((c for c in result.columns if c.endswith(suffix)), None)
        if sample:
            n = result[sample].notna().sum()
            print(f"  Rows with {role} data: {n:,} / {len(result):,}")

    return result

---

## 5. Run Pipeline

### Step 1 — Process XDF Files

Loads each XDF file, exports all streams to per-participant CSVs, and merges them into a single physio file (`physio_output_path`).

In [37]:
combined_df = process_batch(xdf_folder, metadata_csv, physio_output_path)

WARNING: duplicate Team_IDs in metadata (keeping first): [3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
Found 52 file(s): IDs [4, 6, 7, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 60]

============================================================
Processing ID 4  (4_C.xdf)
  condition=Distrust Priming  video_condition=1
============================================================

Stream 5: No samples in clock offsets (0, 0), skipping...
Stream 17: No samples in clock offsets (0, 0), skipping...
Stream 17: Calculated effective sampling rate 158.9756 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21299, 1)
  Sample count: 21299

Exported stream 2 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2316, 1)
  Sample count: 2316

Exported stream 3 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (7, 2)
  Sample count: 7

Exported stream 4 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (42591, 1)
  Sample count: 42591

Exported stream 5 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1815, 1)
  Sample count: 1815

Exported stream 6 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (70769, 1)
  Sample count: 70769

Exported stream 7 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21297, 1)
  Sample count: 21297

Exported stream 9 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21294, 1)
  Sample count: 21294

Exported stream 10 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (70656, 1)
  Sample count: 70656

Exported stream 11 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (70658, 1)
  Sample count: 70658

Exported stream 12 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21297, 1)
  Sample count: 21297

Exported stream 13 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (70779, 1)
  Sample count: 70779

Exported stream 14 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (70653, 1)
  Sample count: 70653

Exported stream 15 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (42592, 1)
  Sample count: 42592

Exported stream 16 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (70769, 1)
  Sample count: 70769

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 17 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (462473, 16)
  Sample count: 462473
  First timestamp: 696201.9085749799

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/4_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (70779 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 696424.497 to 698878.769
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 7 events
  DataSyncMarker events:
    t=696424.497, value=1.0
    t=697017.388, value=2.0
    t=697371.266, value=1.0
    t=697971.886, value=2.0
    t=698283.989, value=1.0
    t=698878.632, value=2.0
    t=698878.769, value=0.0
  Added Reliability column using video condition 1: ('LL', 'HH', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 66776/70779 matches (94.3%)
  DataSyncMarker value distribution:
    1.0: 44568 rows (63.0%)
    2.0: 16604 rows (23.5%)
    0.0: 5604 rows (7.9%)
Base PPG timestamps: 696263.920 to 699103.602

Processing EDA_I.csv...
  File timestamps: 696263.887 to 699103.522
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 44728/70779 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 696263.895 to 699103.547
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 22366/70779 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 696263.717 to 699103.304
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 70772/70779 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 696264.021 to 699098.623
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2428/70779 matches (3.4%)

Processing TEMP1_I.csv...
  File timestamps: 696263.797 to 699103.550
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 22371/70779 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 696264.116 to 699103.399
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 70769/70779 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 696263.840 to 699103.627
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 70779/70779 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 696263.714 to 699103.424
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 70775/70779 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 696264.107 to 699103.519
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 22366/70779 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 696264.063 to 699103.646
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 44732/70779 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 696266.141 to 699096.196
  Added 1 column(s) from HR_I.csv
    HR_I_value: 1894/70779 matches (2.7%)

Processing TEMP1_C.csv...
  File timestamps: 696264.056 to 699103.227
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 22359/70779 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 696264.118 to 699103.400
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 70769/70779 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 696201.909 to 699110.983
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 72727 samples (16 channels)
    x: 72727/72727 valid aggregated values (100.0%)
    y: 72727/72727 valid aggregated values (100.0%)
    PupilDiameter_left: 72727/72727 valid aggregated values (100.0%)
    EyeballCenterX_left: 72727/72727 valid aggregated values (100.0%)
    EyeballCenterY_left: 72727/72727 valid aggregated values (100.0%)
    EyeballCenterZ_left: 72727/72727 valid aggregated values (100.0%)
    OpticalAxisX_left: 72727/72727 valid aggregated values (100.0%)
    OpticalAxisY_left: 72727/72727 valid aggregated values (100.0%)
    OpticalAxisZ_left: 72727/72727 valid aggregated values (100.0%)
    PupilDiameter_right: 72727/72727 valid aggregated values (100.0%)
    EyeballCenterX_right: 72727/72727 valid aggregated values (100.0%)
    EyeballCenterY_right: 72727/72727 valid aggregated values (100.0%)
    EyeballCenterZ_right: 72727/72727 valid aggregated values (100.0%)
    OpticalAxisX_right: 72727/72727 valid aggregated values (100.0%)
    OpticalAxisY_right: 72727/72727 valid aggregated values (100.0%)
    OpticalAxisZ_right: 72727/72727 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_y: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 70779/70779 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 70779/70779 matches (100.0%)

Processing temp_datasync_remaining.csv...
  File timestamps: 696424.497 to 698878.769
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 66776/70779 matches (94.3%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 4003:
  UNIX timestamp: 1745000602.677585
  EST time: 2025-04-18 14:23:22.677584887-04:00
  Corresponding EmotiBit timestamp: 696424.525
Successfully created Date and Time columns for all 70779 rows (EST timezone)
Duration: 2839.68 seconds

Example rows around sync point (row 4003):
  Row 4001: EmotiBit=696424.444, diff=-0.081s, Time=14:23:22.596
  Row 4002: EmotiBit=696424.485, diff=-0.040s, Time=14:23:22.637
  Row 4003: EmotiBit=696424.525, diff=+0.000s, Time=14:23:22.677 <- SYNC POINT
  Row 4004: EmotiBit=696424.565, diff=+0.040s, Time=14:23:22.717
  Row 4005: EmotiBit=696424.605, diff=+0.080s, Time=14:23:22.757

Applying forward fill to missing values...
Missing values before ffill: 400632
Missing values after ffill: 12092
Filled 388540 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 70779 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 696263.920 to 699103.602
Duration: 2839.68 seconds
Participant ID: 4
Condition: Distrust Priming
Video condition: 1

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 66776/70779 (94.3% complete)
DataSyncMarker_channel_1: 66776/70779 (94.3% complete)
Reliability: 66776/70779 (94.3% complete)
PPG_GRN_C: 70779/70779 (100.0% complete)
PPG_RED_C: 70774/70779 (100.0% complete)
PPG_IR_C: 70774/70779 (100.0% complete)
EDA_C: 70775/70779 (100.0% complete)
HR_C: 70777/70779 (100.0% complete)
TEMP_C: 70776/70779 (100.0% complete)
THERM_C: 70774/70779 (100.0% complete)
Neon Companion_Neon Gaze_x: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_y: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 70779/70779 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 70779/70779 (100.0% complete)
PPG_GRN_IS: 70779/70779 (100.0% complete)
PPG_RED_IS: 70779/70779 (100.0% complete)
PPG_IR_IS: 70779/70779 (100.0% complete)
EDA_IS: 70778/70779 (100.0% complete)
HR_IS: 70724/70779 (99.9% complete)
TEMP_IS: 70779/70779 (100.0% complete)
THERM_IS: 70776/70779 (100.0% complete)

============================================================
Processing ID 6  (6_C.xdf)
  condition=Distrust Priming  video_condition=2
============================================================

Stream 12: Calculated effective sampling rate 142.4540 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23513, 1)
  Sample count: 23513

Exported stream 1 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78166, 1)
  Sample count: 78166

Exported stream 2 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (25349, 1)
  Sample count: 25349

Exported stream 5 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (84098, 1)
  Sample count: 84098

Exported stream 6 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78166, 1)
  Sample count: 78166

Exported stream 7 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (84098, 1)
  Sample count: 84098

Exported stream 8 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (47028, 1)
  Sample count: 47028

Exported stream 9 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78166, 1)
  Sample count: 78166

Exported stream 10 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (84098, 1)
  Sample count: 84098

Exported stream 11 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23513, 1)
  Sample count: 23513

Exported stream 12 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2401, 1)
  Sample count: 2401

Exported stream 13 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2589, 1)
  Sample count: 2589

Exported stream 14 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (25349, 1)
  Sample count: 25349

Exported stream 15 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (50700, 1)
  Sample count: 50700

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (7, 2)
  Sample count: 7

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 17 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (490322, 16)
  Sample count: 490322
  First timestamp: 948801.0926541018

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/6_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (78166 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 949157.735 to 952073.243
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 7 events
  DataSyncMarker events:
    t=949157.735, value=1.0
    t=949764.634, value=2.0
    t=950316.770, value=1.0
    t=950923.520, value=2.0
    t=951358.417, value=1.0
    t=951976.921, value=2.0
    t=952073.243, value=0.0
  Added Reliability column using video condition 2: ('LL', 'M', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 72677/78166 matches (93.0%)
  DataSyncMarker value distribution:
    1.0: 45667 rows (58.4%)
    2.0: 27004 rows (34.5%)
    0.0: 6 rows (0.0%)
Base PPG timestamps: 948937.557 to 952073.461

Processing EDA_I.csv...
  File timestamps: 948937.270 to 952317.730
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 49405/78166 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 948937.433 to 952317.828
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 24693/78166 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 948937.078 to 952317.757
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 78166/78166 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 948937.069 to 952072.612
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2525/78166 matches (3.2%)

Processing TEMP1_I.csv...
  File timestamps: 948937.452 to 952317.807
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 24702/78166 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 948937.555 to 952073.460
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 78166/78166 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 948937.079 to 952317.758
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 78166/78166 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 948937.077 to 952317.756
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 78166/78166 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 948937.844 to 952073.437
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 24698/78166 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 948937.646 to 952073.402
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 49406/78166 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 948938.753 to 952316.232
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2558/78166 matches (3.3%)

Processing TEMP1_C.csv...
  File timestamps: 948937.836 to 952073.429
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 24707/78166 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 948937.556 to 952073.460
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 78166/78166 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 948801.093 to 952243.054
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 86050 samples (16 channels)
    x: 86050/86050 valid aggregated values (100.0%)
    y: 86050/86050 valid aggregated values (100.0%)
    PupilDiameter_left: 86050/86050 valid aggregated values (100.0%)
    EyeballCenterX_left: 86050/86050 valid aggregated values (100.0%)
    EyeballCenterY_left: 86050/86050 valid aggregated values (100.0%)
    EyeballCenterZ_left: 86050/86050 valid aggregated values (100.0%)
    OpticalAxisX_left: 86050/86050 valid aggregated values (100.0%)
    OpticalAxisY_left: 86050/86050 valid aggregated values (100.0%)
    OpticalAxisZ_left: 86050/86050 valid aggregated values (100.0%)
    PupilDiameter_right: 86050/86050 valid aggregated values (100.0%)
    EyeballCenterX_right: 86050/86050 valid aggregated values (100.0%)
    EyeballCenterY_right: 86050/86050 valid aggregated values (100.0%)
    EyeballCenterZ_right: 86050/86050 valid aggregated values (100.0%)
    OpticalAxisX_right: 86050/86050 valid aggregated values (100.0%)
    OpticalAxisY_right: 86050/86050 valid aggregated values (100.0%)
    OpticalAxisZ_right: 86050/86050 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_y: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 78166/78166 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 78166/78166 matches (100.0%)

Processing temp_datasync_remaining.csv...
  File timestamps: 949157.735 to 952073.243
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 72677/78166 matches (93.0%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 5489:
  UNIX timestamp: 1745253334.544171
  EST time: 2025-04-21 12:35:34.544171095-04:00
  Corresponding EmotiBit timestamp: 949157.77
Successfully created Date and Time columns for all 78166 rows (EST timezone)
Duration: 3135.90 seconds

Example rows around sync point (row 5489):
  Row 5487: EmotiBit=949157.690, diff=-0.080s, Time=12:35:34.464
  Row 5488: EmotiBit=949157.730, diff=-0.040s, Time=12:35:34.504
  Row 5489: EmotiBit=949157.770, diff=+0.000s, Time=12:35:34.544 <- SYNC POINT
  Row 5490: EmotiBit=949157.810, diff=+0.040s, Time=12:35:34.584
  Row 5491: EmotiBit=949157.850, diff=+0.080s, Time=12:35:34.624

Applying forward fill to missing values...
Missing values before ffill: 439107
Missing values after ffill: 16528
Filled 422579 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 78166 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 948937.557 to 952073.461
Duration: 3135.90 seconds
Participant ID: 6
Condition: Distrust Priming
Video condition: 2

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 72677/78166 (93.0% complete)
DataSyncMarker_channel_1: 72677/78166 (93.0% complete)
Reliability: 72677/78166 (93.0% complete)
PPG_GRN_C: 78166/78166 (100.0% complete)
PPG_RED_C: 78166/78166 (100.0% complete)
PPG_IR_C: 78166/78166 (100.0% complete)
EDA_C: 78164/78166 (100.0% complete)
HR_C: 78152/78166 (100.0% complete)
TEMP_C: 78159/78166 (100.0% complete)
THERM_C: 78159/78166 (100.0% complete)
Neon Companion_Neon Gaze_x: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_y: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 78166/78166 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 78166/78166 (100.0% complete)
PPG_GRN_IS: 78166/78166 (100.0% complete)
PPG_RED_IS: 78166/78166 (100.0% complete)
PPG_IR_IS: 78166/78166 (100.0% complete)
EDA_IS: 78166/78166 (100.0% complete)
HR_IS: 78136/78166 (100.0% complete)
TEMP_IS: 78165/78166 (100.0% complete)
THERM_IS: 78166/78166 (100.0% complete)

============================================================
Processing ID 7  (7_C.xdf)
  condition=Trust Priming  video_condition=3
============================================================

Stream 12: Calculated effective sampling rate 149.0366 Hz is different from specified rate 200.0000 Hz.
Stream 12: Segments and clock-segments differ

Exported stream 1 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (158332, 1)
  Sample count: 158332

Exported stream 2 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (47630, 1)
  Sample count: 47630

Exported stream 3 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (47644, 1)
  Sample count: 47644

Exported stream 4 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (95258, 1)
  Sample count: 95258

Exported stream 5 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (47629, 1)
  Sample count: 47629

Exported stream 6 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (5370, 1)
  Sample count: 5370

Exported stream 7 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (158084, 1)
  Sample count: 158084

Exported stream 8 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (158332, 1)
  Sample count: 158332

Exported stream 9 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (158332, 1)
  Sample count: 158332

Exported stream 10 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (158084, 1)
  Sample count: 158084

Exported stream 11 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (4061, 1)
  Sample count: 4061

Exported stream 12 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (47643, 1)
  Sample count: 47643

Exported stream 13 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (158084, 1)
  Sample count: 158084

Exported stream 14 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (95286, 1)
  Sample count: 95286

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (973297, 16)
  Sample count: 973297
  First timestamp: 2046347.522729804

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (7, 2)
  Sample count: 7

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/7_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (158332 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 2046564.918 to 2050961.749
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 7 events
  DataSyncMarker events:
    t=2046564.918, value=1.0
    t=2047405.612, value=2.0
    t=2048691.463, value=1.0
    t=2049513.950, value=2.0
    t=2050147.708, value=1.0
    t=2050946.560, value=2.0
    t=2050961.749, value=2.2896334584515e-311
  Added Reliability column using video condition 3: ('HH', 'LL', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 153544/158332 matches (97.0%)
  DataSyncMarker value distribution:
    1.0: 61365 rows (38.8%)
    2.0: 48225 rows (30.5%)
    2.2896334584515e-311: 43954 rows (27.8%)
Base PPG timestamps: 2046372.831 to 2052725.173

Processing EDA_I.csv...
  File timestamps: 2046373.427 to 2052725.361
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 101137/158332 matches (63.9%)

Processing THERM_I.csv...
  File timestamps: 2046373.479 to 2052725.275
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 50551/158332 matches (31.9%)

Processing PPG_RED_I.csv...
  File timestamps: 2046373.416 to 2052725.373
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 158317/158332 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 2046375.504 to 2052716.709
  Added 1 column(s) from HR_C.csv
    HR_C_value: 5705/158332 matches (3.6%)

Processing TEMP1_I.csv...
  File timestamps: 2046373.403 to 2052725.239
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 50558/158332 matches (31.9%)

Processing PPG_IR_C.csv...
  File timestamps: 2046372.830 to 2052725.172
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 158332/158332 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 2046373.417 to 2052725.374
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 158317/158332 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 2046373.415 to 2052725.372
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 158317/158332 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 2046372.932 to 2052725.313
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 50535/158332 matches (31.9%)

Processing EDA_C.csv...
  File timestamps: 2046372.790 to 2052725.063
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 101076/158332 matches (63.8%)

Processing HR_I.csv...
  File timestamps: 2046373.753 to 2052723.993
  Added 1 column(s) from HR_I.csv
    HR_I_value: 4326/158332 matches (2.7%)

Processing TEMP1_C.csv...
  File timestamps: 2046372.901 to 2052725.225
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 50537/158332 matches (31.9%)

Processing PPG_RED_C.csv...
  File timestamps: 2046372.830 to 2052725.173
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 158332/158332 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 2046347.523 to 2052964.394
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 163265 samples (16 channels)
    x: 163265/163265 valid aggregated values (100.0%)
    y: 163265/163265 valid aggregated values (100.0%)
    PupilDiameter_left: 163265/163265 valid aggregated values (100.0%)
    EyeballCenterX_left: 163265/163265 valid aggregated values (100.0%)
    EyeballCenterY_left: 163265/163265 valid aggregated values (100.0%)
    EyeballCenterZ_left: 163265/163265 valid aggregated values (100.0%)
    OpticalAxisX_left: 163265/163265 valid aggregated values (100.0%)
    OpticalAxisY_left: 163265/163265 valid aggregated values (100.0%)
    OpticalAxisZ_left: 163265/163265 valid aggregated values (100.0%)
    PupilDiameter_right: 163265/163265 valid aggregated values (100.0%)
    EyeballCenterX_right: 163265/163265 valid aggregated values (100.0%)
    EyeballCenterY_right: 163265/163265 valid aggregated values (100.0%)
    EyeballCenterZ_right: 163265/163265 valid aggregated values (100.0%)
    OpticalAxisX_right: 163265/163265 valid aggregated values (100.0%)
    OpticalAxisY_right: 163265/163265 valid aggregated values (100.0%)
    OpticalAxisZ_right: 163265/163265 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_y: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 156182/158332 matches (98.6%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 156182/158332 matches (98.6%)

Processing temp_datasync_remaining.csv...
  File timestamps: 2046564.918 to 2050961.749
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 153544/158332 matches (97.0%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 4788:
  UNIX timestamp: 1749220931.799605
  EST time: 2025-06-06 10:42:11.799604893-04:00
  Corresponding EmotiBit timestamp: 2046564.929
Successfully created Date and Time columns for all 158332 rows (EST timezone)
Duration: 6352.34 seconds

Example rows around sync point (row 4788):
  Row 4786: EmotiBit=2046564.848, diff=-0.081s, Time=10:42:11.718
  Row 4787: EmotiBit=2046564.888, diff=-0.041s, Time=10:42:11.758
  Row 4788: EmotiBit=2046564.929, diff=+0.000s, Time=10:42:11.799 <- SYNC POINT
  Row 4789: EmotiBit=2046564.969, diff=+0.040s, Time=10:42:11.839
  Row 4790: EmotiBit=2046565.009, diff=+0.080s, Time=10:42:11.879

Applying forward fill to missing values...
Missing values before ffill: 944994
Missing values after ffill: 14549
Filled 930445 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 158332 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 2046372.831 to 2052725.173
Duration: 6352.34 seconds
Participant ID: 7
Condition: Trust Priming
Video condition: 3

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 153544/158332 (97.0% complete)
DataSyncMarker_channel_1: 153544/158332 (97.0% complete)
Reliability: 153544/158332 (97.0% complete)
PPG_GRN_C: 158332/158332 (100.0% complete)
PPG_RED_C: 158332/158332 (100.0% complete)
PPG_IR_C: 158332/158332 (100.0% complete)
EDA_C: 158331/158332 (100.0% complete)
HR_C: 158265/158332 (100.0% complete)
TEMP_C: 158330/158332 (100.0% complete)
THERM_C: 158330/158332 (100.0% complete)
Neon Companion_Neon Gaze_x: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_y: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 158332/158332 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 158332/158332 (100.0% complete)
PPG_GRN_IS: 158317/158332 (100.0% complete)
PPG_RED_IS: 158317/158332 (100.0% complete)
PPG_IR_IS: 158317/158332 (100.0% complete)
EDA_IS: 158317/158332 (100.0% complete)
HR_IS: 158309/158332 (100.0% complete)
TEMP_IS: 158318/158332 (100.0% complete)
THERM_IS: 158316/158332 (100.0% complete)

============================================================
Processing ID 10  (10_C.xdf)
  condition=Trust Priming  video_condition=4
============================================================

Stream 14: Calculated effective sampling rate 153.7945 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (85714, 1)
  Sample count: 85714

Exported stream 1 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2125, 1)
  Sample count: 2125

Exported stream 2 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (51673, 1)
  Sample count: 51673

Exported stream 3 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (25835, 1)
  Sample count: 25835

Exported stream 4 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (85714, 1)
  Sample count: 85714

Exported stream 5 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (51742, 1)
  Sample count: 51742

Exported stream 7 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (86013, 1)
  Sample count: 86013

Exported stream 8 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1952, 1)
  Sample count: 1952

Exported stream 9 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (25837, 1)
  Sample count: 25837

Exported stream 10 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (86013, 1)
  Sample count: 86013

Exported stream 11 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (85714, 1)
  Sample count: 85714

Exported stream 12 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (86013, 1)
  Sample count: 86013

Exported stream 13 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (25866, 1)
  Sample count: 25866

Exported stream 14 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (25870, 1)
  Sample count: 25870

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (537381, 16)
  Sample count: 537381
  First timestamp: 1886673.1659427618

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/10_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (86013 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 1886812.923 to 1889968.501
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=1886812.923, value=1.0
    t=1887647.052, value=2.0
    t=1888080.620, value=1.0
    t=1888906.673, value=2.0
    t=1889146.441, value=1.0
    t=1889968.501, value=2.0
  Added Reliability column using video condition 4: ('HH', 'M', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 84006/86013 matches (97.7%)
  DataSyncMarker value distribution:
    1.0: 61541 rows (71.5%)
    2.0: 22465 rows (26.1%)
Base PPG timestamps: 1886732.007 to 1890201.189

Processing EDA_I.csv...
  File timestamps: 1886731.220 to 1890202.816
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 54494/86013 matches (63.4%)

Processing THERM_I.csv...
  File timestamps: 1886731.134 to 1890202.772
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 27248/86013 matches (31.7%)

Processing PPG_RED_I.csv...
  File timestamps: 1886731.183 to 1890202.995
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 86013/86013 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 1886738.929 to 1890197.822
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2227/86013 matches (2.6%)

Processing TEMP1_I.csv...
  File timestamps: 1886731.179 to 1890202.833
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 27246/86013 matches (31.7%)

Processing PPG_IR_C.csv...
  File timestamps: 1886732.005 to 1890201.188
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 86013/86013 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 1886731.184 to 1890202.995
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 86013/86013 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 1886731.182 to 1890202.994
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 86013/86013 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 1886731.901 to 1890201.053
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 27297/86013 matches (31.7%)

Processing EDA_C.csv...
  File timestamps: 1886731.852 to 1890201.083
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 54612/86013 matches (63.5%)

Processing HR_I.csv...
  File timestamps: 1886735.978 to 1890199.103
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2073/86013 matches (2.4%)

Processing TEMP1_C.csv...
  File timestamps: 1886731.977 to 1890201.314
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 27293/86013 matches (31.7%)

Processing PPG_RED_C.csv...
  File timestamps: 1886732.006 to 1890201.188
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 86013/86013 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 1886673.166 to 1890167.309
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 87354 samples (16 channels)
    x: 87354/87354 valid aggregated values (100.0%)
    y: 87354/87354 valid aggregated values (100.0%)
    PupilDiameter_left: 87354/87354 valid aggregated values (100.0%)
    EyeballCenterX_left: 87354/87354 valid aggregated values (100.0%)
    EyeballCenterY_left: 87354/87354 valid aggregated values (100.0%)
    EyeballCenterZ_left: 87354/87354 valid aggregated values (100.0%)
    OpticalAxisX_left: 87354/87354 valid aggregated values (100.0%)
    OpticalAxisY_left: 87354/87354 valid aggregated values (100.0%)
    OpticalAxisZ_left: 87354/87354 valid aggregated values (100.0%)
    PupilDiameter_right: 87354/87354 valid aggregated values (100.0%)
    EyeballCenterX_right: 87354/87354 valid aggregated values (100.0%)
    EyeballCenterY_right: 87354/87354 valid aggregated values (100.0%)
    EyeballCenterZ_right: 87354/87354 valid aggregated values (100.0%)
    OpticalAxisX_right: 87354/87354 valid aggregated values (100.0%)
    OpticalAxisY_right: 87354/87354 valid aggregated values (100.0%)
    OpticalAxisZ_right: 87354/87354 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_y: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 85172/86013 matches (99.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 85172/86013 matches (99.0%)

Processing temp_datasync_remaining.csv...
  File timestamps: 1886812.923 to 1889968.501
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 84006/86013 matches (97.7%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 2007:
  UNIX timestamp: 1751378594.911935
  EST time: 2025-07-01 10:03:14.911935091-04:00
  Corresponding EmotiBit timestamp: 1886812.957
Successfully created Date and Time columns for all 86013 rows (EST timezone)
Duration: 3469.18 seconds

Example rows around sync point (row 2007):
  Row 2005: EmotiBit=1886812.876, diff=-0.081s, Time=10:03:14.830
  Row 2006: EmotiBit=1886812.916, diff=-0.041s, Time=10:03:14.870
  Row 2007: EmotiBit=1886812.957, diff=+0.000s, Time=10:03:14.911 <- SYNC POINT
  Row 2008: EmotiBit=1886812.997, diff=+0.040s, Time=10:03:14.951
  Row 2009: EmotiBit=1886813.037, diff=+0.080s, Time=10:03:14.991

Applying forward fill to missing values...
Missing values before ffill: 485091
Missing values after ffill: 6297
Filled 478794 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 86013 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 1886732.007 to 1890201.189
Duration: 3469.18 seconds
Participant ID: 10
Condition: Trust Priming
Video condition: 4

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 84006/86013 (97.7% complete)
DataSyncMarker_channel_1: 84006/86013 (97.7% complete)
Reliability: 84006/86013 (97.7% complete)
PPG_GRN_C: 86013/86013 (100.0% complete)
PPG_RED_C: 86013/86013 (100.0% complete)
PPG_IR_C: 86013/86013 (100.0% complete)
EDA_C: 86013/86013 (100.0% complete)
HR_C: 85841/86013 (99.8% complete)
TEMP_C: 86010/86013 (100.0% complete)
THERM_C: 86012/86013 (100.0% complete)
Neon Companion_Neon Gaze_x: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_y: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 86013/86013 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 86013/86013 (100.0% complete)
PPG_GRN_IS: 86013/86013 (100.0% complete)
PPG_RED_IS: 86013/86013 (100.0% complete)
PPG_IR_IS: 86013/86013 (100.0% complete)
EDA_IS: 86013/86013 (100.0% complete)
HR_IS: 85915/86013 (99.9% complete)
TEMP_IS: 86013/86013 (100.0% complete)
THERM_IS: 86011/86013 (100.0% complete)

============================================================
Processing ID 12  (12_C.xdf)
  condition=Trust Priming  video_condition=5
============================================================

Stream 5: Calculated effective sampling rate 145.1319 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (110925, 1)
  Sample count: 110925

Exported stream 1 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (111169, 1)
  Sample count: 111169

Exported stream 2 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (33446, 1)
  Sample count: 33446

Exported stream 3 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (111169, 1)
  Sample count: 111169

Exported stream 4 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (110925, 1)
  Sample count: 110925

Exported stream 5 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (33445, 1)
  Sample count: 33445

Exported stream 6 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (33445, 1)
  Sample count: 33445

Exported stream 7 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (33446, 1)
  Sample count: 33446

Exported stream 8 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (4306, 1)
  Sample count: 4306

Exported stream 9 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (66889, 1)
  Sample count: 66889

Exported stream 10 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (111169, 1)
  Sample count: 111169

Exported stream 12 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (66889, 1)
  Sample count: 66889

Exported stream 13 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (110925, 1)
  Sample count: 110925

Exported stream 14 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (4931, 1)
  Sample count: 4931

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (677244, 16)
  Sample count: 677244
  First timestamp: 415453.89109724696

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/12_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (111169 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 415632.554 to 418936.272
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=415632.554, value=1.0
    t=416442.454, value=2.0
    t=416922.890, value=1.0
    t=417748.238, value=2.0
    t=418104.663, value=1.0
    t=418936.272, value=2.0
  Added Reliability column using video condition 5: ('M', 'LL', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 109470/111169 matches (98.5%)
  DataSyncMarker value distribution:
    1.0: 61496 rows (55.3%)
    2.0: 47974 rows (43.2%)
Base PPG timestamps: 415564.403 to 420023.772

Processing EDA_I.csv...
  File timestamps: 415564.490 to 420023.850
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 68809/111169 matches (61.9%)

Processing THERM_I.csv...
  File timestamps: 415564.442 to 420023.875
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 34403/111169 matches (30.9%)

Processing PPG_RED_I.csv...
  File timestamps: 415564.378 to 420023.790
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 111169/111169 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 415564.780 to 420023.021
  Added 1 column(s) from HR_C.csv
    HR_C_value: 4429/111169 matches (4.0%)

Processing TEMP1_I.csv...
  File timestamps: 415564.435 to 420023.868
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 34415/111169 matches (31.0%)

Processing PPG_IR_C.csv...
  File timestamps: 415564.402 to 420023.771
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 111169/111169 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 415564.379 to 420023.791
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 111169/111169 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 415564.378 to 420023.789
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 111169/111169 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 415564.348 to 420023.636
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 34384/111169 matches (30.9%)

Processing EDA_C.csv...
  File timestamps: 415564.328 to 420023.677
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 68820/111169 matches (61.9%)

Processing HR_I.csv...
  File timestamps: 415564.880 to 420023.388
  Added 1 column(s) from HR_I.csv
    HR_I_value: 5052/111169 matches (4.5%)

Processing TEMP1_C.csv...
  File timestamps: 415564.340 to 420023.628
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 34438/111169 matches (31.0%)

Processing PPG_RED_C.csv...
  File timestamps: 415564.403 to 420023.771
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 111169/111169 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 415453.891 to 420120.288
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 116660 samples (16 channels)
    x: 116660/116660 valid aggregated values (100.0%)
    y: 116660/116660 valid aggregated values (100.0%)
    PupilDiameter_left: 116660/116660 valid aggregated values (100.0%)
    EyeballCenterX_left: 116660/116660 valid aggregated values (100.0%)
    EyeballCenterY_left: 116660/116660 valid aggregated values (100.0%)
    EyeballCenterZ_left: 116660/116660 valid aggregated values (100.0%)
    OpticalAxisX_left: 116660/116660 valid aggregated values (100.0%)
    OpticalAxisY_left: 116660/116660 valid aggregated values (100.0%)
    OpticalAxisZ_left: 116660/116660 valid aggregated values (100.0%)
    PupilDiameter_right: 116660/116660 valid aggregated values (100.0%)
    EyeballCenterX_right: 116660/116660 valid aggregated values (100.0%)
    EyeballCenterY_right: 116660/116660 valid aggregated values (100.0%)
    EyeballCenterZ_right: 116660/116660 valid aggregated values (100.0%)
    OpticalAxisX_right: 116660/116660 valid aggregated values (100.0%)
    OpticalAxisY_right: 116660/116660 valid aggregated values (100.0%)
    OpticalAxisZ_right: 116660/116660 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_y: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 111169/111169 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 111169/111169 matches (100.0%)

Processing temp_datasync_remaining.csv...
  File timestamps: 415632.554 to 418936.272
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 109470/111169 matches (98.5%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 1699:
  UNIX timestamp: 1753205181.452762
  EST time: 2025-07-22 13:26:21.452761889-04:00
  Corresponding EmotiBit timestamp: 415632.557
Successfully created Date and Time columns for all 111169 rows (EST timezone)
Duration: 4459.37 seconds

Example rows around sync point (row 1699):
  Row 1697: EmotiBit=415632.477, diff=-0.080s, Time=13:26:21.372
  Row 1698: EmotiBit=415632.517, diff=-0.040s, Time=13:26:21.412
  Row 1699: EmotiBit=415632.557, diff=+0.000s, Time=13:26:21.452 <- SYNC POINT
  Row 1700: EmotiBit=415632.597, diff=+0.040s, Time=13:26:21.492
  Row 1701: EmotiBit=415632.637, diff=+0.080s, Time=13:26:21.532

Applying forward fill to missing values...
Missing values before ffill: 609699
Missing values after ffill: 5126
Filled 604573 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 111169 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 415564.403 to 420023.772
Duration: 4459.37 seconds
Participant ID: 12
Condition: Trust Priming
Video condition: 5

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 109470/111169 (98.5% complete)
DataSyncMarker_channel_1: 109470/111169 (98.5% complete)
Reliability: 109470/111169 (98.5% complete)
PPG_GRN_C: 111169/111169 (100.0% complete)
PPG_RED_C: 111169/111169 (100.0% complete)
PPG_IR_C: 111169/111169 (100.0% complete)
EDA_C: 111169/111169 (100.0% complete)
HR_C: 111160/111169 (100.0% complete)
TEMP_C: 111167/111169 (100.0% complete)
THERM_C: 111167/111169 (100.0% complete)
Neon Companion_Neon Gaze_x: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_y: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 111169/111169 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 111169/111169 (100.0% complete)
PPG_GRN_IS: 111169/111169 (100.0% complete)
PPG_RED_IS: 111169/111169 (100.0% complete)
PPG_IR_IS: 111169/111169 (100.0% complete)
EDA_IS: 111167/111169 (100.0% complete)
HR_IS: 111157/111169 (100.0% complete)
TEMP_IS: 111168/111169 (100.0% complete)
THERM_IS: 111168/111169 (100.0% complete)

============================================================
Processing ID 13  (13_C.xdf)
  condition=Distrust Priming  video_condition=5
============================================================

found likely XDF file corruption (unpack requires a buffer of 8 bytes), scanning forward to next boundary chunk.
Stream 12: Calculated effective sampling rate 171.4024 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20927, 1)
  Sample count: 20927

Exported stream 1 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (34792, 1)
  Sample count: 34792

Exported stream 2 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1202, 1)
  Sample count: 1202

Exported stream 3 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (34724, 1)
  Sample count: 34724

Exported stream 4 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (34712, 1)
  Sample count: 34712

Exported stream 5 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (34792, 1)
  Sample count: 34792

Exported stream 6 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (1095, 1)
  Sample count: 1095

Exported stream 7 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (10468, 1)
  Sample count: 10468

Exported stream 8 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (10467, 1)
  Sample count: 10467

Exported stream 10 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (34792, 1)
  Sample count: 34792

Exported stream 11 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (34724, 1)
  Sample count: 34724

Exported stream 12 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (10468, 1)
  Sample count: 10468

Exported stream 13 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20934, 1)
  Sample count: 20934

Exported stream 14 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (10463, 1)
  Sample count: 10463

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (3, 2)
  Sample count: 3

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (235726, 16)
  Sample count: 235726
  First timestamp: 2924483.6078419285

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/13_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (34792 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 2924644.534 to 2925587.198
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 3 events
  DataSyncMarker events:
    t=2924644.534, value=1.0
    t=2925250.800, value=2.0
    t=2925587.198, value=1.0
  Added Reliability column using video condition 5: ('M', 'LL', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 30927/34792 matches (88.9%)
  DataSyncMarker value distribution:
    1.0: 22540 rows (64.8%)
    2.0: 8387 rows (24.1%)
Base PPG timestamps: 2924489.538 to 2925885.062

Processing EDA_I.csv...
  File timestamps: 2924489.537 to 2925884.569
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 21807/34792 matches (62.7%)

Processing THERM_I.csv...
  File timestamps: 2924489.560 to 2925885.034
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 10909/34792 matches (31.4%)

Processing PPG_RED_I.csv...
  File timestamps: 2924489.435 to 2925885.025
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 34791/34792 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 2924490.846 to 2925884.714
  Added 1 column(s) from HR_C.csv
    HR_C_value: 1142/34792 matches (3.3%)

Processing TEMP1_I.csv...
  File timestamps: 2924489.552 to 2925885.026
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 10913/34792 matches (31.4%)

Processing PPG_IR_C.csv...
  File timestamps: 2924489.537 to 2925885.061
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 34792/34792 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 2924489.435 to 2925885.026
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 34791/34792 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 2924489.434 to 2925884.542
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 34779/34792 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 2924489.652 to 2925884.454
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 10895/34792 matches (31.3%)

Processing EDA_C.csv...
  File timestamps: 2924489.562 to 2925885.056
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 21817/34792 matches (62.7%)

Processing HR_I.csv...
  File timestamps: 2924490.428 to 2925883.697
  Added 1 column(s) from HR_I.csv
    HR_I_value: 1266/34792 matches (3.6%)

Processing TEMP1_C.csv...
  File timestamps: 2924489.645 to 2925884.980
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 10898/34792 matches (31.3%)

Processing PPG_RED_C.csv...
  File timestamps: 2924489.538 to 2925885.061
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 34792/34792 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 2924483.608 to 2925858.880
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 34382 samples (16 channels)
    x: 34382/34382 valid aggregated values (100.0%)
    y: 34382/34382 valid aggregated values (100.0%)
    PupilDiameter_left: 34382/34382 valid aggregated values (100.0%)
    EyeballCenterX_left: 34382/34382 valid aggregated values (100.0%)
    EyeballCenterY_left: 34382/34382 valid aggregated values (100.0%)
    EyeballCenterZ_left: 34382/34382 valid aggregated values (100.0%)
    OpticalAxisX_left: 34382/34382 valid aggregated values (100.0%)
    OpticalAxisY_left: 34382/34382 valid aggregated values (100.0%)
    OpticalAxisZ_left: 34382/34382 valid aggregated values (100.0%)
    PupilDiameter_right: 34382/34382 valid aggregated values (100.0%)
    EyeballCenterX_right: 34382/34382 valid aggregated values (100.0%)
    EyeballCenterY_right: 34382/34382 valid aggregated values (100.0%)
    EyeballCenterZ_right: 34382/34382 valid aggregated values (100.0%)
    OpticalAxisX_right: 34382/34382 valid aggregated values (100.0%)
    OpticalAxisY_right: 34382/34382 valid aggregated values (100.0%)
    OpticalAxisZ_right: 34382/34382 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_y: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 34139/34792 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 34139/34792 matches (98.1%)

Processing temp_datasync_remaining.csv...
  File timestamps: 2924644.534 to 2925587.198
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 30927/34792 matches (88.9%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3865:
  UNIX timestamp: 1755714202.4398332
  EST time: 2025-08-20 14:23:22.439833164-04:00
  Corresponding EmotiBit timestamp: 2924644.57
Successfully created Date and Time columns for all 34792 rows (EST timezone)
Duration: 1395.52 seconds

Example rows around sync point (row 3865):
  Row 3863: EmotiBit=2924644.490, diff=-0.080s, Time=14:23:22.359
  Row 3864: EmotiBit=2924644.530, diff=-0.040s, Time=14:23:22.399
  Row 3865: EmotiBit=2924644.570, diff=+0.000s, Time=14:23:22.439 <- SYNC POINT
  Row 3866: EmotiBit=2924644.610, diff=+0.040s, Time=14:23:22.479
  Row 3867: EmotiBit=2924644.650, diff=+0.080s, Time=14:23:22.519

Applying forward fill to missing values...
Missing values before ffill: 210747
Missing values after ffill: 11658
Filled 199089 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 34792 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 2924489.538 to 2925885.062
Duration: 1395.52 seconds
Participant ID: 13
Condition: Distrust Priming
Video condition: 5

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 30927/34792 (88.9% complete)
DataSyncMarker_channel_1: 30927/34792 (88.9% complete)
Reliability: 30927/34792 (88.9% complete)
PPG_GRN_C: 34792/34792 (100.0% complete)
PPG_RED_C: 34792/34792 (100.0% complete)
PPG_IR_C: 34792/34792 (100.0% complete)
EDA_C: 34791/34792 (100.0% complete)
HR_C: 34759/34792 (99.9% complete)
TEMP_C: 34789/34792 (100.0% complete)
THERM_C: 34789/34792 (100.0% complete)
Neon Companion_Neon Gaze_x: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_y: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 34792/34792 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 34792/34792 (100.0% complete)
PPG_GRN_IS: 34792/34792 (100.0% complete)
PPG_RED_IS: 34792/34792 (100.0% complete)
PPG_IR_IS: 34792/34792 (100.0% complete)
EDA_IS: 34792/34792 (100.0% complete)
HR_IS: 34770/34792 (99.9% complete)
TEMP_IS: 34792/34792 (100.0% complete)
THERM_IS: 34791/34792 (100.0% complete)

============================================================
Processing ID 14  (14_C.xdf)
  condition=Trust Priming  video_condition=6
============================================================

Stream 6: Calculated effective sampling rate 142.0508 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72815, 1)
  Sample count: 72815

Exported stream 1 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72673, 1)
  Sample count: 72673

Exported stream 2 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21909, 1)
  Sample count: 21909

Exported stream 4 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (43816, 1)
  Sample count: 43816

Exported stream 6 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21907, 1)
  Sample count: 21907

Exported stream 7 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (43815, 1)
  Sample count: 43815

Exported stream 8 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2394, 1)
  Sample count: 2394

Exported stream 9 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72815, 1)
  Sample count: 72815

Exported stream 10 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21908, 1)
  Sample count: 21908

Exported stream 11 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72815, 1)
  Sample count: 72815

Exported stream 12 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72673, 1)
  Sample count: 72673

Exported stream 13 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21909, 1)
  Sample count: 21909

Exported stream 14 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72673, 1)
  Sample count: 72673

Exported stream 15 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2332, 1)
  Sample count: 2332

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (458811, 16)
  Sample count: 458811
  First timestamp: 2931186.2759693526

Exported stream 17 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (7, 2)
  Sample count: 7

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/14_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (72815 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 2931506.065 to 2934235.962
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 7 events
  DataSyncMarker events:
    t=2931506.065, value=1.0
    t=2932114.658, value=2.0
    t=2932614.545, value=1.0
    t=2933228.503, value=2.0
    t=2933587.655, value=1.0
    t=2934198.211, value=2.0
    t=2934235.962, value=0.0
  Added Reliability column using video condition 6: ('M', 'HH', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 68040/72815 matches (93.4%)
  DataSyncMarker value distribution:
    1.0: 45681 rows (62.7%)
    2.0: 22347 rows (30.7%)
    0.0: 12 rows (0.0%)
Base PPG timestamps: 2931314.461 to 2934236.422

Processing EDA_I.csv...
  File timestamps: 2931314.468 to 2934236.322
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 45604/72815 matches (62.6%)

Processing THERM_I.csv...
  File timestamps: 2931314.502 to 2934236.289
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 22805/72815 matches (31.3%)

Processing PPG_RED_I.csv...
  File timestamps: 2931314.404 to 2934236.377
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 72814/72815 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 2931322.092 to 2934235.388
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2494/72815 matches (3.4%)

Processing TEMP1_I.csv...
  File timestamps: 2931314.495 to 2934236.282
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 22815/72815 matches (31.3%)

Processing PPG_IR_C.csv...
  File timestamps: 2931314.460 to 2934236.421
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 72815/72815 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 2931314.405 to 2934236.378
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 72814/72815 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 2931314.404 to 2934236.377
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 72814/72815 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 2931314.522 to 2934236.300
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 22809/72815 matches (31.3%)

Processing EDA_C.csv...
  File timestamps: 2931314.480 to 2934236.353
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 45621/72815 matches (62.7%)

Processing HR_I.csv...
  File timestamps: 2931327.993 to 2934235.822
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2407/72815 matches (3.3%)

Processing TEMP1_C.csv...
  File timestamps: 2931314.514 to 2934236.426
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 22819/72815 matches (31.3%)

Processing PPG_RED_C.csv...
  File timestamps: 2931314.461 to 2934236.422
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 72815/72815 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 2931186.276 to 2934416.177
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 80748 samples (16 channels)
    x: 80748/80748 valid aggregated values (100.0%)
    y: 80748/80748 valid aggregated values (100.0%)
    PupilDiameter_left: 80748/80748 valid aggregated values (100.0%)
    EyeballCenterX_left: 80748/80748 valid aggregated values (100.0%)
    EyeballCenterY_left: 80748/80748 valid aggregated values (100.0%)
    EyeballCenterZ_left: 80748/80748 valid aggregated values (100.0%)
    OpticalAxisX_left: 80748/80748 valid aggregated values (100.0%)
    OpticalAxisY_left: 80748/80748 valid aggregated values (100.0%)
    OpticalAxisZ_left: 80748/80748 valid aggregated values (100.0%)
    PupilDiameter_right: 80748/80748 valid aggregated values (100.0%)
    EyeballCenterX_right: 80748/80748 valid aggregated values (100.0%)
    EyeballCenterY_right: 80748/80748 valid aggregated values (100.0%)
    EyeballCenterZ_right: 80748/80748 valid aggregated values (100.0%)
    OpticalAxisX_right: 80748/80748 valid aggregated values (100.0%)
    OpticalAxisY_right: 80748/80748 valid aggregated values (100.0%)
    OpticalAxisZ_right: 80748/80748 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_y: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 72815/72815 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 72815/72815 matches (100.0%)

Processing temp_datasync_remaining.csv...
  File timestamps: 2931506.065 to 2934235.962
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 68040/72815 matches (93.4%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 4775:
  UNIX timestamp: 1755721059.989127
  EST time: 2025-08-20 16:17:39.989126921-04:00
  Corresponding EmotiBit timestamp: 2931506.078
Successfully created Date and Time columns for all 72815 rows (EST timezone)
Duration: 2921.96 seconds

Example rows around sync point (row 4775):
  Row 4773: EmotiBit=2931505.998, diff=-0.080s, Time=16:17:39.909
  Row 4774: EmotiBit=2931506.038, diff=-0.040s, Time=16:17:39.949
  Row 4775: EmotiBit=2931506.078, diff=+0.000s, Time=16:17:39.989 <- SYNC POINT
  Row 4776: EmotiBit=2931506.118, diff=+0.040s, Time=16:17:40.029
  Row 4777: EmotiBit=2931506.158, diff=+0.080s, Time=16:17:40.069

Applying forward fill to missing values...
Missing values before ffill: 409486
Missing values after ffill: 14856
Filled 394630 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 72815 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 2931314.461 to 2934236.422
Duration: 2921.96 seconds
Participant ID: 14
Condition: Trust Priming
Video condition: 6

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 68040/72815 (93.4% complete)
DataSyncMarker_channel_1: 68040/72815 (93.4% complete)
Reliability: 68040/72815 (93.4% complete)
PPG_GRN_C: 72815/72815 (100.0% complete)
PPG_RED_C: 72815/72815 (100.0% complete)
PPG_IR_C: 72815/72815 (100.0% complete)
EDA_C: 72815/72815 (100.0% complete)
HR_C: 72625/72815 (99.7% complete)
TEMP_C: 72814/72815 (100.0% complete)
THERM_C: 72814/72815 (100.0% complete)
Neon Companion_Neon Gaze_x: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_y: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 72815/72815 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 72815/72815 (100.0% complete)
PPG_GRN_IS: 72815/72815 (100.0% complete)
PPG_RED_IS: 72815/72815 (100.0% complete)
PPG_IR_IS: 72815/72815 (100.0% complete)
EDA_IS: 72815/72815 (100.0% complete)
HR_IS: 72478/72815 (99.5% complete)
TEMP_IS: 72814/72815 (100.0% complete)
THERM_IS: 72814/72815 (100.0% complete)

============================================================
Processing ID 15  (15_C.xdf)
  condition=Distrust Priming  video_condition=6
============================================================

Stream 16: Calculated effective sampling rate 145.3526 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (24519, 1)
  Sample count: 24519

Exported stream 1 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (81343, 1)
  Sample count: 81343

Exported stream 2 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (49038, 1)
  Sample count: 49038

Exported stream 3 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (81343, 1)
  Sample count: 81343

Exported stream 4 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (49036, 1)
  Sample count: 49036

Exported stream 5 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2910, 1)
  Sample count: 2910

Exported stream 7 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2051, 1)
  Sample count: 2051

Exported stream 8 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (81493, 1)
  Sample count: 81493

Exported stream 9 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (24517, 1)
  Sample count: 24517

Exported stream 10 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (81343, 1)
  Sample count: 81343

Exported stream 11 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (81493, 1)
  Sample count: 81493

Exported stream 12 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (24519, 1)
  Sample count: 24519

Exported stream 13 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (24517, 1)
  Sample count: 24517

Exported stream 14 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (81493, 1)
  Sample count: 81493

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (478357, 16)
  Sample count: 478357
  First timestamp: 2996396.060385361

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/15_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (81493 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 2996782.857 to 2999476.199
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=2996782.857, value=1.0
    t=2997390.755, value=2.0
    t=2997849.668, value=1.0
    t=2998466.435, value=2.0
    t=2998867.050, value=1.0
    t=2999476.199, value=2.0
  Added Reliability column using video condition 6: ('M', 'HH', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 75275/81493 matches (92.4%)
  DataSyncMarker value distribution:
    1.0: 45711 rows (56.1%)
    2.0: 29564 rows (36.3%)
Base PPG timestamps: 2996533.415 to 2999802.662

Processing EDA_I.csv...
  File timestamps: 2996533.541 to 2999802.589
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 51075/81493 matches (62.7%)

Processing THERM_I.csv...
  File timestamps: 2996533.525 to 2999802.561
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 25553/81493 matches (31.4%)

Processing PPG_RED_I.csv...
  File timestamps: 2996533.449 to 2999802.586
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 81490/81493 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 2996533.636 to 2999802.615
  Added 1 column(s) from HR_C.csv
    HR_C_value: 3028/81493 matches (3.7%)

Processing TEMP1_I.csv...
  File timestamps: 2996533.518 to 2999802.554
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 25550/81493 matches (31.4%)

Processing PPG_IR_C.csv...
  File timestamps: 2996533.414 to 2999802.661
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 81493/81493 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 2996533.449 to 2999802.587
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 81490/81493 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 2996533.448 to 2999802.586
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 81490/81493 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 2996533.519 to 2999802.615
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 25544/81493 matches (31.3%)

Processing EDA_C.csv...
  File timestamps: 2996533.476 to 2999802.621
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 51069/81493 matches (62.7%)

Processing HR_I.csv...
  File timestamps: 2996533.519 to 2999723.336
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2136/81493 matches (2.6%)

Processing TEMP1_C.csv...
  File timestamps: 2996533.512 to 2999802.608
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 25537/81493 matches (31.3%)

Processing PPG_RED_C.csv...
  File timestamps: 2996533.414 to 2999802.662
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 81493/81493 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 2996396.060 to 2999687.064
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 82276 samples (16 channels)
    x: 82276/82276 valid aggregated values (100.0%)
    y: 82276/82276 valid aggregated values (100.0%)
    PupilDiameter_left: 82276/82276 valid aggregated values (100.0%)
    EyeballCenterX_left: 82276/82276 valid aggregated values (100.0%)
    EyeballCenterY_left: 82276/82276 valid aggregated values (100.0%)
    EyeballCenterZ_left: 82276/82276 valid aggregated values (100.0%)
    OpticalAxisX_left: 82276/82276 valid aggregated values (100.0%)
    OpticalAxisY_left: 82276/82276 valid aggregated values (100.0%)
    OpticalAxisZ_left: 82276/82276 valid aggregated values (100.0%)
    PupilDiameter_right: 82276/82276 valid aggregated values (100.0%)
    EyeballCenterX_right: 82276/82276 valid aggregated values (100.0%)
    EyeballCenterY_right: 82276/82276 valid aggregated values (100.0%)
    EyeballCenterZ_right: 82276/82276 valid aggregated values (100.0%)
    OpticalAxisX_right: 82276/82276 valid aggregated values (100.0%)
    OpticalAxisY_right: 82276/82276 valid aggregated values (100.0%)
    OpticalAxisZ_right: 82276/82276 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_y: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 78611/81493 matches (96.5%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 78611/81493 matches (96.5%)

Processing temp_datasync_remaining.csv...
  File timestamps: 2996782.857 to 2999476.199
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 75275/81493 matches (92.4%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 6218:
  UNIX timestamp: 1755786340.827496
  EST time: 2025-08-21 10:25:40.827496052-04:00
  Corresponding EmotiBit timestamp: 2996782.865
Successfully created Date and Time columns for all 81493 rows (EST timezone)
Duration: 3269.25 seconds

Example rows around sync point (row 6218):
  Row 6216: EmotiBit=2996782.785, diff=-0.080s, Time=10:25:40.747
  Row 6217: EmotiBit=2996782.825, diff=-0.040s, Time=10:25:40.787
  Row 6218: EmotiBit=2996782.865, diff=+0.000s, Time=10:25:40.827 <- SYNC POINT
  Row 6219: EmotiBit=2996782.905, diff=+0.040s, Time=10:25:40.867
  Row 6220: EmotiBit=2996782.945, diff=+0.080s, Time=10:25:40.907

Applying forward fill to missing values...
Missing values before ffill: 507227
Missing values after ffill: 18680
Filled 488547 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 81493 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 2996533.415 to 2999802.662
Duration: 3269.25 seconds
Participant ID: 15
Condition: Distrust Priming
Video condition: 6

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 75275/81493 (92.4% complete)
DataSyncMarker_channel_1: 75275/81493 (92.4% complete)
Reliability: 75275/81493 (92.4% complete)
PPG_GRN_C: 81493/81493 (100.0% complete)
PPG_RED_C: 81493/81493 (100.0% complete)
PPG_IR_C: 81493/81493 (100.0% complete)
EDA_C: 81492/81493 (100.0% complete)
HR_C: 81488/81493 (100.0% complete)
TEMP_C: 81491/81493 (100.0% complete)
THERM_C: 81490/81493 (100.0% complete)
Neon Companion_Neon Gaze_x: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_y: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 81493/81493 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 81493/81493 (100.0% complete)
PPG_GRN_IS: 81492/81493 (100.0% complete)
PPG_RED_IS: 81492/81493 (100.0% complete)
PPG_IR_IS: 81492/81493 (100.0% complete)
EDA_IS: 81490/81493 (100.0% complete)
HR_IS: 81490/81493 (100.0% complete)
TEMP_IS: 81490/81493 (100.0% complete)
THERM_IS: 81490/81493 (100.0% complete)

============================================================
Processing ID 16  (16_C.xdf)
  condition=Trust Priming  video_condition=1
============================================================

Stream 4: Calculated effective sampling rate 166.4873 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2489, 1)
  Sample count: 2489

Exported stream 1 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (178687, 1)
  Sample count: 178687

Exported stream 2 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (53861, 1)
  Sample count: 53861

Exported stream 3 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (178687, 1)
  Sample count: 178687

Exported stream 4 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (53748, 1)
  Sample count: 53748

Exported stream 5 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (53749, 1)
  Sample count: 53749

Exported stream 6 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (178750, 1)
  Sample count: 178750

Exported stream 8 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (178750, 1)
  Sample count: 178750

Exported stream 9 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (178687, 1)
  Sample count: 178687

Exported stream 10 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (107497, 1)
  Sample count: 107497

Exported stream 11 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1924, 1)
  Sample count: 1924

Exported stream 12 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (107725, 1)
  Sample count: 107725

Exported stream 13 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (178750, 1)
  Sample count: 178750

Exported stream 14 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (53862, 1)
  Sample count: 53862

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (1199488, 16)
  Sample count: 1199488
  First timestamp: 3004230.1753874947

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (7, 2)
  Sample count: 7

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/16_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (178687 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 3004225.611 to 3007837.187
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 7 events
  DataSyncMarker events:
    t=3004225.611, value=1.0
    t=3004835.567, value=2.0
    t=3005307.483, value=1.0
    t=3005925.386, value=2.0
    t=3006159.304, value=1.0
    t=3006767.372, value=2.0
    t=3007837.187, value=2.2896334584515e-311
  Added Reliability column using video condition 1: ('LL', 'HH', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 175856/178687 matches (98.4%)
  DataSyncMarker value distribution:
    2.2896334584515e-311: 85809 rows (48.0%)
    1.0: 45775 rows (25.6%)
    2.0: 44272 rows (24.8%)
Base PPG timestamps: 3004112.104 to 3011278.734

Processing EDA_I.csv...
  File timestamps: 3004112.056 to 3011294.092
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 111983/178687 matches (62.7%)

Processing THERM_I.csv...
  File timestamps: 3004112.145 to 3011294.039
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 56014/178687 matches (31.3%)

Processing PPG_RED_I.csv...
  File timestamps: 3004112.608 to 3011294.671
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 178674/178687 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 3004112.030 to 3011277.960
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2599/178687 matches (1.5%)

Processing TEMP1_I.csv...
  File timestamps: 3004112.102 to 3011294.062
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 55984/178687 matches (31.3%)

Processing PPG_IR_C.csv...
  File timestamps: 3004112.102 to 3011278.733
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 178687/178687 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 3004112.609 to 3011294.672
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 178674/178687 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 3004112.608 to 3011294.670
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 178674/178687 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 3004111.932 to 3011278.489
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 56002/178687 matches (31.3%)

Processing EDA_C.csv...
  File timestamps: 3004111.981 to 3011278.481
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 111996/178687 matches (62.7%)

Processing HR_I.csv...
  File timestamps: 3004115.047 to 3011294.127
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2007/178687 matches (1.1%)

Processing TEMP1_C.csv...
  File timestamps: 3004112.009 to 3011278.504
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 55985/178687 matches (31.3%)

Processing PPG_RED_C.csv...
  File timestamps: 3004112.103 to 3011278.734
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 178687/178687 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 3004230.175 to 3011434.850
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 180117 samples (16 channels)
    x: 180117/180117 valid aggregated values (100.0%)
    y: 180117/180117 valid aggregated values (100.0%)
    PupilDiameter_left: 180117/180117 valid aggregated values (100.0%)
    EyeballCenterX_left: 180117/180117 valid aggregated values (100.0%)
    EyeballCenterY_left: 180117/180117 valid aggregated values (100.0%)
    EyeballCenterZ_left: 180117/180117 valid aggregated values (100.0%)
    OpticalAxisX_left: 180117/180117 valid aggregated values (100.0%)
    OpticalAxisY_left: 180117/180117 valid aggregated values (100.0%)
    OpticalAxisZ_left: 180117/180117 valid aggregated values (100.0%)
    PupilDiameter_right: 180117/180117 valid aggregated values (100.0%)
    EyeballCenterX_right: 180117/180117 valid aggregated values (100.0%)
    EyeballCenterY_right: 180117/180117 valid aggregated values (100.0%)
    EyeballCenterZ_right: 180117/180117 valid aggregated values (100.0%)
    OpticalAxisX_right: 180117/180117 valid aggregated values (100.0%)
    OpticalAxisY_right: 180117/180117 valid aggregated values (100.0%)
    OpticalAxisZ_right: 180117/180117 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_y: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 175743/178687 matches (98.4%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 175743/178687 matches (98.4%)

Processing temp_datasync_remaining.csv...
  File timestamps: 3004225.611 to 3007837.187
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 175856/178687 matches (98.4%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 2831:
  UNIX timestamp: 1755793783.542117
  EST time: 2025-08-21 12:29:43.542117119-04:00
  Corresponding EmotiBit timestamp: 3004225.648
Successfully created Date and Time columns for all 178687 rows (EST timezone)
Duration: 7166.63 seconds

Example rows around sync point (row 2831):
  Row 2829: EmotiBit=3004225.567, diff=-0.081s, Time=12:29:43.461
  Row 2830: EmotiBit=3004225.607, diff=-0.041s, Time=12:29:43.501
  Row 2831: EmotiBit=3004225.648, diff=+0.000s, Time=12:29:43.542 <- SYNC POINT
  Row 2832: EmotiBit=3004225.688, diff=+0.040s, Time=12:29:43.582
  Row 2833: EmotiBit=3004225.728, diff=+0.080s, Time=12:29:43.622

Applying forward fill to missing values...
Missing values before ffill: 1118371
Missing values after ffill: 55741
Filled 1062630 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 178687 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 3004112.104 to 3011278.734
Duration: 7166.63 seconds
Participant ID: 16
Condition: Trust Priming
Video condition: 1

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 175856/178687 (98.4% complete)
DataSyncMarker_channel_1: 175856/178687 (98.4% complete)
Reliability: 175856/178687 (98.4% complete)
PPG_GRN_C: 178687/178687 (100.0% complete)
PPG_RED_C: 178687/178687 (100.0% complete)
PPG_IR_C: 178687/178687 (100.0% complete)
EDA_C: 178687/178687 (100.0% complete)
HR_C: 178659/178687 (100.0% complete)
TEMP_C: 178686/178687 (100.0% complete)
THERM_C: 178685/178687 (100.0% complete)
Neon Companion_Neon Gaze_x: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_y: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 175743/178687 (98.4% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 175743/178687 (98.4% complete)
PPG_GRN_IS: 178674/178687 (100.0% complete)
PPG_RED_IS: 178674/178687 (100.0% complete)
PPG_IR_IS: 178674/178687 (100.0% complete)
EDA_IS: 178687/178687 (100.0% complete)
HR_IS: 178614/178687 (100.0% complete)
TEMP_IS: 178687/178687 (100.0% complete)
THERM_IS: 178686/178687 (100.0% complete)

============================================================
Processing ID 17  (17_C.xdf)
  condition=Distrust Priming  video_condition=1
============================================================

Stream 9: Calculated effective sampling rate 147.8954 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (74913, 1)
  Sample count: 74913

Exported stream 1 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2706, 1)
  Sample count: 2706

Exported stream 2 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (74745, 1)
  Sample count: 74745

Exported stream 3 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (74745, 1)
  Sample count: 74745

Exported stream 4 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (74913, 1)
  Sample count: 74913

Exported stream 5 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (22535, 1)
  Sample count: 22535

Exported stream 7 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (22535, 1)
  Sample count: 22535

Exported stream 8 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (74745, 1)
  Sample count: 74745

Exported stream 9 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (74913, 1)
  Sample count: 74913

Exported stream 10 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (22537, 1)
  Sample count: 22537

Exported stream 11 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (45070, 1)
  Sample count: 45070

Exported stream 12 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (45074, 1)
  Sample count: 45074

Exported stream 13 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (3006, 1)
  Sample count: 3006

Exported stream 14 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (22537, 1)
  Sample count: 22537

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (444045, 16)
  Sample count: 444045
  First timestamp: 3360078.676507973

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/17_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (74913 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 3360529.516 to 3362976.075
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=3360529.516, value=1.0
    t=3361140.400, value=2.0
    t=3361482.046, value=1.0
    t=3362095.547, value=2.0
    t=3362365.604, value=1.0
    t=3362976.075, value=2.0
  Added Reliability column using video condition 1: ('LL', 'HH', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 66197/74913 matches (88.4%)
  DataSyncMarker value distribution:
    1.0: 45745 rows (61.1%)
    2.0: 20452 rows (27.3%)
Base PPG timestamps: 3360179.956 to 3363184.666

Processing EDA_I.csv...
  File timestamps: 3360180.051 to 3363184.661
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 46935/74913 matches (62.7%)

Processing THERM_I.csv...
  File timestamps: 3360180.031 to 3363184.672
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 23473/74913 matches (31.3%)

Processing PPG_RED_I.csv...
  File timestamps: 3360179.817 to 3363184.668
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 74913/74913 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 3360182.284 to 3363180.093
  Added 1 column(s) from HR_C.csv
    HR_C_value: 3118/74913 matches (4.2%)

Processing TEMP1_I.csv...
  File timestamps: 3360180.024 to 3363184.664
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 23470/74913 matches (31.3%)

Processing PPG_IR_C.csv...
  File timestamps: 3360179.955 to 3363184.664
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 74913/74913 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 3360179.818 to 3363184.668
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 74913/74913 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 3360179.817 to 3363184.667
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 74913/74913 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 3360180.127 to 3363184.639
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 23484/74913 matches (31.3%)

Processing EDA_C.csv...
  File timestamps: 3360180.059 to 3363184.638
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 46951/74913 matches (62.7%)

Processing HR_I.csv...
  File timestamps: 3360267.647 to 3363184.511
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2819/74913 matches (3.8%)

Processing TEMP1_C.csv...
  File timestamps: 3360180.119 to 3363184.632
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 23461/74913 matches (31.3%)

Processing PPG_RED_C.csv...
  File timestamps: 3360179.956 to 3363184.665
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 74913/74913 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 3360078.677 to 3363081.096
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 75061 samples (16 channels)
    x: 75061/75061 valid aggregated values (100.0%)
    y: 75061/75061 valid aggregated values (100.0%)
    PupilDiameter_left: 75061/75061 valid aggregated values (100.0%)
    EyeballCenterX_left: 75061/75061 valid aggregated values (100.0%)
    EyeballCenterY_left: 75061/75061 valid aggregated values (100.0%)
    EyeballCenterZ_left: 75061/75061 valid aggregated values (100.0%)
    OpticalAxisX_left: 75061/75061 valid aggregated values (100.0%)
    OpticalAxisY_left: 75061/75061 valid aggregated values (100.0%)
    OpticalAxisZ_left: 75061/75061 valid aggregated values (100.0%)
    PupilDiameter_right: 75061/75061 valid aggregated values (100.0%)
    EyeballCenterX_right: 75061/75061 valid aggregated values (100.0%)
    EyeballCenterY_right: 75061/75061 valid aggregated values (100.0%)
    EyeballCenterZ_right: 75061/75061 valid aggregated values (100.0%)
    OpticalAxisX_right: 75061/75061 valid aggregated values (100.0%)
    OpticalAxisY_right: 75061/75061 valid aggregated values (100.0%)
    OpticalAxisZ_right: 75061/75061 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_y: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 72330/74913 matches (96.6%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 72330/74913 matches (96.6%)

Processing temp_datasync_remaining.csv...
  File timestamps: 3360529.516 to 3362976.075
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 66197/74913 matches (88.4%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 8716:
  UNIX timestamp: 1756150087.147991
  EST time: 2025-08-25 15:28:07.147990942-04:00
  Corresponding EmotiBit timestamp: 3360529.554
Successfully created Date and Time columns for all 74913 rows (EST timezone)
Duration: 3004.71 seconds

Example rows around sync point (row 8716):
  Row 8714: EmotiBit=3360529.474, diff=-0.080s, Time=15:28:07.067
  Row 8715: EmotiBit=3360529.514, diff=-0.040s, Time=15:28:07.107
  Row 8716: EmotiBit=3360529.554, diff=+0.000s, Time=15:28:07.147 <- SYNC POINT
  Row 8717: EmotiBit=3360529.594, diff=+0.040s, Time=15:28:07.187
  Row 8718: EmotiBit=3360529.634, diff=+0.080s, Time=15:28:07.227

Applying forward fill to missing values...
Missing values before ffill: 473069
Missing values after ffill: 28409
Filled 444660 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 74913 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 3360179.956 to 3363184.666
Duration: 3004.71 seconds
Participant ID: 17
Condition: Distrust Priming
Video condition: 1

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 66197/74913 (88.4% complete)
DataSyncMarker_channel_1: 66197/74913 (88.4% complete)
Reliability: 66197/74913 (88.4% complete)
PPG_GRN_C: 74913/74913 (100.0% complete)
PPG_RED_C: 74913/74913 (100.0% complete)
PPG_IR_C: 74913/74913 (100.0% complete)
EDA_C: 74910/74913 (100.0% complete)
HR_C: 74855/74913 (99.9% complete)
TEMP_C: 74909/74913 (100.0% complete)
THERM_C: 74909/74913 (100.0% complete)
Neon Companion_Neon Gaze_x: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_y: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 74913/74913 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 74913/74913 (100.0% complete)
PPG_GRN_IS: 74913/74913 (100.0% complete)
PPG_RED_IS: 74913/74913 (100.0% complete)
PPG_IR_IS: 74913/74913 (100.0% complete)
EDA_IS: 74911/74913 (100.0% complete)
HR_IS: 72727/74913 (97.1% complete)
TEMP_IS: 74911/74913 (100.0% complete)
THERM_IS: 74911/74913 (100.0% complete)

============================================================
Processing ID 18  (18_C.xdf)
  condition=Trust Priming  video_condition=2
============================================================

Stream 8: Calculated effective sampling rate 141.8641 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (75840, 1)
  Sample count: 75840

Exported stream 1 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (75840, 1)
  Sample count: 75840

Exported stream 3 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2191, 1)
  Sample count: 2191

Exported stream 4 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (75840, 1)
  Sample count: 75840

Exported stream 5 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (75984, 1)
  Sample count: 75984

Exported stream 6 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (22859, 1)
  Sample count: 22859

Exported stream 7 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (75984, 1)
  Sample count: 75984

Exported stream 8 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (22858, 1)
  Sample count: 22858

Exported stream 9 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (45715, 1)
  Sample count: 45715

Exported stream 10 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (75984, 1)
  Sample count: 75984

Exported stream 11 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (22859, 1)
  Sample count: 22859

Exported stream 12 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2018, 1)
  Sample count: 2018

Exported stream 13 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (22858, 1)
  Sample count: 22858

Exported stream 14 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (45717, 1)
  Sample count: 45717

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (436748, 16)
  Sample count: 436748
  First timestamp: 3367148.093878311

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/18_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (75984 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 3367396.902 to 3370006.619
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=3367396.902, value=1.0
    t=3368004.721, value=2.0
    t=3368420.173, value=1.0
    t=3369028.644, value=2.0
    t=3369385.111, value=1.0
    t=3370006.619, value=2.0
  Added Reliability column using video condition 2: ('LL', 'M', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 72636/75984 matches (95.6%)
  DataSyncMarker value distribution:
    1.0: 45820 rows (60.3%)
    2.0: 26816 rows (35.3%)
Base PPG timestamps: 3367262.633 to 3370310.254

Processing EDA_I.csv...
  File timestamps: 3367262.698 to 3370310.296
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 47611/75984 matches (62.7%)

Processing THERM_I.csv...
  File timestamps: 3367262.722 to 3370310.232
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 23801/75984 matches (31.3%)

Processing PPG_RED_I.csv...
  File timestamps: 3367262.664 to 3370310.334
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 75983/75984 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 3367262.969 to 3370310.308
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2293/75984 matches (3.0%)

Processing TEMP1_I.csv...
  File timestamps: 3367262.848 to 3370310.358
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 23816/75984 matches (31.3%)

Processing PPG_IR_C.csv...
  File timestamps: 3367262.632 to 3370310.253
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 75984/75984 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 3367262.664 to 3370310.335
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 75983/75984 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 3367262.663 to 3370310.334
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 75983/75984 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 3367262.628 to 3370310.229
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 23816/75984 matches (31.3%)

Processing EDA_C.csv...
  File timestamps: 3367262.627 to 3370310.227
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 47633/75984 matches (62.7%)

Processing HR_I.csv...
  File timestamps: 3367264.468 to 3370306.392
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2110/75984 matches (2.8%)

Processing TEMP1_C.csv...
  File timestamps: 3367262.620 to 3370310.221
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 23812/75984 matches (31.3%)

Processing PPG_RED_C.csv...
  File timestamps: 3367262.632 to 3370310.253
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 75984/75984 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 3367148.094 to 3370226.722
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 76966 samples (16 channels)
    x: 76966/76966 valid aggregated values (100.0%)
    y: 76966/76966 valid aggregated values (100.0%)
    PupilDiameter_left: 76966/76966 valid aggregated values (100.0%)
    EyeballCenterX_left: 76966/76966 valid aggregated values (100.0%)
    EyeballCenterY_left: 76966/76966 valid aggregated values (100.0%)
    EyeballCenterZ_left: 76966/76966 valid aggregated values (100.0%)
    OpticalAxisX_left: 76966/76966 valid aggregated values (100.0%)
    OpticalAxisY_left: 76966/76966 valid aggregated values (100.0%)
    OpticalAxisZ_left: 76966/76966 valid aggregated values (100.0%)
    PupilDiameter_right: 76966/76966 valid aggregated values (100.0%)
    EyeballCenterX_right: 76966/76966 valid aggregated values (100.0%)
    EyeballCenterY_right: 76966/76966 valid aggregated values (100.0%)
    EyeballCenterZ_right: 76966/76966 valid aggregated values (100.0%)
    OpticalAxisX_right: 76966/76966 valid aggregated values (100.0%)
    OpticalAxisY_right: 76966/76966 valid aggregated values (100.0%)
    OpticalAxisZ_right: 76966/76966 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_y: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 73901/75984 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 73901/75984 matches (97.3%)

Processing temp_datasync_remaining.csv...
  File timestamps: 3367396.902 to 3370006.619
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 72636/75984 matches (95.6%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3348:
  UNIX timestamp: 1756156954.4512792
  EST time: 2025-08-25 17:22:34.451279163-04:00
  Corresponding EmotiBit timestamp: 3367396.919
Successfully created Date and Time columns for all 75984 rows (EST timezone)
Duration: 3047.62 seconds

Example rows around sync point (row 3348):
  Row 3346: EmotiBit=3367396.838, diff=-0.081s, Time=17:22:34.370
  Row 3347: EmotiBit=3367396.878, diff=-0.041s, Time=17:22:34.410
  Row 3348: EmotiBit=3367396.919, diff=+0.000s, Time=17:22:34.451 <- SYNC POINT
  Row 3349: EmotiBit=3367396.959, diff=+0.040s, Time=17:22:34.491
  Row 3350: EmotiBit=3367396.999, diff=+0.080s, Time=17:22:34.531

Applying forward fill to missing values...
Missing values before ffill: 456355
Missing values after ffill: 10110
Filled 446245 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 75984 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 3367262.633 to 3370310.254
Duration: 3047.62 seconds
Participant ID: 18
Condition: Trust Priming
Video condition: 2

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 72636/75984 (95.6% complete)
DataSyncMarker_channel_1: 72636/75984 (95.6% complete)
Reliability: 72636/75984 (95.6% complete)
PPG_GRN_C: 75984/75984 (100.0% complete)
PPG_RED_C: 75984/75984 (100.0% complete)
PPG_IR_C: 75984/75984 (100.0% complete)
EDA_C: 75984/75984 (100.0% complete)
HR_C: 75976/75984 (100.0% complete)
TEMP_C: 75984/75984 (100.0% complete)
THERM_C: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_x: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_y: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 75984/75984 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 75984/75984 (100.0% complete)
PPG_GRN_IS: 75983/75984 (100.0% complete)
PPG_RED_IS: 75983/75984 (100.0% complete)
PPG_IR_IS: 75983/75984 (100.0% complete)
EDA_IS: 75982/75984 (100.0% complete)
HR_IS: 75938/75984 (99.9% complete)
TEMP_IS: 75979/75984 (100.0% complete)
THERM_IS: 75982/75984 (100.0% complete)

============================================================
Processing ID 19  (19_C.xdf)
  condition=Distrust Priming  video_condition=2
============================================================

Stream 6: Calculated effective sampling rate 153.1732 Hz is different from specified rate 200.0000 Hz.

Exported stream 1 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (22094, 1)
  Sample count: 22094

Exported stream 2 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (22094, 1)
  Sample count: 22094

Exported stream 3 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (44190, 1)
  Sample count: 44190

Exported stream 4 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73447, 1)
  Sample count: 73447

Exported stream 5 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (73289, 1)
  Sample count: 73289

Exported stream 6 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (3710, 1)
  Sample count: 3710

Exported stream 7 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (22095, 1)
  Sample count: 22095

Exported stream 8 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (73289, 1)
  Sample count: 73289

Exported stream 9 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2033, 1)
  Sample count: 2033

Exported stream 10 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (44186, 1)
  Sample count: 44186

Exported stream 11 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (22095, 1)
  Sample count: 22095

Exported stream 12 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (73289, 1)
  Sample count: 73289

Exported stream 13 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73447, 1)
  Sample count: 73447

Exported stream 14 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73447, 1)
  Sample count: 73447

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (453196, 16)
  Sample count: 453196
  First timestamp: 3428109.752249811

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/19_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (73447 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 3428370.993 to 3430852.044
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=3428370.993, value=1.0
    t=3428980.122, value=2.0
    t=3429345.802, value=1.0
    t=3429953.434, value=2.0
    t=3430229.458, value=1.0
    t=3430852.044, value=2.0
  Added Reliability column using video condition 2: ('LL', 'M', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 69219/73447 matches (94.2%)
  DataSyncMarker value distribution:
    1.0: 45859 rows (62.4%)
    2.0: 23360 rows (31.8%)
Base PPG timestamps: 3428201.431 to 3431147.208

Processing EDA_I.csv...
  File timestamps: 3428201.551 to 3431147.210
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 46033/73447 matches (62.7%)

Processing THERM_I.csv...
  File timestamps: 3428201.534 to 3431147.192
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 23021/73447 matches (31.3%)

Processing PPG_RED_I.csv...
  File timestamps: 3428201.392 to 3431147.171
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 73446/73447 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 3428208.337 to 3431146.417
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2109/73447 matches (2.9%)

Processing TEMP1_I.csv...
  File timestamps: 3428201.526 to 3431147.184
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 23020/73447 matches (31.3%)

Processing PPG_IR_C.csv...
  File timestamps: 3428201.430 to 3431147.207
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 73447/73447 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 3428201.392 to 3431147.172
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 73446/73447 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 3428201.391 to 3431147.171
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 73446/73447 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 3428201.460 to 3431147.046
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 23015/73447 matches (31.3%)

Processing EDA_C.csv...
  File timestamps: 3428201.459 to 3431147.112
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 46027/73447 matches (62.7%)

Processing HR_I.csv...
  File timestamps: 3428202.655 to 3431143.867
  Added 1 column(s) from HR_I.csv
    HR_I_value: 3865/73447 matches (5.3%)

Processing TEMP1_C.csv...
  File timestamps: 3428201.453 to 3431147.039
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 23011/73447 matches (31.3%)

Processing PPG_RED_C.csv...
  File timestamps: 3428201.430 to 3431147.207
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 73447/73447 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 3428109.752 to 3431068.461
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 73968 samples (16 channels)
    x: 73968/73968 valid aggregated values (100.0%)
    y: 73968/73968 valid aggregated values (100.0%)
    PupilDiameter_left: 73968/73968 valid aggregated values (100.0%)
    EyeballCenterX_left: 73968/73968 valid aggregated values (100.0%)
    EyeballCenterY_left: 73968/73968 valid aggregated values (100.0%)
    EyeballCenterZ_left: 73968/73968 valid aggregated values (100.0%)
    OpticalAxisX_left: 73968/73968 valid aggregated values (100.0%)
    OpticalAxisY_left: 73968/73968 valid aggregated values (100.0%)
    OpticalAxisZ_left: 73968/73968 valid aggregated values (100.0%)
    PupilDiameter_right: 73968/73968 valid aggregated values (100.0%)
    EyeballCenterX_right: 73968/73968 valid aggregated values (100.0%)
    EyeballCenterY_right: 73968/73968 valid aggregated values (100.0%)
    EyeballCenterZ_right: 73968/73968 valid aggregated values (100.0%)
    OpticalAxisX_right: 73968/73968 valid aggregated values (100.0%)
    OpticalAxisY_right: 73968/73968 valid aggregated values (100.0%)
    OpticalAxisZ_right: 73968/73968 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_y: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 71483/73447 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 71483/73447 matches (97.3%)

Processing temp_datasync_remaining.csv...
  File timestamps: 3428370.993 to 3430852.044
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 69219/73447 matches (94.2%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 4228:
  UNIX timestamp: 1756217928.473129
  EST time: 2025-08-26 10:18:48.473129034-04:00
  Corresponding EmotiBit timestamp: 3428371.008
Successfully created Date and Time columns for all 73447 rows (EST timezone)
Duration: 2945.78 seconds

Example rows around sync point (row 4228):
  Row 4226: EmotiBit=3428370.928, diff=-0.080s, Time=10:18:48.393
  Row 4227: EmotiBit=3428370.968, diff=-0.040s, Time=10:18:48.433
  Row 4228: EmotiBit=3428371.008, diff=+0.000s, Time=10:18:48.473 <- SYNC POINT
  Row 4229: EmotiBit=3428371.048, diff=+0.040s, Time=10:18:48.513
  Row 4230: EmotiBit=3428371.088, diff=+0.080s, Time=10:18:48.553

Applying forward fill to missing values...
Missing values before ffill: 441586
Missing values after ffill: 12897
Filled 428689 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 73447 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 3428201.431 to 3431147.208
Duration: 2945.78 seconds
Participant ID: 19
Condition: Distrust Priming
Video condition: 2

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 69219/73447 (94.2% complete)
DataSyncMarker_channel_1: 69219/73447 (94.2% complete)
Reliability: 69219/73447 (94.2% complete)
PPG_GRN_C: 73447/73447 (100.0% complete)
PPG_RED_C: 73447/73447 (100.0% complete)
PPG_IR_C: 73447/73447 (100.0% complete)
EDA_C: 73446/73447 (100.0% complete)
HR_C: 73275/73447 (99.8% complete)
TEMP_C: 73446/73447 (100.0% complete)
THERM_C: 73446/73447 (100.0% complete)
Neon Companion_Neon Gaze_x: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_y: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 73447/73447 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 73447/73447 (100.0% complete)
PPG_GRN_IS: 73447/73447 (100.0% complete)
PPG_RED_IS: 73447/73447 (100.0% complete)
PPG_IR_IS: 73447/73447 (100.0% complete)
EDA_IS: 73444/73447 (100.0% complete)
HR_IS: 73417/73447 (100.0% complete)
TEMP_IS: 73445/73447 (100.0% complete)
THERM_IS: 73444/73447 (100.0% complete)

============================================================
Processing ID 20  (20_C.xdf)
  condition=Trust Priming  video_condition=3
============================================================

Stream 2: Calculated effective sampling rate 147.7553 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (23659, 1)
  Sample count: 23659

Exported stream 1 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78651, 1)
  Sample count: 78651

Exported stream 2 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (47317, 1)
  Sample count: 47317

Exported stream 4 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23662, 1)
  Sample count: 23662

Exported stream 5 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (78488, 1)
  Sample count: 78488

Exported stream 6 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (78486, 1)
  Sample count: 78486

Exported stream 7 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23662, 1)
  Sample count: 23662

Exported stream 8 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78648, 1)
  Sample count: 78648

Exported stream 9 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2329, 1)
  Sample count: 2329

Exported stream 10 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78648, 1)
  Sample count: 78648

Exported stream 11 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (47322, 1)
  Sample count: 47322

Exported stream 12 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2527, 1)
  Sample count: 2527

Exported stream 13 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (23659, 1)
  Sample count: 23659

Exported stream 14 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (78486, 1)
  Sample count: 78486

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (471778, 16)
  Sample count: 471778
  First timestamp: 3435541.7746262643

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/20_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (78648 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 3435821.344 to 3438490.196
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=3435821.344, value=1.0
    t=3436438.129, value=2.0
    t=3436929.242, value=1.0
    t=3437539.148, value=2.0
    t=3437882.010, value=1.0
    t=3438490.196, value=2.0
  Added Reliability column using video condition 3: ('HH', 'LL', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 74355/78648 matches (94.5%)
  DataSyncMarker value distribution:
    1.0: 45745 rows (58.2%)
    2.0: 28610 rows (36.4%)
Base PPG timestamps: 3435649.174 to 3438803.759

Processing EDA_I.csv...
  File timestamps: 3435649.049 to 3438803.856
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 49294/78648 matches (62.7%)

Processing THERM_I.csv...
  File timestamps: 3435649.164 to 3438803.735
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 24651/78648 matches (31.3%)

Processing PPG_RED_I.csv...
  File timestamps: 3435649.081 to 3438803.831
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 78648/78648 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 3435650.822 to 3438803.074
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2615/78648 matches (3.3%)

Processing TEMP1_I.csv...
  File timestamps: 3435649.156 to 3438803.728
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 24643/78648 matches (31.3%)

Processing PPG_IR_C.csv...
  File timestamps: 3435649.173 to 3438803.758
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 78648/78648 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 3435649.001 to 3438803.831
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 78648/78648 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 3435649.080 to 3438803.830
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 78648/78648 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 3435649.174 to 3438803.671
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 24651/78648 matches (31.3%)

Processing EDA_C.csv...
  File timestamps: 3435649.208 to 3438803.773
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 49323/78648 matches (62.7%)

Processing HR_I.csv...
  File timestamps: 3435649.257 to 3438798.441
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2435/78648 matches (3.1%)

Processing TEMP1_C.csv...
  File timestamps: 3435649.166 to 3438803.663
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 24650/78648 matches (31.3%)

Processing PPG_RED_C.csv...
  File timestamps: 3435649.053 to 3438803.759
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 78648/78648 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 3435541.775 to 3438734.737
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 79825 samples (16 channels)
    x: 79825/79825 valid aggregated values (100.0%)
    y: 79825/79825 valid aggregated values (100.0%)
    PupilDiameter_left: 79825/79825 valid aggregated values (100.0%)
    EyeballCenterX_left: 79825/79825 valid aggregated values (100.0%)
    EyeballCenterY_left: 79825/79825 valid aggregated values (100.0%)
    EyeballCenterZ_left: 79825/79825 valid aggregated values (100.0%)
    OpticalAxisX_left: 79825/79825 valid aggregated values (100.0%)
    OpticalAxisY_left: 79825/79825 valid aggregated values (100.0%)
    OpticalAxisZ_left: 79825/79825 valid aggregated values (100.0%)
    PupilDiameter_right: 79825/79825 valid aggregated values (100.0%)
    EyeballCenterX_right: 79825/79825 valid aggregated values (100.0%)
    EyeballCenterY_right: 79825/79825 valid aggregated values (100.0%)
    EyeballCenterZ_right: 79825/79825 valid aggregated values (100.0%)
    OpticalAxisX_right: 79825/79825 valid aggregated values (100.0%)
    OpticalAxisY_right: 79825/79825 valid aggregated values (100.0%)
    OpticalAxisZ_right: 79825/79825 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_y: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 76927/78648 matches (97.8%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 76927/78648 matches (97.8%)

Processing temp_datasync_remaining.csv...
  File timestamps: 3435821.344 to 3438490.196
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 74355/78648 matches (94.5%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 4293:
  UNIX timestamp: 1756225378.891856
  EST time: 2025-08-26 12:22:58.891855955-04:00
  Corresponding EmotiBit timestamp: 3435821.369
Successfully created Date and Time columns for all 78648 rows (EST timezone)
Duration: 3154.59 seconds

Example rows around sync point (row 4293):
  Row 4291: EmotiBit=3435821.289, diff=-0.080s, Time=12:22:58.811
  Row 4292: EmotiBit=3435821.329, diff=-0.040s, Time=12:22:58.851
  Row 4293: EmotiBit=3435821.369, diff=+0.000s, Time=12:22:58.891 <- SYNC POINT
  Row 4294: EmotiBit=3435821.409, diff=+0.040s, Time=12:22:58.931
  Row 4295: EmotiBit=3435821.449, diff=+0.080s, Time=12:22:58.971

Applying forward fill to missing values...
Missing values before ffill: 467337
Missing values after ffill: 12923
Filled 454414 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 78648 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 3435649.174 to 3438803.759
Duration: 3154.58 seconds
Participant ID: 20
Condition: Trust Priming
Video condition: 3

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 74355/78648 (94.5% complete)
DataSyncMarker_channel_1: 74355/78648 (94.5% complete)
Reliability: 74355/78648 (94.5% complete)
PPG_GRN_C: 78648/78648 (100.0% complete)
PPG_RED_C: 78648/78648 (100.0% complete)
PPG_IR_C: 78648/78648 (100.0% complete)
EDA_C: 78647/78648 (100.0% complete)
HR_C: 78607/78648 (99.9% complete)
TEMP_C: 78648/78648 (100.0% complete)
THERM_C: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_x: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_y: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 78648/78648 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 78648/78648 (100.0% complete)
PPG_GRN_IS: 78648/78648 (100.0% complete)
PPG_RED_IS: 78648/78648 (100.0% complete)
PPG_IR_IS: 78648/78648 (100.0% complete)
EDA_IS: 78648/78648 (100.0% complete)
HR_IS: 78646/78648 (100.0% complete)
TEMP_IS: 78648/78648 (100.0% complete)
THERM_IS: 78648/78648 (100.0% complete)

============================================================
Processing ID 21  (21_C.xdf)
  condition=Distrust Priming  video_condition=3
============================================================

Stream 5: Calculated effective sampling rate 142.2360 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (23455, 1)
  Sample count: 23455

Exported stream 1 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23456, 1)
  Sample count: 23456

Exported stream 2 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (3053, 1)
  Sample count: 3053

Exported stream 3 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (77796, 1)
  Sample count: 77796

Exported stream 4 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23456, 1)
  Sample count: 23456

Exported stream 5 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (77970, 1)
  Sample count: 77970

Exported stream 6 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (3151, 1)
  Sample count: 3151

Exported stream 7 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (46912, 1)
  Sample count: 46912

Exported stream 8 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (46911, 1)
  Sample count: 46911

Exported stream 9 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (77970, 1)
  Sample count: 77970

Exported stream 11 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (77796, 1)
  Sample count: 77796

Exported stream 12 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (23456, 1)
  Sample count: 23456

Exported stream 13 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (77970, 1)
  Sample count: 77970

Exported stream 14 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (77796, 1)
  Sample count: 77796

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (466949, 16)
  Sample count: 466949
  First timestamp: 88242.50286453191

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/21_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (77970 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 88565.470 to 90978.568
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=88565.470, value=1.0
    t=89182.802, value=2.0
    t=89549.342, value=1.0
    t=90157.804, value=2.0
    t=90368.962, value=1.0
    t=90978.568, value=2.0
  Added Reliability column using video condition 3: ('HH', 'LL', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 72945/77970 matches (93.6%)
  DataSyncMarker value distribution:
    1.0: 45764 rows (58.7%)
    2.0: 27181 rows (34.9%)
Base PPG timestamps: 88363.934 to 91491.037

Processing EDA_I.csv...
  File timestamps: 88363.985 to 91491.103
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 49233/77970 matches (63.1%)

Processing THERM_I.csv...
  File timestamps: 88363.986 to 91491.037
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 24613/77970 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 88363.877 to 91491.141
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 77970/77970 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 88375.462 to 91490.437
  Added 1 column(s) from HR_C.csv
    HR_C_value: 3307/77970 matches (4.2%)

Processing TEMP1_I.csv...
  File timestamps: 88364.112 to 91491.030
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 24614/77970 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 88363.933 to 91491.036
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 77970/77970 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 88363.878 to 91491.141
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 77970/77970 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 88363.877 to 91491.140
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 77970/77970 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 88363.976 to 91491.016
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 24621/77970 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 88363.955 to 91491.064
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 49219/77970 matches (63.1%)

Processing HR_I.csv...
  File timestamps: 88364.412 to 91488.504
  Added 1 column(s) from HR_I.csv
    HR_I_value: 3199/77970 matches (4.1%)

Processing TEMP1_C.csv...
  File timestamps: 88363.969 to 91491.009
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 24611/77970 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 88363.934 to 91491.036
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 77970/77970 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 88242.503 to 91525.414
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 82073 samples (16 channels)
    x: 82073/82073 valid aggregated values (100.0%)
    y: 82073/82073 valid aggregated values (100.0%)
    PupilDiameter_left: 82073/82073 valid aggregated values (100.0%)
    EyeballCenterX_left: 82073/82073 valid aggregated values (100.0%)
    EyeballCenterY_left: 82073/82073 valid aggregated values (100.0%)
    EyeballCenterZ_left: 82073/82073 valid aggregated values (100.0%)
    OpticalAxisX_left: 82073/82073 valid aggregated values (100.0%)
    OpticalAxisY_left: 82073/82073 valid aggregated values (100.0%)
    OpticalAxisZ_left: 82073/82073 valid aggregated values (100.0%)
    PupilDiameter_right: 82073/82073 valid aggregated values (100.0%)
    EyeballCenterX_right: 82073/82073 valid aggregated values (100.0%)
    EyeballCenterY_right: 82073/82073 valid aggregated values (100.0%)
    EyeballCenterZ_right: 82073/82073 valid aggregated values (100.0%)
    OpticalAxisX_right: 82073/82073 valid aggregated values (100.0%)
    OpticalAxisY_right: 82073/82073 valid aggregated values (100.0%)
    OpticalAxisZ_right: 82073/82073 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_y: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 77970/77970 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 77970/77970 matches (100.0%)

Processing temp_datasync_remaining.csv...
  File timestamps: 88565.470 to 90978.568
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 72945/77970 matches (93.6%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 5025:
  UNIX timestamp: 1756318989.578233
  EST time: 2025-08-27 14:23:09.578233004-04:00
  Corresponding EmotiBit timestamp: 88565.472
Successfully created Date and Time columns for all 77970 rows (EST timezone)
Duration: 3127.10 seconds

Example rows around sync point (row 5025):
  Row 5023: EmotiBit=88565.392, diff=-0.080s, Time=14:23:09.498
  Row 5024: EmotiBit=88565.432, diff=-0.040s, Time=14:23:09.538
  Row 5025: EmotiBit=88565.472, diff=+0.000s, Time=14:23:09.578 <- SYNC POINT
  Row 5026: EmotiBit=88565.512, diff=+0.040s, Time=14:23:09.618
  Row 5027: EmotiBit=88565.552, diff=+0.080s, Time=14:23:09.658

Applying forward fill to missing values...
Missing values before ffill: 435418
Missing values after ffill: 15383
Filled 420035 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 77970 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 88363.934 to 91491.037
Duration: 3127.10 seconds
Participant ID: 21
Condition: Distrust Priming
Video condition: 3

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 72945/77970 (93.6% complete)
DataSyncMarker_channel_1: 72945/77970 (93.6% complete)
Reliability: 72945/77970 (93.6% complete)
PPG_GRN_C: 77970/77970 (100.0% complete)
PPG_RED_C: 77970/77970 (100.0% complete)
PPG_IR_C: 77970/77970 (100.0% complete)
EDA_C: 77969/77970 (100.0% complete)
HR_C: 77683/77970 (99.6% complete)
TEMP_C: 77969/77970 (100.0% complete)
THERM_C: 77969/77970 (100.0% complete)
Neon Companion_Neon Gaze_x: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_y: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 77970/77970 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 77970/77970 (100.0% complete)
PPG_GRN_IS: 77970/77970 (100.0% complete)
PPG_RED_IS: 77970/77970 (100.0% complete)
PPG_IR_IS: 77970/77970 (100.0% complete)
EDA_IS: 77969/77970 (100.0% complete)
HR_IS: 77958/77970 (100.0% complete)
TEMP_IS: 77966/77970 (100.0% complete)
THERM_IS: 77969/77970 (100.0% complete)

============================================================
Processing ID 22  (22_C.xdf)
  condition=Trust Priming  video_condition=4
============================================================

Stream 5: Calculated effective sampling rate 140.7036 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (25596, 1)
  Sample count: 25596

Exported stream 1 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (3233, 1)
  Sample count: 3233

Exported stream 2 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (51199, 1)
  Sample count: 51199

Exported stream 3 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (85098, 1)
  Sample count: 85098

Exported stream 4 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (85098, 1)
  Sample count: 85098

Exported stream 5 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (84911, 1)
  Sample count: 84911

Exported stream 6 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (84911, 1)
  Sample count: 84911

Exported stream 7 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (25599, 1)
  Sample count: 25599

Exported stream 8 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (25596, 1)
  Sample count: 25596

Exported stream 9 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (51192, 1)
  Sample count: 51192

Exported stream 11 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (25599, 1)
  Sample count: 25599

Exported stream 12 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (84911, 1)
  Sample count: 84911

Exported stream 13 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (85098, 1)
  Sample count: 85098

Exported stream 14 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (3067, 1)
  Sample count: 3067

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (502650, 16)
  Sample count: 502650
  First timestamp: 95252.15675968268

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/22_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (85098 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 95569.589 to 98094.002
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=95569.589, value=1.0
    t=96182.346, value=2.0
    t=96558.472, value=1.0
    t=97167.524, value=2.0
    t=97477.175, value=1.0
    t=98094.002, value=2.0
  Added Reliability column using video condition 4: ('HH', 'M', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 80621/85098 matches (94.7%)
  DataSyncMarker value distribution:
    1.0: 45837 rows (53.9%)
    2.0: 34784 rows (40.9%)
Base PPG timestamps: 95390.045 to 98803.417

Processing EDA_I.csv...
  File timestamps: 95390.092 to 98803.386
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 53723/85098 matches (63.1%)

Processing THERM_I.csv...
  File timestamps: 95390.154 to 98803.332
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 26854/85098 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 95390.053 to 98803.344
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 85096/85098 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 95390.358 to 98798.336
  Added 1 column(s) from HR_C.csv
    HR_C_value: 3227/85098 matches (3.8%)

Processing TEMP1_I.csv...
  File timestamps: 95390.147 to 98803.325
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 26860/85098 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 95390.044 to 98803.415
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 85098/85098 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 95390.053 to 98803.345
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 85096/85098 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 95390.052 to 98803.344
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 85096/85098 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 95390.090 to 98803.352
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 26845/85098 matches (31.5%)

Processing EDA_C.csv...
  File timestamps: 95390.087 to 98803.344
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 53710/85098 matches (63.1%)

Processing HR_I.csv...
  File timestamps: 95390.525 to 98790.571
  Added 1 column(s) from HR_I.csv
    HR_I_value: 3406/85098 matches (4.0%)

Processing TEMP1_C.csv...
  File timestamps: 95390.139 to 98803.372
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 26862/85098 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 95390.045 to 98803.416
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 85098/85098 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 95252.157 to 98824.554
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 89310 samples (16 channels)
    x: 89310/89310 valid aggregated values (100.0%)
    y: 89310/89310 valid aggregated values (100.0%)
    PupilDiameter_left: 89310/89310 valid aggregated values (100.0%)
    EyeballCenterX_left: 89310/89310 valid aggregated values (100.0%)
    EyeballCenterY_left: 89310/89310 valid aggregated values (100.0%)
    EyeballCenterZ_left: 89310/89310 valid aggregated values (100.0%)
    OpticalAxisX_left: 89310/89310 valid aggregated values (100.0%)
    OpticalAxisY_left: 89310/89310 valid aggregated values (100.0%)
    OpticalAxisZ_left: 89310/89310 valid aggregated values (100.0%)
    PupilDiameter_right: 89310/89310 valid aggregated values (100.0%)
    EyeballCenterX_right: 89310/89310 valid aggregated values (100.0%)
    EyeballCenterY_right: 89310/89310 valid aggregated values (100.0%)
    EyeballCenterZ_right: 89310/89310 valid aggregated values (100.0%)
    OpticalAxisX_right: 89310/89310 valid aggregated values (100.0%)
    OpticalAxisY_right: 89310/89310 valid aggregated values (100.0%)
    OpticalAxisZ_right: 89310/89310 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_y: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 85098/85098 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 85098/85098 matches (100.0%)

Processing temp_datasync_remaining.csv...
  File timestamps: 95569.589 to 98094.002
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 80621/85098 matches (94.7%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 4477:
  UNIX timestamp: 1756325993.708443
  EST time: 2025-08-27 16:19:53.708442926-04:00
  Corresponding EmotiBit timestamp: 95569.625
Successfully created Date and Time columns for all 85098 rows (EST timezone)
Duration: 3413.37 seconds

Example rows around sync point (row 4477):
  Row 4475: EmotiBit=95569.544, diff=-0.081s, Time=16:19:53.627
  Row 4476: EmotiBit=95569.585, diff=-0.040s, Time=16:19:53.668
  Row 4477: EmotiBit=95569.625, diff=+0.000s, Time=16:19:53.708 <- SYNC POINT
  Row 4478: EmotiBit=95569.665, diff=+0.040s, Time=16:19:53.748
  Row 4479: EmotiBit=95569.705, diff=+0.080s, Time=16:19:53.788

Applying forward fill to missing values...
Missing values before ffill: 472734
Missing values after ffill: 13461
Filled 459273 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 85098 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 95390.045 to 98803.417
Duration: 3413.37 seconds
Participant ID: 22
Condition: Trust Priming
Video condition: 4

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 80621/85098 (94.7% complete)
DataSyncMarker_channel_1: 80621/85098 (94.7% complete)
Reliability: 80621/85098 (94.7% complete)
PPG_GRN_C: 85098/85098 (100.0% complete)
PPG_RED_C: 85098/85098 (100.0% complete)
PPG_IR_C: 85098/85098 (100.0% complete)
EDA_C: 85097/85098 (100.0% complete)
HR_C: 85090/85098 (100.0% complete)
TEMP_C: 85096/85098 (100.0% complete)
THERM_C: 85097/85098 (100.0% complete)
Neon Companion_Neon Gaze_x: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_y: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 85098/85098 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 85098/85098 (100.0% complete)
PPG_GRN_IS: 85098/85098 (100.0% complete)
PPG_RED_IS: 85098/85098 (100.0% complete)
PPG_IR_IS: 85098/85098 (100.0% complete)
EDA_IS: 85097/85098 (100.0% complete)
HR_IS: 85086/85098 (100.0% complete)
TEMP_IS: 85096/85098 (100.0% complete)
THERM_IS: 85095/85098 (100.0% complete)

============================================================
Processing ID 23  (23_C.xdf)
  condition=Distrust Priming  video_condition=4
============================================================

Stream 1: Calculated effective sampling rate 146.2071 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21055, 1)
  Sample count: 21055

Exported stream 1 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21055, 1)
  Sample count: 21055

Exported stream 2 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21054, 1)
  Sample count: 21054

Exported stream 4 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (69847, 1)
  Sample count: 69847

Exported stream 5 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (69988, 1)
  Sample count: 69988

Exported stream 6 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (69847, 1)
  Sample count: 69847

Exported stream 7 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21055, 1)
  Sample count: 21055

Exported stream 8 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (69988, 1)
  Sample count: 69988

Exported stream 9 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2027, 1)
  Sample count: 2027

Exported stream 10 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (42109, 1)
  Sample count: 42109

Exported stream 11 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (69988, 1)
  Sample count: 69988

Exported stream 12 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (42108, 1)
  Sample count: 42108

Exported stream 13 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1748, 1)
  Sample count: 1748

Exported stream 14 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (69847, 1)
  Sample count: 69847

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (406157, 16)
  Sample count: 406157
  First timestamp: 160472.59502772603

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/23_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (69988 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 160757.375 to 163150.877
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=160757.375, value=1.0
    t=161374.997, value=2.0
    t=161694.651, value=1.0
    t=162308.175, value=2.0
    t=162534.096, value=1.0
    t=163150.877, value=2.0
  Added Reliability column using video condition 4: ('HH', 'M', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 65342/69988 matches (93.4%)
  DataSyncMarker value distribution:
    1.0: 46074 rows (65.8%)
    2.0: 19268 rows (27.5%)
Base PPG timestamps: 160571.037 to 163378.166

Processing EDA_I.csv...
  File timestamps: 160570.934 to 163377.903
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 43601/69988 matches (62.3%)

Processing THERM_I.csv...
  File timestamps: 160571.009 to 163377.953
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 21805/69988 matches (31.2%)

Processing PPG_RED_I.csv...
  File timestamps: 160570.822 to 163377.871
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 69981/69988 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 160571.944 to 163376.966
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2093/69988 matches (3.0%)

Processing TEMP1_I.csv...
  File timestamps: 160571.002 to 163377.946
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 21808/69988 matches (31.2%)

Processing PPG_IR_C.csv...
  File timestamps: 160571.037 to 163378.165
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 69988/69988 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 160570.823 to 163377.871
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 69981/69988 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 160570.822 to 163377.870
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 69981/69988 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 160571.035 to 163378.099
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 21808/69988 matches (31.2%)

Processing EDA_C.csv...
  File timestamps: 160571.054 to 163378.117
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 43608/69988 matches (62.3%)

Processing HR_I.csv...
  File timestamps: 160574.811 to 163377.534
  Added 1 column(s) from HR_I.csv
    HR_I_value: 1794/69988 matches (2.6%)

Processing TEMP1_C.csv...
  File timestamps: 160571.161 to 163378.091
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 21810/69988 matches (31.2%)

Processing PPG_RED_C.csv...
  File timestamps: 160571.037 to 163378.165
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 69988/69988 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 160472.595 to 163250.546
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 69449 samples (16 channels)
    x: 69449/69449 valid aggregated values (100.0%)
    y: 69449/69449 valid aggregated values (100.0%)
    PupilDiameter_left: 69449/69449 valid aggregated values (100.0%)
    EyeballCenterX_left: 69449/69449 valid aggregated values (100.0%)
    EyeballCenterY_left: 69449/69449 valid aggregated values (100.0%)
    EyeballCenterZ_left: 69449/69449 valid aggregated values (100.0%)
    OpticalAxisX_left: 69449/69449 valid aggregated values (100.0%)
    OpticalAxisY_left: 69449/69449 valid aggregated values (100.0%)
    OpticalAxisZ_left: 69449/69449 valid aggregated values (100.0%)
    PupilDiameter_right: 69449/69449 valid aggregated values (100.0%)
    EyeballCenterX_right: 69449/69449 valid aggregated values (100.0%)
    EyeballCenterY_right: 69449/69449 valid aggregated values (100.0%)
    EyeballCenterZ_right: 69449/69449 valid aggregated values (100.0%)
    OpticalAxisX_right: 69449/69449 valid aggregated values (100.0%)
    OpticalAxisY_right: 69449/69449 valid aggregated values (100.0%)
    OpticalAxisZ_right: 69449/69449 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_y: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 66805/69988 matches (95.5%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 66805/69988 matches (95.5%)

Processing temp_datasync_remaining.csv...
  File timestamps: 160757.375 to 163150.877
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 65342/69988 matches (93.4%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 4646:
  UNIX timestamp: 1756391181.159796
  EST time: 2025-08-28 10:26:21.159796-04:00
  Corresponding EmotiBit timestamp: 160757.385
Successfully created Date and Time columns for all 69988 rows (EST timezone)
Duration: 2807.13 seconds

Example rows around sync point (row 4646):
  Row 4644: EmotiBit=160757.305, diff=-0.080s, Time=10:26:21.079
  Row 4645: EmotiBit=160757.345, diff=-0.040s, Time=10:26:21.119
  Row 4646: EmotiBit=160757.385, diff=+0.000s, Time=10:26:21.159 <- SYNC POINT
  Row 4647: EmotiBit=160757.425, diff=+0.040s, Time=10:26:21.199
  Row 4648: EmotiBit=160757.465, diff=+0.080s, Time=10:26:21.239

Applying forward fill to missing values...
Missing values before ffill: 446464
Missing values after ffill: 14064
Filled 432400 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 69988 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 160571.037 to 163378.166
Duration: 2807.13 seconds
Participant ID: 23
Condition: Distrust Priming
Video condition: 4

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 65342/69988 (93.4% complete)
DataSyncMarker_channel_1: 65342/69988 (93.4% complete)
Reliability: 65342/69988 (93.4% complete)
PPG_GRN_C: 69988/69988 (100.0% complete)
PPG_RED_C: 69988/69988 (100.0% complete)
PPG_IR_C: 69988/69988 (100.0% complete)
EDA_C: 69988/69988 (100.0% complete)
HR_C: 69965/69988 (100.0% complete)
TEMP_C: 69985/69988 (100.0% complete)
THERM_C: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_x: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_y: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 69988/69988 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 69988/69988 (100.0% complete)
PPG_GRN_IS: 69988/69988 (100.0% complete)
PPG_RED_IS: 69988/69988 (100.0% complete)
PPG_IR_IS: 69988/69988 (100.0% complete)
EDA_IS: 69987/69988 (100.0% complete)
HR_IS: 69894/69988 (99.9% complete)
TEMP_IS: 69986/69988 (100.0% complete)
THERM_IS: 69985/69988 (100.0% complete)

============================================================
Processing ID 24  (24_C.xdf)
  condition=Trust Priming  video_condition=5
============================================================

Stream 15: Calculated effective sampling rate 151.2246 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (60576, 1)
  Sample count: 60576

Exported stream 1 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (60576, 1)
  Sample count: 60576

Exported stream 2 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23465, 1)
  Sample count: 23465

Exported stream 3 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78001, 1)
  Sample count: 78001

Exported stream 5 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (60576, 1)
  Sample count: 60576

Exported stream 6 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (18257, 1)
  Sample count: 18257

Exported stream 7 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (46928, 1)
  Sample count: 46928

Exported stream 8 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (36512, 1)
  Sample count: 36512

Exported stream 9 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (18256, 1)
  Sample count: 18256

Exported stream 10 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (1887, 1)
  Sample count: 1887

Exported stream 11 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78001, 1)
  Sample count: 78001

Exported stream 12 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2484, 1)
  Sample count: 2484

Exported stream 13 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23464, 1)
  Sample count: 23464

Exported stream 14 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78001, 1)
  Sample count: 78001

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (476398, 16)
  Sample count: 476398
  First timestamp: 592330.516174941

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/24_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (78001 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 592515.479 to 595240.770
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=592515.479, value=1.0
    t=593124.873, value=2.0
    t=593637.723, value=1.0
    t=594251.811, value=2.0
    t=594621.141, value=1.0
    t=595240.770, value=2.0
  Added Reliability column using video condition 5: ('M', 'LL', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 75493/78001 matches (96.8%)
  DataSyncMarker value distribution:
    1.0: 45955 rows (58.9%)
    2.0: 29538 rows (37.9%)
Base PPG timestamps: 592414.919 to 595543.294

Processing EDA_I.csv...
  File timestamps: 592414.951 to 594848.922
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 38353/78001 matches (49.2%)

Processing THERM_I.csv...
  File timestamps: 592415.019 to 594848.923
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 19180/78001 matches (24.6%)

Processing PPG_RED_I.csv...
  File timestamps: 592414.769 to 594848.880
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 60687/78001 matches (77.8%)

Processing HR_C.csv...
  File timestamps: 592417.531 to 595542.823
  Added 1 column(s) from HR_C.csv
    HR_C_value: 1984/78001 matches (2.5%)

Processing TEMP1_I.csv...
  File timestamps: 592414.920 to 594848.896
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 19188/78001 matches (24.6%)

Processing PPG_IR_C.csv...
  File timestamps: 592414.918 to 595543.293
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 78001/78001 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 592414.770 to 594848.881
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 60687/78001 matches (77.8%)

Processing PPG_IR_I.csv...
  File timestamps: 592414.768 to 594848.880
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 60687/78001 matches (77.8%)

Processing THERM_C.csv...
  File timestamps: 592415.072 to 595543.329
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 24632/78001 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 592415.021 to 595543.319
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 49300/78001 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 592414.800 to 594848.773
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2588/78001 matches (3.3%)

Processing TEMP1_C.csv...
  File timestamps: 592414.965 to 595543.305
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 24634/78001 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 592414.919 to 595543.293
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 78001/78001 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 592330.516 to 595480.778
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 78757 samples (16 channels)
    x: 78757/78757 valid aggregated values (100.0%)
    y: 78757/78757 valid aggregated values (100.0%)
    PupilDiameter_left: 78757/78757 valid aggregated values (100.0%)
    EyeballCenterX_left: 78757/78757 valid aggregated values (100.0%)
    EyeballCenterY_left: 78757/78757 valid aggregated values (100.0%)
    EyeballCenterZ_left: 78757/78757 valid aggregated values (100.0%)
    OpticalAxisX_left: 78757/78757 valid aggregated values (100.0%)
    OpticalAxisY_left: 78757/78757 valid aggregated values (100.0%)
    OpticalAxisZ_left: 78757/78757 valid aggregated values (100.0%)
    PupilDiameter_right: 78757/78757 valid aggregated values (100.0%)
    EyeballCenterX_right: 78757/78757 valid aggregated values (100.0%)
    EyeballCenterY_right: 78757/78757 valid aggregated values (100.0%)
    EyeballCenterZ_right: 78757/78757 valid aggregated values (100.0%)
    OpticalAxisX_right: 78757/78757 valid aggregated values (100.0%)
    OpticalAxisY_right: 78757/78757 valid aggregated values (100.0%)
    OpticalAxisZ_right: 78757/78757 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_y: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 76442/78001 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 76442/78001 matches (98.0%)

Processing temp_datasync_remaining.csv...
  File timestamps: 592515.479 to 595240.770
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 75493/78001 matches (96.8%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 2508:
  UNIX timestamp: 1756822938.590922
  EST time: 2025-09-02 10:22:18.590922117-04:00
  Corresponding EmotiBit timestamp: 592515.509
Successfully created Date and Time columns for all 78001 rows (EST timezone)
Duration: 3128.38 seconds

Example rows around sync point (row 2508):
  Row 2506: EmotiBit=592515.428, diff=-0.081s, Time=10:22:18.509
  Row 2507: EmotiBit=592515.468, diff=-0.041s, Time=10:22:18.549
  Row 2508: EmotiBit=592515.509, diff=+0.000s, Time=10:22:18.590 <- SYNC POINT
  Row 2509: EmotiBit=592515.549, diff=+0.040s, Time=10:22:18.630
  Row 2510: EmotiBit=592515.589, diff=+0.080s, Time=10:22:18.670

Applying forward fill to missing values...
Missing values before ffill: 528559
Missing values after ffill: 7615
Filled 520944 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 78001 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 592414.919 to 595543.294
Duration: 3128.38 seconds
Participant ID: 24
Condition: Trust Priming
Video condition: 5

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 75493/78001 (96.8% complete)
DataSyncMarker_channel_1: 75493/78001 (96.8% complete)
Reliability: 75493/78001 (96.8% complete)
PPG_GRN_C: 78001/78001 (100.0% complete)
PPG_RED_C: 78001/78001 (100.0% complete)
PPG_IR_C: 78001/78001 (100.0% complete)
EDA_C: 77998/78001 (100.0% complete)
HR_C: 77936/78001 (99.9% complete)
TEMP_C: 78000/78001 (100.0% complete)
THERM_C: 77997/78001 (100.0% complete)
Neon Companion_Neon Gaze_x: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_y: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 78001/78001 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 78001/78001 (100.0% complete)
PPG_GRN_IS: 78001/78001 (100.0% complete)
PPG_RED_IS: 78001/78001 (100.0% complete)
PPG_IR_IS: 78001/78001 (100.0% complete)
EDA_IS: 78000/78001 (100.0% complete)
HR_IS: 77986/78001 (100.0% complete)
TEMP_IS: 78001/78001 (100.0% complete)
THERM_IS: 77999/78001 (100.0% complete)

============================================================
Processing ID 25  (25_C.xdf)
  condition=Distrust Priming  video_condition=5
============================================================

Stream 1: Calculated effective sampling rate 147.0490 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21565, 1)
  Sample count: 21565

Exported stream 1 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (43131, 1)
  Sample count: 43131

Exported stream 2 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71693, 1)
  Sample count: 71693

Exported stream 3 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71545, 1)
  Sample count: 71545

Exported stream 4 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (43129, 1)
  Sample count: 43129

Exported stream 5 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21565, 1)
  Sample count: 21565

Exported stream 6 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21565, 1)
  Sample count: 21565

Exported stream 7 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2406, 1)
  Sample count: 2406

Exported stream 8 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71690, 1)
  Sample count: 71690

Exported stream 9 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71545, 1)
  Sample count: 71545

Exported stream 10 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71545, 1)
  Sample count: 71545

Exported stream 12 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (1852, 1)
  Sample count: 1852

Exported stream 13 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71693, 1)
  Sample count: 71693

Exported stream 14 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21565, 1)
  Sample count: 21565

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (428671, 16)
  Sample count: 428671
  First timestamp: 599281.4213660232

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (10, 2)
  Sample count: 10

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/25_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (71690 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 599534.807 to 602056.015
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 10 events
  DataSyncMarker events:
    t=599534.807, value=1.0
    t=600147.716, value=2.0
    t=600440.953, value=1.0
    t=600564.299, value=3.480073097183e-312
    t=600572.441, value=1.0
    t=600573.056, value=3.0
    t=600574.482, value=1.0
    t=601192.308, value=2.0
    t=601433.507, value=1.0
    t=602056.015, value=2.0
  Added Reliability column using video condition 5: ('M', 'LL', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 68004/71690 matches (94.9%)
  DataSyncMarker value distribution:
    1.0: 49301 rows (68.8%)
    2.0: 18464 rows (25.8%)
    3.480073097183e-312: 203 rows (0.3%)
    3.0: 36 rows (0.1%)
Base PPG timestamps: 599386.985 to 602262.105

Processing EDA_I.csv...
  File timestamps: 599386.991 to 602262.023
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 45301/71690 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 599387.064 to 602262.002
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 22653/71690 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 599386.838 to 602262.013
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 71688/71690 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 599387.914 to 602259.751
  Added 1 column(s) from HR_C.csv
    HR_C_value: 1960/71690 matches (2.7%)

Processing TEMP1_I.csv...
  File timestamps: 599387.057 to 602261.995
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 22642/71690 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 599386.863 to 602262.103
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 71690/71690 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 599386.838 to 602262.013
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 71688/71690 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 599386.837 to 602262.012
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 71688/71690 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 599386.942 to 602262.057
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 22655/71690 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 599386.879 to 602262.033
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 45311/71690 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 599387.281 to 602260.867
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2519/71690 matches (3.5%)

Processing TEMP1_C.csv...
  File timestamps: 599386.934 to 602262.049
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 22667/71690 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 599386.864 to 602262.104
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 71690/71690 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 599281.421 to 602196.572
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 72879 samples (16 channels)
    x: 72879/72879 valid aggregated values (100.0%)
    y: 72879/72879 valid aggregated values (100.0%)
    PupilDiameter_left: 72879/72879 valid aggregated values (100.0%)
    EyeballCenterX_left: 72879/72879 valid aggregated values (100.0%)
    EyeballCenterY_left: 72879/72879 valid aggregated values (100.0%)
    EyeballCenterZ_left: 72879/72879 valid aggregated values (100.0%)
    OpticalAxisX_left: 72879/72879 valid aggregated values (100.0%)
    OpticalAxisY_left: 72879/72879 valid aggregated values (100.0%)
    OpticalAxisZ_left: 72879/72879 valid aggregated values (100.0%)
    PupilDiameter_right: 72879/72879 valid aggregated values (100.0%)
    EyeballCenterX_right: 72879/72879 valid aggregated values (100.0%)
    EyeballCenterY_right: 72879/72879 valid aggregated values (100.0%)
    EyeballCenterZ_right: 72879/72879 valid aggregated values (100.0%)
    OpticalAxisX_right: 72879/72879 valid aggregated values (100.0%)
    OpticalAxisY_right: 72879/72879 valid aggregated values (100.0%)
    OpticalAxisZ_right: 72879/72879 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_y: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 70055/71690 matches (97.7%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 70055/71690 matches (97.7%)

Processing temp_datasync_remaining.csv...
  File timestamps: 599534.807 to 602056.015
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 68004/71690 matches (94.9%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3686:
  UNIX timestamp: 1756829957.91982
  EST time: 2025-09-02 12:19:17.919820070-04:00
  Corresponding EmotiBit timestamp: 599534.814
Successfully created Date and Time columns for all 71690 rows (EST timezone)
Duration: 2875.12 seconds

Example rows around sync point (row 3686):
  Row 3684: EmotiBit=599534.733, diff=-0.081s, Time=12:19:17.838
  Row 3685: EmotiBit=599534.773, diff=-0.041s, Time=12:19:17.878
  Row 3686: EmotiBit=599534.814, diff=+0.000s, Time=12:19:17.919 <- SYNC POINT
  Row 3687: EmotiBit=599534.854, diff=+0.040s, Time=12:19:17.959
  Row 3688: EmotiBit=599534.894, diff=+0.080s, Time=12:19:17.999

Applying forward fill to missing values...
Missing values before ffill: 456202
Missing values after ffill: 11097
Filled 445105 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 71690 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 599386.985 to 602262.105
Duration: 2875.12 seconds
Participant ID: 25
Condition: Distrust Priming
Video condition: 5

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 68004/71690 (94.9% complete)
DataSyncMarker_channel_1: 68004/71690 (94.9% complete)
Reliability: 68004/71690 (94.9% complete)
PPG_GRN_C: 71690/71690 (100.0% complete)
PPG_RED_C: 71690/71690 (100.0% complete)
PPG_IR_C: 71690/71690 (100.0% complete)
EDA_C: 71689/71690 (100.0% complete)
HR_C: 71667/71690 (100.0% complete)
TEMP_C: 71688/71690 (100.0% complete)
THERM_C: 71688/71690 (100.0% complete)
Neon Companion_Neon Gaze_x: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_y: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 71690/71690 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 71690/71690 (100.0% complete)
PPG_GRN_IS: 71690/71690 (100.0% complete)
PPG_RED_IS: 71690/71690 (100.0% complete)
PPG_IR_IS: 71690/71690 (100.0% complete)
EDA_IS: 71690/71690 (100.0% complete)
HR_IS: 71683/71690 (100.0% complete)
TEMP_IS: 71688/71690 (100.0% complete)
THERM_IS: 71688/71690 (100.0% complete)

Applying restart fix for ID 25 (restarted at block 2)...
DataSyncMarker==1 runs: 5
  run 1: rows 3686-18968 (n=15283)
  run 2: rows 26280-29355 (n=3076)
  run 3: rows 29559-29573 (n=15)
  run 4: rows 29610-45014 (n=15405)
  run 5: rows 51029-66550 (n=15522)
DataSyncMarker==3 runs: 1
  run 1: rows 29574-29609 (n=36)
Restart window: rows 26280-29609 (n=3330)
  (3686 row(s) outside the window had no marker yet -- expected before the first block starts)
Tagged 3330 row(s) as 'Restart'
Re-saved relabeled CSV: /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/merged_data_25.csv

============================================================
Processing ID 26  (26_C.xdf)
  condition=Trust Priming  video_condition=6
============================================================

Stream 5: Calculated effective sampling rate 147.8301 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71339, 1)
  Sample count: 71339

Exported stream 1 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (42924, 1)
  Sample count: 42924

Exported stream 2 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (3000, 1)
  Sample count: 3000

Exported stream 3 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2203, 1)
  Sample count: 2203

Exported stream 4 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71339, 1)
  Sample count: 71339

Exported stream 5 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21463, 1)
  Sample count: 21463

Exported stream 6 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21462, 1)
  Sample count: 21462

Exported stream 7 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (42926, 1)
  Sample count: 42926

Exported stream 8 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71205, 1)
  Sample count: 71205

Exported stream 9 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21462, 1)
  Sample count: 21462

Exported stream 10 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71205, 1)
  Sample count: 71205

Exported stream 11 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21463, 1)
  Sample count: 21463

Exported stream 13 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71339, 1)
  Sample count: 71339

Exported stream 14 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71205, 1)
  Sample count: 71205

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (429732, 16)
  Sample count: 429732
  First timestamp: 693014.0484176358

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/26_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (71339 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 693245.410 to 695702.864
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=693245.410, value=1.0
    t=693853.317, value=2.0
    t=694224.164, value=1.0
    t=694840.639, value=2.0
    t=695087.583, value=1.0
    t=695702.864, value=2.0
  Added Reliability column using video condition 6: ('M', 'HH', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 68146/71339 matches (95.5%)
  DataSyncMarker value distribution:
    1.0: 45864 rows (64.3%)
    2.0: 22282 rows (31.2%)
Base PPG timestamps: 693117.350 to 695978.802

Processing EDA_I.csv...
  File timestamps: 693117.222 to 695978.798
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 45106/71339 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 693117.299 to 695978.842
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 22536/71339 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 693117.187 to 695978.777
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 71338/71339 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 693118.351 to 695977.104
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2305/71339 matches (3.2%)

Processing TEMP1_I.csv...
  File timestamps: 693117.291 to 695978.835
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 22571/71339 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 693117.348 to 695978.801
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 71339/71339 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 693117.188 to 695978.778
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 71338/71339 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 693117.187 to 695978.777
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 71338/71339 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 693117.293 to 695978.801
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 22558/71339 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 693117.332 to 695978.812
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 45102/71339 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 693117.334 to 695978.603
  Added 1 column(s) from HR_I.csv
    HR_I_value: 3148/71339 matches (4.4%)

Processing TEMP1_C.csv...
  File timestamps: 693117.286 to 695978.794
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 22533/71339 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 693117.349 to 695978.801
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 71339/71339 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 693014.048 to 695920.973
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 72674 samples (16 channels)
    x: 72674/72674 valid aggregated values (100.0%)
    y: 72674/72674 valid aggregated values (100.0%)
    PupilDiameter_left: 72674/72674 valid aggregated values (100.0%)
    EyeballCenterX_left: 72674/72674 valid aggregated values (100.0%)
    EyeballCenterY_left: 72674/72674 valid aggregated values (100.0%)
    EyeballCenterZ_left: 72674/72674 valid aggregated values (100.0%)
    OpticalAxisX_left: 72674/72674 valid aggregated values (100.0%)
    OpticalAxisY_left: 72674/72674 valid aggregated values (100.0%)
    OpticalAxisZ_left: 72674/72674 valid aggregated values (100.0%)
    PupilDiameter_right: 72674/72674 valid aggregated values (100.0%)
    EyeballCenterX_right: 72674/72674 valid aggregated values (100.0%)
    EyeballCenterY_right: 72674/72674 valid aggregated values (100.0%)
    EyeballCenterZ_right: 72674/72674 valid aggregated values (100.0%)
    OpticalAxisX_right: 72674/72674 valid aggregated values (100.0%)
    OpticalAxisY_right: 72674/72674 valid aggregated values (100.0%)
    OpticalAxisZ_right: 72674/72674 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_y: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 69897/71339 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 69897/71339 matches (98.0%)

Processing temp_datasync_remaining.csv...
  File timestamps: 693245.410 to 695702.864
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 68146/71339 matches (95.5%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3193:
  UNIX timestamp: 1756923668.1209128
  EST time: 2025-09-03 14:21:08.120912790-04:00
  Corresponding EmotiBit timestamp: 693245.425
Successfully created Date and Time columns for all 71339 rows (EST timezone)
Duration: 2861.45 seconds

Example rows around sync point (row 3193):
  Row 3191: EmotiBit=693245.345, diff=-0.080s, Time=14:21:08.040
  Row 3192: EmotiBit=693245.385, diff=-0.040s, Time=14:21:08.080
  Row 3193: EmotiBit=693245.425, diff=+0.000s, Time=14:21:08.120 <- SYNC POINT
  Row 3194: EmotiBit=693245.465, diff=+0.040s, Time=14:21:08.160
  Row 3195: EmotiBit=693245.505, diff=+0.080s, Time=14:21:08.200

Applying forward fill to missing values...
Missing values before ffill: 417507
Missing values after ffill: 9612
Filled 407895 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 71339 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 693117.350 to 695978.802
Duration: 2861.45 seconds
Participant ID: 26
Condition: Trust Priming
Video condition: 6

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 68146/71339 (95.5% complete)
DataSyncMarker_channel_1: 68146/71339 (95.5% complete)
Reliability: 68146/71339 (95.5% complete)
PPG_GRN_C: 71339/71339 (100.0% complete)
PPG_RED_C: 71339/71339 (100.0% complete)
PPG_IR_C: 71339/71339 (100.0% complete)
EDA_C: 71339/71339 (100.0% complete)
HR_C: 71314/71339 (100.0% complete)
TEMP_C: 71337/71339 (100.0% complete)
THERM_C: 71337/71339 (100.0% complete)
Neon Companion_Neon Gaze_x: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_y: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 71339/71339 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 71339/71339 (100.0% complete)
PPG_GRN_IS: 71339/71339 (100.0% complete)
PPG_RED_IS: 71339/71339 (100.0% complete)
PPG_IR_IS: 71339/71339 (100.0% complete)
EDA_IS: 71339/71339 (100.0% complete)
HR_IS: 71339/71339 (100.0% complete)
TEMP_IS: 71337/71339 (100.0% complete)
THERM_IS: 71337/71339 (100.0% complete)

============================================================
Processing ID 27  (27_C.xdf)
  condition=Distrust Priming  video_condition=6
============================================================

Stream 4: Calculated effective sampling rate 143.8251 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2154, 1)
  Sample count: 2154

Exported stream 1 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (67845, 1)
  Sample count: 67845

Exported stream 3 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (67845, 1)
  Sample count: 67845

Exported stream 4 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (40886, 1)
  Sample count: 40886

Exported stream 5 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (67845, 1)
  Sample count: 67845

Exported stream 6 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (40888, 1)
  Sample count: 40888

Exported stream 7 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (67954, 1)
  Sample count: 67954

Exported stream 8 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20443, 1)
  Sample count: 20443

Exported stream 9 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (67954, 1)
  Sample count: 67954

Exported stream 10 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20444, 1)
  Sample count: 20444

Exported stream 11 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20444, 1)
  Sample count: 20444

Exported stream 12 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20445, 1)
  Sample count: 20445

Exported stream 13 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1734, 1)
  Sample count: 1734

Exported stream 14 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (67954, 1)
  Sample count: 67954

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (396930, 16)
  Sample count: 396930
  First timestamp: 700520.5437997425

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/27_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (67954 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 700743.437 to 703127.934
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=700743.437, value=1.0
    t=701355.034, value=2.0
    t=701662.379, value=1.0
    t=702278.055, value=2.0
    t=702519.552, value=1.0
    t=703127.934, value=2.0
  Added Reliability column using video condition 6: ('M', 'HH', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 64530/67954 matches (95.0%)
  DataSyncMarker value distribution:
    1.0: 45761 rows (67.3%)
    2.0: 18769 rows (27.6%)
Base PPG timestamps: 700606.092 to 703331.919

Processing EDA_I.csv...
  File timestamps: 700605.928 to 703332.004
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 42949/67954 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 700606.029 to 703332.043
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 21476/67954 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 700605.808 to 703331.880
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 67953/67954 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 700608.268 to 703330.919
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2254/67954 matches (3.3%)

Processing TEMP1_I.csv...
  File timestamps: 700605.998 to 703331.953
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 21467/67954 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 700606.090 to 703331.918
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 67954/67954 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 700605.808 to 703331.881
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 67953/67954 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 700605.807 to 703331.880
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 67953/67954 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 700606.061 to 703331.763
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 21476/67954 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 700606.129 to 703331.874
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 42975/67954 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 700606.260 to 703324.052
  Added 1 column(s) from HR_I.csv
    HR_I_value: 1806/67954 matches (2.7%)

Processing TEMP1_C.csv...
  File timestamps: 700605.937 to 703331.747
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 21483/67954 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 700606.091 to 703331.918
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 67954/67954 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 700520.544 to 703280.348
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 68996 samples (16 channels)
    x: 68996/68996 valid aggregated values (100.0%)
    y: 68996/68996 valid aggregated values (100.0%)
    PupilDiameter_left: 68996/68996 valid aggregated values (100.0%)
    EyeballCenterX_left: 68996/68996 valid aggregated values (100.0%)
    EyeballCenterY_left: 68996/68996 valid aggregated values (100.0%)
    EyeballCenterZ_left: 68996/68996 valid aggregated values (100.0%)
    OpticalAxisX_left: 68996/68996 valid aggregated values (100.0%)
    OpticalAxisY_left: 68996/68996 valid aggregated values (100.0%)
    OpticalAxisZ_left: 68996/68996 valid aggregated values (100.0%)
    PupilDiameter_right: 68996/68996 valid aggregated values (100.0%)
    EyeballCenterX_right: 68996/68996 valid aggregated values (100.0%)
    EyeballCenterY_right: 68996/68996 valid aggregated values (100.0%)
    EyeballCenterZ_right: 68996/68996 valid aggregated values (100.0%)
    OpticalAxisX_right: 68996/68996 valid aggregated values (100.0%)
    OpticalAxisY_right: 68996/68996 valid aggregated values (100.0%)
    OpticalAxisZ_right: 68996/68996 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_y: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 66668/67954 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 66668/67954 matches (98.1%)

Processing temp_datasync_remaining.csv...
  File timestamps: 700743.437 to 703127.934
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 64530/67954 matches (95.0%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3424:
  UNIX timestamp: 1756931166.212203
  EST time: 2025-09-03 16:26:06.212203026-04:00
  Corresponding EmotiBit timestamp: 700743.44
Successfully created Date and Time columns for all 67954 rows (EST timezone)
Duration: 2725.83 seconds

Example rows around sync point (row 3424):
  Row 3422: EmotiBit=700743.360, diff=-0.080s, Time=16:26:06.132
  Row 3423: EmotiBit=700743.400, diff=-0.040s, Time=16:26:06.172
  Row 3424: EmotiBit=700743.440, diff=+0.000s, Time=16:26:06.212 <- SYNC POINT
  Row 3425: EmotiBit=700743.480, diff=+0.040s, Time=16:26:06.252
  Row 3426: EmotiBit=700743.520, diff=+0.080s, Time=16:26:06.292

Applying forward fill to missing values...
Missing values before ffill: 398597
Missing values after ffill: 10338
Filled 388259 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 67954 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 700606.092 to 703331.919
Duration: 2725.83 seconds
Participant ID: 27
Condition: Distrust Priming
Video condition: 6

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 64530/67954 (95.0% complete)
DataSyncMarker_channel_1: 64530/67954 (95.0% complete)
Reliability: 64530/67954 (95.0% complete)
PPG_GRN_C: 67954/67954 (100.0% complete)
PPG_RED_C: 67954/67954 (100.0% complete)
PPG_IR_C: 67954/67954 (100.0% complete)
EDA_C: 67953/67954 (100.0% complete)
HR_C: 67900/67954 (99.9% complete)
TEMP_C: 67954/67954 (100.0% complete)
THERM_C: 67951/67954 (100.0% complete)
Neon Companion_Neon Gaze_x: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_y: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 67954/67954 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 67954/67954 (100.0% complete)
PPG_GRN_IS: 67954/67954 (100.0% complete)
PPG_RED_IS: 67954/67954 (100.0% complete)
PPG_IR_IS: 67954/67954 (100.0% complete)
EDA_IS: 67953/67954 (100.0% complete)
HR_IS: 67950/67954 (100.0% complete)
TEMP_IS: 67953/67954 (100.0% complete)
THERM_IS: 67952/67954 (100.0% complete)

============================================================
Processing ID 28  (28_C.xdf)
  condition=Trust Priming  video_condition=1
============================================================

Stream 8: Calculated effective sampling rate 151.3566 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72978, 1)
  Sample count: 72978

Exported stream 1 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73113, 1)
  Sample count: 73113

Exported stream 2 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21996, 1)
  Sample count: 21996

Exported stream 3 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73113, 1)
  Sample count: 73113

Exported stream 5 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73113, 1)
  Sample count: 73113

Exported stream 6 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (43989, 1)
  Sample count: 43989

Exported stream 7 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21995, 1)
  Sample count: 21995

Exported stream 8 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21995, 1)
  Sample count: 21995

Exported stream 9 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72978, 1)
  Sample count: 72978

Exported stream 10 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21996, 1)
  Sample count: 21996

Exported stream 11 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (43992, 1)
  Sample count: 43992

Exported stream 12 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2510, 1)
  Sample count: 2510

Exported stream 13 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72978, 1)
  Sample count: 72978

Exported stream 14 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (3026, 1)
  Sample count: 3026

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (441679, 16)
  Sample count: 441679
  First timestamp: 1128721.19766742

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/28_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (73113 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 1128911.741 to 1131394.899
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=1128911.741, value=1.0
    t=1129523.515, value=2.0
    t=1129882.635, value=1.0
    t=1130506.024, value=2.0
    t=1130784.428, value=1.0
    t=1131394.899, value=2.0
  Added Reliability column using video condition 1: ('LL', 'HH', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 70354/73113 matches (96.2%)
  DataSyncMarker value distribution:
    1.0: 46014 rows (62.9%)
    2.0: 24340 rows (33.3%)
Base PPG timestamps: 1128801.092 to 1131733.640

Processing EDA_I.csv...
  File timestamps: 1128801.045 to 1131733.607
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 46682/73113 matches (63.8%)

Processing THERM_I.csv...
  File timestamps: 1128801.058 to 1131733.521
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 23339/73113 matches (31.9%)

Processing PPG_RED_I.csv...
  File timestamps: 1128801.000 to 1131733.674
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 73113/73113 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 1128801.351 to 1131729.384
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2649/73113 matches (3.6%)

Processing TEMP1_I.csv...
  File timestamps: 1128801.050 to 1131733.514
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 23338/73113 matches (31.9%)

Processing PPG_IR_C.csv...
  File timestamps: 1128801.090 to 1131733.638
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 73113/73113 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 1128801.000 to 1131733.674
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 73113/73113 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 1128800.999 to 1131733.673
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 73113/73113 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 1128801.180 to 1131733.571
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 23339/73113 matches (31.9%)

Processing EDA_C.csv...
  File timestamps: 1128801.112 to 1131733.570
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 46683/73113 matches (63.9%)

Processing HR_I.csv...
  File timestamps: 1128801.417 to 1131721.318
  Added 1 column(s) from HR_I.csv
    HR_I_value: 3236/73113 matches (4.4%)

Processing TEMP1_C.csv...
  File timestamps: 1128801.172 to 1131733.564
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 23347/73113 matches (31.9%)

Processing PPG_RED_C.csv...
  File timestamps: 1128801.091 to 1131733.639
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 73113/73113 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 1128721.198 to 1131639.325
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 72954 samples (16 channels)
    x: 72954/72954 valid aggregated values (100.0%)
    y: 72954/72954 valid aggregated values (100.0%)
    PupilDiameter_left: 72954/72954 valid aggregated values (100.0%)
    EyeballCenterX_left: 72954/72954 valid aggregated values (100.0%)
    EyeballCenterY_left: 72954/72954 valid aggregated values (100.0%)
    EyeballCenterZ_left: 72954/72954 valid aggregated values (100.0%)
    OpticalAxisX_left: 72954/72954 valid aggregated values (100.0%)
    OpticalAxisY_left: 72954/72954 valid aggregated values (100.0%)
    OpticalAxisZ_left: 72954/72954 valid aggregated values (100.0%)
    PupilDiameter_right: 72954/72954 valid aggregated values (100.0%)
    EyeballCenterX_right: 72954/72954 valid aggregated values (100.0%)
    EyeballCenterY_right: 72954/72954 valid aggregated values (100.0%)
    EyeballCenterZ_right: 72954/72954 valid aggregated values (100.0%)
    OpticalAxisX_right: 72954/72954 valid aggregated values (100.0%)
    OpticalAxisY_right: 72954/72954 valid aggregated values (100.0%)
    OpticalAxisZ_right: 72954/72954 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_y: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 70761/73113 matches (96.8%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 70761/73113 matches (96.8%)

Processing temp_datasync_remaining.csv...
  File timestamps: 1128911.741 to 1131394.899
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 70354/73113 matches (96.2%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 2759:
  UNIX timestamp: 1757359330.742495
  EST time: 2025-09-08 15:22:10.742495060-04:00
  Corresponding EmotiBit timestamp: 1128911.756
Successfully created Date and Time columns for all 73113 rows (EST timezone)
Duration: 2932.55 seconds

Example rows around sync point (row 2759):
  Row 2757: EmotiBit=1128911.676, diff=-0.080s, Time=15:22:10.662
  Row 2758: EmotiBit=1128911.716, diff=-0.040s, Time=15:22:10.702
  Row 2759: EmotiBit=1128911.756, diff=+0.000s, Time=15:22:10.742 <- SYNC POINT
  Row 2760: EmotiBit=1128911.796, diff=+0.040s, Time=15:22:10.782
  Row 2761: EmotiBit=1128911.836, diff=+0.080s, Time=15:22:10.822

Applying forward fill to missing values...
Missing values before ffill: 438200
Missing values after ffill: 8299
Filled 429901 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 73113 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 1128801.092 to 1131733.640
Duration: 2932.55 seconds
Participant ID: 28
Condition: Trust Priming
Video condition: 1

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 70354/73113 (96.2% complete)
DataSyncMarker_channel_1: 70354/73113 (96.2% complete)
Reliability: 70354/73113 (96.2% complete)
PPG_GRN_C: 73113/73113 (100.0% complete)
PPG_RED_C: 73113/73113 (100.0% complete)
PPG_IR_C: 73113/73113 (100.0% complete)
EDA_C: 73113/73113 (100.0% complete)
HR_C: 73107/73113 (100.0% complete)
TEMP_C: 73111/73113 (100.0% complete)
THERM_C: 73111/73113 (100.0% complete)
Neon Companion_Neon Gaze_x: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_y: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 73113/73113 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 73113/73113 (100.0% complete)
PPG_GRN_IS: 73113/73113 (100.0% complete)
PPG_RED_IS: 73113/73113 (100.0% complete)
PPG_IR_IS: 73113/73113 (100.0% complete)
EDA_IS: 73113/73113 (100.0% complete)
HR_IS: 73105/73113 (100.0% complete)
TEMP_IS: 73111/73113 (100.0% complete)
THERM_IS: 73111/73113 (100.0% complete)

============================================================
Processing ID 29  (29_C.xdf)
  condition=Distrust Priming  video_condition=3
============================================================

Stream 16: Calculated effective sampling rate 129.5946 Hz is different from specified rate 200.0000 Hz.

Exported stream 1 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (68118, 1)
  Sample count: 68118

Exported stream 2 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20533, 1)
  Sample count: 20533

Exported stream 3 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20533, 1)
  Sample count: 20533

Exported stream 4 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (41053, 1)
  Sample count: 41053

Exported stream 5 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (68225, 1)
  Sample count: 68225

Exported stream 6 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (68225, 1)
  Sample count: 68225

Exported stream 7 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20527, 1)
  Sample count: 20527

Exported stream 8 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (68105, 1)
  Sample count: 68105

Exported stream 9 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2707, 1)
  Sample count: 2707

Exported stream 10 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (68118, 1)
  Sample count: 68118

Exported stream 11 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20526, 1)
  Sample count: 20526

Exported stream 12 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (68225, 1)
  Sample count: 68225

Exported stream 13 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (41058, 1)
  Sample count: 41058

Exported stream 14 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1798, 1)
  Sample count: 1798

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (363913, 16)
  Sample count: 363913
  First timestamp: 1136204.0652087121

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/29_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (68225 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 1136434.673 to 1138833.769
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=1136434.673, value=1.0
    t=1137054.443, value=2.0
    t=1137382.504, value=1.0
    t=1137994.958, value=2.0
    t=1138224.373, value=1.0
    t=1138833.769, value=2.0
  Added Reliability column using video condition 3: ('HH', 'LL', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 65322/68225 matches (95.7%)
  DataSyncMarker value distribution:
    1.0: 45908 rows (67.3%)
    2.0: 19414 rows (28.5%)
Base PPG timestamps: 1136318.221 to 1139055.051

Processing EDA_I.csv...
  File timestamps: 1136318.098 to 1139055.017
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 43567/68225 matches (63.9%)

Processing THERM_I.csv...
  File timestamps: 1136318.008 to 1139055.429
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 21785/68225 matches (31.9%)

Processing PPG_RED_I.csv...
  File timestamps: 1136317.930 to 1139055.485
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 68225/68225 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 1136318.219 to 1139053.693
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2882/68225 matches (4.2%)

Processing TEMP1_I.csv...
  File timestamps: 1136318.001 to 1139055.422
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 21772/68225 matches (31.9%)

Processing PPG_IR_C.csv...
  File timestamps: 1136318.220 to 1139055.049
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 68225/68225 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 1136318.052 to 1139055.084
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 68225/68225 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 1136317.930 to 1139055.484
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 68225/68225 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 1136318.202 to 1139054.957
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 21793/68225 matches (31.9%)

Processing EDA_C.csv...
  File timestamps: 1136318.212 to 1139055.065
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 43564/68225 matches (63.9%)

Processing HR_I.csv...
  File timestamps: 1136319.485 to 1139054.576
  Added 1 column(s) from HR_I.csv
    HR_I_value: 1919/68225 matches (2.8%)

Processing TEMP1_C.csv...
  File timestamps: 1136318.158 to 1139054.911
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 21773/68225 matches (31.9%)

Processing PPG_RED_C.csv...
  File timestamps: 1136318.220 to 1139055.050
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 68225/68225 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 1136204.065 to 1139012.146
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 70203 samples (16 channels)
    x: 70203/70203 valid aggregated values (100.0%)
    y: 70203/70203 valid aggregated values (100.0%)
    PupilDiameter_left: 70203/70203 valid aggregated values (100.0%)
    EyeballCenterX_left: 70203/70203 valid aggregated values (100.0%)
    EyeballCenterY_left: 70203/70203 valid aggregated values (100.0%)
    EyeballCenterZ_left: 70203/70203 valid aggregated values (100.0%)
    OpticalAxisX_left: 70203/70203 valid aggregated values (100.0%)
    OpticalAxisY_left: 70203/70203 valid aggregated values (100.0%)
    OpticalAxisZ_left: 70203/70203 valid aggregated values (100.0%)
    PupilDiameter_right: 70203/70203 valid aggregated values (100.0%)
    EyeballCenterX_right: 70203/70203 valid aggregated values (100.0%)
    EyeballCenterY_right: 70203/70203 valid aggregated values (100.0%)
    EyeballCenterZ_right: 70203/70203 valid aggregated values (100.0%)
    OpticalAxisX_right: 70203/70203 valid aggregated values (100.0%)
    OpticalAxisY_right: 70203/70203 valid aggregated values (100.0%)
    OpticalAxisZ_right: 70203/70203 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_y: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 67155/68225 matches (98.4%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 67155/68225 matches (98.4%)

Processing temp_datasync_remaining.csv...
  File timestamps: 1136434.673 to 1138833.769
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 65322/68225 matches (95.7%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 2903:
  UNIX timestamp: 1757366853.7531688
  EST time: 2025-09-08 17:27:33.753168821-04:00
  Corresponding EmotiBit timestamp: 1136434.676
Successfully created Date and Time columns for all 68225 rows (EST timezone)
Duration: 2736.83 seconds

Example rows around sync point (row 2903):
  Row 2901: EmotiBit=1136434.596, diff=-0.080s, Time=17:27:33.673
  Row 2902: EmotiBit=1136434.636, diff=-0.040s, Time=17:27:33.713
  Row 2903: EmotiBit=1136434.676, diff=+0.000s, Time=17:27:33.753 <- SYNC POINT
  Row 2904: EmotiBit=1136434.716, diff=+0.040s, Time=17:27:33.793
  Row 2905: EmotiBit=1136434.756, diff=+0.080s, Time=17:27:33.833

Applying forward fill to missing values...
Missing values before ffill: 392574
Missing values after ffill: 8745
Filled 383829 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 68225 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 1136318.221 to 1139055.051
Duration: 2736.83 seconds
Participant ID: 29
Condition: Distrust Priming
Video condition: 3

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 65322/68225 (95.7% complete)
DataSyncMarker_channel_1: 65322/68225 (95.7% complete)
Reliability: 65322/68225 (95.7% complete)
PPG_GRN_C: 68225/68225 (100.0% complete)
PPG_RED_C: 68225/68225 (100.0% complete)
PPG_IR_C: 68225/68225 (100.0% complete)
EDA_C: 68225/68225 (100.0% complete)
HR_C: 68225/68225 (100.0% complete)
TEMP_C: 68223/68225 (100.0% complete)
THERM_C: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_x: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_y: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 68225/68225 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 68225/68225 (100.0% complete)
PPG_GRN_IS: 68225/68225 (100.0% complete)
PPG_RED_IS: 68225/68225 (100.0% complete)
PPG_IR_IS: 68225/68225 (100.0% complete)
EDA_IS: 68225/68225 (100.0% complete)
HR_IS: 68193/68225 (100.0% complete)
TEMP_IS: 68224/68225 (100.0% complete)
THERM_IS: 68224/68225 (100.0% complete)

============================================================
Processing ID 30  (30_C.xdf)
  condition=Trust Priming  video_condition=4
============================================================

Stream 12: Clock offsets (0, 1) cannot be used for synchronization
Stream 12: No samples in clock offsets (0, 1), skipping...
Stream 2: Clock offsets (0, 1) cannot be used for synchronization
Stream 2: No samples in clock offsets (0, 1), skipping...
Stream 12: Calculated effective sampling rate 150.5721 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (22218, 1)
  Sample count: 22218

Exported stream 1 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73854, 1)
  Sample count: 73854

Exported stream 2 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (22217, 1)
  Sample count: 22217

Exported stream 4 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73854, 1)
  Sample count: 73854

Exported stream 5 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (73703, 1)
  Sample count: 73703

Exported stream 6 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (73703, 1)
  Sample count: 73703

Exported stream 7 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2606, 1)
  Sample count: 2606

Exported stream 8 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (44433, 1)
  Sample count: 44433

Exported stream 9 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (22217, 1)
  Sample count: 22217

Exported stream 10 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (73703, 1)
  Sample count: 73703

Exported stream 11 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (22218, 1)
  Sample count: 22218

Exported stream 12 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (44435, 1)
  Sample count: 44435

Exported stream 13 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (1142, 1)
  Sample count: 1142

Exported stream 14 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73854, 1)
  Sample count: 73854

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (449915, 16)
  Sample count: 449915
  First timestamp: 1197412.9134168671

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/30_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (73854 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 1197614.432 to 1200237.936
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=1197614.432, value=1.0
    t=1198232.046, value=2.0
    t=1198703.382, value=1.0
    t=1199315.757, value=2.0
    t=1199628.591, value=1.0
    t=1200237.936, value=2.0
  Added Reliability column using video condition 4: ('HH', 'M', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 71072/73854 matches (96.2%)
  DataSyncMarker value distribution:
    1.0: 45860 rows (62.1%)
    2.0: 25212 rows (34.1%)
Base PPG timestamps: 1197502.867 to 1200464.934

Processing EDA_I.csv...
  File timestamps: 1197502.787 to 1200464.893
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 47177/73854 matches (63.9%)

Processing THERM_I.csv...
  File timestamps: 1197502.788 to 1200464.894
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 23594/73854 matches (31.9%)

Processing PPG_RED_I.csv...
  File timestamps: 1197502.727 to 1200464.882
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 73853/73854 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 1197503.547 to 1200461.411
  Added 1 column(s) from HR_C.csv
    HR_C_value: 1203/73854 matches (1.6%)

Processing TEMP1_I.csv...
  File timestamps: 1197502.781 to 1200464.886
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 23587/73854 matches (31.9%)

Processing PPG_IR_C.csv...
  File timestamps: 1197502.866 to 1200464.933
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 73854/73854 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 1197502.728 to 1200464.883
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 73853/73854 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 1197502.727 to 1200464.882
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 73853/73854 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 1197502.940 to 1200464.903
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 23585/73854 matches (31.9%)

Processing EDA_C.csv...
  File timestamps: 1197502.939 to 1200464.901
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 47151/73854 matches (63.8%)

Processing HR_I.csv...
  File timestamps: 1197503.548 to 1200464.912
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2741/73854 matches (3.7%)

Processing TEMP1_C.csv...
  File timestamps: 1197502.933 to 1200464.895
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 23594/73854 matches (31.9%)

Processing PPG_RED_C.csv...
  File timestamps: 1197502.866 to 1200464.934
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 73854/73854 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 1197412.913 to 1200400.943
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 74701 samples (16 channels)
    x: 74701/74701 valid aggregated values (100.0%)
    y: 74701/74701 valid aggregated values (100.0%)
    PupilDiameter_left: 74701/74701 valid aggregated values (100.0%)
    EyeballCenterX_left: 74701/74701 valid aggregated values (100.0%)
    EyeballCenterY_left: 74701/74701 valid aggregated values (100.0%)
    EyeballCenterZ_left: 74701/74701 valid aggregated values (100.0%)
    OpticalAxisX_left: 74701/74701 valid aggregated values (100.0%)
    OpticalAxisY_left: 74701/74701 valid aggregated values (100.0%)
    OpticalAxisZ_left: 74701/74701 valid aggregated values (100.0%)
    PupilDiameter_right: 74701/74701 valid aggregated values (100.0%)
    EyeballCenterX_right: 74701/74701 valid aggregated values (100.0%)
    EyeballCenterY_right: 74701/74701 valid aggregated values (100.0%)
    EyeballCenterZ_right: 74701/74701 valid aggregated values (100.0%)
    OpticalAxisX_right: 74701/74701 valid aggregated values (100.0%)
    OpticalAxisY_right: 74701/74701 valid aggregated values (100.0%)
    OpticalAxisZ_right: 74701/74701 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_y: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 72258/73854 matches (97.8%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 72258/73854 matches (97.8%)

Processing temp_datasync_remaining.csv...
  File timestamps: 1197614.432 to 1200237.936
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 71072/73854 matches (96.2%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 2782:
  UNIX timestamp: 1757428033.152565
  EST time: 2025-09-09 10:27:13.152565002-04:00
  Corresponding EmotiBit timestamp: 1197614.447
Successfully created Date and Time columns for all 73854 rows (EST timezone)
Duration: 2962.07 seconds

Example rows around sync point (row 2782):
  Row 2780: EmotiBit=1197614.366, diff=-0.081s, Time=10:27:13.071
  Row 2781: EmotiBit=1197614.406, diff=-0.041s, Time=10:27:13.111
  Row 2782: EmotiBit=1197614.447, diff=+0.000s, Time=10:27:13.152 <- SYNC POINT
  Row 2783: EmotiBit=1197614.487, diff=+0.040s, Time=10:27:13.192
  Row 2784: EmotiBit=1197614.527, diff=+0.080s, Time=10:27:13.232

Applying forward fill to missing values...
Missing values before ffill: 432085
Missing values after ffill: 8388
Filled 423697 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 73854 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 1197502.867 to 1200464.934
Duration: 2962.07 seconds
Participant ID: 30
Condition: Trust Priming
Video condition: 4

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 71072/73854 (96.2% complete)
DataSyncMarker_channel_1: 71072/73854 (96.2% complete)
Reliability: 71072/73854 (96.2% complete)
PPG_GRN_C: 73854/73854 (100.0% complete)
PPG_RED_C: 73854/73854 (100.0% complete)
PPG_IR_C: 73854/73854 (100.0% complete)
EDA_C: 73852/73854 (100.0% complete)
HR_C: 73837/73854 (100.0% complete)
TEMP_C: 73852/73854 (100.0% complete)
THERM_C: 73852/73854 (100.0% complete)
Neon Companion_Neon Gaze_x: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_y: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 73854/73854 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 73854/73854 (100.0% complete)
PPG_GRN_IS: 73854/73854 (100.0% complete)
PPG_RED_IS: 73854/73854 (100.0% complete)
PPG_IR_IS: 73854/73854 (100.0% complete)
EDA_IS: 73854/73854 (100.0% complete)
HR_IS: 73837/73854 (100.0% complete)
TEMP_IS: 73853/73854 (100.0% complete)
THERM_IS: 73853/73854 (100.0% complete)

============================================================
Processing ID 31  (31_C.xdf)
  condition=Distrust Priming  video_condition=4
============================================================

Stream 16: Calculated effective sampling rate 132.1751 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (81521, 1)
  Sample count: 81521

Exported stream 1 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (1712, 1)
  Sample count: 1712

Exported stream 2 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (81350, 1)
  Sample count: 81350

Exported stream 4 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2851, 1)
  Sample count: 2851

Exported stream 5 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (49046, 1)
  Sample count: 49046

Exported stream 6 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (81521, 1)
  Sample count: 81521

Exported stream 7 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (24523, 1)
  Sample count: 24523

Exported stream 8 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (81350, 1)
  Sample count: 81350

Exported stream 9 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (24523, 1)
  Sample count: 24523

Exported stream 10 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (24522, 1)
  Sample count: 24522

Exported stream 11 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (81350, 1)
  Sample count: 81350

Exported stream 12 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (49047, 1)
  Sample count: 49047

Exported stream 13 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (24522, 1)
  Sample count: 24522

Exported stream 14 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (81521, 1)
  Sample count: 81521

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (438712, 16)
  Sample count: 438712
  First timestamp: 1204459.6918264818

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/31_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (81521 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 1204819.640 to 1207546.347
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=1204819.640, value=1.0
    t=1205437.013, value=2.0
    t=1205964.043, value=1.0
    t=1206573.578, value=2.0
    t=1206934.673, value=1.0
    t=1207546.347, value=2.0
  Added Reliability column using video condition 4: ('HH', 'M', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 76516/81521 matches (93.9%)
  DataSyncMarker value distribution:
    1.0: 45843 rows (56.2%)
    2.0: 30673 rows (37.6%)
Base PPG timestamps: 1204618.933 to 1207888.411

Processing EDA_I.csv...
  File timestamps: 1204619.011 to 1207888.483
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 52056/81521 matches (63.9%)

Processing THERM_I.csv...
  File timestamps: 1204619.079 to 1207888.417
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 26027/81521 matches (31.9%)

Processing PPG_RED_I.csv...
  File timestamps: 1204618.810 to 1207888.443
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 81521/81521 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 1204621.949 to 1207887.349
  Added 1 column(s) from HR_C.csv
    HR_C_value: 1827/81521 matches (2.2%)

Processing TEMP1_I.csv...
  File timestamps: 1204619.072 to 1207888.410
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 26033/81521 matches (31.9%)

Processing PPG_IR_C.csv...
  File timestamps: 1204618.932 to 1207888.409
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 81521/81521 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 1204618.811 to 1207888.444
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 81521/81521 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 1204618.810 to 1207888.443
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 81521/81521 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 1204619.074 to 1207888.301
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 26033/81521 matches (31.9%)

Processing EDA_C.csv...
  File timestamps: 1204619.011 to 1207888.422
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 52070/81521 matches (63.9%)

Processing HR_I.csv...
  File timestamps: 1204618.899 to 1207887.516
  Added 1 column(s) from HR_I.csv
    HR_I_value: 3039/81521 matches (3.7%)

Processing TEMP1_C.csv...
  File timestamps: 1204619.066 to 1207888.293
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 26018/81521 matches (31.9%)

Processing PPG_RED_C.csv...
  File timestamps: 1204618.933 to 1207888.410
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 81521/81521 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 1204459.692 to 1207778.857
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 82980 samples (16 channels)
    x: 82980/82980 valid aggregated values (100.0%)
    y: 82980/82980 valid aggregated values (100.0%)
    PupilDiameter_left: 82980/82980 valid aggregated values (100.0%)
    EyeballCenterX_left: 82980/82980 valid aggregated values (100.0%)
    EyeballCenterY_left: 82980/82980 valid aggregated values (100.0%)
    EyeballCenterZ_left: 82980/82980 valid aggregated values (100.0%)
    OpticalAxisX_left: 82980/82980 valid aggregated values (100.0%)
    OpticalAxisY_left: 82980/82980 valid aggregated values (100.0%)
    OpticalAxisZ_left: 82980/82980 valid aggregated values (100.0%)
    PupilDiameter_right: 82980/82980 valid aggregated values (100.0%)
    EyeballCenterX_right: 82980/82980 valid aggregated values (100.0%)
    EyeballCenterY_right: 82980/82980 valid aggregated values (100.0%)
    EyeballCenterZ_right: 82980/82980 valid aggregated values (100.0%)
    OpticalAxisX_right: 82980/82980 valid aggregated values (100.0%)
    OpticalAxisY_right: 82980/82980 valid aggregated values (100.0%)
    OpticalAxisZ_right: 82980/82980 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_y: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 78789/81521 matches (96.6%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 78789/81521 matches (96.6%)

Processing temp_datasync_remaining.csv...
  File timestamps: 1204819.640 to 1207546.347
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 76516/81521 matches (93.9%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 5005:
  UNIX timestamp: 1757435238.379328
  EST time: 2025-09-09 12:27:18.379328012-04:00
  Corresponding EmotiBit timestamp: 1204819.666
Successfully created Date and Time columns for all 81521 rows (EST timezone)
Duration: 3269.48 seconds

Example rows around sync point (row 5005):
  Row 5003: EmotiBit=1204819.586, diff=-0.080s, Time=12:27:18.299
  Row 5004: EmotiBit=1204819.626, diff=-0.040s, Time=12:27:18.339
  Row 5005: EmotiBit=1204819.666, diff=+0.000s, Time=12:27:18.379 <- SYNC POINT
  Row 5006: EmotiBit=1204819.706, diff=+0.040s, Time=12:27:18.419
  Row 5007: EmotiBit=1204819.746, diff=+0.080s, Time=12:27:18.459

Applying forward fill to missing values...
Missing values before ffill: 497792
Missing values after ffill: 15302
Filled 482490 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 81521 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 1204618.933 to 1207888.411
Duration: 3269.48 seconds
Participant ID: 31
Condition: Distrust Priming
Video condition: 4

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 76516/81521 (93.9% complete)
DataSyncMarker_channel_1: 76516/81521 (93.9% complete)
Reliability: 76516/81521 (93.9% complete)
PPG_GRN_C: 81521/81521 (100.0% complete)
PPG_RED_C: 81521/81521 (100.0% complete)
PPG_IR_C: 81521/81521 (100.0% complete)
EDA_C: 81519/81521 (100.0% complete)
HR_C: 81446/81521 (99.9% complete)
TEMP_C: 81518/81521 (100.0% complete)
THERM_C: 81518/81521 (100.0% complete)
Neon Companion_Neon Gaze_x: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_y: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 81521/81521 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 81521/81521 (100.0% complete)
PPG_GRN_IS: 81521/81521 (100.0% complete)
PPG_RED_IS: 81521/81521 (100.0% complete)
PPG_IR_IS: 81521/81521 (100.0% complete)
EDA_IS: 81519/81521 (100.0% complete)
HR_IS: 81326/81521 (99.8% complete)
TEMP_IS: 81518/81521 (100.0% complete)
THERM_IS: 81517/81521 (100.0% complete)

============================================================
Processing ID 32  (32_C.xdf)
  condition=Trust Priming  video_condition=1
============================================================

Stream 15: Calculated effective sampling rate 148.9480 Hz is different from specified rate 200.0000 Hz.
Stream 15: Segments and clock-segments differ

Exported stream 0 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71038, 1)
  Sample count: 71038

Exported stream 1 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (70887, 1)
  Sample count: 70887

Exported stream 2 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21372, 1)
  Sample count: 21372

Exported stream 3 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (70884, 1)
  Sample count: 70884

Exported stream 5 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1530, 1)
  Sample count: 1530

Exported stream 6 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21370, 1)
  Sample count: 21370

Exported stream 7 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (42744, 1)
  Sample count: 42744

Exported stream 8 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2657, 1)
  Sample count: 2657

Exported stream 9 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (70884, 1)
  Sample count: 70884

Exported stream 10 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (42740, 1)
  Sample count: 42740

Exported stream 11 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71038, 1)
  Sample count: 71038

Exported stream 12 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21370, 1)
  Sample count: 21370

Exported stream 13 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71038, 1)
  Sample count: 71038

Exported stream 14 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21372, 1)
  Sample count: 21372

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (418980, 16)
  Sample count: 418980
  First timestamp: 88799.75108515976

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/32_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (71038 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 88941.052 to 91442.965
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=88941.052, value=1.0
    t=89551.175, value=2.0
    t=89879.986, value=1.0
    t=90502.254, value=2.0
    t=90831.750, value=1.0
    t=91442.965, value=2.0
  Added Reliability column using video condition 1: ('LL', 'HH', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 67878/71038 matches (95.6%)
  DataSyncMarker value distribution:
    1.0: 45963 rows (64.7%)
    2.0: 21915 rows (30.8%)
Base PPG timestamps: 88814.314 to 91663.625

Processing EDA_I.csv...
  File timestamps: 88814.438 to 91663.509
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 44862/71038 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 88814.439 to 91663.443
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 22389/71038 matches (31.5%)

Processing PPG_RED_I.csv...
  File timestamps: 88814.367 to 91663.524
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 71035/71038 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 88815.186 to 91662.289
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2801/71038 matches (3.9%)

Processing TEMP1_I.csv...
  File timestamps: 88814.432 to 91663.436
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 22467/71038 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 88814.313 to 91663.623
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 71038/71038 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 88814.247 to 91663.524
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 71036/71038 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 88814.366 to 91663.523
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 71035/71038 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 88814.420 to 91663.620
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 22435/71038 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 88814.352 to 91663.618
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 44845/71038 matches (63.1%)

Processing HR_I.csv...
  File timestamps: 88815.620 to 91656.139
  Added 1 column(s) from HR_I.csv
    HR_I_value: 1600/71038 matches (2.3%)

Processing TEMP1_C.csv...
  File timestamps: 88814.412 to 91663.612
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 22463/71038 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 88814.314 to 91663.624
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 71038/71038 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 88799.751 to 91680.631
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 70325 samples (16 channels)
    x: 70324/70325 valid aggregated values (100.0%)
    y: 70324/70325 valid aggregated values (100.0%)
    PupilDiameter_left: 70325/70325 valid aggregated values (100.0%)
    EyeballCenterX_left: 70325/70325 valid aggregated values (100.0%)
    EyeballCenterY_left: 70325/70325 valid aggregated values (100.0%)
    EyeballCenterZ_left: 70325/70325 valid aggregated values (100.0%)
    OpticalAxisX_left: 70325/70325 valid aggregated values (100.0%)
    OpticalAxisY_left: 70325/70325 valid aggregated values (100.0%)
    OpticalAxisZ_left: 70325/70325 valid aggregated values (100.0%)
    PupilDiameter_right: 70325/70325 valid aggregated values (100.0%)
    EyeballCenterX_right: 70325/70325 valid aggregated values (100.0%)
    EyeballCenterY_right: 70325/70325 valid aggregated values (100.0%)
    EyeballCenterZ_right: 70325/70325 valid aggregated values (100.0%)
    OpticalAxisX_right: 70325/70325 valid aggregated values (100.0%)
    OpticalAxisY_right: 70325/70325 valid aggregated values (100.0%)
    OpticalAxisZ_right: 70325/70325 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 69345/71038 matches (97.6%)
    Neon Companion_Neon Gaze_y: 69345/71038 matches (97.6%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 69346/71038 matches (97.6%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 69346/71038 matches (97.6%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 69346/71038 matches (97.6%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 69346/71038 matches (97.6%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 69346/71038 matches (97.6%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 69346/71038 matches (97.6%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 69346/71038 matches (97.6%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 69346/71038 matches (97.6%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 69346/71038 matches (97.6%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 69346/71038 matches (97.6%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 69346/71038 matches (97.6%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 69346/71038 matches (97.6%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 69346/71038 matches (97.6%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 69346/71038 matches (97.6%)

Processing temp_datasync_remaining.csv...
  File timestamps: 88941.052 to 91442.965
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 67878/71038 matches (95.6%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3160:
  UNIX timestamp: 1757528662.136072
  EST time: 2025-09-10 14:24:22.136071920-04:00
  Corresponding EmotiBit timestamp: 88941.063
Successfully created Date and Time columns for all 71038 rows (EST timezone)
Duration: 2849.31 seconds

Example rows around sync point (row 3160):
  Row 3158: EmotiBit=88940.982, diff=-0.081s, Time=14:24:22.055
  Row 3159: EmotiBit=88941.023, diff=-0.040s, Time=14:24:22.096
  Row 3160: EmotiBit=88941.063, diff=+0.000s, Time=14:24:22.136 <- SYNC POINT
  Row 3161: EmotiBit=88941.103, diff=+0.040s, Time=14:24:22.176
  Row 3162: EmotiBit=88941.143, diff=+0.080s, Time=14:24:22.216

Applying forward fill to missing values...
Missing values before ffill: 421004
Missing values after ffill: 9552
Filled 411452 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 71038 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 88814.314 to 91663.625
Duration: 2849.31 seconds
Participant ID: 32
Condition: Trust Priming
Video condition: 1

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 67878/71038 (95.6% complete)
DataSyncMarker_channel_1: 67878/71038 (95.6% complete)
Reliability: 67878/71038 (95.6% complete)
PPG_GRN_C: 71038/71038 (100.0% complete)
PPG_RED_C: 71038/71038 (100.0% complete)
PPG_IR_C: 71038/71038 (100.0% complete)
EDA_C: 71037/71038 (100.0% complete)
HR_C: 71016/71038 (100.0% complete)
TEMP_C: 71036/71038 (100.0% complete)
THERM_C: 71035/71038 (100.0% complete)
Neon Companion_Neon Gaze_x: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_y: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 71038/71038 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 71038/71038 (100.0% complete)
PPG_GRN_IS: 71038/71038 (100.0% complete)
PPG_RED_IS: 71037/71038 (100.0% complete)
PPG_IR_IS: 71037/71038 (100.0% complete)
EDA_IS: 71035/71038 (100.0% complete)
HR_IS: 71005/71038 (100.0% complete)
TEMP_IS: 71035/71038 (100.0% complete)
THERM_IS: 71035/71038 (100.0% complete)

============================================================
Processing ID 33  (33_C.xdf)
  condition=Distrust Priming  video_condition=1
============================================================

Stream 5: Calculated effective sampling rate 143.7938 Hz is different from specified rate 200.0000 Hz.
Stream 5: Segments and clock-segments differ

Exported stream 0 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2145, 1)
  Sample count: 2145

Exported stream 1 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (24351, 1)
  Sample count: 24351

Exported stream 3 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (24351, 1)
  Sample count: 24351

Exported stream 4 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (80785, 1)
  Sample count: 80785

Exported stream 5 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (80785, 1)
  Sample count: 80785

Exported stream 6 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (80785, 1)
  Sample count: 80785

Exported stream 7 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (80936, 1)
  Sample count: 80936

Exported stream 8 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (24352, 1)
  Sample count: 24352

Exported stream 9 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (48702, 1)
  Sample count: 48702

Exported stream 10 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (24351, 1)
  Sample count: 24351

Exported stream 11 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (80936, 1)
  Sample count: 80936

Exported stream 12 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (48704, 1)
  Sample count: 48704

Exported stream 13 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (3062, 1)
  Sample count: 3062

Exported stream 14 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (80936, 1)
  Sample count: 80936

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (462386, 16)
  Sample count: 462386
  First timestamp: 95870.52846876225

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/33_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (80936 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 96045.678 to 98765.268
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=96045.678, value=1.0
    t=96656.967, value=2.0
    t=97154.387, value=1.0
    t=97775.564, value=2.0
    t=98157.550, value=1.0
    t=98765.268, value=2.0
  Added Reliability column using video condition 1: ('LL', 'HH', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 77261/80936 matches (95.5%)
  DataSyncMarker value distribution:
    1.0: 45874 rows (56.7%)
    2.0: 31387 rows (38.8%)
Base PPG timestamps: 95898.279 to 99144.929

Processing EDA_I.csv...
  File timestamps: 95898.336 to 99144.909
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 51119/80936 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 95898.337 to 99144.843
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 25552/80936 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 95898.283 to 99144.932
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 80936/80936 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 95900.493 to 99140.660
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2253/80936 matches (2.8%)

Processing TEMP1_I.csv...
  File timestamps: 95898.463 to 99144.835
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 25542/80936 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 95898.278 to 99144.928
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 80936/80936 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 95898.283 to 99144.932
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 80936/80936 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 95898.282 to 99144.931
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 80936/80936 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 95898.450 to 99144.811
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 25558/80936 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 95898.360 to 99144.876
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 51114/80936 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 95898.475 to 99137.543
  Added 1 column(s) from HR_I.csv
    HR_I_value: 3218/80936 matches (4.0%)

Processing TEMP1_C.csv...
  File timestamps: 95898.443 to 99144.803
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 25535/80936 matches (31.5%)

Processing PPG_RED_C.csv...
  File timestamps: 95898.278 to 99144.929
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 80936/80936 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 95870.528 to 99143.709
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 80392 samples (16 channels)
    x: 80392/80392 valid aggregated values (100.0%)
    y: 80392/80392 valid aggregated values (100.0%)
    PupilDiameter_left: 80392/80392 valid aggregated values (100.0%)
    EyeballCenterX_left: 80392/80392 valid aggregated values (100.0%)
    EyeballCenterY_left: 80392/80392 valid aggregated values (100.0%)
    EyeballCenterZ_left: 80392/80392 valid aggregated values (100.0%)
    OpticalAxisX_left: 80392/80392 valid aggregated values (100.0%)
    OpticalAxisY_left: 80392/80392 valid aggregated values (100.0%)
    OpticalAxisZ_left: 80392/80392 valid aggregated values (100.0%)
    PupilDiameter_right: 80392/80392 valid aggregated values (100.0%)
    EyeballCenterX_right: 80392/80392 valid aggregated values (100.0%)
    EyeballCenterY_right: 80392/80392 valid aggregated values (100.0%)
    EyeballCenterZ_right: 80392/80392 valid aggregated values (100.0%)
    OpticalAxisX_right: 80392/80392 valid aggregated values (100.0%)
    OpticalAxisY_right: 80392/80392 valid aggregated values (100.0%)
    OpticalAxisZ_right: 80392/80392 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_y: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 79471/80936 matches (98.2%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 79471/80936 matches (98.2%)

Processing temp_datasync_remaining.csv...
  File timestamps: 96045.678 to 98765.268
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 77261/80936 matches (95.5%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3675:
  UNIX timestamp: 1757535766.7658188
  EST time: 2025-09-10 16:22:46.765818834-04:00
  Corresponding EmotiBit timestamp: 96045.699
Successfully created Date and Time columns for all 80936 rows (EST timezone)
Duration: 3246.65 seconds

Example rows around sync point (row 3675):
  Row 3673: EmotiBit=96045.619, diff=-0.080s, Time=16:22:46.685
  Row 3674: EmotiBit=96045.659, diff=-0.040s, Time=16:22:46.725
  Row 3675: EmotiBit=96045.699, diff=+0.000s, Time=16:22:46.765 <- SYNC POINT
  Row 3676: EmotiBit=96045.739, diff=+0.040s, Time=16:22:46.805
  Row 3677: EmotiBit=96045.779, diff=+0.080s, Time=16:22:46.845

Applying forward fill to missing values...
Missing values before ffill: 472062
Missing values after ffill: 11102
Filled 460960 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 80936 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 95898.279 to 99144.929
Duration: 3246.65 seconds
Participant ID: 33
Condition: Distrust Priming
Video condition: 1

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 77261/80936 (95.5% complete)
DataSyncMarker_channel_1: 77261/80936 (95.5% complete)
Reliability: 77261/80936 (95.5% complete)
PPG_GRN_C: 80936/80936 (100.0% complete)
PPG_RED_C: 80936/80936 (100.0% complete)
PPG_IR_C: 80936/80936 (100.0% complete)
EDA_C: 80934/80936 (100.0% complete)
HR_C: 80881/80936 (99.9% complete)
TEMP_C: 80932/80936 (100.0% complete)
THERM_C: 80932/80936 (100.0% complete)
Neon Companion_Neon Gaze_x: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_y: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 80936/80936 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 80936/80936 (100.0% complete)
PPG_GRN_IS: 80936/80936 (100.0% complete)
PPG_RED_IS: 80936/80936 (100.0% complete)
PPG_IR_IS: 80936/80936 (100.0% complete)
EDA_IS: 80935/80936 (100.0% complete)
HR_IS: 80931/80936 (100.0% complete)
TEMP_IS: 80931/80936 (100.0% complete)
THERM_IS: 80935/80936 (100.0% complete)

============================================================
Processing ID 34  (34_C.xdf)
  condition=Trust Priming  video_condition=2
============================================================

Stream 8: Calculated effective sampling rate 153.5317 Hz is different from specified rate 200.0000 Hz.
Stream 8: Segments and clock-segments differ

Exported stream 0 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (41861, 1)
  Sample count: 41861

Exported stream 2 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (69453, 1)
  Sample count: 69453

Exported stream 3 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (69572, 1)
  Sample count: 69572

Exported stream 4 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20931, 1)
  Sample count: 20931

Exported stream 5 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20930, 1)
  Sample count: 20930

Exported stream 6 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (1566, 1)
  Sample count: 1566

Exported stream 7 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (69453, 1)
  Sample count: 69453

Exported stream 8 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20930, 1)
  Sample count: 20930

Exported stream 9 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (69572, 1)
  Sample count: 69572

Exported stream 10 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20929, 1)
  Sample count: 20929

Exported stream 11 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (69456, 1)
  Sample count: 69456

Exported stream 12 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (41858, 1)
  Sample count: 41858

Exported stream 13 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (69572, 1)
  Sample count: 69572

Exported stream 14 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1448, 1)
  Sample count: 1448

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (422328, 16)
  Sample count: 422328
  First timestamp: 160715.822991107

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/34_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (69572 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 160867.559 to 163287.101
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=160867.559, value=1.0
    t=161478.665, value=2.0
    t=161814.148, value=1.0
    t=162421.759, value=2.0
    t=162671.054, value=1.0
    t=163287.101, value=2.0
  Added Reliability column using video condition 2: ('LL', 'M', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 65693/69572 matches (94.4%)
  DataSyncMarker value distribution:
    1.0: 45743 rows (65.7%)
    2.0: 19950 rows (28.7%)
Base PPG timestamps: 160712.008 to 163502.494

Processing EDA_I.csv...
  File timestamps: 160711.871 to 163502.403
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 43342/69572 matches (62.3%)

Processing THERM_I.csv...
  File timestamps: 160711.937 to 163502.376
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 21681/69572 matches (31.2%)

Processing PPG_RED_I.csv...
  File timestamps: 160711.769 to 163502.350
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 69568/69572 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 160713.872 to 163500.192
  Added 1 column(s) from HR_C.csv
    HR_C_value: 1614/69572 matches (2.3%)

Processing TEMP1_I.csv...
  File timestamps: 160711.970 to 163502.397
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 21667/69572 matches (31.1%)

Processing PPG_IR_C.csv...
  File timestamps: 160712.007 to 163502.493
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 69572/69572 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 160711.769 to 163502.471
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 69571/69572 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 160711.768 to 163502.350
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 69568/69572 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 160712.078 to 163502.481
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 21678/69572 matches (31.2%)

Processing EDA_C.csv...
  File timestamps: 160712.039 to 163502.497
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 43329/69572 matches (62.3%)

Processing HR_I.csv...
  File timestamps: 160714.420 to 163500.259
  Added 1 column(s) from HR_I.csv
    HR_I_value: 1514/69572 matches (2.2%)

Processing TEMP1_C.csv...
  File timestamps: 160712.127 to 163502.507
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 21665/69572 matches (31.1%)

Processing PPG_RED_C.csv...
  File timestamps: 160712.008 to 163502.493
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 69572/69572 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 160715.823 to 163515.104
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 68772 samples (16 channels)
    x: 68772/68772 valid aggregated values (100.0%)
    y: 68772/68772 valid aggregated values (100.0%)
    PupilDiameter_left: 68772/68772 valid aggregated values (100.0%)
    EyeballCenterX_left: 68772/68772 valid aggregated values (100.0%)
    EyeballCenterY_left: 68772/68772 valid aggregated values (100.0%)
    EyeballCenterZ_left: 68772/68772 valid aggregated values (100.0%)
    OpticalAxisX_left: 68772/68772 valid aggregated values (100.0%)
    OpticalAxisY_left: 68772/68772 valid aggregated values (100.0%)
    OpticalAxisZ_left: 68772/68772 valid aggregated values (100.0%)
    PupilDiameter_right: 68772/68772 valid aggregated values (100.0%)
    EyeballCenterX_right: 68772/68772 valid aggregated values (100.0%)
    EyeballCenterY_right: 68772/68772 valid aggregated values (100.0%)
    EyeballCenterZ_right: 68772/68772 valid aggregated values (100.0%)
    OpticalAxisX_right: 68772/68772 valid aggregated values (100.0%)
    OpticalAxisY_right: 68772/68772 valid aggregated values (100.0%)
    OpticalAxisZ_right: 68772/68772 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_y: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 68270/69572 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 68270/69572 matches (98.1%)

Processing temp_datasync_remaining.csv...
  File timestamps: 160867.559 to 163287.101
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 65693/69572 matches (94.4%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3879:
  UNIX timestamp: 1757600588.070487
  EST time: 2025-09-11 10:23:08.070487022-04:00
  Corresponding EmotiBit timestamp: 160867.595
Successfully created Date and Time columns for all 69572 rows (EST timezone)
Duration: 2790.49 seconds

Example rows around sync point (row 3879):
  Row 3877: EmotiBit=160867.515, diff=-0.080s, Time=10:23:07.990
  Row 3878: EmotiBit=160867.555, diff=-0.040s, Time=10:23:08.030
  Row 3879: EmotiBit=160867.595, diff=+0.000s, Time=10:23:08.070 <- SYNC POINT
  Row 3880: EmotiBit=160867.635, diff=+0.040s, Time=10:23:08.110
  Row 3881: EmotiBit=160867.675, diff=+0.080s, Time=10:23:08.150

Applying forward fill to missing values...
Missing values before ffill: 412564
Missing values after ffill: 13273
Filled 399291 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 69572 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 160712.008 to 163502.494
Duration: 2790.49 seconds
Participant ID: 34
Condition: Trust Priming
Video condition: 2

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 65693/69572 (94.4% complete)
DataSyncMarker_channel_1: 65693/69572 (94.4% complete)
Reliability: 65693/69572 (94.4% complete)
PPG_GRN_C: 69572/69572 (100.0% complete)
PPG_RED_C: 69572/69572 (100.0% complete)
PPG_IR_C: 69572/69572 (100.0% complete)
EDA_C: 69571/69572 (100.0% complete)
HR_C: 69526/69572 (99.9% complete)
TEMP_C: 69569/69572 (100.0% complete)
THERM_C: 69570/69572 (100.0% complete)
Neon Companion_Neon Gaze_x: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_y: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 69477/69572 (99.9% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 69477/69572 (99.9% complete)
PPG_GRN_IS: 69572/69572 (100.0% complete)
PPG_RED_IS: 69572/69572 (100.0% complete)
PPG_IR_IS: 69572/69572 (100.0% complete)
EDA_IS: 69572/69572 (100.0% complete)
HR_IS: 69512/69572 (99.9% complete)
TEMP_IS: 69570/69572 (100.0% complete)
THERM_IS: 69570/69572 (100.0% complete)

============================================================
Processing ID 35  (35_C.xdf)
  condition=Distrust Priming  video_condition=2
============================================================

Stream 13: Calculated effective sampling rate 151.5154 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21465, 1)
  Sample count: 21465

Exported stream 1 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21467, 1)
  Sample count: 21467

Exported stream 2 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (42934, 1)
  Sample count: 42934

Exported stream 3 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71209, 1)
  Sample count: 71209

Exported stream 4 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21468, 1)
  Sample count: 21468

Exported stream 5 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71355, 1)
  Sample count: 71355

Exported stream 6 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71355, 1)
  Sample count: 71355

Exported stream 7 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71209, 1)
  Sample count: 71209

Exported stream 8 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (42931, 1)
  Sample count: 42931

Exported stream 9 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21465, 1)
  Sample count: 21465

Exported stream 10 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71209, 1)
  Sample count: 71209

Exported stream 11 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (1262, 1)
  Sample count: 1262

Exported stream 12 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71355, 1)
  Sample count: 71355

Exported stream 14 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2457, 1)
  Sample count: 2457

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (433777, 16)
  Sample count: 433777
  First timestamp: 246473.4986257704

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/35_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (71355 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 246641.979 to 249192.585
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=246641.979, value=1.0
    t=247252.523, value=2.0
    t=247602.582, value=1.0
    t=248211.688, value=2.0
    t=248574.917, value=1.0
    t=249192.585, value=2.0
  Added Reliability column using video condition 2: ('LL', 'M', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 69105/71355 matches (96.8%)
  DataSyncMarker value distribution:
    1.0: 45805 rows (64.2%)
    2.0: 23300 rows (32.7%)
Base PPG timestamps: 246551.759 to 249413.908

Processing EDA_I.csv...
  File timestamps: 246552.061 to 249413.935
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 44471/71355 matches (62.3%)

Processing THERM_I.csv...
  File timestamps: 246552.099 to 249413.883
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 22218/71355 matches (31.1%)

Processing PPG_RED_I.csv...
  File timestamps: 246551.913 to 249413.941
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 71351/71355 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 246552.427 to 249413.113
  Added 1 column(s) from HR_C.csv
    HR_C_value: 1298/71355 matches (1.8%)

Processing TEMP1_I.csv...
  File timestamps: 246552.092 to 249413.876
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 22236/71355 matches (31.2%)

Processing PPG_IR_C.csv...
  File timestamps: 246551.757 to 249413.907
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 71355/71355 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 246551.914 to 249413.941
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 71351/71355 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 246551.913 to 249413.940
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 71351/71355 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 246551.887 to 249413.900
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 22246/71355 matches (31.2%)

Processing EDA_C.csv...
  File timestamps: 246551.819 to 249413.899
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 44440/71355 matches (62.3%)

Processing HR_I.csv...
  File timestamps: 246552.161 to 249413.279
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2531/71355 matches (3.5%)

Processing TEMP1_C.csv...
  File timestamps: 246551.920 to 249413.920
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 22229/71355 matches (31.2%)

Processing PPG_RED_C.csv...
  File timestamps: 246551.758 to 249413.908
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 71355/71355 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 246473.499 to 249336.416
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 71573 samples (16 channels)
    x: 71573/71573 valid aggregated values (100.0%)
    y: 71573/71573 valid aggregated values (100.0%)
    PupilDiameter_left: 71573/71573 valid aggregated values (100.0%)
    EyeballCenterX_left: 71573/71573 valid aggregated values (100.0%)
    EyeballCenterY_left: 71573/71573 valid aggregated values (100.0%)
    EyeballCenterZ_left: 71573/71573 valid aggregated values (100.0%)
    OpticalAxisX_left: 71573/71573 valid aggregated values (100.0%)
    OpticalAxisY_left: 71573/71573 valid aggregated values (100.0%)
    OpticalAxisZ_left: 71573/71573 valid aggregated values (100.0%)
    PupilDiameter_right: 71573/71573 valid aggregated values (100.0%)
    EyeballCenterX_right: 71573/71573 valid aggregated values (100.0%)
    EyeballCenterY_right: 71573/71573 valid aggregated values (100.0%)
    EyeballCenterZ_right: 71573/71573 valid aggregated values (100.0%)
    OpticalAxisX_right: 71573/71573 valid aggregated values (100.0%)
    OpticalAxisY_right: 71573/71573 valid aggregated values (100.0%)
    OpticalAxisZ_right: 71573/71573 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_y: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 69422/71355 matches (97.3%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 69422/71355 matches (97.3%)

Processing temp_datasync_remaining.csv...
  File timestamps: 246641.979 to 249192.585
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 69105/71355 matches (96.8%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 2250:
  UNIX timestamp: 1757686362.4991932
  EST time: 2025-09-12 10:12:42.499193192-04:00
  Corresponding EmotiBit timestamp: 246642.01
Successfully created Date and Time columns for all 71355 rows (EST timezone)
Duration: 2862.15 seconds

Example rows around sync point (row 2250):
  Row 2248: EmotiBit=246641.930, diff=-0.080s, Time=10:12:42.419
  Row 2249: EmotiBit=246641.970, diff=-0.040s, Time=10:12:42.459
  Row 2250: EmotiBit=246642.010, diff=+0.000s, Time=10:12:42.499 <- SYNC POINT
  Row 2251: EmotiBit=246642.051, diff=+0.041s, Time=10:12:42.540
  Row 2252: EmotiBit=246642.091, diff=+0.081s, Time=10:12:42.580

Applying forward fill to missing values...
Missing values before ffill: 426861
Missing values after ffill: 6821
Filled 420040 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 71355 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 246551.759 to 249413.908
Duration: 2862.15 seconds
Participant ID: 35
Condition: Distrust Priming
Video condition: 2

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 69105/71355 (96.8% complete)
DataSyncMarker_channel_1: 69105/71355 (96.8% complete)
Reliability: 69105/71355 (96.8% complete)
PPG_GRN_C: 71355/71355 (100.0% complete)
PPG_RED_C: 71355/71355 (100.0% complete)
PPG_IR_C: 71355/71355 (100.0% complete)
EDA_C: 71354/71355 (100.0% complete)
HR_C: 71338/71355 (100.0% complete)
TEMP_C: 71351/71355 (100.0% complete)
THERM_C: 71352/71355 (100.0% complete)
Neon Companion_Neon Gaze_x: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_y: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 71355/71355 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 71355/71355 (100.0% complete)
PPG_GRN_IS: 71351/71355 (100.0% complete)
PPG_RED_IS: 71351/71355 (100.0% complete)
PPG_IR_IS: 71351/71355 (100.0% complete)
EDA_IS: 71347/71355 (100.0% complete)
HR_IS: 71345/71355 (100.0% complete)
TEMP_IS: 71347/71355 (100.0% complete)
THERM_IS: 71347/71355 (100.0% complete)

============================================================
Processing ID 36  (36_C.xdf)
  condition=Trust Priming  video_condition=3
============================================================

Stream 1: Calculated effective sampling rate 147.5046 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (24884, 1)
  Sample count: 24884

Exported stream 1 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (82538, 1)
  Sample count: 82538

Exported stream 2 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (49769, 1)
  Sample count: 49769

Exported stream 3 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (82710, 1)
  Sample count: 82710

Exported stream 4 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (49767, 1)
  Sample count: 49767

Exported stream 5 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (24885, 1)
  Sample count: 24885

Exported stream 6 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (82538, 1)
  Sample count: 82538

Exported stream 7 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2742, 1)
  Sample count: 2742

Exported stream 8 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (82710, 1)
  Sample count: 82710

Exported stream 9 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (82710, 1)
  Sample count: 82710

Exported stream 10 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2529, 1)
  Sample count: 2529

Exported stream 11 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (24885, 1)
  Sample count: 24885

Exported stream 12 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (24884, 1)
  Sample count: 24884

Exported stream 13 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (82538, 1)
  Sample count: 82538

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (487918, 16)
  Sample count: 487918
  First timestamp: 523858.76722936315

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/36_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (82710 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 524188.342 to 526937.408
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=524188.342, value=1.0
    t=524805.116, value=2.0
    t=525338.282, value=1.0
    t=525955.818, value=2.0
    t=526324.530, value=1.0
    t=526937.408, value=2.0
  Added Reliability column using video condition 3: ('HH', 'LL', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 77243/82710 matches (93.4%)
  DataSyncMarker value distribution:
    1.0: 46053 rows (55.7%)
    2.0: 31190 rows (37.7%)
Base PPG timestamps: 523969.082 to 527286.604

Processing EDA_I.csv...
  File timestamps: 523968.975 to 527286.540
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 52182/82710 matches (63.1%)

Processing THERM_I.csv...
  File timestamps: 523968.976 to 527286.540
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 26098/82710 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 523968.807 to 527286.527
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 82708/82710 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 523970.163 to 527285.494
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2637/82710 matches (3.2%)

Processing TEMP1_I.csv...
  File timestamps: 523968.968 to 527286.533
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 26081/82710 matches (31.5%)

Processing PPG_IR_C.csv...
  File timestamps: 523969.081 to 527286.604
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 82710/82710 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 523968.808 to 527286.527
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 82708/82710 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 523968.807 to 527286.526
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 82708/82710 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 523969.099 to 527286.583
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 26092/82710 matches (31.5%)

Processing EDA_C.csv...
  File timestamps: 523969.098 to 527286.582
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 52180/82710 matches (63.1%)

Processing HR_I.csv...
  File timestamps: 523970.913 to 527284.377
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2874/82710 matches (3.5%)

Processing TEMP1_C.csv...
  File timestamps: 523969.091 to 527286.576
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 26086/82710 matches (31.5%)

Processing PPG_RED_C.csv...
  File timestamps: 523969.082 to 527286.604
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 82710/82710 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 523858.767 to 527166.576
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 82696 samples (16 channels)
    x: 82696/82696 valid aggregated values (100.0%)
    y: 82696/82696 valid aggregated values (100.0%)
    PupilDiameter_left: 82696/82696 valid aggregated values (100.0%)
    EyeballCenterX_left: 82696/82696 valid aggregated values (100.0%)
    EyeballCenterY_left: 82696/82696 valid aggregated values (100.0%)
    EyeballCenterZ_left: 82696/82696 valid aggregated values (100.0%)
    OpticalAxisX_left: 82696/82696 valid aggregated values (100.0%)
    OpticalAxisY_left: 82696/82696 valid aggregated values (100.0%)
    OpticalAxisZ_left: 82696/82696 valid aggregated values (100.0%)
    PupilDiameter_right: 82696/82696 valid aggregated values (100.0%)
    EyeballCenterX_right: 82696/82696 valid aggregated values (100.0%)
    EyeballCenterY_right: 82696/82696 valid aggregated values (100.0%)
    EyeballCenterZ_right: 82696/82696 valid aggregated values (100.0%)
    OpticalAxisX_right: 82696/82696 valid aggregated values (100.0%)
    OpticalAxisY_right: 82696/82696 valid aggregated values (100.0%)
    OpticalAxisZ_right: 82696/82696 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_y: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 79717/82710 matches (96.4%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 79717/82710 matches (96.4%)

Processing temp_datasync_remaining.csv...
  File timestamps: 524188.342 to 526937.408
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 77243/82710 matches (93.4%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 5467:
  UNIX timestamp: 1757963907.742684
  EST time: 2025-09-15 15:18:27.742683887-04:00
  Corresponding EmotiBit timestamp: 524188.368
Successfully created Date and Time columns for all 82710 rows (EST timezone)
Duration: 3317.52 seconds

Example rows around sync point (row 5467):
  Row 5465: EmotiBit=524188.287, diff=-0.081s, Time=15:18:27.661
  Row 5466: EmotiBit=524188.328, diff=-0.040s, Time=15:18:27.702
  Row 5467: EmotiBit=524188.368, diff=+0.000s, Time=15:18:27.742 <- SYNC POINT
  Row 5468: EmotiBit=524188.408, diff=+0.040s, Time=15:18:27.782
  Row 5469: EmotiBit=524188.448, diff=+0.080s, Time=15:18:27.822

Applying forward fill to missing values...
Missing values before ffill: 511745
Missing values after ffill: 16476
Filled 495269 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 82710 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 523969.082 to 527286.604
Duration: 3317.52 seconds
Participant ID: 36
Condition: Trust Priming
Video condition: 3

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 77243/82710 (93.4% complete)
DataSyncMarker_channel_1: 77243/82710 (93.4% complete)
Reliability: 77243/82710 (93.4% complete)
PPG_GRN_C: 82710/82710 (100.0% complete)
PPG_RED_C: 82710/82710 (100.0% complete)
PPG_IR_C: 82710/82710 (100.0% complete)
EDA_C: 82710/82710 (100.0% complete)
HR_C: 82683/82710 (100.0% complete)
TEMP_C: 82710/82710 (100.0% complete)
THERM_C: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_x: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_y: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 82710/82710 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 82710/82710 (100.0% complete)
PPG_GRN_IS: 82710/82710 (100.0% complete)
PPG_RED_IS: 82710/82710 (100.0% complete)
PPG_IR_IS: 82710/82710 (100.0% complete)
EDA_IS: 82709/82710 (100.0% complete)
HR_IS: 82664/82710 (99.9% complete)
TEMP_IS: 82710/82710 (100.0% complete)
THERM_IS: 82709/82710 (100.0% complete)

============================================================
Processing ID 37  (37_C.xdf)
  condition=Distrust Priming  video_condition=3
============================================================

Stream 6: Calculated effective sampling rate 134.8566 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (70497, 1)
  Sample count: 70497

Exported stream 1 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21250, 1)
  Sample count: 21250

Exported stream 2 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (70647, 1)
  Sample count: 70647

Exported stream 3 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2544, 1)
  Sample count: 2544

Exported stream 4 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (70497, 1)
  Sample count: 70497

Exported stream 5 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21254, 1)
  Sample count: 21254

Exported stream 6 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (70647, 1)
  Sample count: 70647

Exported stream 7 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (70644, 1)
  Sample count: 70644

Exported stream 8 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (42508, 1)
  Sample count: 42508

Exported stream 9 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (42506, 1)
  Sample count: 42506

Exported stream 11 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21250, 1)
  Sample count: 21250

Exported stream 12 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (70497, 1)
  Sample count: 70497

Exported stream 13 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21253, 1)
  Sample count: 21253

Exported stream 14 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (1559, 1)
  Sample count: 1559

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (390596, 16)
  Sample count: 390596
  First timestamp: 531390.5437610988

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/37_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (70644 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 531625.853 to 534128.648
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=531625.853, value=1.0
    t=532243.129, value=2.0
    t=532604.312, value=1.0
    t=533216.507, value=2.0
    t=533514.505, value=1.0
    t=534128.648, value=2.0
  Added Reliability column using video condition 3: ('HH', 'LL', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 67964/70644 matches (96.2%)
  DataSyncMarker value distribution:
    1.0: 45962 rows (65.1%)
    2.0: 22002 rows (31.1%)
Base PPG timestamps: 531518.370 to 534351.941

Processing EDA_I.csv...
  File timestamps: 531518.411 to 534351.952
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 44649/70644 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 531518.478 to 534351.420
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 22323/70644 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 531518.262 to 534351.940
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 70644/70644 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 531518.321 to 534334.574
  Added 1 column(s) from HR_C.csv
    HR_C_value: 1638/70644 matches (2.3%)

Processing TEMP1_I.csv...
  File timestamps: 531518.471 to 534351.412
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 22327/70644 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 531518.249 to 534351.940
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 70644/70644 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 531518.262 to 534351.941
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 70644/70644 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 531518.261 to 534351.940
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 70644/70644 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 531518.240 to 534351.813
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 22321/70644 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 531518.373 to 534351.879
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 44655/70644 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 531519.537 to 534334.741
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2668/70644 matches (3.8%)

Processing TEMP1_C.csv...
  File timestamps: 531518.366 to 534351.806
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 22327/70644 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 531518.249 to 534351.941
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 70644/70644 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 531390.544 to 534286.916
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 72410 samples (16 channels)
    x: 72410/72410 valid aggregated values (100.0%)
    y: 72410/72410 valid aggregated values (100.0%)
    PupilDiameter_left: 72410/72410 valid aggregated values (100.0%)
    EyeballCenterX_left: 72410/72410 valid aggregated values (100.0%)
    EyeballCenterY_left: 72410/72410 valid aggregated values (100.0%)
    EyeballCenterZ_left: 72410/72410 valid aggregated values (100.0%)
    OpticalAxisX_left: 72410/72410 valid aggregated values (100.0%)
    OpticalAxisY_left: 72410/72410 valid aggregated values (100.0%)
    OpticalAxisZ_left: 72410/72410 valid aggregated values (100.0%)
    PupilDiameter_right: 72410/72410 valid aggregated values (100.0%)
    EyeballCenterX_right: 72410/72410 valid aggregated values (100.0%)
    EyeballCenterY_right: 72410/72410 valid aggregated values (100.0%)
    EyeballCenterZ_right: 72410/72410 valid aggregated values (100.0%)
    OpticalAxisX_right: 72410/72410 valid aggregated values (100.0%)
    OpticalAxisY_right: 72410/72410 valid aggregated values (100.0%)
    OpticalAxisZ_right: 72410/72410 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_y: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 69023/70644 matches (97.7%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 69023/70644 matches (97.7%)

Processing temp_datasync_remaining.csv...
  File timestamps: 531625.853 to 534128.648
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 67964/70644 matches (96.2%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 2680:
  UNIX timestamp: 1757971345.242037
  EST time: 2025-09-15 17:22:25.242037058-04:00
  Corresponding EmotiBit timestamp: 531625.868
Successfully created Date and Time columns for all 70644 rows (EST timezone)
Duration: 2833.57 seconds

Example rows around sync point (row 2680):
  Row 2678: EmotiBit=531625.787, diff=-0.081s, Time=17:22:25.161
  Row 2679: EmotiBit=531625.827, diff=-0.041s, Time=17:22:25.201
  Row 2680: EmotiBit=531625.868, diff=+0.000s, Time=17:22:25.242 <- SYNC POINT
  Row 2681: EmotiBit=531625.908, diff=+0.040s, Time=17:22:25.282
  Row 2682: EmotiBit=531625.948, diff=+0.080s, Time=17:22:25.322

Applying forward fill to missing values...
Missing values before ffill: 416220
Missing values after ffill: 8150
Filled 408070 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 70644 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 531518.370 to 534351.941
Duration: 2833.57 seconds
Participant ID: 37
Condition: Distrust Priming
Video condition: 3

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 67964/70644 (96.2% complete)
DataSyncMarker_channel_1: 67964/70644 (96.2% complete)
Reliability: 67964/70644 (96.2% complete)
PPG_GRN_C: 70644/70644 (100.0% complete)
PPG_RED_C: 70644/70644 (100.0% complete)
PPG_IR_C: 70644/70644 (100.0% complete)
EDA_C: 70644/70644 (100.0% complete)
HR_C: 70570/70644 (99.9% complete)
TEMP_C: 70644/70644 (100.0% complete)
THERM_C: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_x: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_y: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 70644/70644 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 70644/70644 (100.0% complete)
PPG_GRN_IS: 70644/70644 (100.0% complete)
PPG_RED_IS: 70644/70644 (100.0% complete)
PPG_IR_IS: 70644/70644 (100.0% complete)
EDA_IS: 70643/70644 (100.0% complete)
HR_IS: 70615/70644 (100.0% complete)
TEMP_IS: 70641/70644 (100.0% complete)
THERM_IS: 70641/70644 (100.0% complete)

============================================================
Processing ID 38  (38_C.xdf)
  condition=Trust Priming  video_condition=4
============================================================

Stream 10: Calculated effective sampling rate 147.4324 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (45199, 1)
  Sample count: 45199

Exported stream 1 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (74990, 1)
  Sample count: 74990

Exported stream 2 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (22600, 1)
  Sample count: 22600

Exported stream 4 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1852, 1)
  Sample count: 1852

Exported stream 5 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (75118, 1)
  Sample count: 75118

Exported stream 6 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2542, 1)
  Sample count: 2542

Exported stream 7 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (22600, 1)
  Sample count: 22600

Exported stream 8 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (45200, 1)
  Sample count: 45200

Exported stream 9 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (74990, 1)
  Sample count: 74990

Exported stream 10 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (22600, 1)
  Sample count: 22600

Exported stream 11 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (22600, 1)
  Sample count: 22600

Exported stream 12 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (74990, 1)
  Sample count: 74990

Exported stream 13 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (75118, 1)
  Sample count: 75118

Exported stream 14 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (75118, 1)
  Sample count: 75118

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (441353, 16)
  Sample count: 441353
  First timestamp: 359.1446075115233

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/38_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (75118 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 591.776 to 3104.422
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=591.776, value=1.0
    t=1211.156, value=2.0
    t=1536.825, value=1.0
    t=2151.500, value=2.0
    t=2487.618, value=1.0
    t=3104.422, value=2.0
  Added Reliability column using video condition 4: ('HH', 'M', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 71874/75118 matches (95.7%)
  DataSyncMarker value distribution:
    1.0: 46145 rows (61.4%)
    2.0: 25729 rows (34.3%)
Base PPG timestamps: 461.666 to 3474.676

Processing EDA_I.csv...
  File timestamps: 461.754 to 3474.680
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 47524/75118 matches (63.3%)

Processing THERM_I.csv...
  File timestamps: 461.821 to 3474.748
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 23772/75118 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 461.671 to 3474.688
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 75118/75118 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 462.220 to 3472.095
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2649/75118 matches (3.5%)

Processing TEMP1_I.csv...
  File timestamps: 461.814 to 3474.741
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 23730/75118 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 461.665 to 3474.675
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 75118/75118 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 461.672 to 3474.688
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 75118/75118 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 461.671 to 3474.687
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 75118/75118 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 461.720 to 3474.636
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 23745/75118 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 461.718 to 3474.702
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 47511/75118 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 467.419 to 3473.663
  Added 1 column(s) from HR_I.csv
    HR_I_value: 1952/75118 matches (2.6%)

Processing TEMP1_C.csv...
  File timestamps: 461.712 to 3474.630
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 23765/75118 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 461.665 to 3474.676
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 75118/75118 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 359.145 to 3352.734
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 74840 samples (16 channels)
    x: 74840/74840 valid aggregated values (100.0%)
    y: 74840/74840 valid aggregated values (100.0%)
    PupilDiameter_left: 74840/74840 valid aggregated values (100.0%)
    EyeballCenterX_left: 74840/74840 valid aggregated values (100.0%)
    EyeballCenterY_left: 74840/74840 valid aggregated values (100.0%)
    EyeballCenterZ_left: 74840/74840 valid aggregated values (100.0%)
    OpticalAxisX_left: 74840/74840 valid aggregated values (100.0%)
    OpticalAxisY_left: 74840/74840 valid aggregated values (100.0%)
    OpticalAxisZ_left: 74840/74840 valid aggregated values (100.0%)
    PupilDiameter_right: 74840/74840 valid aggregated values (100.0%)
    EyeballCenterX_right: 74840/74840 valid aggregated values (100.0%)
    EyeballCenterY_right: 74840/74840 valid aggregated values (100.0%)
    EyeballCenterZ_right: 74840/74840 valid aggregated values (100.0%)
    OpticalAxisX_right: 74840/74840 valid aggregated values (100.0%)
    OpticalAxisY_right: 74840/74840 valid aggregated values (100.0%)
    OpticalAxisZ_right: 74840/74840 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_y: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 72077/75118 matches (96.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 72077/75118 matches (96.0%)

Processing temp_datasync_remaining.csv...
  File timestamps: 591.776 to 3104.422
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 71874/75118 matches (95.7%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3244:
  UNIX timestamp: 1758032320.014258
  EST time: 2025-09-16 10:18:40.014257908-04:00
  Corresponding EmotiBit timestamp: 591.786
Successfully created Date and Time columns for all 75118 rows (EST timezone)
Duration: 3013.01 seconds

Example rows around sync point (row 3244):
  Row 3242: EmotiBit=591.706, diff=-0.080s, Time=10:18:39.934
  Row 3243: EmotiBit=591.746, diff=-0.040s, Time=10:18:39.974
  Row 3244: EmotiBit=591.786, diff=+0.000s, Time=10:18:40.014 <- SYNC POINT
  Row 3245: EmotiBit=591.826, diff=+0.040s, Time=10:18:40.054
  Row 3246: EmotiBit=591.866, diff=+0.080s, Time=10:18:40.094

Applying forward fill to missing values...
Missing values before ffill: 464684
Missing values after ffill: 9902
Filled 454782 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 75118 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 461.666 to 3474.676
Duration: 3013.01 seconds
Participant ID: 38
Condition: Trust Priming
Video condition: 4

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 71874/75118 (95.7% complete)
DataSyncMarker_channel_1: 71874/75118 (95.7% complete)
Reliability: 71874/75118 (95.7% complete)
PPG_GRN_C: 75118/75118 (100.0% complete)
PPG_RED_C: 75118/75118 (100.0% complete)
PPG_IR_C: 75118/75118 (100.0% complete)
EDA_C: 75117/75118 (100.0% complete)
HR_C: 75104/75118 (100.0% complete)
TEMP_C: 75117/75118 (100.0% complete)
THERM_C: 75117/75118 (100.0% complete)
Neon Companion_Neon Gaze_x: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_y: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 75118/75118 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 75118/75118 (100.0% complete)
PPG_GRN_IS: 75118/75118 (100.0% complete)
PPG_RED_IS: 75118/75118 (100.0% complete)
PPG_IR_IS: 75118/75118 (100.0% complete)
EDA_IS: 75116/75118 (100.0% complete)
HR_IS: 74975/75118 (99.8% complete)
TEMP_IS: 75114/75118 (100.0% complete)
THERM_IS: 75114/75118 (100.0% complete)

============================================================
Processing ID 39  (39_C.xdf)
  condition=Distrust Priming  video_condition=4
============================================================

Stream 16: Calculated effective sampling rate 141.0215 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73456, 1)
  Sample count: 73456

Exported stream 2 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (1652, 1)
  Sample count: 1652

Exported stream 3 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (73332, 1)
  Sample count: 73332

Exported stream 4 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (73332, 1)
  Sample count: 73332

Exported stream 5 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (22096, 1)
  Sample count: 22096

Exported stream 6 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (73332, 1)
  Sample count: 73332

Exported stream 7 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (44191, 1)
  Sample count: 44191

Exported stream 8 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73456, 1)
  Sample count: 73456

Exported stream 9 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (22096, 1)
  Sample count: 22096

Exported stream 10 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1654, 1)
  Sample count: 1654

Exported stream 11 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (44194, 1)
  Sample count: 44194

Exported stream 12 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (22097, 1)
  Sample count: 22097

Exported stream 13 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (22097, 1)
  Sample count: 22097

Exported stream 14 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73456, 1)
  Sample count: 73456

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (429474, 16)
  Sample count: 429474
  First timestamp: 7640.893255740059

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/39_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (73456 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 7886.493 to 10389.564
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=7886.493, value=1.0
    t=8503.641, value=2.0
    t=8860.797, value=1.0
    t=9468.713, value=2.0
    t=9772.531, value=1.0
    t=10389.564, value=2.0
  Added Reliability column using video condition 4: ('HH', 'M', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 69388/73456 matches (94.5%)
  DataSyncMarker value distribution:
    1.0: 45929 rows (62.5%)
    2.0: 23459 rows (31.9%)
Base PPG timestamps: 7723.356 to 10669.436

Processing EDA_I.csv...
  File timestamps: 7723.362 to 10669.412
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 46070/73456 matches (62.7%)

Processing THERM_I.csv...
  File timestamps: 7723.430 to 10669.413
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 23040/73456 matches (31.4%)

Processing PPG_RED_I.csv...
  File timestamps: 7723.377 to 10669.438
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 73455/73456 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 7728.028 to 10669.141
  Added 1 column(s) from HR_C.csv
    HR_C_value: 1721/73456 matches (2.3%)

Processing TEMP1_I.csv...
  File timestamps: 7723.423 to 10669.405
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 23058/73456 matches (31.4%)

Processing PPG_IR_C.csv...
  File timestamps: 7723.355 to 10669.435
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 73456/73456 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 7723.378 to 10669.439
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 73455/73456 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 7723.377 to 10669.438
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 73455/73456 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 7723.417 to 10669.450
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 23044/73456 matches (31.4%)

Processing EDA_C.csv...
  File timestamps: 7723.416 to 10669.449
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 46158/73456 matches (62.8%)

Processing HR_I.csv...
  File timestamps: 7723.595 to 10659.325
  Added 1 column(s) from HR_I.csv
    HR_I_value: 1744/73456 matches (2.4%)

Processing TEMP1_C.csv...
  File timestamps: 7723.410 to 10669.443
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 23065/73456 matches (31.4%)

Processing PPG_RED_C.csv...
  File timestamps: 7723.355 to 10669.435
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 73456/73456 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 7640.893 to 10686.336
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 76137 samples (16 channels)
    x: 76137/76137 valid aggregated values (100.0%)
    y: 76137/76137 valid aggregated values (100.0%)
    PupilDiameter_left: 76137/76137 valid aggregated values (100.0%)
    EyeballCenterX_left: 76137/76137 valid aggregated values (100.0%)
    EyeballCenterY_left: 76137/76137 valid aggregated values (100.0%)
    EyeballCenterZ_left: 76137/76137 valid aggregated values (100.0%)
    OpticalAxisX_left: 76137/76137 valid aggregated values (100.0%)
    OpticalAxisY_left: 76137/76137 valid aggregated values (100.0%)
    OpticalAxisZ_left: 76137/76137 valid aggregated values (100.0%)
    PupilDiameter_right: 76137/76137 valid aggregated values (100.0%)
    EyeballCenterX_right: 76137/76137 valid aggregated values (100.0%)
    EyeballCenterY_right: 76137/76137 valid aggregated values (100.0%)
    EyeballCenterZ_right: 76137/76137 valid aggregated values (100.0%)
    OpticalAxisX_right: 76137/76137 valid aggregated values (100.0%)
    OpticalAxisY_right: 76137/76137 valid aggregated values (100.0%)
    OpticalAxisZ_right: 76137/76137 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_y: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 73456/73456 matches (100.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 73456/73456 matches (100.0%)

Processing temp_datasync_remaining.csv...
  File timestamps: 7886.493 to 10389.564
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 69388/73456 matches (94.5%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 4068:
  UNIX timestamp: 1758039614.788249
  EST time: 2025-09-16 12:20:14.788249016-04:00
  Corresponding EmotiBit timestamp: 7886.512
Successfully created Date and Time columns for all 73456 rows (EST timezone)
Duration: 2946.08 seconds

Example rows around sync point (row 4068):
  Row 4066: EmotiBit=7886.432, diff=-0.080s, Time=12:20:14.708
  Row 4067: EmotiBit=7886.472, diff=-0.040s, Time=12:20:14.748
  Row 4068: EmotiBit=7886.512, diff=+0.000s, Time=12:20:14.788 <- SYNC POINT
  Row 4069: EmotiBit=7886.552, diff=+0.040s, Time=12:20:14.828
  Row 4070: EmotiBit=7886.592, diff=+0.080s, Time=12:20:14.868

Applying forward fill to missing values...
Missing values before ffill: 411955
Missing values after ffill: 12337
Filled 399618 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 73456 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 7723.356 to 10669.436
Duration: 2946.08 seconds
Participant ID: 39
Condition: Distrust Priming
Video condition: 4

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 69388/73456 (94.5% complete)
DataSyncMarker_channel_1: 69388/73456 (94.5% complete)
Reliability: 69388/73456 (94.5% complete)
PPG_GRN_C: 73456/73456 (100.0% complete)
PPG_RED_C: 73456/73456 (100.0% complete)
PPG_IR_C: 73456/73456 (100.0% complete)
EDA_C: 73455/73456 (100.0% complete)
HR_C: 73340/73456 (99.8% complete)
TEMP_C: 73455/73456 (100.0% complete)
THERM_C: 73454/73456 (100.0% complete)
Neon Companion_Neon Gaze_x: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_y: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 73456/73456 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 73456/73456 (100.0% complete)
PPG_GRN_IS: 73455/73456 (100.0% complete)
PPG_RED_IS: 73455/73456 (100.0% complete)
PPG_IR_IS: 73455/73456 (100.0% complete)
EDA_IS: 73456/73456 (100.0% complete)
HR_IS: 73450/73456 (100.0% complete)
TEMP_IS: 73454/73456 (100.0% complete)
THERM_IS: 73454/73456 (100.0% complete)

============================================================
Processing ID 40  (40_C.xdf)
  condition=Trust Priming  video_condition=5
============================================================

Stream 11: Calculated effective sampling rate 149.0171 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (19864, 1)
  Sample count: 19864

Exported stream 1 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (66034, 1)
  Sample count: 66034

Exported stream 2 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (66034, 1)
  Sample count: 66034

Exported stream 3 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (65895, 1)
  Sample count: 65895

Exported stream 4 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2898, 1)
  Sample count: 2898

Exported stream 5 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (19865, 1)
  Sample count: 19865

Exported stream 6 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (66034, 1)
  Sample count: 66034

Exported stream 8 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2425, 1)
  Sample count: 2425

Exported stream 9 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (19864, 1)
  Sample count: 19864

Exported stream 10 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (65895, 1)
  Sample count: 65895

Exported stream 11 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (39729, 1)
  Sample count: 39729

Exported stream 12 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported stream 13 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (19866, 1)
  Sample count: 19866

Exported stream 14 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (39730, 1)
  Sample count: 39730

Exported stream 15 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (65895, 1)
  Sample count: 65895

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (394520, 16)
  Sample count: 394520
  First timestamp: 101301.11178228319

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/40_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (66034 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 101487.114 to 103849.043
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=101487.114, value=1.0
    t=102098.165, value=2.0
    t=102383.514, value=1.0
    t=103000.723, value=2.0
    t=103229.779, value=1.0
    t=103849.043, value=2.0
  Added Reliability column using video condition 5: ('M', 'LL', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 63711/66034 matches (96.5%)
  DataSyncMarker value distribution:
    1.0: 46065 rows (69.8%)
    2.0: 17646 rows (26.7%)
Base PPG timestamps: 101393.953 to 104042.317

Processing EDA_I.csv...
  File timestamps: 101393.825 to 104042.292
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 41684/66034 matches (63.1%)

Processing THERM_I.csv...
  File timestamps: 101393.958 to 104042.294
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 20846/66034 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 101393.711 to 104042.235
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 66032/66034 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 101394.749 to 104040.143
  Added 1 column(s) from HR_C.csv
    HR_C_value: 3042/66034 matches (4.6%)

Processing TEMP1_I.csv...
  File timestamps: 101393.950 to 104042.287
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 20842/66034 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 101393.952 to 104042.316
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 66034/66034 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 101393.712 to 104042.236
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 66032/66034 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 101393.711 to 104042.235
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 66032/66034 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 101393.964 to 104042.252
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 20843/66034 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 101393.963 to 104042.318
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 41694/66034 matches (63.1%)

Processing HR_I.csv...
  File timestamps: 101394.250 to 104040.926
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2525/66034 matches (3.8%)

Processing TEMP1_C.csv...
  File timestamps: 101393.827 to 104042.244
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 20855/66034 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 101393.953 to 104042.317
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 66034/66034 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 101301.112 to 103948.586
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 66187 samples (16 channels)
    x: 66187/66187 valid aggregated values (100.0%)
    y: 66187/66187 valid aggregated values (100.0%)
    PupilDiameter_left: 66187/66187 valid aggregated values (100.0%)
    EyeballCenterX_left: 66187/66187 valid aggregated values (100.0%)
    EyeballCenterY_left: 66187/66187 valid aggregated values (100.0%)
    EyeballCenterZ_left: 66187/66187 valid aggregated values (100.0%)
    OpticalAxisX_left: 66187/66187 valid aggregated values (100.0%)
    OpticalAxisY_left: 66187/66187 valid aggregated values (100.0%)
    OpticalAxisZ_left: 66187/66187 valid aggregated values (100.0%)
    PupilDiameter_right: 66187/66187 valid aggregated values (100.0%)
    EyeballCenterX_right: 66187/66187 valid aggregated values (100.0%)
    EyeballCenterY_right: 66187/66187 valid aggregated values (100.0%)
    EyeballCenterZ_right: 66187/66187 valid aggregated values (100.0%)
    OpticalAxisX_right: 66187/66187 valid aggregated values (100.0%)
    OpticalAxisY_right: 66187/66187 valid aggregated values (100.0%)
    OpticalAxisZ_right: 66187/66187 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_y: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 63696/66034 matches (96.5%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 63696/66034 matches (96.5%)

Processing temp_datasync_remaining.csv...
  File timestamps: 101487.114 to 103849.043
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 63711/66034 matches (96.5%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 2323:
  UNIX timestamp: 1758133215.19599
  EST time: 2025-09-17 14:20:15.195990086-04:00
  Corresponding EmotiBit timestamp: 101487.121
Successfully created Date and Time columns for all 66034 rows (EST timezone)
Duration: 2648.36 seconds

Example rows around sync point (row 2323):
  Row 2321: EmotiBit=101487.041, diff=-0.080s, Time=14:20:15.115
  Row 2322: EmotiBit=101487.081, diff=-0.040s, Time=14:20:15.155
  Row 2323: EmotiBit=101487.121, diff=+0.000s, Time=14:20:15.195 <- SYNC POINT
  Row 2324: EmotiBit=101487.161, diff=+0.040s, Time=14:20:15.235
  Row 2325: EmotiBit=101487.201, diff=+0.080s, Time=14:20:15.275

Applying forward fill to missing values...
Missing values before ffill: 400324
Missing values after ffill: 6996
Filled 393328 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 66034 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 101393.953 to 104042.317
Duration: 2648.36 seconds
Participant ID: 40
Condition: Trust Priming
Video condition: 5

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 63711/66034 (96.5% complete)
DataSyncMarker_channel_1: 63711/66034 (96.5% complete)
Reliability: 63711/66034 (96.5% complete)
PPG_GRN_C: 66034/66034 (100.0% complete)
PPG_RED_C: 66034/66034 (100.0% complete)
PPG_IR_C: 66034/66034 (100.0% complete)
EDA_C: 66034/66034 (100.0% complete)
HR_C: 66014/66034 (100.0% complete)
TEMP_C: 66034/66034 (100.0% complete)
THERM_C: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_x: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_y: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 66034/66034 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 66034/66034 (100.0% complete)
PPG_GRN_IS: 66034/66034 (100.0% complete)
PPG_RED_IS: 66034/66034 (100.0% complete)
PPG_IR_IS: 66034/66034 (100.0% complete)
EDA_IS: 66034/66034 (100.0% complete)
HR_IS: 66027/66034 (100.0% complete)
TEMP_IS: 66034/66034 (100.0% complete)
THERM_IS: 66034/66034 (100.0% complete)

============================================================
Processing ID 41  (41_C.xdf)
  condition=Distrust Priming  video_condition=5
============================================================

Stream 4: Calculated effective sampling rate 142.4631 Hz is different from specified rate 200.0000 Hz.
Stream 4: Segments and clock-segments differ

Exported stream 0 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (25707, 1)
  Sample count: 25707

Exported stream 1 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (51412, 1)
  Sample count: 51412

Exported stream 2 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (51414, 1)
  Sample count: 51414

Exported stream 3 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (25705, 1)
  Sample count: 25705

Exported stream 5 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (85450, 1)
  Sample count: 85450

Exported stream 6 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (25705, 1)
  Sample count: 25705

Exported stream 7 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (3761, 1)
  Sample count: 3761

Exported stream 8 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (25707, 1)
  Sample count: 25707

Exported stream 9 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (4255, 1)
  Sample count: 4255

Exported stream 10 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (85450, 1)
  Sample count: 85450

Exported stream 11 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (85273, 1)
  Sample count: 85273

Exported stream 12 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (85273, 1)
  Sample count: 85273

Exported stream 13 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (85273, 1)
  Sample count: 85273

Exported stream 14 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (85450, 1)
  Sample count: 85450

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (484883, 16)
  Sample count: 484883
  First timestamp: 173314.89917650467

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/41_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (85450 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 173605.586 to 176536.569
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=173605.586, value=1.0
    t=174215.402, value=2.0
    t=174752.842, value=1.0
    t=175366.290, value=2.0
    t=175918.595, value=1.0
    t=176536.569, value=2.0
  Added Reliability column using video condition 5: ('M', 'LL', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 80253/85450 matches (93.9%)
  DataSyncMarker value distribution:
    1.0: 45907 rows (53.7%)
    2.0: 34346 rows (40.2%)
Base PPG timestamps: 173397.154 to 176824.333

Processing EDA_I.csv...
  File timestamps: 173397.153 to 176824.373
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 53251/85450 matches (62.3%)

Processing THERM_I.csv...
  File timestamps: 173397.221 to 176824.374
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 26628/85450 matches (31.2%)

Processing PPG_RED_I.csv...
  File timestamps: 173397.098 to 176824.422
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 85450/85450 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 173397.814 to 176821.088
  Added 1 column(s) from HR_C.csv
    HR_C_value: 4413/85450 matches (5.2%)

Processing TEMP1_I.csv...
  File timestamps: 173397.213 to 176824.366
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 26631/85450 matches (31.2%)

Processing PPG_IR_C.csv...
  File timestamps: 173397.153 to 176824.332
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 85450/85450 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 173397.098 to 176824.423
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 85450/85450 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 173397.097 to 176824.422
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 85450/85450 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 173397.212 to 176824.262
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 26629/85450 matches (31.2%)

Processing EDA_C.csv...
  File timestamps: 173397.167 to 176824.328
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 53245/85450 matches (62.3%)

Processing HR_I.csv...
  File timestamps: 173398.698 to 176816.105
  Added 1 column(s) from HR_I.csv
    HR_I_value: 3883/85450 matches (4.5%)

Processing TEMP1_C.csv...
  File timestamps: 173397.205 to 176824.254
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 26627/85450 matches (31.2%)

Processing PPG_RED_C.csv...
  File timestamps: 173397.153 to 176824.332
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 85450/85450 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 173314.899 to 176798.338
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 85089 samples (16 channels)
    x: 85089/85089 valid aggregated values (100.0%)
    y: 85089/85089 valid aggregated values (100.0%)
    PupilDiameter_left: 85089/85089 valid aggregated values (100.0%)
    EyeballCenterX_left: 85089/85089 valid aggregated values (100.0%)
    EyeballCenterY_left: 85089/85089 valid aggregated values (100.0%)
    EyeballCenterZ_left: 85089/85089 valid aggregated values (100.0%)
    OpticalAxisX_left: 85089/85089 valid aggregated values (100.0%)
    OpticalAxisY_left: 85089/85089 valid aggregated values (100.0%)
    OpticalAxisZ_left: 85089/85089 valid aggregated values (100.0%)
    PupilDiameter_right: 85089/85089 valid aggregated values (100.0%)
    EyeballCenterX_right: 85089/85089 valid aggregated values (100.0%)
    EyeballCenterY_right: 85089/85089 valid aggregated values (100.0%)
    EyeballCenterZ_right: 85089/85089 valid aggregated values (100.0%)
    OpticalAxisX_right: 85089/85089 valid aggregated values (100.0%)
    OpticalAxisY_right: 85089/85089 valid aggregated values (100.0%)
    OpticalAxisZ_right: 85089/85089 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_y: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 82810/85450 matches (96.9%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 82810/85450 matches (96.9%)

Processing temp_datasync_remaining.csv...
  File timestamps: 173605.586 to 176536.569
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 80253/85450 matches (93.9%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 5197:
  UNIX timestamp: 1758205333.6351612
  EST time: 2025-09-18 10:22:13.635161161-04:00
  Corresponding EmotiBit timestamp: 173605.594
Successfully created Date and Time columns for all 85450 rows (EST timezone)
Duration: 3427.18 seconds

Example rows around sync point (row 5197):
  Row 5195: EmotiBit=173605.514, diff=-0.080s, Time=10:22:13.555
  Row 5196: EmotiBit=173605.554, diff=-0.040s, Time=10:22:13.595
  Row 5197: EmotiBit=173605.594, diff=+0.000s, Time=10:22:13.635 <- SYNC POINT
  Row 5198: EmotiBit=173605.635, diff=+0.041s, Time=10:22:13.676
  Row 5199: EmotiBit=173605.675, diff=+0.081s, Time=10:22:13.716

Applying forward fill to missing values...
Missing values before ffill: 520124
Missing values after ffill: 15650
Filled 504474 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 85450 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 173397.154 to 176824.333
Duration: 3427.18 seconds
Participant ID: 41
Condition: Distrust Priming
Video condition: 5

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 80253/85450 (93.9% complete)
DataSyncMarker_channel_1: 80253/85450 (93.9% complete)
Reliability: 80253/85450 (93.9% complete)
PPG_GRN_C: 85450/85450 (100.0% complete)
PPG_RED_C: 85450/85450 (100.0% complete)
PPG_IR_C: 85450/85450 (100.0% complete)
EDA_C: 85450/85450 (100.0% complete)
HR_C: 85434/85450 (100.0% complete)
TEMP_C: 85449/85450 (100.0% complete)
THERM_C: 85449/85450 (100.0% complete)
Neon Companion_Neon Gaze_x: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_y: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 85450/85450 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 85450/85450 (100.0% complete)
PPG_GRN_IS: 85450/85450 (100.0% complete)
PPG_RED_IS: 85450/85450 (100.0% complete)
PPG_IR_IS: 85450/85450 (100.0% complete)
EDA_IS: 85450/85450 (100.0% complete)
HR_IS: 85412/85450 (100.0% complete)
TEMP_IS: 85449/85450 (100.0% complete)
THERM_IS: 85448/85450 (100.0% complete)

============================================================
Processing ID 42  (42_C.xdf)
  condition=Trust Priming  video_condition=6
============================================================

Stream 15: Calculated effective sampling rate 143.3925 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (60736, 1)
  Sample count: 60736

Exported stream 1 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (25268, 1)
  Sample count: 25268

Exported stream 2 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (83992, 1)
  Sample count: 83992

Exported stream 3 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (36620, 1)
  Sample count: 36620

Exported stream 4 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (1222, 1)
  Sample count: 1222

Exported stream 5 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (60736, 1)
  Sample count: 60736

Exported stream 6 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2094, 1)
  Sample count: 2094

Exported stream 8 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (18310, 1)
  Sample count: 18310

Exported stream 9 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (25267, 1)
  Sample count: 25267

Exported stream 10 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (60734, 1)
  Sample count: 60734

Exported stream 11 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (18310, 1)
  Sample count: 18310

Exported stream 12 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (50536, 1)
  Sample count: 50536

Exported stream 13 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (83992, 1)
  Sample count: 83992

Exported stream 14 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (83992, 1)
  Sample count: 83992

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (495557, 16)
  Sample count: 495557
  First timestamp: 180443.5992157253

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/42_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (83992 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 180695.244 to 183350.966
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=180695.244, value=1.0
    t=181306.472, value=2.0
    t=181772.813, value=1.0
    t=182396.514, value=2.0
    t=182733.051, value=1.0
    t=183350.966, value=2.0
  Added Reliability column using video condition 6: ('M', 'HH', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 80329/83992 matches (95.6%)
  DataSyncMarker value distribution:
    1.0: 46193 rows (55.0%)
    2.0: 34136 rows (40.6%)
Base PPG timestamps: 180548.322 to 183917.217

Processing EDA_I.csv...
  File timestamps: 180548.380 to 182989.461
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 37965/83992 matches (45.2%)

Processing THERM_I.csv...
  File timestamps: 180548.408 to 182989.384
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 18960/83992 matches (22.6%)

Processing PPG_RED_I.csv...
  File timestamps: 180548.313 to 182989.442
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 60861/83992 matches (72.5%)

Processing HR_C.csv...
  File timestamps: 180549.876 to 183917.253
  Added 1 column(s) from HR_C.csv
    HR_C_value: 1264/83992 matches (1.5%)

Processing TEMP1_I.csv...
  File timestamps: 180548.400 to 182989.377
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 18953/83992 matches (22.6%)

Processing PPG_IR_C.csv...
  File timestamps: 180548.321 to 183917.216
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 83992/83992 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 180548.313 to 182989.442
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 60861/83992 matches (72.5%)

Processing PPG_IR_I.csv...
  File timestamps: 180548.392 to 182989.441
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 60859/83992 matches (72.5%)

Processing THERM_C.csv...
  File timestamps: 180548.263 to 183917.113
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 26169/83992 matches (31.2%)

Processing EDA_C.csv...
  File timestamps: 180548.262 to 183917.179
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 52340/83992 matches (62.3%)

Processing HR_I.csv...
  File timestamps: 180551.226 to 182988.679
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2163/83992 matches (2.6%)

Processing TEMP1_C.csv...
  File timestamps: 180548.389 to 183917.105
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 26132/83992 matches (31.1%)

Processing PPG_RED_C.csv...
  File timestamps: 180548.321 to 183917.217
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 83992/83992 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 180443.599 to 183899.541
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 86399 samples (16 channels)
    x: 86399/86399 valid aggregated values (100.0%)
    y: 86399/86399 valid aggregated values (100.0%)
    PupilDiameter_left: 86399/86399 valid aggregated values (100.0%)
    EyeballCenterX_left: 86399/86399 valid aggregated values (100.0%)
    EyeballCenterY_left: 86399/86399 valid aggregated values (100.0%)
    EyeballCenterZ_left: 86399/86399 valid aggregated values (100.0%)
    OpticalAxisX_left: 86399/86399 valid aggregated values (100.0%)
    OpticalAxisY_left: 86399/86399 valid aggregated values (100.0%)
    OpticalAxisZ_left: 86399/86399 valid aggregated values (100.0%)
    PupilDiameter_right: 86399/86399 valid aggregated values (100.0%)
    EyeballCenterX_right: 86399/86399 valid aggregated values (100.0%)
    EyeballCenterY_right: 86399/86399 valid aggregated values (100.0%)
    EyeballCenterZ_right: 86399/86399 valid aggregated values (100.0%)
    OpticalAxisX_right: 86399/86399 valid aggregated values (100.0%)
    OpticalAxisY_right: 86399/86399 valid aggregated values (100.0%)
    OpticalAxisZ_right: 86399/86399 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_y: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 83551/83992 matches (99.5%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 83551/83992 matches (99.5%)

Processing temp_datasync_remaining.csv...
  File timestamps: 180695.244 to 183350.966
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 80329/83992 matches (95.6%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3663:
  UNIX timestamp: 1758212423.212832
  EST time: 2025-09-18 12:20:23.212831974-04:00
  Corresponding EmotiBit timestamp: 180695.245
Successfully created Date and Time columns for all 83992 rows (EST timezone)
Duration: 3368.89 seconds

Example rows around sync point (row 3663):
  Row 3661: EmotiBit=180695.165, diff=-0.080s, Time=12:20:23.132
  Row 3662: EmotiBit=180695.205, diff=-0.040s, Time=12:20:23.172
  Row 3663: EmotiBit=180695.245, diff=+0.000s, Time=12:20:23.212 <- SYNC POINT
  Row 3664: EmotiBit=180695.285, diff=+0.040s, Time=12:20:23.252
  Row 3665: EmotiBit=180695.326, diff=+0.081s, Time=12:20:23.293

Applying forward fill to missing values...
Missing values before ffill: 575430
Missing values after ffill: 11111
Filled 564319 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 83992 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 180548.322 to 183917.217
Duration: 3368.90 seconds
Participant ID: 42
Condition: Trust Priming
Video condition: 6

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 80329/83992 (95.6% complete)
DataSyncMarker_channel_1: 80329/83992 (95.6% complete)
Reliability: 80329/83992 (95.6% complete)
PPG_GRN_C: 83992/83992 (100.0% complete)
PPG_RED_C: 83992/83992 (100.0% complete)
PPG_IR_C: 83992/83992 (100.0% complete)
EDA_C: 83992/83992 (100.0% complete)
HR_C: 83953/83992 (100.0% complete)
TEMP_C: 83990/83992 (100.0% complete)
THERM_C: 83990/83992 (100.0% complete)
Neon Companion_Neon Gaze_x: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_y: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 83992/83992 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 83992/83992 (100.0% complete)
PPG_GRN_IS: 83992/83992 (100.0% complete)
PPG_RED_IS: 83992/83992 (100.0% complete)
PPG_IR_IS: 83990/83992 (100.0% complete)
EDA_IS: 83991/83992 (100.0% complete)
HR_IS: 83920/83992 (99.9% complete)
TEMP_IS: 83990/83992 (100.0% complete)
THERM_IS: 83990/83992 (100.0% complete)

============================================================
Processing ID 43  (43_C.xdf)
  condition=Distrust Priming  video_condition=6
============================================================

Stream 15: Calculated effective sampling rate 151.5611 Hz is different from specified rate 200.0000 Hz.

Exported stream 1 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20028, 1)
  Sample count: 20028

Exported stream 2 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2217, 1)
  Sample count: 2217

Exported stream 3 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (40054, 1)
  Sample count: 40054

Exported stream 4 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (40055, 1)
  Sample count: 40055

Exported stream 5 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (66565, 1)
  Sample count: 66565

Exported stream 6 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2713, 1)
  Sample count: 2713

Exported stream 7 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20027, 1)
  Sample count: 20027

Exported stream 8 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (66565, 1)
  Sample count: 66565

Exported stream 9 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (66447, 1)
  Sample count: 66447

Exported stream 10 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (66447, 1)
  Sample count: 66447

Exported stream 11 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20027, 1)
  Sample count: 20027

Exported stream 12 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (66447, 1)
  Sample count: 66447

Exported stream 13 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20028, 1)
  Sample count: 20028

Exported stream 14 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (66565, 1)
  Sample count: 66565

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (409155, 16)
  Sample count: 409155
  First timestamp: 259791.76158065043

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/43_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (66565 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 260002.381 to 262355.191
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=260002.381, value=1.0
    t=260612.893, value=2.0
    t=260872.268, value=1.0
    t=261494.503, value=2.0
    t=261740.160, value=1.0
    t=262355.191, value=2.0
  Added Reliability column using video condition 6: ('M', 'HH', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 63416/66565 matches (95.3%)
  DataSyncMarker value distribution:
    1.0: 46064 rows (69.2%)
    2.0: 17352 rows (26.1%)
Base PPG timestamps: 259876.077 to 262546.187

Processing EDA_I.csv...
  File timestamps: 259875.984 to 262546.007
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 41440/66565 matches (62.3%)

Processing THERM_I.csv...
  File timestamps: 259876.052 to 262545.942
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 20721/66565 matches (31.1%)

Processing PPG_RED_I.csv...
  File timestamps: 259875.864 to 262545.979
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 66560/66565 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 259877.030 to 262538.837
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2805/66565 matches (4.2%)

Processing TEMP1_I.csv...
  File timestamps: 259876.044 to 262545.934
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 20718/66565 matches (31.1%)

Processing PPG_IR_C.csv...
  File timestamps: 259876.076 to 262546.186
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 66565/66565 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 259875.865 to 262545.979
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 66560/66565 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 259875.864 to 262545.978
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 66560/66565 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 259876.106 to 262546.148
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 20713/66565 matches (31.1%)

Processing EDA_C.csv...
  File timestamps: 259876.111 to 262546.168
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 41431/66565 matches (62.2%)

Processing HR_I.csv...
  File timestamps: 259877.428 to 262541.404
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2293/66565 matches (3.4%)

Processing TEMP1_C.csv...
  File timestamps: 259876.099 to 262546.140
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 20718/66565 matches (31.1%)

Processing PPG_RED_C.csv...
  File timestamps: 259876.076 to 262546.186
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 66565/66565 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 259791.762 to 262491.359
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 67490 samples (16 channels)
    x: 67490/67490 valid aggregated values (100.0%)
    y: 67490/67490 valid aggregated values (100.0%)
    PupilDiameter_left: 67490/67490 valid aggregated values (100.0%)
    EyeballCenterX_left: 67490/67490 valid aggregated values (100.0%)
    EyeballCenterY_left: 67490/67490 valid aggregated values (100.0%)
    EyeballCenterZ_left: 67490/67490 valid aggregated values (100.0%)
    OpticalAxisX_left: 67490/67490 valid aggregated values (100.0%)
    OpticalAxisY_left: 67490/67490 valid aggregated values (100.0%)
    OpticalAxisZ_left: 67490/67490 valid aggregated values (100.0%)
    PupilDiameter_right: 67490/67490 valid aggregated values (100.0%)
    EyeballCenterX_right: 67490/67490 valid aggregated values (100.0%)
    EyeballCenterY_right: 67490/67490 valid aggregated values (100.0%)
    EyeballCenterZ_right: 67490/67490 valid aggregated values (100.0%)
    OpticalAxisX_right: 67490/67490 valid aggregated values (100.0%)
    OpticalAxisY_right: 67490/67490 valid aggregated values (100.0%)
    OpticalAxisZ_right: 67490/67490 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_y: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 65197/66565 matches (97.9%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 65197/66565 matches (97.9%)

Processing temp_datasync_remaining.csv...
  File timestamps: 260002.381 to 262355.191
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 63416/66565 matches (95.3%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3149:
  UNIX timestamp: 1758291730.201058
  EST time: 2025-09-19 10:22:10.201057911-04:00
  Corresponding EmotiBit timestamp: 260002.394
Successfully created Date and Time columns for all 66565 rows (EST timezone)
Duration: 2670.11 seconds

Example rows around sync point (row 3149):
  Row 3147: EmotiBit=260002.314, diff=-0.080s, Time=10:22:10.121
  Row 3148: EmotiBit=260002.354, diff=-0.040s, Time=10:22:10.161
  Row 3149: EmotiBit=260002.394, diff=+0.000s, Time=10:22:10.201 <- SYNC POINT
  Row 3150: EmotiBit=260002.434, diff=+0.040s, Time=10:22:10.241
  Row 3151: EmotiBit=260002.474, diff=+0.080s, Time=10:22:10.281

Applying forward fill to missing values...
Missing values before ffill: 393031
Missing values after ffill: 9515
Filled 383516 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 66565 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 259876.077 to 262546.187
Duration: 2670.11 seconds
Participant ID: 43
Condition: Distrust Priming
Video condition: 6

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 63416/66565 (95.3% complete)
DataSyncMarker_channel_1: 63416/66565 (95.3% complete)
Reliability: 63416/66565 (95.3% complete)
PPG_GRN_C: 66565/66565 (100.0% complete)
PPG_RED_C: 66565/66565 (100.0% complete)
PPG_IR_C: 66565/66565 (100.0% complete)
EDA_C: 66564/66565 (100.0% complete)
HR_C: 66541/66565 (100.0% complete)
TEMP_C: 66564/66565 (100.0% complete)
THERM_C: 66564/66565 (100.0% complete)
Neon Companion_Neon Gaze_x: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_y: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 66565/66565 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 66565/66565 (100.0% complete)
PPG_GRN_IS: 66565/66565 (100.0% complete)
PPG_RED_IS: 66565/66565 (100.0% complete)
PPG_IR_IS: 66565/66565 (100.0% complete)
EDA_IS: 66564/66565 (100.0% complete)
HR_IS: 66531/66565 (99.9% complete)
TEMP_IS: 66562/66565 (100.0% complete)
THERM_IS: 66562/66565 (100.0% complete)

============================================================
Processing ID 44  (44_C.xdf)
  condition=Trust Priming  video_condition=1
============================================================

Stream 2: Calculated effective sampling rate 146.8681 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72130, 1)
  Sample count: 72130

Exported stream 1 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72131, 1)
  Sample count: 72131

Exported stream 2 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71997, 1)
  Sample count: 71997

Exported stream 3 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (43401, 1)
  Sample count: 43401

Exported stream 4 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (3556, 1)
  Sample count: 3556

Exported stream 5 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72131, 1)
  Sample count: 72131

Exported stream 6 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21701, 1)
  Sample count: 21701

Exported stream 7 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2621, 1)
  Sample count: 2621

Exported stream 8 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21699, 1)
  Sample count: 21699

Exported stream 10 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71997, 1)
  Sample count: 71997

Exported stream 11 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (43399, 1)
  Sample count: 43399

Exported stream 12 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21699, 1)
  Sample count: 21699

Exported stream 13 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21701, 1)
  Sample count: 21701

Exported stream 14 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71997, 1)
  Sample count: 71997

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (430986, 16)
  Sample count: 430986
  First timestamp: 536565.380147896

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/44_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (72131 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 536780.769 to 539288.621
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=536780.769, value=1.0
    t=537389.548, value=2.0
    t=537786.633, value=1.0
    t=538414.304, value=2.0
    t=538668.345, value=1.0
    t=539288.621, value=2.0
  Added Reliability column using video condition 1: ('LL', 'HH', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 69158/72131 matches (95.9%)
  DataSyncMarker value distribution:
    1.0: 46291 rows (64.2%)
    2.0: 22867 rows (31.7%)
Base PPG timestamps: 536661.538 to 539554.703

Processing EDA_I.csv...
  File timestamps: 536661.524 to 539554.591
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 45580/72131 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 536661.525 to 539554.592
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 22803/72131 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 536661.371 to 539554.543
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 72127/72131 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 536663.201 to 539551.300
  Added 1 column(s) from HR_C.csv
    HR_C_value: 3756/72131 matches (5.2%)

Processing TEMP1_I.csv...
  File timestamps: 536661.518 to 539554.584
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 22773/72131 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 536661.536 to 539554.702
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 72131/72131 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 536661.371 to 539554.544
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 72127/72131 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 536661.370 to 539554.543
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 72127/72131 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 536661.632 to 539554.553
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 22790/72131 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 536661.565 to 539554.618
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 45571/72131 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 536664.550 to 539544.866
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2754/72131 matches (3.8%)

Processing TEMP1_C.csv...
  File timestamps: 536661.625 to 539554.545
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 22795/72131 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 536661.537 to 539554.662
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 72130/72131 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 536565.380 to 539499.884
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 73363 samples (16 channels)
    x: 73363/73363 valid aggregated values (100.0%)
    y: 73363/73363 valid aggregated values (100.0%)
    PupilDiameter_left: 73363/73363 valid aggregated values (100.0%)
    EyeballCenterX_left: 73363/73363 valid aggregated values (100.0%)
    EyeballCenterY_left: 73363/73363 valid aggregated values (100.0%)
    EyeballCenterZ_left: 73363/73363 valid aggregated values (100.0%)
    OpticalAxisX_left: 73363/73363 valid aggregated values (100.0%)
    OpticalAxisY_left: 73363/73363 valid aggregated values (100.0%)
    OpticalAxisZ_left: 73363/73363 valid aggregated values (100.0%)
    PupilDiameter_right: 73363/73363 valid aggregated values (100.0%)
    EyeballCenterX_right: 73363/73363 valid aggregated values (100.0%)
    EyeballCenterY_right: 73363/73363 valid aggregated values (100.0%)
    EyeballCenterZ_right: 73363/73363 valid aggregated values (100.0%)
    OpticalAxisX_right: 73363/73363 valid aggregated values (100.0%)
    OpticalAxisY_right: 73363/73363 valid aggregated values (100.0%)
    OpticalAxisZ_right: 73363/73363 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_y: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 70764/72131 matches (98.1%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 70764/72131 matches (98.1%)

Processing temp_datasync_remaining.csv...
  File timestamps: 536780.769 to 539288.621
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 69158/72131 matches (95.9%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 2973:
  UNIX timestamp: 1758568507.48735
  EST time: 2025-09-22 15:15:07.487349987-04:00
  Corresponding EmotiBit timestamp: 536780.786
Successfully created Date and Time columns for all 72131 rows (EST timezone)
Duration: 2893.16 seconds

Example rows around sync point (row 2973):
  Row 2971: EmotiBit=536780.706, diff=-0.080s, Time=15:15:07.407
  Row 2972: EmotiBit=536780.746, diff=-0.040s, Time=15:15:07.447
  Row 2973: EmotiBit=536780.786, diff=+0.000s, Time=15:15:07.487 <- SYNC POINT
  Row 2974: EmotiBit=536780.826, diff=+0.040s, Time=15:15:07.527
  Row 2975: EmotiBit=536780.866, diff=+0.080s, Time=15:15:07.567

Applying forward fill to missing values...
Missing values before ffill: 419030
Missing values after ffill: 9040
Filled 409990 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 72131 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 536661.538 to 539554.703
Duration: 2893.17 seconds
Participant ID: 44
Condition: Trust Priming
Video condition: 1

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 69158/72131 (95.9% complete)
DataSyncMarker_channel_1: 69158/72131 (95.9% complete)
Reliability: 69158/72131 (95.9% complete)
PPG_GRN_C: 72131/72131 (100.0% complete)
PPG_RED_C: 72131/72131 (100.0% complete)
PPG_IR_C: 72131/72131 (100.0% complete)
EDA_C: 72130/72131 (100.0% complete)
HR_C: 72090/72131 (99.9% complete)
TEMP_C: 72129/72131 (100.0% complete)
THERM_C: 72129/72131 (100.0% complete)
Neon Companion_Neon Gaze_x: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_y: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 72131/72131 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 72131/72131 (100.0% complete)
PPG_GRN_IS: 72131/72131 (100.0% complete)
PPG_RED_IS: 72131/72131 (100.0% complete)
PPG_IR_IS: 72131/72131 (100.0% complete)
EDA_IS: 72131/72131 (100.0% complete)
HR_IS: 72056/72131 (99.9% complete)
TEMP_IS: 72131/72131 (100.0% complete)
THERM_IS: 72131/72131 (100.0% complete)

============================================================
Processing ID 45  (45_C.xdf)
  condition=Trust Priming  video_condition=2
============================================================

Stream 5: Calculated effective sampling rate 133.3535 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20674, 1)
  Sample count: 20674

Exported stream 1 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20674, 1)
  Sample count: 20674

Exported stream 2 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (68713, 1)
  Sample count: 68713

Exported stream 4 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (68713, 1)
  Sample count: 68713

Exported stream 5 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (3131, 1)
  Sample count: 3131

Exported stream 6 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (68574, 1)
  Sample count: 68574

Exported stream 7 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20675, 1)
  Sample count: 20675

Exported stream 8 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (68574, 1)
  Sample count: 68574

Exported stream 9 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (68574, 1)
  Sample count: 68574

Exported stream 10 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (41350, 1)
  Sample count: 41350

Exported stream 11 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (68713, 1)
  Sample count: 68713

Exported stream 12 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (41348, 1)
  Sample count: 41348

Exported stream 13 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20674, 1)
  Sample count: 20674

Exported stream 14 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (3203, 1)
  Sample count: 3203

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (375064, 16)
  Sample count: 375064
  First timestamp: 544470.1977323259

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/45_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (68713 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 544684.542 to 547057.503
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=544684.542, value=1.0
    t=545297.263, value=2.0
    t=545588.772, value=1.0
    t=546203.353, value=2.0
    t=546433.222, value=1.0
    t=547057.503, value=2.0
  Added Reliability column using video condition 2: ('LL', 'M', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 65292/68713 matches (95.0%)
  DataSyncMarker value distribution:
    1.0: 46152 rows (67.2%)
    2.0: 19140 rows (27.9%)
Base PPG timestamps: 544547.337 to 547303.941

Processing EDA_I.csv...
  File timestamps: 544547.328 to 547303.973
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 43441/68713 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 544547.376 to 547303.920
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 21722/68713 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 544547.267 to 547303.949
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 68713/68713 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 544551.537 to 547300.241
  Added 1 column(s) from HR_C.csv
    HR_C_value: 3292/68713 matches (4.8%)

Processing TEMP1_I.csv...
  File timestamps: 544547.407 to 547303.887
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 21725/68713 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 544547.335 to 547303.940
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 68713/68713 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 544547.267 to 547303.950
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 68713/68713 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 544547.266 to 547303.949
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 68713/68713 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 544547.401 to 547303.934
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 21727/68713 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 544547.419 to 547303.920
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 43443/68713 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 544548.019 to 547298.691
  Added 1 column(s) from HR_I.csv
    HR_I_value: 3380/68713 matches (4.9%)

Processing TEMP1_C.csv...
  File timestamps: 544547.393 to 547303.927
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 21729/68713 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 544547.336 to 547303.941
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 68713/68713 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 544470.198 to 547282.745
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 70314 samples (16 channels)
    x: 70314/70314 valid aggregated values (100.0%)
    y: 70314/70314 valid aggregated values (100.0%)
    PupilDiameter_left: 70314/70314 valid aggregated values (100.0%)
    EyeballCenterX_left: 70314/70314 valid aggregated values (100.0%)
    EyeballCenterY_left: 70314/70314 valid aggregated values (100.0%)
    EyeballCenterZ_left: 70314/70314 valid aggregated values (100.0%)
    OpticalAxisX_left: 70314/70314 valid aggregated values (100.0%)
    OpticalAxisY_left: 70314/70314 valid aggregated values (100.0%)
    OpticalAxisZ_left: 70314/70314 valid aggregated values (100.0%)
    PupilDiameter_right: 70314/70314 valid aggregated values (100.0%)
    EyeballCenterX_right: 70314/70314 valid aggregated values (100.0%)
    EyeballCenterY_right: 70314/70314 valid aggregated values (100.0%)
    EyeballCenterZ_right: 70314/70314 valid aggregated values (100.0%)
    OpticalAxisX_right: 70314/70314 valid aggregated values (100.0%)
    OpticalAxisY_right: 70314/70314 valid aggregated values (100.0%)
    OpticalAxisZ_right: 70314/70314 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_y: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 68184/68713 matches (99.2%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 68184/68713 matches (99.2%)

Processing temp_datasync_remaining.csv...
  File timestamps: 544684.542 to 547057.503
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 65292/68713 matches (95.0%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3421:
  UNIX timestamp: 1758576411.33005
  EST time: 2025-09-22 17:26:51.330049992-04:00
  Corresponding EmotiBit timestamp: 544684.581
Successfully created Date and Time columns for all 68713 rows (EST timezone)
Duration: 2756.60 seconds

Example rows around sync point (row 3421):
  Row 3419: EmotiBit=544684.501, diff=-0.080s, Time=17:26:51.250
  Row 3420: EmotiBit=544684.541, diff=-0.040s, Time=17:26:51.290
  Row 3421: EmotiBit=544684.581, diff=+0.000s, Time=17:26:51.330 <- SYNC POINT
  Row 3422: EmotiBit=544684.621, diff=+0.040s, Time=17:26:51.370
  Row 3423: EmotiBit=544684.661, diff=+0.080s, Time=17:26:51.410

Applying forward fill to missing values...
Missing values before ffill: 387972
Missing values after ffill: 10393
Filled 377579 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 68713 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 544547.337 to 547303.941
Duration: 2756.60 seconds
Participant ID: 45
Condition: Trust Priming
Video condition: 2

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 65292/68713 (95.0% complete)
DataSyncMarker_channel_1: 65292/68713 (95.0% complete)
Reliability: 65292/68713 (95.0% complete)
PPG_GRN_C: 68713/68713 (100.0% complete)
PPG_RED_C: 68713/68713 (100.0% complete)
PPG_IR_C: 68713/68713 (100.0% complete)
EDA_C: 68711/68713 (100.0% complete)
HR_C: 68608/68713 (99.8% complete)
TEMP_C: 68712/68713 (100.0% complete)
THERM_C: 68711/68713 (100.0% complete)
Neon Companion_Neon Gaze_x: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_y: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 68713/68713 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 68713/68713 (100.0% complete)
PPG_GRN_IS: 68713/68713 (100.0% complete)
PPG_RED_IS: 68713/68713 (100.0% complete)
PPG_IR_IS: 68713/68713 (100.0% complete)
EDA_IS: 68713/68713 (100.0% complete)
HR_IS: 68696/68713 (100.0% complete)
TEMP_IS: 68711/68713 (100.0% complete)
THERM_IS: 68712/68713 (100.0% complete)

============================================================
Processing ID 46  (46_C.xdf)
  condition=Trust Priming  video_condition=3
============================================================

Stream 14: Calculated effective sampling rate 143.0666 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (48459, 1)
  Sample count: 48459

Exported stream 1 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (80533, 1)
  Sample count: 80533

Exported stream 2 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (80533, 1)
  Sample count: 80533

Exported stream 3 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (24229, 1)
  Sample count: 24229

Exported stream 4 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (24229, 1)
  Sample count: 24229

Exported stream 5 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (24230, 1)
  Sample count: 24230

Exported stream 6 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (80381, 1)
  Sample count: 80381

Exported stream 8 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (24230, 1)
  Sample count: 24230

Exported stream 9 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (48460, 1)
  Sample count: 48460

Exported stream 10 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2411, 1)
  Sample count: 2411

Exported stream 11 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (80380, 1)
  Sample count: 80380

Exported stream 12 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (80380, 1)
  Sample count: 80380

Exported stream 13 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2133, 1)
  Sample count: 2133

Exported stream 14 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (80533, 1)
  Sample count: 80533

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (12, 2)
  Sample count: 12

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (466697, 16)
  Sample count: 466697
  First timestamp: 604989.8920402153

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/46_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (80533 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 605225.302 to 608064.020
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 12 events
  DataSyncMarker events:
    t=605225.302, value=1.0
    t=605842.834, value=2.0
    t=606219.245, value=1.0
    t=606833.894, value=2.0
    t=607089.601, value=1.0
    t=607441.089, value=0.0
    t=607448.565, value=1.0
    t=607448.977, value=3.0
    t=607450.075, value=1.0
    t=607450.375, value=3.0
    t=607453.926, value=1.0
    t=608064.020, value=2.0
  Added Reliability column using video condition 3: ('HH', 'LL', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 77831/80533 matches (96.6%)
  DataSyncMarker value distribution:
    1.0: 54703 rows (67.9%)
    2.0: 22826 rows (28.3%)
    0.0: 187 rows (0.2%)
    3.0: 115 rows (0.1%)
Base PPG timestamps: 605116.939 to 608347.603

Processing EDA_I.csv...
  File timestamps: 605116.858 to 608347.506
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 50898/80533 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 605116.859 to 608347.507
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 25447/80533 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 605116.871 to 608347.587
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 80533/80533 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 605117.374 to 608347.289
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2541/80533 matches (3.2%)

Processing TEMP1_I.csv...
  File timestamps: 605116.852 to 608347.499
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 25458/80533 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 605116.938 to 608347.602
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 80533/80533 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 605116.791 to 608347.548
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 80532/80533 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 605116.870 to 608347.587
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 80533/80533 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 605117.091 to 608347.626
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 25452/80533 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 605116.970 to 608347.591
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 50899/80533 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 605117.224 to 608342.457
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2259/80533 matches (2.8%)

Processing TEMP1_C.csv...
  File timestamps: 605117.083 to 608347.618
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 25455/80533 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 605116.938 to 608347.602
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 80533/80533 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 604989.892 to 608251.981
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 81553 samples (16 channels)
    x: 81553/81553 valid aggregated values (100.0%)
    y: 81553/81553 valid aggregated values (100.0%)
    PupilDiameter_left: 81553/81553 valid aggregated values (100.0%)
    EyeballCenterX_left: 81553/81553 valid aggregated values (100.0%)
    EyeballCenterY_left: 81553/81553 valid aggregated values (100.0%)
    EyeballCenterZ_left: 81553/81553 valid aggregated values (100.0%)
    OpticalAxisX_left: 81553/81553 valid aggregated values (100.0%)
    OpticalAxisY_left: 81553/81553 valid aggregated values (100.0%)
    OpticalAxisZ_left: 81553/81553 valid aggregated values (100.0%)
    PupilDiameter_right: 81553/81553 valid aggregated values (100.0%)
    EyeballCenterX_right: 81553/81553 valid aggregated values (100.0%)
    EyeballCenterY_right: 81553/81553 valid aggregated values (100.0%)
    EyeballCenterZ_right: 81553/81553 valid aggregated values (100.0%)
    OpticalAxisX_right: 81553/81553 valid aggregated values (100.0%)
    OpticalAxisY_right: 81553/81553 valid aggregated values (100.0%)
    OpticalAxisZ_right: 81553/81553 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_y: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 78149/80533 matches (97.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 78149/80533 matches (97.0%)

Processing temp_datasync_remaining.csv...
  File timestamps: 605225.302 to 608064.020
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 77831/80533 matches (96.6%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 2702:
  UNIX timestamp: 1758636952.202868
  EST time: 2025-09-23 10:15:52.202867985-04:00
  Corresponding EmotiBit timestamp: 605225.333
Successfully created Date and Time columns for all 80533 rows (EST timezone)
Duration: 3230.66 seconds

Example rows around sync point (row 2702):
  Row 2700: EmotiBit=605225.253, diff=-0.080s, Time=10:15:52.122
  Row 2701: EmotiBit=605225.293, diff=-0.040s, Time=10:15:52.162
  Row 2702: EmotiBit=605225.333, diff=+0.000s, Time=10:15:52.202 <- SYNC POINT
  Row 2703: EmotiBit=605225.374, diff=+0.041s, Time=10:15:52.243
  Row 2704: EmotiBit=605225.414, diff=+0.081s, Time=10:15:52.283

Applying forward fill to missing values...
Missing values before ffill: 497635
Missing values after ffill: 8135
Filled 489500 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 80533 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 605116.939 to 608347.603
Duration: 3230.66 seconds
Participant ID: 46
Condition: Trust Priming
Video condition: 3

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 77831/80533 (96.6% complete)
DataSyncMarker_channel_1: 77831/80533 (96.6% complete)
Reliability: 77831/80533 (96.6% complete)
PPG_GRN_C: 80533/80533 (100.0% complete)
PPG_RED_C: 80533/80533 (100.0% complete)
PPG_IR_C: 80533/80533 (100.0% complete)
EDA_C: 80532/80533 (100.0% complete)
HR_C: 80522/80533 (100.0% complete)
TEMP_C: 80529/80533 (100.0% complete)
THERM_C: 80529/80533 (100.0% complete)
Neon Companion_Neon Gaze_x: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_y: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 80533/80533 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 80533/80533 (100.0% complete)
PPG_GRN_IS: 80533/80533 (100.0% complete)
PPG_RED_IS: 80533/80533 (100.0% complete)
PPG_IR_IS: 80533/80533 (100.0% complete)
EDA_IS: 80533/80533 (100.0% complete)
HR_IS: 80526/80533 (100.0% complete)
TEMP_IS: 80532/80533 (100.0% complete)
THERM_IS: 80532/80533 (100.0% complete)

Applying restart fix for ID 46 (restarted at block 3)...
DataSyncMarker==1 runs: 6
  run 1: rows 2702-18094 (n=15393)
  run 2: rows 27478-42799 (n=15322)
  run 3: rows 49174-57934 (n=8761)
  run 4: rows 58122-58131 (n=10)
  run 5: rows 58159-58166 (n=8)
  run 6: rows 58255-73463 (n=15209)
DataSyncMarker==3 runs: 2
  run 1: rows 58132-58158 (n=27)
  run 2: rows 58167-58254 (n=88)
Restart window: rows 49174-58254 (n=9081)
WARNING: 2702 row(s) outside the restart window had an unexpected non-1/2 DataSyncMarker state
Tagged 9081 row(s) as 'Restart'
Re-saved relabeled CSV: /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/merged_data_46.csv

============================================================
Processing ID 47  (47_C.xdf)
  condition=Distrust Priming  video_condition=4
============================================================

Stream 12: Calculated effective sampling rate 140.5081 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21286, 1)
  Sample count: 21286

Exported stream 1 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2370, 1)
  Sample count: 2370

Exported stream 2 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21286, 1)
  Sample count: 21286

Exported stream 3 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21285, 1)
  Sample count: 21285

Exported stream 4 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2594, 1)
  Sample count: 2594

Exported stream 5 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (70604, 1)
  Sample count: 70604

Exported stream 6 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (70762, 1)
  Sample count: 70762

Exported stream 8 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21285, 1)
  Sample count: 21285

Exported stream 9 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (42570, 1)
  Sample count: 42570

Exported stream 10 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (70604, 1)
  Sample count: 70604

Exported stream 11 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (70762, 1)
  Sample count: 70762

Exported stream 12 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (70601, 1)
  Sample count: 70601

Exported stream 13 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (42569, 1)
  Sample count: 42569

Exported stream 14 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (70762, 1)
  Sample count: 70762

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (403645, 16)
  Sample count: 403645
  First timestamp: 612399.6635065743

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/47_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (70762 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 612648.728 to 615087.738
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=612648.728, value=1.0
    t=613268.648, value=2.0
    t=613602.881, value=1.0
    t=614216.088, value=2.0
    t=614469.427, value=1.0
    t=615087.738, value=2.0
  Added Reliability column using video condition 4: ('HH', 'M', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 66673/70762 matches (94.2%)
  DataSyncMarker value distribution:
    1.0: 46167 rows (65.2%)
    2.0: 20506 rows (29.0%)
Base PPG timestamps: 612484.788 to 615322.476

Processing EDA_I.csv...
  File timestamps: 612484.817 to 615322.522
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 44736/70762 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 612484.760 to 615322.502
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 22355/70762 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 612484.766 to 615322.557
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 70762/70762 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 612488.272 to 615320.274
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2477/70762 matches (3.5%)

Processing TEMP1_I.csv...
  File timestamps: 612484.752 to 615322.494
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 22349/70762 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 612484.787 to 615322.475
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 70762/70762 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 612484.646 to 615322.557
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 70762/70762 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 612484.645 to 615322.556
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 70762/70762 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 612484.744 to 615322.342
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 22358/70762 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 612484.743 to 615322.407
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 44734/70762 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 612486.773 to 615317.325
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2736/70762 matches (3.9%)

Processing TEMP1_C.csv...
  File timestamps: 612484.737 to 615322.334
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 22367/70762 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 612484.787 to 615322.475
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 70762/70762 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 612399.664 to 615272.410
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 71819 samples (16 channels)
    x: 71819/71819 valid aggregated values (100.0%)
    y: 71819/71819 valid aggregated values (100.0%)
    PupilDiameter_left: 71819/71819 valid aggregated values (100.0%)
    EyeballCenterX_left: 71819/71819 valid aggregated values (100.0%)
    EyeballCenterY_left: 71819/71819 valid aggregated values (100.0%)
    EyeballCenterZ_left: 71819/71819 valid aggregated values (100.0%)
    OpticalAxisX_left: 71819/71819 valid aggregated values (100.0%)
    OpticalAxisY_left: 71819/71819 valid aggregated values (100.0%)
    OpticalAxisZ_left: 71819/71819 valid aggregated values (100.0%)
    PupilDiameter_right: 71819/71819 valid aggregated values (100.0%)
    EyeballCenterX_right: 71819/71819 valid aggregated values (100.0%)
    EyeballCenterY_right: 71819/71819 valid aggregated values (100.0%)
    EyeballCenterZ_right: 71819/71819 valid aggregated values (100.0%)
    OpticalAxisX_right: 71819/71819 valid aggregated values (100.0%)
    OpticalAxisY_right: 71819/71819 valid aggregated values (100.0%)
    OpticalAxisZ_right: 71819/71819 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_y: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 69513/70762 matches (98.2%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 69513/70762 matches (98.2%)

Processing temp_datasync_remaining.csv...
  File timestamps: 612648.728 to 615087.738
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 66673/70762 matches (94.2%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 4089:
  UNIX timestamp: 1758644375.6554902
  EST time: 2025-09-23 12:19:35.655490160-04:00
  Corresponding EmotiBit timestamp: 612648.767
Successfully created Date and Time columns for all 70762 rows (EST timezone)
Duration: 2837.69 seconds

Example rows around sync point (row 4089):
  Row 4087: EmotiBit=612648.686, diff=-0.081s, Time=12:19:35.574
  Row 4088: EmotiBit=612648.727, diff=-0.040s, Time=12:19:35.615
  Row 4089: EmotiBit=612648.767, diff=+0.000s, Time=12:19:35.655 <- SYNC POINT
  Row 4090: EmotiBit=612648.807, diff=+0.040s, Time=12:19:35.695
  Row 4091: EmotiBit=612648.847, diff=+0.080s, Time=12:19:35.735

Applying forward fill to missing values...
Missing values before ffill: 414235
Missing values after ffill: 12414
Filled 401821 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 70762 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 612484.788 to 615322.476
Duration: 2837.69 seconds
Participant ID: 47
Condition: Distrust Priming
Video condition: 4

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 66673/70762 (94.2% complete)
DataSyncMarker_channel_1: 66673/70762 (94.2% complete)
Reliability: 66673/70762 (94.2% complete)
PPG_GRN_C: 70762/70762 (100.0% complete)
PPG_RED_C: 70762/70762 (100.0% complete)
PPG_IR_C: 70762/70762 (100.0% complete)
EDA_C: 70761/70762 (100.0% complete)
HR_C: 70675/70762 (99.9% complete)
TEMP_C: 70760/70762 (100.0% complete)
THERM_C: 70760/70762 (100.0% complete)
Neon Companion_Neon Gaze_x: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_y: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 70762/70762 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 70762/70762 (100.0% complete)
PPG_GRN_IS: 70762/70762 (100.0% complete)
PPG_RED_IS: 70762/70762 (100.0% complete)
PPG_IR_IS: 70762/70762 (100.0% complete)
EDA_IS: 70761/70762 (100.0% complete)
HR_IS: 70713/70762 (99.9% complete)
TEMP_IS: 70760/70762 (100.0% complete)
THERM_IS: 70759/70762 (100.0% complete)

============================================================
Processing ID 48  (48_C.xdf)
  condition=Distrust Priming  video_condition=5
============================================================

Stream 6: Calculated effective sampling rate 142.3992 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (43271, 1)
  Sample count: 43271

Exported stream 2 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71908, 1)
  Sample count: 71908

Exported stream 3 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21636, 1)
  Sample count: 21636

Exported stream 4 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71782, 1)
  Sample count: 71782

Exported stream 5 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71782, 1)
  Sample count: 71782

Exported stream 6 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71908, 1)
  Sample count: 71908

Exported stream 7 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1514, 1)
  Sample count: 1514

Exported stream 8 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (71908, 1)
  Sample count: 71908

Exported stream 9 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (3607, 1)
  Sample count: 3607

Exported stream 10 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (43273, 1)
  Sample count: 43273

Exported stream 11 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21636, 1)
  Sample count: 21636

Exported stream 12 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (71782, 1)
  Sample count: 71782

Exported stream 13 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21636, 1)
  Sample count: 21636

Exported stream 14 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21636, 1)
  Sample count: 21636

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (412452, 16)
  Sample count: 412452
  First timestamp: 705366.0742222627

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/48_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (71908 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 705624.566 to 708111.680
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=705624.566, value=1.0
    t=706211.000, value=2.0
    t=706586.462, value=1.0
    t=707175.616, value=2.0
    t=707513.475, value=1.0
    t=708111.680, value=2.0
  Added Reliability column using video condition 5: ('M', 'LL', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 68609/71908 matches (95.4%)
  DataSyncMarker value distribution:
    1.0: 44215 rows (61.5%)
    2.0: 24394 rows (33.9%)
Base PPG timestamps: 705492.251 to 708376.975

Processing EDA_I.csv...
  File timestamps: 705492.295 to 708376.869
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 45450/71908 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 705492.403 to 708376.882
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 22709/71908 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 705492.244 to 708376.896
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 71906/71908 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 705497.734 to 708376.649
  Added 1 column(s) from HR_C.csv
    HR_C_value: 3789/71908 matches (5.3%)

Processing TEMP1_I.csv...
  File timestamps: 705492.395 to 708376.875
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 22723/71908 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 705492.250 to 708376.974
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 71908/71908 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 705492.245 to 708376.896
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 71906/71908 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 705492.244 to 708376.895
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 71906/71908 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 705492.225 to 708376.938
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 22726/71908 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 705492.274 to 708377.012
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 45449/71908 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 705492.750 to 708371.200
  Added 1 column(s) from HR_I.csv
    HR_I_value: 1600/71908 matches (2.2%)

Processing TEMP1_C.csv...
  File timestamps: 705492.218 to 708376.931
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 22730/71908 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 705492.251 to 708376.975
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 71908/71908 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 705366.074 to 708262.517
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 72412 samples (16 channels)
    x: 72412/72412 valid aggregated values (100.0%)
    y: 72412/72412 valid aggregated values (100.0%)
    PupilDiameter_left: 72412/72412 valid aggregated values (100.0%)
    EyeballCenterX_left: 72412/72412 valid aggregated values (100.0%)
    EyeballCenterY_left: 72412/72412 valid aggregated values (100.0%)
    EyeballCenterZ_left: 72412/72412 valid aggregated values (100.0%)
    OpticalAxisX_left: 72412/72412 valid aggregated values (100.0%)
    OpticalAxisY_left: 72412/72412 valid aggregated values (100.0%)
    OpticalAxisZ_left: 72412/72412 valid aggregated values (100.0%)
    PupilDiameter_right: 72412/72412 valid aggregated values (100.0%)
    EyeballCenterX_right: 72412/72412 valid aggregated values (100.0%)
    EyeballCenterY_right: 72412/72412 valid aggregated values (100.0%)
    EyeballCenterZ_right: 72412/72412 valid aggregated values (100.0%)
    OpticalAxisX_right: 72412/72412 valid aggregated values (100.0%)
    OpticalAxisY_right: 72412/72412 valid aggregated values (100.0%)
    OpticalAxisZ_right: 72412/72412 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_y: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 69055/71908 matches (96.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 69055/71908 matches (96.0%)

Processing temp_datasync_remaining.csv...
  File timestamps: 705624.566 to 708111.680
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 68609/71908 matches (95.4%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3299:
  UNIX timestamp: 1758737351.438727
  EST time: 2025-09-24 14:09:11.438726902-04:00
  Corresponding EmotiBit timestamp: 705624.599
Successfully created Date and Time columns for all 71908 rows (EST timezone)
Duration: 2884.72 seconds

Example rows around sync point (row 3299):
  Row 3297: EmotiBit=705624.518, diff=-0.081s, Time=14:09:11.357
  Row 3298: EmotiBit=705624.559, diff=-0.040s, Time=14:09:11.398
  Row 3299: EmotiBit=705624.599, diff=+0.000s, Time=14:09:11.438 <- SYNC POINT
  Row 3300: EmotiBit=705624.639, diff=+0.040s, Time=14:09:11.478
  Row 3301: EmotiBit=705624.679, diff=+0.080s, Time=14:09:11.518

Applying forward fill to missing values...
Missing values before ffill: 443639
Missing values after ffill: 10061
Filled 433578 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 71908 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 705492.251 to 708376.975
Duration: 2884.72 seconds
Participant ID: 48
Condition: Distrust Priming
Video condition: 5

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 68609/71908 (95.4% complete)
DataSyncMarker_channel_1: 68609/71908 (95.4% complete)
Reliability: 68609/71908 (95.4% complete)
PPG_GRN_C: 71908/71908 (100.0% complete)
PPG_RED_C: 71908/71908 (100.0% complete)
PPG_IR_C: 71908/71908 (100.0% complete)
EDA_C: 71907/71908 (100.0% complete)
HR_C: 71771/71908 (99.8% complete)
TEMP_C: 71906/71908 (100.0% complete)
THERM_C: 71905/71908 (100.0% complete)
Neon Companion_Neon Gaze_x: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_y: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 71908/71908 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 71908/71908 (100.0% complete)
PPG_GRN_IS: 71908/71908 (100.0% complete)
PPG_RED_IS: 71908/71908 (100.0% complete)
PPG_IR_IS: 71908/71908 (100.0% complete)
EDA_IS: 71907/71908 (100.0% complete)
HR_IS: 71896/71908 (100.0% complete)
TEMP_IS: 71904/71908 (100.0% complete)
THERM_IS: 71904/71908 (100.0% complete)

============================================================
Processing ID 49  (49_C.xdf)
  condition=Trust Priming  video_condition=6
============================================================

Stream 17: Calculated effective sampling rate 133.0116 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21828, 1)
  Sample count: 21828

Exported stream 1 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72413, 1)
  Sample count: 72413

Exported stream 2 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21829, 1)
  Sample count: 21829

Exported stream 3 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (43656, 1)
  Sample count: 43656

Exported stream 4 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1827, 1)
  Sample count: 1827

Exported stream 5 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72563, 1)
  Sample count: 72563

Exported stream 6 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21827, 1)
  Sample count: 21827

Exported stream 7 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21828, 1)
  Sample count: 21828

Exported stream 9 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2744, 1)
  Sample count: 2744

Exported stream 10 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72413, 1)
  Sample count: 72413

Exported stream 11 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72563, 1)
  Sample count: 72563

Exported stream 12 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72563, 1)
  Sample count: 72563

Exported stream 13 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72413, 1)
  Sample count: 72413

Exported stream 14 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (43654, 1)
  Sample count: 43654

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (394132, 16)
  Sample count: 394132
  First timestamp: 713739.3900109569

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/49_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (72563 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 714068.015 to 716478.987
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=714068.015, value=1.0
    t=714658.726, value=2.0
    t=715087.672, value=1.0
    t=715687.690, value=2.0
    t=715889.522, value=1.0
    t=716478.987, value=2.0
  Added Reliability column using video condition 6: ('M', 'HH', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 67915/72563 matches (93.6%)
  DataSyncMarker value distribution:
    1.0: 44388 rows (61.2%)
    2.0: 23527 rows (32.4%)
Base PPG timestamps: 713881.623 to 716791.711

Processing EDA_I.csv...
  File timestamps: 713881.696 to 716791.660
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 45885/72563 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 713881.653 to 716791.651
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 22936/72563 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 713881.792 to 716791.792
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 72559/72563 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 713891.172 to 716785.802
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2886/72563 matches (4.0%)

Processing TEMP1_I.csv...
  File timestamps: 713881.735 to 716791.664
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 22924/72563 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 713881.622 to 716791.709
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 72563/72563 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 713881.793 to 716791.793
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 72559/72563 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 713881.792 to 716791.792
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 72559/72563 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 713881.631 to 716791.620
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 22951/72563 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 713881.630 to 716791.686
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 45862/72563 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 713881.772 to 716788.419
  Added 1 column(s) from HR_I.csv
    HR_I_value: 1913/72563 matches (2.6%)

Processing TEMP1_C.csv...
  File timestamps: 713881.624 to 716791.746
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 22948/72563 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 713881.623 to 716791.710
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 72563/72563 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 713739.390 to 716702.523
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 74079 samples (16 channels)
    x: 74079/74079 valid aggregated values (100.0%)
    y: 74079/74079 valid aggregated values (100.0%)
    PupilDiameter_left: 74079/74079 valid aggregated values (100.0%)
    EyeballCenterX_left: 74079/74079 valid aggregated values (100.0%)
    EyeballCenterY_left: 74079/74079 valid aggregated values (100.0%)
    EyeballCenterZ_left: 74079/74079 valid aggregated values (100.0%)
    OpticalAxisX_left: 74079/74079 valid aggregated values (100.0%)
    OpticalAxisY_left: 74079/74079 valid aggregated values (100.0%)
    OpticalAxisZ_left: 74079/74079 valid aggregated values (100.0%)
    PupilDiameter_right: 74079/74079 valid aggregated values (100.0%)
    EyeballCenterX_right: 74079/74079 valid aggregated values (100.0%)
    EyeballCenterY_right: 74079/74079 valid aggregated values (100.0%)
    EyeballCenterZ_right: 74079/74079 valid aggregated values (100.0%)
    OpticalAxisX_right: 74079/74079 valid aggregated values (100.0%)
    OpticalAxisY_right: 74079/74079 valid aggregated values (100.0%)
    OpticalAxisZ_right: 74079/74079 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_y: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 70339/72563 matches (96.9%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 70339/72563 matches (96.9%)

Processing temp_datasync_remaining.csv...
  File timestamps: 714068.015 to 716478.987
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 67915/72563 matches (93.6%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 4648:
  UNIX timestamp: 1758745794.959463
  EST time: 2025-09-24 16:29:54.959462881-04:00
  Corresponding EmotiBit timestamp: 714068.03
Successfully created Date and Time columns for all 72563 rows (EST timezone)
Duration: 2910.09 seconds

Example rows around sync point (row 4648):
  Row 4646: EmotiBit=714067.950, diff=-0.080s, Time=16:29:54.879
  Row 4647: EmotiBit=714067.990, diff=-0.040s, Time=16:29:54.919
  Row 4648: EmotiBit=714068.030, diff=+0.000s, Time=16:29:54.959 <- SYNC POINT
  Row 4649: EmotiBit=714068.070, diff=+0.040s, Time=16:29:54.999
  Row 4650: EmotiBit=714068.111, diff=+0.081s, Time=16:29:55.040

Applying forward fill to missing values...
Missing values before ffill: 441739
Missing values after ffill: 14204
Filled 427535 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 72563 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 713881.623 to 716791.711
Duration: 2910.09 seconds
Participant ID: 49
Condition: Trust Priming
Video condition: 6

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 67915/72563 (93.6% complete)
DataSyncMarker_channel_1: 67915/72563 (93.6% complete)
Reliability: 67915/72563 (93.6% complete)
PPG_GRN_C: 72563/72563 (100.0% complete)
PPG_RED_C: 72563/72563 (100.0% complete)
PPG_IR_C: 72563/72563 (100.0% complete)
EDA_C: 72563/72563 (100.0% complete)
HR_C: 72325/72563 (99.7% complete)
TEMP_C: 72563/72563 (100.0% complete)
THERM_C: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_x: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_y: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 72563/72563 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 72563/72563 (100.0% complete)
PPG_GRN_IS: 72559/72563 (100.0% complete)
PPG_RED_IS: 72559/72563 (100.0% complete)
PPG_IR_IS: 72559/72563 (100.0% complete)
EDA_IS: 72561/72563 (100.0% complete)
HR_IS: 72559/72563 (100.0% complete)
TEMP_IS: 72560/72563 (100.0% complete)
THERM_IS: 72562/72563 (100.0% complete)

============================================================
Processing ID 50  (50_C.xdf)
  condition=Distrust Priming  video_condition=6
============================================================

Stream 6: Calculated effective sampling rate 124.0486 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (67306, 1)
  Sample count: 67306

Exported stream 1 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (892, 1)
  Sample count: 892

Exported stream 2 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (67436, 1)
  Sample count: 67436

Exported stream 3 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20290, 1)
  Sample count: 20290

Exported stream 5 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2811, 1)
  Sample count: 2811

Exported stream 6 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20290, 1)
  Sample count: 20290

Exported stream 7 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20290, 1)
  Sample count: 20290

Exported stream 8 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (67306, 1)
  Sample count: 67306

Exported stream 9 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (40579, 1)
  Sample count: 40579

Exported stream 10 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (67306, 1)
  Sample count: 67306

Exported stream 11 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20289, 1)
  Sample count: 20289

Exported stream 12 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (67436, 1)
  Sample count: 67436

Exported stream 13 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (40579, 1)
  Sample count: 40579

Exported stream 14 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (67436, 1)
  Sample count: 67436

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (346888, 16)
  Sample count: 346888
  First timestamp: 778212.7657393183

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/50_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (67436 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 778510.376 to 780856.766
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=778510.376, value=1.0
    t=779119.363, value=2.0
    t=779417.380, value=1.0
    t=780043.069, value=2.0
    t=780238.027, value=1.0
    t=780856.766, value=2.0
  Added Reliability column using video condition 6: ('M', 'HH', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 63679/67436 matches (94.4%)
  DataSyncMarker value distribution:
    1.0: 46203 rows (68.5%)
    2.0: 17476 rows (25.9%)
Base PPG timestamps: 778359.666 to 781064.838

Processing EDA_I.csv...
  File timestamps: 778359.698 to 781064.847
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 42619/67436 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 778359.700 to 781064.848
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 21316/67436 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 778359.525 to 781064.735
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 67433/67436 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 778360.125 to 781063.882
  Added 1 column(s) from HR_C.csv
    HR_C_value: 930/67436 matches (1.4%)

Processing TEMP1_I.csv...
  File timestamps: 778359.692 to 781064.841
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 21311/67436 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 778359.665 to 781064.837
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 67436/67436 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 778359.525 to 781064.736
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 67434/67436 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 778359.524 to 781064.735
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 67433/67436 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 778359.747 to 781064.753
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 21309/67436 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 778359.679 to 781064.819
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 42618/67436 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 778360.125 to 781057.732
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2947/67436 matches (4.4%)

Processing TEMP1_C.csv...
  File timestamps: 778359.769 to 781064.709
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 21317/67436 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 778359.665 to 781064.837
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 67436/67436 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 778212.766 to 781009.146
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 69910 samples (16 channels)
    x: 69910/69910 valid aggregated values (100.0%)
    y: 69910/69910 valid aggregated values (100.0%)
    PupilDiameter_left: 69910/69910 valid aggregated values (100.0%)
    EyeballCenterX_left: 69910/69910 valid aggregated values (100.0%)
    EyeballCenterY_left: 69910/69910 valid aggregated values (100.0%)
    EyeballCenterZ_left: 69910/69910 valid aggregated values (100.0%)
    OpticalAxisX_left: 69910/69910 valid aggregated values (100.0%)
    OpticalAxisY_left: 69910/69910 valid aggregated values (100.0%)
    OpticalAxisZ_left: 69910/69910 valid aggregated values (100.0%)
    PupilDiameter_right: 69910/69910 valid aggregated values (100.0%)
    EyeballCenterX_right: 69910/69910 valid aggregated values (100.0%)
    EyeballCenterY_right: 69910/69910 valid aggregated values (100.0%)
    EyeballCenterZ_right: 69910/69910 valid aggregated values (100.0%)
    OpticalAxisX_right: 69910/69910 valid aggregated values (100.0%)
    OpticalAxisY_right: 69910/69910 valid aggregated values (100.0%)
    OpticalAxisZ_right: 69910/69910 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_y: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 66047/67436 matches (97.9%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 66047/67436 matches (97.9%)

Processing temp_datasync_remaining.csv...
  File timestamps: 778510.376 to 780856.766
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 63679/67436 matches (94.4%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3757:
  UNIX timestamp: 1758810237.353529
  EST time: 2025-09-25 10:23:57.353528976-04:00
  Corresponding EmotiBit timestamp: 778510.379
Successfully created Date and Time columns for all 67436 rows (EST timezone)
Duration: 2705.17 seconds

Example rows around sync point (row 3757):
  Row 3755: EmotiBit=778510.299, diff=-0.080s, Time=10:23:57.273
  Row 3756: EmotiBit=778510.339, diff=-0.040s, Time=10:23:57.313
  Row 3757: EmotiBit=778510.379, diff=+0.000s, Time=10:23:57.353 <- SYNC POINT
  Row 3758: EmotiBit=778510.419, diff=+0.040s, Time=10:23:57.393
  Row 3759: EmotiBit=778510.459, diff=+0.080s, Time=10:23:57.433

Applying forward fill to missing values...
Missing values before ffill: 398624
Missing values after ffill: 11301
Filled 387323 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 67436 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 778359.666 to 781064.838
Duration: 2705.17 seconds
Participant ID: 50
Condition: Distrust Priming
Video condition: 6

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 63679/67436 (94.4% complete)
DataSyncMarker_channel_1: 63679/67436 (94.4% complete)
Reliability: 63679/67436 (94.4% complete)
PPG_GRN_C: 67436/67436 (100.0% complete)
PPG_RED_C: 67436/67436 (100.0% complete)
PPG_IR_C: 67436/67436 (100.0% complete)
EDA_C: 67436/67436 (100.0% complete)
HR_C: 67425/67436 (100.0% complete)
TEMP_C: 67433/67436 (100.0% complete)
THERM_C: 67434/67436 (100.0% complete)
Neon Companion_Neon Gaze_x: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_y: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 67436/67436 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 67436/67436 (100.0% complete)
PPG_GRN_IS: 67436/67436 (100.0% complete)
PPG_RED_IS: 67436/67436 (100.0% complete)
PPG_IR_IS: 67436/67436 (100.0% complete)
EDA_IS: 67435/67436 (100.0% complete)
HR_IS: 67425/67436 (100.0% complete)
TEMP_IS: 67435/67436 (100.0% complete)
THERM_IS: 67435/67436 (100.0% complete)

============================================================
Processing ID 51  (51_C.xdf)
  condition=Distrust Priming  video_condition=1
============================================================

Stream 8: Calculated effective sampling rate 151.7475 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72361, 1)
  Sample count: 72361

Exported stream 1 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72219, 1)
  Sample count: 72219

Exported stream 2 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (43537, 1)
  Sample count: 43537

Exported stream 3 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72361, 1)
  Sample count: 72361

Exported stream 4 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72361, 1)
  Sample count: 72361

Exported stream 5 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1351, 1)
  Sample count: 1351

Exported stream 6 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21768, 1)
  Sample count: 21768

Exported stream 7 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21768, 1)
  Sample count: 21768

Exported stream 8 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72219, 1)
  Sample count: 72219

Exported stream 9 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21769, 1)
  Sample count: 21769

Exported stream 11 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72219, 1)
  Sample count: 72219

Exported stream 12 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2402, 1)
  Sample count: 2402

Exported stream 13 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21769, 1)
  Sample count: 21769

Exported stream 14 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (43537, 1)
  Sample count: 43537

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (443271, 16)
  Sample count: 443271
  First timestamp: 864715.7607064937

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/51_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (72361 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 864986.082 to 867487.858
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=864986.082, value=1.0
    t=865599.138, value=2.0
    t=865994.026, value=1.0
    t=866618.805, value=2.0
    t=866876.473, value=1.0
    t=867487.858, value=2.0
  Added Reliability column using video condition 1: ('LL', 'HH', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 67873/72361 matches (93.8%)
  DataSyncMarker value distribution:
    1.0: 46107 rows (63.7%)
    2.0: 21766 rows (30.1%)
Base PPG timestamps: 864806.099 to 867708.258

Processing EDA_I.csv...
  File timestamps: 864806.032 to 867708.168
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 45735/72361 matches (63.2%)

Processing THERM_I.csv...
  File timestamps: 864806.033 to 867708.170
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 22867/72361 matches (31.6%)

Processing PPG_RED_I.csv...
  File timestamps: 864806.003 to 867708.191
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 72359/72361 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 864806.452 to 867707.235
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2530/72361 matches (3.5%)

Processing TEMP1_I.csv...
  File timestamps: 864806.026 to 867708.162
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 22863/72361 matches (31.6%)

Processing PPG_IR_C.csv...
  File timestamps: 864806.098 to 867708.257
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 72361/72361 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 864806.004 to 867708.192
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 72359/72361 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 864806.002 to 867708.191
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 72359/72361 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 864806.151 to 867708.225
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 22868/72361 matches (31.6%)

Processing EDA_C.csv...
  File timestamps: 864806.083 to 867708.290
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 45740/72361 matches (63.2%)

Processing HR_I.csv...
  File timestamps: 864807.070 to 867704.955
  Added 1 column(s) from HR_I.csv
    HR_I_value: 1414/72361 matches (2.0%)

Processing TEMP1_C.csv...
  File timestamps: 864806.144 to 867708.217
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 22864/72361 matches (31.6%)

Processing PPG_RED_C.csv...
  File timestamps: 864806.099 to 867708.257
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 72361/72361 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 864715.761 to 867636.863
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 73028 samples (16 channels)
    x: 73028/73028 valid aggregated values (100.0%)
    y: 73028/73028 valid aggregated values (100.0%)
    PupilDiameter_left: 73028/73028 valid aggregated values (100.0%)
    EyeballCenterX_left: 73028/73028 valid aggregated values (100.0%)
    EyeballCenterY_left: 73028/73028 valid aggregated values (100.0%)
    EyeballCenterZ_left: 73028/73028 valid aggregated values (100.0%)
    OpticalAxisX_left: 73028/73028 valid aggregated values (100.0%)
    OpticalAxisY_left: 73028/73028 valid aggregated values (100.0%)
    OpticalAxisZ_left: 73028/73028 valid aggregated values (100.0%)
    PupilDiameter_right: 73028/73028 valid aggregated values (100.0%)
    EyeballCenterX_right: 73028/73028 valid aggregated values (100.0%)
    EyeballCenterY_right: 73028/73028 valid aggregated values (100.0%)
    EyeballCenterZ_right: 73028/73028 valid aggregated values (100.0%)
    OpticalAxisX_right: 73028/73028 valid aggregated values (100.0%)
    OpticalAxisY_right: 73028/73028 valid aggregated values (100.0%)
    OpticalAxisZ_right: 73028/73028 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_y: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 70580/72361 matches (97.5%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 70580/72361 matches (97.5%)

Processing temp_datasync_remaining.csv...
  File timestamps: 864986.082 to 867487.858
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 67873/72361 matches (93.8%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 4488:
  UNIX timestamp: 1758896713.109717
  EST time: 2025-09-26 10:25:13.109716892-04:00
  Corresponding EmotiBit timestamp: 864986.101
Successfully created Date and Time columns for all 72361 rows (EST timezone)
Duration: 2902.16 seconds

Example rows around sync point (row 4488):
  Row 4486: EmotiBit=864986.020, diff=-0.081s, Time=10:25:13.028
  Row 4487: EmotiBit=864986.061, diff=-0.040s, Time=10:25:13.069
  Row 4488: EmotiBit=864986.101, diff=+0.000s, Time=10:25:13.109 <- SYNC POINT
  Row 4489: EmotiBit=864986.141, diff=+0.040s, Time=10:25:13.149
  Row 4490: EmotiBit=864986.181, diff=+0.080s, Time=10:25:13.189

Applying forward fill to missing values...
Missing values before ffill: 433973
Missing values after ffill: 13502
Filled 420471 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 72361 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 864806.099 to 867708.258
Duration: 2902.16 seconds
Participant ID: 51
Condition: Distrust Priming
Video condition: 1

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 67873/72361 (93.8% complete)
DataSyncMarker_channel_1: 67873/72361 (93.8% complete)
Reliability: 67873/72361 (93.8% complete)
PPG_GRN_C: 72361/72361 (100.0% complete)
PPG_RED_C: 72361/72361 (100.0% complete)
PPG_IR_C: 72361/72361 (100.0% complete)
EDA_C: 72361/72361 (100.0% complete)
HR_C: 72352/72361 (100.0% complete)
TEMP_C: 72360/72361 (100.0% complete)
THERM_C: 72360/72361 (100.0% complete)
Neon Companion_Neon Gaze_x: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_y: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 72361/72361 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 72361/72361 (100.0% complete)
PPG_GRN_IS: 72361/72361 (100.0% complete)
PPG_RED_IS: 72361/72361 (100.0% complete)
PPG_IR_IS: 72361/72361 (100.0% complete)
EDA_IS: 72361/72361 (100.0% complete)
HR_IS: 72337/72361 (100.0% complete)
TEMP_IS: 72360/72361 (100.0% complete)
THERM_IS: 72359/72361 (100.0% complete)

============================================================
Processing ID 52  (52_C.xdf)
  condition=Trust Priming  video_condition=2
============================================================

Stream 5: Calculated effective sampling rate 152.5187 Hz is different from specified rate 200.0000 Hz.

Exported stream 1 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72565, 1)
  Sample count: 72565

Exported stream 2 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21830, 1)
  Sample count: 21830

Exported stream 3 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21832, 1)
  Sample count: 21832

Exported stream 4 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72446, 1)
  Sample count: 72446

Exported stream 5 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (43661, 1)
  Sample count: 43661

Exported stream 6 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (21831, 1)
  Sample count: 21831

Exported stream 7 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72435, 1)
  Sample count: 72435

Exported stream 8 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (72435, 1)
  Sample count: 72435

Exported stream 9 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (43662, 1)
  Sample count: 43662

Exported stream 10 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1986, 1)
  Sample count: 1986

Exported stream 11 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72565, 1)
  Sample count: 72565

Exported stream 12 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (21831, 1)
  Sample count: 21831

Exported stream 13 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2277, 1)
  Sample count: 2277

Exported stream 14 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (72565, 1)
  Sample count: 72565

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (441097, 16)
  Sample count: 441097
  First timestamp: 1142098.6017182108

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/52_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (72565 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 1142344.385 to 1144843.534
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=1142344.385, value=1.0
    t=1142957.006, value=2.0
    t=1143333.650, value=1.0
    t=1143944.729, value=2.0
    t=1144226.111, value=1.0
    t=1144843.534, value=2.0
  Added Reliability column using video condition 2: ('LL', 'M', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 68567/72565 matches (94.5%)
  DataSyncMarker value distribution:
    1.0: 45899 rows (63.3%)
    2.0: 22668 rows (31.2%)
Base PPG timestamps: 1142184.041 to 1145094.718

Processing EDA_I.csv...
  File timestamps: 1142183.947 to 1145094.738
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 46335/72565 matches (63.9%)

Processing THERM_I.csv...
  File timestamps: 1142184.014 to 1145094.739
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 23163/72565 matches (31.9%)

Processing PPG_RED_I.csv...
  File timestamps: 1142183.870 to 1145094.705
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 72565/72565 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 1142184.820 to 1145087.669
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2412/72565 matches (3.3%)

Processing TEMP1_I.csv...
  File timestamps: 1142184.048 to 1145094.761
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 23162/72565 matches (31.9%)

Processing PPG_IR_C.csv...
  File timestamps: 1142184.040 to 1145094.717
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 72565/72565 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 1142183.870 to 1145095.148
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 72565/72565 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 1142183.869 to 1145094.704
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 72565/72565 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 1142184.155 to 1145094.736
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 23163/72565 matches (31.9%)

Processing EDA_C.csv...
  File timestamps: 1142184.100 to 1145094.706
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 46336/72565 matches (63.9%)

Processing HR_I.csv...
  File timestamps: 1142189.554 to 1145085.668
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2103/72565 matches (2.9%)

Processing TEMP1_C.csv...
  File timestamps: 1142184.107 to 1145094.699
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 23167/72565 matches (31.9%)

Processing PPG_RED_C.csv...
  File timestamps: 1142184.041 to 1145094.718
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 72565/72565 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 1142098.602 to 1144990.679
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 72302 samples (16 channels)
    x: 72302/72302 valid aggregated values (100.0%)
    y: 72302/72302 valid aggregated values (100.0%)
    PupilDiameter_left: 72302/72302 valid aggregated values (100.0%)
    EyeballCenterX_left: 72302/72302 valid aggregated values (100.0%)
    EyeballCenterY_left: 72302/72302 valid aggregated values (100.0%)
    EyeballCenterZ_left: 72302/72302 valid aggregated values (100.0%)
    OpticalAxisX_left: 72302/72302 valid aggregated values (100.0%)
    OpticalAxisY_left: 72302/72302 valid aggregated values (100.0%)
    OpticalAxisZ_left: 72302/72302 valid aggregated values (100.0%)
    PupilDiameter_right: 72302/72302 valid aggregated values (100.0%)
    EyeballCenterX_right: 72302/72302 valid aggregated values (100.0%)
    EyeballCenterY_right: 72302/72302 valid aggregated values (100.0%)
    EyeballCenterZ_right: 72302/72302 valid aggregated values (100.0%)
    OpticalAxisX_right: 72302/72302 valid aggregated values (100.0%)
    OpticalAxisY_right: 72302/72302 valid aggregated values (100.0%)
    OpticalAxisZ_right: 72302/72302 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_y: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 69970/72565 matches (96.4%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 69970/72565 matches (96.4%)

Processing temp_datasync_remaining.csv...
  File timestamps: 1142344.385 to 1144843.534
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 68567/72565 matches (94.5%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3998:
  UNIX timestamp: 1759174071.5308878
  EST time: 2025-09-29 15:27:51.530887842-04:00
  Corresponding EmotiBit timestamp: 1142344.409
Successfully created Date and Time columns for all 72565 rows (EST timezone)
Duration: 2910.68 seconds

Example rows around sync point (row 3998):
  Row 3996: EmotiBit=1142344.328, diff=-0.081s, Time=15:27:51.449
  Row 3997: EmotiBit=1142344.369, diff=-0.040s, Time=15:27:51.490
  Row 3998: EmotiBit=1142344.409, diff=+0.000s, Time=15:27:51.530 <- SYNC POINT
  Row 3999: EmotiBit=1142344.449, diff=+0.040s, Time=15:27:51.570
  Row 4000: EmotiBit=1142344.489, diff=+0.080s, Time=15:27:51.610

Applying forward fill to missing values...
Missing values before ffill: 444193
Missing values after ffill: 12160
Filled 432033 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 72565 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 1142184.041 to 1145094.718
Duration: 2910.68 seconds
Participant ID: 52
Condition: Trust Priming
Video condition: 2

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 68567/72565 (94.5% complete)
DataSyncMarker_channel_1: 68567/72565 (94.5% complete)
Reliability: 68567/72565 (94.5% complete)
PPG_GRN_C: 72565/72565 (100.0% complete)
PPG_RED_C: 72565/72565 (100.0% complete)
PPG_IR_C: 72565/72565 (100.0% complete)
EDA_C: 72564/72565 (100.0% complete)
HR_C: 72546/72565 (100.0% complete)
TEMP_C: 72563/72565 (100.0% complete)
THERM_C: 72562/72565 (100.0% complete)
Neon Companion_Neon Gaze_x: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_y: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 72565/72565 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 72565/72565 (100.0% complete)
PPG_GRN_IS: 72565/72565 (100.0% complete)
PPG_RED_IS: 72565/72565 (100.0% complete)
PPG_IR_IS: 72565/72565 (100.0% complete)
EDA_IS: 72564/72565 (100.0% complete)
HR_IS: 72428/72565 (99.8% complete)
TEMP_IS: 72565/72565 (100.0% complete)
THERM_IS: 72562/72565 (100.0% complete)

============================================================
Processing ID 53  (53_C.xdf)
  condition=Distrust Priming  video_condition=2
============================================================

Stream 8: Calculated effective sampling rate 137.0344 Hz is different from specified rate 200.0000 Hz.

Exported stream 1 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (23687, 1)
  Sample count: 23687

Exported stream 2 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78725, 1)
  Sample count: 78725

Exported stream 3 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (47373, 1)
  Sample count: 47373

Exported stream 4 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2833, 1)
  Sample count: 2833

Exported stream 5 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (78563, 1)
  Sample count: 78563

Exported stream 6 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (78562, 1)
  Sample count: 78562

Exported stream 7 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78725, 1)
  Sample count: 78725

Exported stream 8 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23685, 1)
  Sample count: 23685

Exported stream 9 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (47366, 1)
  Sample count: 47366

Exported stream 10 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78725, 1)
  Sample count: 78725

Exported stream 11 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (78563, 1)
  Sample count: 78563

Exported stream 12 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2843, 1)
  Sample count: 2843

Exported stream 13 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (23687, 1)
  Sample count: 23687

Exported stream 14 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23684, 1)
  Sample count: 23684

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (441514, 16)
  Sample count: 441514
  First timestamp: 1148914.5052150278

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/53_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (78725 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 1149222.312 to 1151903.015
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=1149222.312, value=1.0
    t=1149834.537, value=2.0
    t=1150388.782, value=1.0
    t=1150999.629, value=2.0
    t=1151281.802, value=1.0
    t=1151903.015, value=2.0
  Added Reliability column using video condition 2: ('LL', 'M', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 74190/78725 matches (94.2%)
  DataSyncMarker value distribution:
    1.0: 45975 rows (58.4%)
    2.0: 28215 rows (35.8%)
Base PPG timestamps: 1149040.398 to 1152198.377

Processing EDA_I.csv...
  File timestamps: 1149040.318 to 1152198.441
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 50302/78725 matches (63.9%)

Processing THERM_I.csv...
  File timestamps: 1149040.407 to 1152198.438
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 25128/78725 matches (31.9%)

Processing PPG_RED_I.csv...
  File timestamps: 1149040.262 to 1152198.487
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 78725/78725 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 1149042.369 to 1152195.271
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2993/78725 matches (3.8%)

Processing TEMP1_I.csv...
  File timestamps: 1149040.267 to 1152198.297
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 25140/78725 matches (31.9%)

Processing PPG_IR_C.csv...
  File timestamps: 1149040.397 to 1152198.375
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 78725/78725 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 1149040.182 to 1152198.367
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 78725/78725 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 1149040.262 to 1152198.487
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 78725/78725 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 1149040.430 to 1152198.414
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 25126/78725 matches (31.9%)

Processing EDA_C.csv...
  File timestamps: 1149040.407 to 1152198.417
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 50262/78725 matches (63.8%)

Processing HR_I.csv...
  File timestamps: 1149047.234 to 1152193.121
  Added 1 column(s) from HR_I.csv
    HR_I_value: 3028/78725 matches (3.8%)

Processing TEMP1_C.csv...
  File timestamps: 1149040.493 to 1152198.510
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 25143/78725 matches (31.9%)

Processing PPG_RED_C.csv...
  File timestamps: 1149040.398 to 1152198.376
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 78725/78725 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 1148914.505 to 1152136.418
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 80548 samples (16 channels)
    x: 80548/80548 valid aggregated values (100.0%)
    y: 80548/80548 valid aggregated values (100.0%)
    PupilDiameter_left: 80548/80548 valid aggregated values (100.0%)
    EyeballCenterX_left: 80548/80548 valid aggregated values (100.0%)
    EyeballCenterY_left: 80548/80548 valid aggregated values (100.0%)
    EyeballCenterZ_left: 80548/80548 valid aggregated values (100.0%)
    OpticalAxisX_left: 80548/80548 valid aggregated values (100.0%)
    OpticalAxisY_left: 80548/80548 valid aggregated values (100.0%)
    OpticalAxisZ_left: 80548/80548 valid aggregated values (100.0%)
    PupilDiameter_right: 80548/80548 valid aggregated values (100.0%)
    EyeballCenterX_right: 80548/80548 valid aggregated values (100.0%)
    EyeballCenterY_right: 80548/80548 valid aggregated values (100.0%)
    EyeballCenterZ_right: 80548/80548 valid aggregated values (100.0%)
    OpticalAxisX_right: 80548/80548 valid aggregated values (100.0%)
    OpticalAxisY_right: 80548/80548 valid aggregated values (100.0%)
    OpticalAxisZ_right: 80548/80548 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_y: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 77180/78725 matches (98.0%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 77180/78725 matches (98.0%)

Processing temp_datasync_remaining.csv...
  File timestamps: 1149222.312 to 1151903.015
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 74190/78725 matches (94.2%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 4535:
  UNIX timestamp: 1759180949.437554
  EST time: 2025-09-29 17:22:29.437553883-04:00
  Corresponding EmotiBit timestamp: 1149222.318
Successfully created Date and Time columns for all 78725 rows (EST timezone)
Duration: 3157.98 seconds

Example rows around sync point (row 4535):
  Row 4533: EmotiBit=1149222.238, diff=-0.080s, Time=17:22:29.357
  Row 4534: EmotiBit=1149222.278, diff=-0.040s, Time=17:22:29.397
  Row 4535: EmotiBit=1149222.318, diff=+0.000s, Time=17:22:29.437 <- SYNC POINT
  Row 4536: EmotiBit=1149222.358, diff=+0.040s, Time=17:22:29.477
  Row 4537: EmotiBit=1149222.398, diff=+0.080s, Time=17:22:29.517

Applying forward fill to missing values...
Missing values before ffill: 461003
Missing values after ffill: 13827
Filled 447176 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 78725 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 1149040.398 to 1152198.377
Duration: 3157.98 seconds
Participant ID: 53
Condition: Distrust Priming
Video condition: 2

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 74190/78725 (94.2% complete)
DataSyncMarker_channel_1: 74190/78725 (94.2% complete)
Reliability: 74190/78725 (94.2% complete)
PPG_GRN_C: 78725/78725 (100.0% complete)
PPG_RED_C: 78725/78725 (100.0% complete)
PPG_IR_C: 78725/78725 (100.0% complete)
EDA_C: 78725/78725 (100.0% complete)
HR_C: 78676/78725 (99.9% complete)
TEMP_C: 78723/78725 (100.0% complete)
THERM_C: 78724/78725 (100.0% complete)
Neon Companion_Neon Gaze_x: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_y: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 78725/78725 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 78725/78725 (100.0% complete)
PPG_GRN_IS: 78725/78725 (100.0% complete)
PPG_RED_IS: 78725/78725 (100.0% complete)
PPG_IR_IS: 78725/78725 (100.0% complete)
EDA_IS: 78725/78725 (100.0% complete)
HR_IS: 78555/78725 (99.8% complete)
TEMP_IS: 78725/78725 (100.0% complete)
THERM_IS: 78725/78725 (100.0% complete)

============================================================
Processing ID 54  (54_C.xdf)
  condition=Trust Priming  video_condition=3
============================================================

Stream 15: Calculated effective sampling rate 149.2421 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78015, 1)
  Sample count: 78015

Exported stream 1 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78015, 1)
  Sample count: 78015

Exported stream 2 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23470, 1)
  Sample count: 23470

Exported stream 3 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1699, 1)
  Sample count: 1699

Exported stream 4 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (77864, 1)
  Sample count: 77864

Exported stream 6 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (23471, 1)
  Sample count: 23471

Exported stream 7 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23470, 1)
  Sample count: 23470

Exported stream 8 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (77864, 1)
  Sample count: 77864

Exported stream 9 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (77864, 1)
  Sample count: 77864

Exported stream 10 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2192, 1)
  Sample count: 2192

Exported stream 11 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78015, 1)
  Sample count: 78015

Exported stream 12 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (46941, 1)
  Sample count: 46941

Exported stream 13 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (23472, 1)
  Sample count: 23472

Exported stream 14 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (46943, 1)
  Sample count: 46943

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (444279, 16)
  Sample count: 444279
  First timestamp: 1210628.9571429463

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/54_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (78015 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 1210938.851 to 1213598.687
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=1210938.851, value=1.0
    t=1211555.433, value=2.0
    t=1212045.833, value=1.0
    t=1212657.748, value=2.0
    t=1212992.921, value=1.0
    t=1213598.687, value=2.0
  Added Reliability column using video condition 3: ('HH', 'LL', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 72850/78015 matches (93.4%)
  DataSyncMarker value distribution:
    1.0: 45728 rows (58.6%)
    2.0: 27122 rows (34.8%)
Base PPG timestamps: 1210731.695 to 1213861.046

Processing EDA_I.csv...
  File timestamps: 1210731.590 to 1213860.977
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 49763/78015 matches (63.8%)

Processing THERM_I.csv...
  File timestamps: 1210731.712 to 1213861.040
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 24912/78015 matches (31.9%)

Processing PPG_RED_I.csv...
  File timestamps: 1210731.447 to 1213860.948
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 78013/78015 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 1210741.349 to 1213860.171
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2330/78015 matches (3.0%)

Processing TEMP1_I.csv...
  File timestamps: 1210731.705 to 1213860.899
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 24906/78015 matches (31.9%)

Processing PPG_IR_C.csv...
  File timestamps: 1210731.694 to 1213861.045
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 78015/78015 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 1210731.448 to 1213860.948
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 78013/78015 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 1210731.447 to 1213860.947
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 78013/78015 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 1210731.678 to 1213861.003
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 24907/78015 matches (31.9%)

Processing EDA_C.csv...
  File timestamps: 1210731.605 to 1213860.975
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 49812/78015 matches (63.8%)

Processing HR_I.csv...
  File timestamps: 1210731.700 to 1213860.104
  Added 1 column(s) from HR_I.csv
    HR_I_value: 1811/78015 matches (2.3%)

Processing TEMP1_C.csv...
  File timestamps: 1210731.670 to 1213860.996
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 24909/78015 matches (31.9%)

Processing PPG_RED_C.csv...
  File timestamps: 1210731.695 to 1213861.045
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 78015/78015 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 1210628.957 to 1213605.852
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 74423 samples (16 channels)
    x: 74423/74423 valid aggregated values (100.0%)
    y: 74423/74423 valid aggregated values (100.0%)
    PupilDiameter_left: 74423/74423 valid aggregated values (100.0%)
    EyeballCenterX_left: 74423/74423 valid aggregated values (100.0%)
    EyeballCenterY_left: 74423/74423 valid aggregated values (100.0%)
    EyeballCenterZ_left: 74423/74423 valid aggregated values (100.0%)
    OpticalAxisX_left: 74423/74423 valid aggregated values (100.0%)
    OpticalAxisY_left: 74423/74423 valid aggregated values (100.0%)
    OpticalAxisZ_left: 74423/74423 valid aggregated values (100.0%)
    PupilDiameter_right: 74423/74423 valid aggregated values (100.0%)
    EyeballCenterX_right: 74423/74423 valid aggregated values (100.0%)
    EyeballCenterY_right: 74423/74423 valid aggregated values (100.0%)
    EyeballCenterZ_right: 74423/74423 valid aggregated values (100.0%)
    OpticalAxisX_right: 74423/74423 valid aggregated values (100.0%)
    OpticalAxisY_right: 74423/74423 valid aggregated values (100.0%)
    OpticalAxisZ_right: 74423/74423 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_y: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 71653/78015 matches (91.8%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 71653/78015 matches (91.8%)

Processing temp_datasync_remaining.csv...
  File timestamps: 1210938.851 to 1213598.687
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 72850/78015 matches (93.4%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 5165:
  UNIX timestamp: 1759242665.9891908
  EST time: 2025-09-30 10:31:05.989190817-04:00
  Corresponding EmotiBit timestamp: 1210938.877
Successfully created Date and Time columns for all 78015 rows (EST timezone)
Duration: 3129.35 seconds

Example rows around sync point (row 5165):
  Row 5163: EmotiBit=1210938.797, diff=-0.080s, Time=10:31:05.909
  Row 5164: EmotiBit=1210938.837, diff=-0.040s, Time=10:31:05.949
  Row 5165: EmotiBit=1210938.877, diff=+0.000s, Time=10:31:05.989 <- SYNC POINT
  Row 5166: EmotiBit=1210938.917, diff=+0.040s, Time=10:31:06.029
  Row 5167: EmotiBit=1210938.957, diff=+0.080s, Time=10:31:06.069

Applying forward fill to missing values...
Missing values before ffill: 538063
Missing values after ffill: 15741
Filled 522322 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 78015 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 1210731.695 to 1213861.046
Duration: 3129.35 seconds
Participant ID: 54
Condition: Trust Priming
Video condition: 3

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 72850/78015 (93.4% complete)
DataSyncMarker_channel_1: 72850/78015 (93.4% complete)
Reliability: 72850/78015 (93.4% complete)
PPG_GRN_C: 78015/78015 (100.0% complete)
PPG_RED_C: 78015/78015 (100.0% complete)
PPG_IR_C: 78015/78015 (100.0% complete)
EDA_C: 78014/78015 (100.0% complete)
HR_C: 77774/78015 (99.7% complete)
TEMP_C: 78012/78015 (100.0% complete)
THERM_C: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_x: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_y: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 78015/78015 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 78015/78015 (100.0% complete)
PPG_GRN_IS: 78015/78015 (100.0% complete)
PPG_RED_IS: 78015/78015 (100.0% complete)
PPG_IR_IS: 78015/78015 (100.0% complete)
EDA_IS: 78014/78015 (100.0% complete)
HR_IS: 78015/78015 (100.0% complete)
TEMP_IS: 78015/78015 (100.0% complete)
THERM_IS: 78015/78015 (100.0% complete)

============================================================
Processing ID 55  (55_C.xdf)
  condition=Trust Priming  video_condition=4
============================================================

Stream 10: Calculated effective sampling rate 149.6890 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (47376, 1)
  Sample count: 47376

Exported stream 1 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78742, 1)
  Sample count: 78742

Exported stream 2 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (78562, 1)
  Sample count: 78562

Exported stream 4 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (78562, 1)
  Sample count: 78562

Exported stream 5 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78742, 1)
  Sample count: 78742

Exported stream 6 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (78562, 1)
  Sample count: 78562

Exported stream 7 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (47373, 1)
  Sample count: 47373

Exported stream 8 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (23686, 1)
  Sample count: 23686

Exported stream 9 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (3472, 1)
  Sample count: 3472

Exported stream 10 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (78742, 1)
  Sample count: 78742

Exported stream 11 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23688, 1)
  Sample count: 23688

Exported stream 12 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (2202, 1)
  Sample count: 2202

Exported stream 13 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23688, 1)
  Sample count: 23688

Exported stream 14 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (23686, 1)
  Sample count: 23686

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (479440, 16)
  Sample count: 479440
  First timestamp: 1218218.0813467586

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/55_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (78742 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 1218565.652 to 1221214.713
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=1218565.652, value=1.0
    t=1219181.298, value=2.0
    t=1219657.337, value=1.0
    t=1220323.921, value=2.0
    t=1220592.059, value=1.0
    t=1221214.713, value=2.0
  Added Reliability column using video condition 4: ('HH', 'M', 'LL')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 72202/78742 matches (91.7%)
  DataSyncMarker value distribution:
    1.0: 47495 rows (60.3%)
    2.0: 24707 rows (31.4%)
Base PPG timestamps: 1218303.358 to 1221461.421

Processing EDA_I.csv...
  File timestamps: 1218303.465 to 1221461.548
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 50271/78742 matches (63.8%)

Processing THERM_I.csv...
  File timestamps: 1218303.533 to 1221461.482
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 25149/78742 matches (31.9%)

Processing PPG_RED_I.csv...
  File timestamps: 1218303.384 to 1221461.534
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 78741/78742 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 1218306.749 to 1221456.853
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2332/78742 matches (3.0%)

Processing TEMP1_I.csv...
  File timestamps: 1218303.526 to 1221461.475
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 25145/78742 matches (31.9%)

Processing PPG_IR_C.csv...
  File timestamps: 1218303.356 to 1221461.420
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 78742/78742 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 1218303.385 to 1221461.534
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 78741/78742 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 1218303.383 to 1221461.533
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 78741/78742 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 1218303.375 to 1221461.368
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 25139/78742 matches (31.9%)

Processing EDA_C.csv...
  File timestamps: 1218303.373 to 1221461.434
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 50283/78742 matches (63.9%)

Processing HR_I.csv...
  File timestamps: 1218303.917 to 1221459.736
  Added 1 column(s) from HR_I.csv
    HR_I_value: 3671/78742 matches (4.7%)

Processing TEMP1_C.csv...
  File timestamps: 1218303.367 to 1221461.361
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 25141/78742 matches (31.9%)

Processing PPG_RED_C.csv...
  File timestamps: 1218303.357 to 1221461.420
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 78742/78742 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 1218218.081 to 1221420.982
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 80073 samples (16 channels)
    x: 80073/80073 valid aggregated values (100.0%)
    y: 80073/80073 valid aggregated values (100.0%)
    PupilDiameter_left: 80073/80073 valid aggregated values (100.0%)
    EyeballCenterX_left: 80073/80073 valid aggregated values (100.0%)
    EyeballCenterY_left: 80073/80073 valid aggregated values (100.0%)
    EyeballCenterZ_left: 80073/80073 valid aggregated values (100.0%)
    OpticalAxisX_left: 80073/80073 valid aggregated values (100.0%)
    OpticalAxisY_left: 80073/80073 valid aggregated values (100.0%)
    OpticalAxisZ_left: 80073/80073 valid aggregated values (100.0%)
    PupilDiameter_right: 80073/80073 valid aggregated values (100.0%)
    EyeballCenterX_right: 80073/80073 valid aggregated values (100.0%)
    EyeballCenterY_right: 80073/80073 valid aggregated values (100.0%)
    EyeballCenterZ_right: 80073/80073 valid aggregated values (100.0%)
    OpticalAxisX_right: 80073/80073 valid aggregated values (100.0%)
    OpticalAxisY_right: 80073/80073 valid aggregated values (100.0%)
    OpticalAxisZ_right: 80073/80073 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_y: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 77733/78742 matches (98.7%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 77733/78742 matches (98.7%)

Processing temp_datasync_remaining.csv...
  File timestamps: 1218565.652 to 1221214.713
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 72202/78742 matches (91.7%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 6540:
  UNIX timestamp: 1759250292.886788
  EST time: 2025-09-30 12:38:12.886787891-04:00
  Corresponding EmotiBit timestamp: 1218565.657
Successfully created Date and Time columns for all 78742 rows (EST timezone)
Duration: 3158.06 seconds

Example rows around sync point (row 6540):
  Row 6538: EmotiBit=1218565.577, diff=-0.080s, Time=12:38:12.806
  Row 6539: EmotiBit=1218565.617, diff=-0.040s, Time=12:38:12.846
  Row 6540: EmotiBit=1218565.657, diff=+0.000s, Time=12:38:12.886 <- SYNC POINT
  Row 6541: EmotiBit=1218565.697, diff=+0.040s, Time=12:38:12.926
  Row 6542: EmotiBit=1218565.737, diff=+0.080s, Time=12:38:12.966

Applying forward fill to missing values...
Missing values before ffill: 458572
Missing values after ffill: 19733
Filled 438839 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 78742 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 1218303.358 to 1221461.421
Duration: 3158.06 seconds
Participant ID: 55
Condition: Trust Priming
Video condition: 4

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 72202/78742 (91.7% complete)
DataSyncMarker_channel_1: 72202/78742 (91.7% complete)
Reliability: 72202/78742 (91.7% complete)
PPG_GRN_C: 78742/78742 (100.0% complete)
PPG_RED_C: 78742/78742 (100.0% complete)
PPG_IR_C: 78742/78742 (100.0% complete)
EDA_C: 78742/78742 (100.0% complete)
HR_C: 78657/78742 (99.9% complete)
TEMP_C: 78742/78742 (100.0% complete)
THERM_C: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_x: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_y: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 78742/78742 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 78742/78742 (100.0% complete)
PPG_GRN_IS: 78741/78742 (100.0% complete)
PPG_RED_IS: 78741/78742 (100.0% complete)
PPG_IR_IS: 78741/78742 (100.0% complete)
EDA_IS: 78739/78742 (100.0% complete)
HR_IS: 78728/78742 (100.0% complete)
TEMP_IS: 78738/78742 (100.0% complete)
THERM_IS: 78738/78742 (100.0% complete)

============================================================
Processing ID 56  (56_C.xdf)
  condition=Trust Priming  video_condition=3
============================================================

Stream 13: Calculated effective sampling rate 146.4879 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (65583, 1)
  Sample count: 65583

Exported stream 1 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (19770, 1)
  Sample count: 19770

Exported stream 2 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (65708, 1)
  Sample count: 65708

Exported stream 3 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (65581, 1)
  Sample count: 65581

Exported stream 4 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (65581, 1)
  Sample count: 65581

Exported stream 5 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (39540, 1)
  Sample count: 39540

Exported stream 6 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (19770, 1)
  Sample count: 19770

Exported stream 7 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (65708, 1)
  Sample count: 65708

Exported stream 8 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (19770, 1)
  Sample count: 19770

Exported stream 9 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (39538, 1)
  Sample count: 39538

Exported stream 10 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2471, 1)
  Sample count: 2471

Exported stream 12 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (1867, 1)
  Sample count: 1867

Exported stream 13 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (19770, 1)
  Sample count: 19770

Exported stream 14 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (65708, 1)
  Sample count: 65708

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (388009, 16)
  Sample count: 388009
  First timestamp: 1310833.1807854115

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/56_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (65708 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 1311060.979 to 1313373.826
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=1311060.979, value=1.0
    t=1311678.324, value=2.0
    t=1311947.516, value=1.0
    t=1312558.725, value=2.0
    t=1312762.860, value=1.0
    t=1313373.826, value=2.0
  Added Reliability column using video condition 3: ('HH', 'LL', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 62493/65708 matches (95.1%)
  DataSyncMarker value distribution:
    1.0: 45858 rows (69.8%)
    2.0: 16635 rows (25.3%)
Base PPG timestamps: 1310932.026 to 1313567.740

Processing EDA_I.csv...
  File timestamps: 1310932.124 to 1313567.660
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 41954/65708 matches (63.8%)

Processing THERM_I.csv...
  File timestamps: 1310931.992 to 1313567.595
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 20981/65708 matches (31.9%)

Processing PPG_RED_I.csv...
  File timestamps: 1310931.907 to 1313567.683
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 65707/65708 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 1310932.868 to 1313560.014
  Added 1 column(s) from HR_C.csv
    HR_C_value: 1983/65708 matches (3.0%)

Processing TEMP1_I.csv...
  File timestamps: 1310931.985 to 1313567.587
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 20979/65708 matches (31.9%)

Processing PPG_IR_C.csv...
  File timestamps: 1310932.025 to 1313567.739
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 65708/65708 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 1310931.988 to 1313567.684
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 65707/65708 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 1310931.987 to 1313567.683
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 65707/65708 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 1310932.040 to 1313567.633
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 20981/65708 matches (31.9%)

Processing EDA_C.csv...
  File timestamps: 1310932.039 to 1313567.699
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 41960/65708 matches (63.9%)

Processing HR_I.csv...
  File timestamps: 1310936.801 to 1313566.162
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2626/65708 matches (4.0%)

Processing TEMP1_C.csv...
  File timestamps: 1310932.033 to 1313567.626
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 20985/65708 matches (31.9%)

Processing PPG_RED_C.csv...
  File timestamps: 1310932.025 to 1313567.740
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 65708/65708 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 1310833.181 to 1313481.917
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 66219 samples (16 channels)
    x: 66219/66219 valid aggregated values (100.0%)
    y: 66219/66219 valid aggregated values (100.0%)
    PupilDiameter_left: 66219/66219 valid aggregated values (100.0%)
    EyeballCenterX_left: 66219/66219 valid aggregated values (100.0%)
    EyeballCenterY_left: 66219/66219 valid aggregated values (100.0%)
    EyeballCenterZ_left: 66219/66219 valid aggregated values (100.0%)
    OpticalAxisX_left: 66219/66219 valid aggregated values (100.0%)
    OpticalAxisY_left: 66219/66219 valid aggregated values (100.0%)
    OpticalAxisZ_left: 66219/66219 valid aggregated values (100.0%)
    PupilDiameter_right: 66219/66219 valid aggregated values (100.0%)
    EyeballCenterX_right: 66219/66219 valid aggregated values (100.0%)
    EyeballCenterY_right: 66219/66219 valid aggregated values (100.0%)
    EyeballCenterZ_right: 66219/66219 valid aggregated values (100.0%)
    OpticalAxisX_right: 66219/66219 valid aggregated values (100.0%)
    OpticalAxisY_right: 66219/66219 valid aggregated values (100.0%)
    OpticalAxisZ_right: 66219/66219 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_y: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 63568/65708 matches (96.7%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 63568/65708 matches (96.7%)

Processing temp_datasync_remaining.csv...
  File timestamps: 1311060.979 to 1313373.826
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 62493/65708 matches (95.1%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3215:
  UNIX timestamp: 1759342787.90177
  EST time: 2025-10-01 14:19:47.901770115-04:00
  Corresponding EmotiBit timestamp: 1311060.989
Successfully created Date and Time columns for all 65708 rows (EST timezone)
Duration: 2635.71 seconds

Example rows around sync point (row 3215):
  Row 3213: EmotiBit=1311060.909, diff=-0.080s, Time=14:19:47.821
  Row 3214: EmotiBit=1311060.949, diff=-0.040s, Time=14:19:47.861
  Row 3215: EmotiBit=1311060.989, diff=+0.000s, Time=14:19:47.901 <- SYNC POINT
  Row 3216: EmotiBit=1311061.029, diff=+0.040s, Time=14:19:47.941
  Row 3217: EmotiBit=1311061.070, diff=+0.081s, Time=14:19:47.982

Applying forward fill to missing values...
Missing values before ffill: 397103
Missing values after ffill: 9791
Filled 387312 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 65708 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 1310932.026 to 1313567.740
Duration: 2635.71 seconds
Participant ID: 56
Condition: Trust Priming
Video condition: 3

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 62493/65708 (95.1% complete)
DataSyncMarker_channel_1: 62493/65708 (95.1% complete)
Reliability: 62493/65708 (95.1% complete)
PPG_GRN_C: 65708/65708 (100.0% complete)
PPG_RED_C: 65708/65708 (100.0% complete)
PPG_IR_C: 65708/65708 (100.0% complete)
EDA_C: 65708/65708 (100.0% complete)
HR_C: 65687/65708 (100.0% complete)
TEMP_C: 65708/65708 (100.0% complete)
THERM_C: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_x: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_y: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 65708/65708 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 65708/65708 (100.0% complete)
PPG_GRN_IS: 65708/65708 (100.0% complete)
PPG_RED_IS: 65708/65708 (100.0% complete)
PPG_IR_IS: 65708/65708 (100.0% complete)
EDA_IS: 65706/65708 (100.0% complete)
HR_IS: 65589/65708 (99.8% complete)
TEMP_IS: 65706/65708 (100.0% complete)
THERM_IS: 65706/65708 (100.0% complete)

============================================================
Processing ID 57  (57_C.xdf)
  condition=Distrust Priming  video_condition=5
============================================================

Stream 4: Calculated effective sampling rate 133.2985 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (76795, 1)
  Sample count: 76795

Exported stream 1 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (76640, 1)
  Sample count: 76640

Exported stream 2 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (76795, 1)
  Sample count: 76795

Exported stream 3 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (76795, 1)
  Sample count: 76795

Exported stream 4 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (46208, 1)
  Sample count: 46208

Exported stream 5 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (23105, 1)
  Sample count: 23105

Exported stream 6 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (46206, 1)
  Sample count: 46206

Exported stream 7 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23103, 1)
  Sample count: 23103

Exported stream 8 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (23103, 1)
  Sample count: 23103

Exported stream 10 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2133, 1)
  Sample count: 2133

Exported stream 11 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (1689, 1)
  Sample count: 1689

Exported stream 12 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (76640, 1)
  Sample count: 76640

Exported stream 13 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (76640, 1)
  Sample count: 76640

Exported stream 14 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (23105, 1)
  Sample count: 23105

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 15 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (415163, 16)
  Sample count: 415163
  First timestamp: 1317994.3640890983

Exported stream 16 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/57_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (76795 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 1318219.860 to 1320829.265
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=1318219.860, value=1.0
    t=1318831.083, value=2.0
    t=1319305.416, value=1.0
    t=1319913.487, value=2.0
    t=1320211.446, value=1.0
    t=1320829.265, value=2.0
  Added Reliability column using video condition 5: ('M', 'LL', 'HH')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 73019/76795 matches (95.1%)
  DataSyncMarker value distribution:
    1.0: 45800 rows (59.6%)
    2.0: 27219 rows (35.4%)
Base PPG timestamps: 1318068.411 to 1321148.798

Processing EDA_I.csv...
  File timestamps: 1318068.509 to 1321148.890
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 49025/76795 matches (63.8%)

Processing THERM_I.csv...
  File timestamps: 1318068.605 to 1321148.863
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 24519/76795 matches (31.9%)

Processing PPG_RED_I.csv...
  File timestamps: 1318068.357 to 1321148.878
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 76795/76795 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 1318073.156 to 1321148.363
  Added 1 column(s) from HR_C.csv
    HR_C_value: 1792/76795 matches (2.3%)

Processing TEMP1_I.csv...
  File timestamps: 1318068.597 to 1321148.855
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 24524/76795 matches (31.9%)

Processing PPG_IR_C.csv...
  File timestamps: 1318068.409 to 1321148.797
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 76795/76795 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 1318068.357 to 1321148.879
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 76795/76795 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 1318068.356 to 1321148.878
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 76795/76795 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 1318068.552 to 1321148.721
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 24525/76795 matches (31.9%)

Processing EDA_C.csv...
  File timestamps: 1318068.551 to 1321148.787
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 49078/76795 matches (63.9%)

Processing HR_I.csv...
  File timestamps: 1318072.606 to 1321148.313
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2252/76795 matches (2.9%)

Processing TEMP1_C.csv...
  File timestamps: 1318068.544 to 1321148.714
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 24538/76795 matches (32.0%)

Processing PPG_RED_C.csv...
  File timestamps: 1318068.410 to 1321148.797
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 76795/76795 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 1317994.364 to 1321108.893
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 77864 samples (16 channels)
    x: 77864/77864 valid aggregated values (100.0%)
    y: 77864/77864 valid aggregated values (100.0%)
    PupilDiameter_left: 77864/77864 valid aggregated values (100.0%)
    EyeballCenterX_left: 77864/77864 valid aggregated values (100.0%)
    EyeballCenterY_left: 77864/77864 valid aggregated values (100.0%)
    EyeballCenterZ_left: 77864/77864 valid aggregated values (100.0%)
    OpticalAxisX_left: 77864/77864 valid aggregated values (100.0%)
    OpticalAxisY_left: 77864/77864 valid aggregated values (100.0%)
    OpticalAxisZ_left: 77864/77864 valid aggregated values (100.0%)
    PupilDiameter_right: 77864/77864 valid aggregated values (100.0%)
    EyeballCenterX_right: 77864/77864 valid aggregated values (100.0%)
    EyeballCenterY_right: 77864/77864 valid aggregated values (100.0%)
    EyeballCenterZ_right: 77864/77864 valid aggregated values (100.0%)
    OpticalAxisX_right: 77864/77864 valid aggregated values (100.0%)
    OpticalAxisY_right: 77864/77864 valid aggregated values (100.0%)
    OpticalAxisZ_right: 77864/77864 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_y: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 75800/76795 matches (98.7%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 75800/76795 matches (98.7%)

Processing temp_datasync_remaining.csv...
  File timestamps: 1318219.860 to 1320829.265
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 73019/76795 matches (95.1%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3776:
  UNIX timestamp: 1759349946.764927
  EST time: 2025-10-01 16:19:06.764926910-04:00
  Corresponding EmotiBit timestamp: 1318219.875
Successfully created Date and Time columns for all 76795 rows (EST timezone)
Duration: 3080.39 seconds

Example rows around sync point (row 3776):
  Row 3774: EmotiBit=1318219.795, diff=-0.080s, Time=16:19:06.684
  Row 3775: EmotiBit=1318219.835, diff=-0.040s, Time=16:19:06.724
  Row 3776: EmotiBit=1318219.875, diff=+0.000s, Time=16:19:06.764 <- SYNC POINT
  Row 3777: EmotiBit=1318219.915, diff=+0.040s, Time=16:19:06.804
  Row 3778: EmotiBit=1318219.955, diff=+0.080s, Time=16:19:06.844

Applying forward fill to missing values...
Missing values before ffill: 441355
Missing values after ffill: 11572
Filled 429783 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 76795 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 1318068.411 to 1321148.798
Duration: 3080.39 seconds
Participant ID: 57
Condition: Distrust Priming
Video condition: 5

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 73019/76795 (95.1% complete)
DataSyncMarker_channel_1: 73019/76795 (95.1% complete)
Reliability: 73019/76795 (95.1% complete)
PPG_GRN_C: 76795/76795 (100.0% complete)
PPG_RED_C: 76795/76795 (100.0% complete)
PPG_IR_C: 76795/76795 (100.0% complete)
EDA_C: 76792/76795 (100.0% complete)
HR_C: 76677/76795 (99.8% complete)
TEMP_C: 76792/76795 (100.0% complete)
THERM_C: 76792/76795 (100.0% complete)
Neon Companion_Neon Gaze_x: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_y: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 76795/76795 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 76795/76795 (100.0% complete)
PPG_GRN_IS: 76795/76795 (100.0% complete)
PPG_RED_IS: 76795/76795 (100.0% complete)
PPG_IR_IS: 76795/76795 (100.0% complete)
EDA_IS: 76793/76795 (100.0% complete)
HR_IS: 76690/76795 (99.9% complete)
TEMP_IS: 76790/76795 (100.0% complete)
THERM_IS: 76790/76795 (100.0% complete)

============================================================
Processing ID 58  (58_C.xdf)
  condition=Distrust Priming  video_condition=1
============================================================

Stream 9: Calculated effective sampling rate 142.9372 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73513, 1)
  Sample count: 73513

Exported stream 1 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (73363, 1)
  Sample count: 73363

Exported stream 2 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (2171, 1)
  Sample count: 2171

Exported stream 3 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73513, 1)
  Sample count: 73513

Exported stream 4 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (22117, 1)
  Sample count: 22117

Exported stream 5 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (1996, 1)
  Sample count: 1996

Exported stream 6 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (73513, 1)
  Sample count: 73513

Exported stream 7 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (22113, 1)
  Sample count: 22113

Exported stream 8 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (22113, 1)
  Sample count: 22113

Exported stream 9 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (73363, 1)
  Sample count: 73363

Exported stream 10 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (73363, 1)
  Sample count: 73363

Exported stream 11 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (22117, 1)
  Sample count: 22117

Exported stream 12 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (44232, 1)
  Sample count: 44232

Exported stream 13 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (44232, 1)
  Sample count: 44232

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (426186, 16)
  Sample count: 426186
  First timestamp: 1383038.5202621717

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/58_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (73513 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 1383315.304 to 1385802.505
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=1383315.304, value=1.0
    t=1383928.973, value=2.0
    t=1384291.955, value=1.0
    t=1384909.410, value=2.0
    t=1385191.661, value=1.0
    t=1385802.505, value=2.0
  Added Reliability column using video condition 1: ('LL', 'HH', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 69598/73513 matches (94.7%)
  DataSyncMarker value distribution:
    1.0: 45923 rows (62.5%)
    2.0: 23675 rows (32.2%)
Base PPG timestamps: 1383158.294 to 1386106.825

Processing EDA_I.csv...
  File timestamps: 1383158.373 to 1386106.917
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 47084/73513 matches (64.0%)

Processing THERM_I.csv...
  File timestamps: 1383158.367 to 1386106.896
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 23469/73513 matches (31.9%)

Processing PPG_RED_I.csv...
  File timestamps: 1383158.244 to 1386106.898
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 73513/73513 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 1383158.473 to 1386104.235
  Added 1 column(s) from HR_C.csv
    HR_C_value: 2134/73513 matches (2.9%)

Processing TEMP1_I.csv...
  File timestamps: 1383158.359 to 1386106.889
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 23474/73513 matches (31.9%)

Processing PPG_IR_C.csv...
  File timestamps: 1383158.293 to 1386106.824
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 73513/73513 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 1383158.245 to 1386106.899
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 73513/73513 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 1383158.244 to 1386106.898
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 73513/73513 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 1383158.433 to 1386106.418
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 23467/73513 matches (31.9%)

Processing EDA_C.csv...
  File timestamps: 1383158.366 to 1386106.817
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 46934/73513 matches (63.8%)

Processing HR_I.csv...
  File timestamps: 1383162.855 to 1386106.352
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2325/73513 matches (3.2%)

Processing TEMP1_C.csv...
  File timestamps: 1383158.426 to 1386106.411
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 23467/73513 matches (31.9%)

Processing PPG_RED_C.csv...
  File timestamps: 1383158.294 to 1386106.825
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 73513/73513 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 1383038.520 to 1386020.144
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 74541 samples (16 channels)
    x: 74541/74541 valid aggregated values (100.0%)
    y: 74541/74541 valid aggregated values (100.0%)
    PupilDiameter_left: 74541/74541 valid aggregated values (100.0%)
    EyeballCenterX_left: 74541/74541 valid aggregated values (100.0%)
    EyeballCenterY_left: 74541/74541 valid aggregated values (100.0%)
    EyeballCenterZ_left: 74541/74541 valid aggregated values (100.0%)
    OpticalAxisX_left: 74541/74541 valid aggregated values (100.0%)
    OpticalAxisY_left: 74541/74541 valid aggregated values (100.0%)
    OpticalAxisZ_left: 74541/74541 valid aggregated values (100.0%)
    PupilDiameter_right: 74541/74541 valid aggregated values (100.0%)
    EyeballCenterX_right: 74541/74541 valid aggregated values (100.0%)
    EyeballCenterY_right: 74541/74541 valid aggregated values (100.0%)
    EyeballCenterZ_right: 74541/74541 valid aggregated values (100.0%)
    OpticalAxisX_right: 74541/74541 valid aggregated values (100.0%)
    OpticalAxisY_right: 74541/74541 valid aggregated values (100.0%)
    OpticalAxisZ_right: 74541/74541 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_y: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 71351/73513 matches (97.1%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 71351/73513 matches (97.1%)

Processing temp_datasync_remaining.csv...
  File timestamps: 1383315.304 to 1385802.505
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 69598/73513 matches (94.7%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3915:
  UNIX timestamp: 1759415041.917237
  EST time: 2025-10-02 10:24:01.917237043-04:00
  Corresponding EmotiBit timestamp: 1383315.323
Successfully created Date and Time columns for all 73513 rows (EST timezone)
Duration: 2948.53 seconds

Example rows around sync point (row 3915):
  Row 3913: EmotiBit=1383315.243, diff=-0.080s, Time=10:24:01.837
  Row 3914: EmotiBit=1383315.283, diff=-0.040s, Time=10:24:01.877
  Row 3915: EmotiBit=1383315.323, diff=+0.000s, Time=10:24:01.917 <- SYNC POINT
  Row 3916: EmotiBit=1383315.363, diff=+0.040s, Time=10:24:01.957
  Row 3917: EmotiBit=1383315.403, diff=+0.080s, Time=10:24:01.997

Applying forward fill to missing values...
Missing values before ffill: 442087
Missing values after ffill: 11877
Filled 430210 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 73513 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 1383158.294 to 1386106.825
Duration: 2948.53 seconds
Participant ID: 58
Condition: Distrust Priming
Video condition: 1

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 69598/73513 (94.7% complete)
DataSyncMarker_channel_1: 69598/73513 (94.7% complete)
Reliability: 69598/73513 (94.7% complete)
PPG_GRN_C: 73513/73513 (100.0% complete)
PPG_RED_C: 73513/73513 (100.0% complete)
PPG_IR_C: 73513/73513 (100.0% complete)
EDA_C: 73511/73513 (100.0% complete)
HR_C: 73509/73513 (100.0% complete)
TEMP_C: 73510/73513 (100.0% complete)
THERM_C: 73510/73513 (100.0% complete)
Neon Companion_Neon Gaze_x: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_y: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 73513/73513 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 73513/73513 (100.0% complete)
PPG_GRN_IS: 73513/73513 (100.0% complete)
PPG_RED_IS: 73513/73513 (100.0% complete)
PPG_IR_IS: 73513/73513 (100.0% complete)
EDA_IS: 73511/73513 (100.0% complete)
HR_IS: 73399/73513 (99.8% complete)
TEMP_IS: 73511/73513 (100.0% complete)
THERM_IS: 73511/73513 (100.0% complete)

============================================================
Processing ID 60  (60_C.xdf)
  condition=Distrust Priming  video_condition=3
============================================================

Stream 2: Calculated effective sampling rate 152.6520 Hz is different from specified rate 200.0000 Hz.

Exported stream 0 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/PPG_RED_I.csv
  Source ID: MD-V6-0000405
  Data shape: (67162, 1)
  Sample count: 67162

Exported stream 1 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/THERM_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20244, 1)
  Sample count: 20244

Exported stream 2 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/PPG_IR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (67286, 1)
  Sample count: 67286

Exported stream 3 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/HR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (1901, 1)
  Sample count: 1901

Exported stream 4 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/EDA_C.csv
  Source ID: MD-V5-0001023
  Data shape: (40487, 1)
  Sample count: 40487

Exported stream 6 (THERM) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/THERM_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20244, 1)
  Sample count: 20244

Exported stream 7 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/PPG_GRN_C.csv
  Source ID: MD-V5-0001023
  Data shape: (67286, 1)
  Sample count: 67286

Exported stream 8 (PPG_IR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/PPG_IR_I.csv
  Source ID: MD-V6-0000405
  Data shape: (67162, 1)
  Sample count: 67162

Exported stream 9 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/TEMP1_I.csv
  Source ID: MD-V6-0000405
  Data shape: (20243, 1)
  Sample count: 20243

Exported stream 10 (TEMP1) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/TEMP1_C.csv
  Source ID: MD-V5-0001023
  Data shape: (20244, 1)
  Sample count: 20244

Exported stream 11 (EDA) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/EDA_I.csv
  Source ID: MD-V6-0000405
  Data shape: (40486, 1)
  Sample count: 40486

Exported stream 12 (PPG_GRN) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/PPG_GRN_I.csv
  Source ID: MD-V6-0000405
  Data shape: (67162, 1)
  Sample count: 67162

Exported stream 13 (HR) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/HR_C.csv
  Source ID: MD-V5-0001023
  Data shape: (1864, 1)
  Sample count: 1864

Exported stream 14 (PPG_RED) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/PPG_RED_C.csv
  Source ID: MD-V5-0001023
  Data shape: (67286, 1)
  Sample count: 67286

Exported stream 15 (DataSyncMarker) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/DataSyncMarker.csv
  Source ID: 12345
  Data shape: (6, 2)
  Sample count: 6

Exported Neon stream with 16 channels: x, y, PupilDiameter_left, EyeballCenterX_left, EyeballCenterY_left, EyeballCenterZ_left, OpticalAxisX_left, OpticalAxisY_left, OpticalAxisZ_left, PupilDiameter_right, EyeballCenterX_right, EyeballCenterY_right, EyeballCenterZ_right, OpticalAxisX_right, OpticalAxisY_right, OpticalAxisZ_right
Exported stream 16 (Neon Companion_Neon Gaze) to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/Neon Companion_Neon Gaze.csv
  Source ID: b6e958427ed7c562
  Data shape: (418590, 16)
  Sample count: 418590
  First timestamp: 1469668.2226893962

Successfully exported 16 streams to /Users/debbiehsu/Documents/PythonProjects/GTRI_MHMUAV/Data/60_Data/
Found 16 CSV files to merge
Found PPG_GRN base file: PPG_GRN_C.csv
Base file: PPG_GRN_C.csv (67286 rows)

Processing DataSyncMarker.csv (adding after timestamp)...
  File timestamps: 1469893.576 to 1472221.077
  Expanding DataSyncMarker events into time ranges...
  Original DataSyncMarker events: 6 events
  DataSyncMarker events:
    t=1469893.576, value=1.0
    t=1470511.145, value=2.0
    t=1470756.369, value=1.0
    t=1471367.711, value=2.0
    t=1471609.170, value=1.0
    t=1472221.077, value=2.0
  Added Reliability column using video condition 3: ('HH', 'LL', 'M')
  Added DataSyncMarker column after timestamp
    DataSyncMarker: 63538/67286 matches (94.4%)
  DataSyncMarker value distribution:
    1.0: 45894 rows (68.2%)
    2.0: 17644 rows (26.2%)
Base PPG timestamps: 1469743.260 to 1472442.072

Processing EDA_I.csv...
  File timestamps: 1469743.340 to 1472442.236
  Added 1 column(s) from EDA_I.csv
    EDA_I_value: 42963/67286 matches (63.9%)

Processing THERM_I.csv...
  File timestamps: 1469743.360 to 1472442.224
  Added 1 column(s) from THERM_I.csv
    THERM_I_value: 21478/67286 matches (31.9%)

Processing PPG_RED_I.csv...
  File timestamps: 1469743.246 to 1472442.275
  Added 1 column(s) from PPG_RED_I.csv
    PPG_RED_I_value: 67286/67286 matches (100.0%)

Processing HR_C.csv...
  File timestamps: 1469748.227 to 1472428.053
  Added 1 column(s) from HR_C.csv
    HR_C_value: 1972/67286 matches (2.9%)

Processing TEMP1_I.csv...
  File timestamps: 1469743.314 to 1472442.243
  Added 1 column(s) from TEMP1_I.csv
    TEMP1_I_value: 21479/67286 matches (31.9%)

Processing PPG_IR_C.csv...
  File timestamps: 1469743.259 to 1472442.071
  Added 1 column(s) from PPG_IR_C.csv
    PPG_IR_C_value: 67286/67286 matches (100.0%)

Processing PPG_GRN_I.csv...
  File timestamps: 1469743.246 to 1472442.276
  Added 1 column(s) from PPG_GRN_I.csv
    PPG_GRN_I_value: 67286/67286 matches (100.0%)

Processing PPG_IR_I.csv...
  File timestamps: 1469743.245 to 1472442.275
  Added 1 column(s) from PPG_IR_I.csv
    PPG_IR_I_value: 67286/67286 matches (100.0%)

Processing THERM_C.csv...
  File timestamps: 1469743.276 to 1472442.090
  Added 1 column(s) from THERM_C.csv
    THERM_C_value: 21508/67286 matches (32.0%)

Processing EDA_C.csv...
  File timestamps: 1469743.274 to 1472442.091
  Added 1 column(s) from EDA_C.csv
    EDA_C_value: 42900/67286 matches (63.8%)

Processing HR_I.csv...
  File timestamps: 1469743.493 to 1472427.020
  Added 1 column(s) from HR_I.csv
    HR_I_value: 2026/67286 matches (3.0%)

Processing TEMP1_C.csv...
  File timestamps: 1469743.269 to 1472442.083
  Added 1 column(s) from TEMP1_C.csv
    TEMP1_C_value: 21471/67286 matches (31.9%)

Processing PPG_RED_C.csv...
  File timestamps: 1469743.260 to 1472442.071
  Added 1 column(s) from PPG_RED_C.csv
    PPG_RED_C_value: 67286/67286 matches (100.0%)

Processing Neon Companion_Neon Gaze.csv...
  File timestamps: 1469668.223 to 1472410.336
  Downsampling 16 Neon eye-tracking channels from 200Hz to 25Hz using aggregation...
  After aggregation: 68553 samples (16 channels)
    x: 68553/68553 valid aggregated values (100.0%)
    y: 68553/68553 valid aggregated values (100.0%)
    PupilDiameter_left: 68553/68553 valid aggregated values (100.0%)
    EyeballCenterX_left: 68553/68553 valid aggregated values (100.0%)
    EyeballCenterY_left: 68553/68553 valid aggregated values (100.0%)
    EyeballCenterZ_left: 68553/68553 valid aggregated values (100.0%)
    OpticalAxisX_left: 68553/68553 valid aggregated values (100.0%)
    OpticalAxisY_left: 68553/68553 valid aggregated values (100.0%)
    OpticalAxisZ_left: 68553/68553 valid aggregated values (100.0%)
    PupilDiameter_right: 68553/68553 valid aggregated values (100.0%)
    EyeballCenterX_right: 68553/68553 valid aggregated values (100.0%)
    EyeballCenterY_right: 68553/68553 valid aggregated values (100.0%)
    EyeballCenterZ_right: 68553/68553 valid aggregated values (100.0%)
    OpticalAxisX_right: 68553/68553 valid aggregated values (100.0%)
    OpticalAxisY_right: 68553/68553 valid aggregated values (100.0%)
    OpticalAxisZ_right: 68553/68553 valid aggregated values (100.0%)
  Added 16 column(s) from Neon Companion_Neon Gaze.csv
    Neon Companion_Neon Gaze_x: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_y: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_PupilDiameter_left: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_EyeballCenterX_left: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_EyeballCenterY_left: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_EyeballCenterZ_left: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_OpticalAxisX_left: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_OpticalAxisY_left: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_OpticalAxisZ_left: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_PupilDiameter_right: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_EyeballCenterX_right: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_EyeballCenterY_right: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_EyeballCenterZ_right: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_OpticalAxisX_right: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_OpticalAxisY_right: 66494/67286 matches (98.8%)
    Neon Companion_Neon Gaze_OpticalAxisZ_right: 66494/67286 matches (98.8%)

Processing temp_datasync_remaining.csv...
  File timestamps: 1469893.576 to 1472221.077
  Expanding DataSyncMarker_channel_1 events into time ranges...
  Added 1 column(s) from temp_datasync_remaining.csv
    DataSyncMarker_channel_1: 63538/67286 matches (94.4%)

Calculating Date and Time columns using DataSyncMarker and EmotiBit timestamps...
Initial sync point at row 3748:
  UNIX timestamp: 1759501620.114845
  EST time: 2025-10-03 10:27:00.114845037-04:00
  Corresponding EmotiBit timestamp: 1469893.593
Successfully created Date and Time columns for all 67286 rows (EST timezone)
Duration: 2698.81 seconds

Example rows around sync point (row 3748):
  Row 3746: EmotiBit=1469893.513, diff=-0.080s, Time=10:27:00.034
  Row 3747: EmotiBit=1469893.553, diff=-0.040s, Time=10:27:00.074
  Row 3748: EmotiBit=1469893.593, diff=+0.000s, Time=10:27:00.114 <- SYNC POINT
  Row 3749: EmotiBit=1469893.633, diff=+0.040s, Time=10:27:00.154
  Row 3750: EmotiBit=1469893.673, diff=+0.080s, Time=10:27:00.194

Applying forward fill to missing values...
Missing values before ffill: 386407
Missing values after ffill: 11379
Filled 375028 missing values

Renamed 14 columns: {'PPG_GRN_C_value': 'PPG_GRN_C', 'EDA_I_value': 'EDA_IS', 'THERM_I_value': 'THERM_IS', 'PPG_RED_I_value': 'PPG_RED_IS', 'HR_C_value': 'HR_C', 'TEMP1_I_value': 'TEMP_IS', 'PPG_IR_C_value': 'PPG_IR_C', 'PPG_GRN_I_value': 'PPG_GRN_IS', 'PPG_IR_I_value': 'PPG_IR_IS', 'THERM_C_value': 'THERM_C', 'EDA_C_value': 'EDA_C', 'HR_I_value': 'HR_IS', 'TEMP1_C_value': 'TEMP_C', 'PPG_RED_C_value': 'PPG_RED_C'}

=== MERGE SUMMARY ===
Final dataset: 67286 rows, 38 columns
Columns: ['ID', 'Condition', 'Date', 'Time', 'timestamp', 'DataSyncMarker', 'DataSyncMarker_channel_1', 'Reliability', 'PPG_GRN_C', 'PPG_RED_C', 'PPG_IR_C', 'EDA_C', 'HR_C', 'TEMP_C', 'THERM_C', 'Neon Companion_Neon Gaze_x', 'Neon Companion_Neon Gaze_y', 'Neon Companion_Neon Gaze_PupilDiameter_left', 'Neon Companion_Neon Gaze_EyeballCenterX_left', 'Neon Companion_Neon Gaze_EyeballCenterY_left', 'Neon Companion_Neon Gaze_EyeballCenterZ_left', 'Neon Companion_Neon Gaze_OpticalAxisX_left', 'Neon Companion_Neon Gaze_OpticalAxisY_left', 'Neon Companion_Neon Gaze_OpticalAxisZ_left', 'Neon Companion_Neon Gaze_PupilDiameter_right', 'Neon Companion_Neon Gaze_EyeballCenterX_right', 'Neon Companion_Neon Gaze_EyeballCenterY_right', 'Neon Companion_Neon Gaze_EyeballCenterZ_right', 'Neon Companion_Neon Gaze_OpticalAxisX_right', 'Neon Companion_Neon Gaze_OpticalAxisY_right', 'Neon Companion_Neon Gaze_OpticalAxisZ_right', 'PPG_GRN_IS', 'PPG_RED_IS', 'PPG_IR_IS', 'EDA_IS', 'HR_IS', 'TEMP_IS', 'THERM_IS']
Time range: 1469743.260 to 1472442.072
Duration: 2698.81 seconds
Participant ID: 60
Condition: Distrust Priming
Video condition: 3

=== FINAL DATA COMPLETENESS ===
DataSyncMarker: 63538/67286 (94.4% complete)
DataSyncMarker_channel_1: 63538/67286 (94.4% complete)
Reliability: 63538/67286 (94.4% complete)
PPG_GRN_C: 67286/67286 (100.0% complete)
PPG_RED_C: 67286/67286 (100.0% complete)
PPG_IR_C: 67286/67286 (100.0% complete)
EDA_C: 67286/67286 (100.0% complete)
HR_C: 67162/67286 (99.8% complete)
TEMP_C: 67286/67286 (100.0% complete)
THERM_C: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_x: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_y: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_left: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_left: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_left: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_left: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_left: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_left: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_left: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_PupilDiameter_right: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterX_right: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterY_right: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_EyeballCenterZ_right: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisX_right: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisY_right: 67286/67286 (100.0% complete)
Neon Companion_Neon Gaze_OpticalAxisZ_right: 67286/67286 (100.0% complete)
PPG_GRN_IS: 67286/67286 (100.0% complete)
PPG_RED_IS: 67286/67286 (100.0% complete)
PPG_IR_IS: 67286/67286 (100.0% complete)
EDA_IS: 67284/67286 (100.0% complete)
HR_IS: 67280/67286 (100.0% complete)
TEMP_IS: 67285/67286 (100.0% complete)
THERM_IS: 67284/67286 (100.0% complete)

============================================================
BATCH COMPLETE — 52 participant(s): [4, 6, 7, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 60]
Total rows : 4058617
Output     : all_participants_physio.csv
============================================================

In [38]:
# --- Alternative to the full process_batch() call above: reprocess just one participant ---
# combined_df = reprocess_participant(25, xdf_folder, metadata_csv, physio_output_path)

### Step 2 — Merge Survey Data

Reads the raw physio CSV and joins per-block survey scores. Output is saved to `output_path`.

In [51]:
combined_df = pd.read_csv(physio_output_path)   # always read raw physio — no survey columns
survey_df = pd.read_csv(survey_csv)
combined_df = merge_survey_data(combined_df, survey_df)
combined_df.to_csv(output_path, index=False)

=== SURVEY MERGE SUMMARY ===
  ID 4 (Distrust Priming): 3 block(s) detected
  ID 6 (Distrust Priming): 3 block(s) detected
  ID 7 (Trust Priming): 3 block(s) detected
  ID 10 (Trust Priming): 3 block(s) detected
  ID 12 (Trust Priming): 3 block(s) detected
  ID 13 (Distrust Priming): 2 block(s) detected
  ID 14 (Trust Priming): 3 block(s) detected
  ID 15 (Distrust Priming): 3 block(s) detected
  ID 16 (Trust Priming): 3 block(s) detected
  ID 17 (Distrust Priming): 3 block(s) detected
  ID 18 (Trust Priming): 3 block(s) detected
  ID 19 (Distrust Priming): 3 block(s) detected
  ID 20 (Trust Priming): 3 block(s) detected
  ID 21 (Distrust Priming): 3 block(s) detected
  ID 22 (Trust Priming): 3 block(s) detected
  ID 23 (Distrust Priming): 3 block(s) detected
  ID 24 (Trust Priming): 3 block(s) detected
  ID 25 (Distrust Priming): 3 block(s) detected  (3,330 row(s) tagged Restart, excluded)
  ID 26 (Trust Priming): 3 block(s) detected
  ID 27 (Distrust Priming): 3 block(s) detected
  ID 28 (Trust Priming): 3 block(s) detected
  ID 29 (Distrust Priming): 3 block(s) detected
  ID 30 (Trust Priming): 3 block(s) detected
  ID 31 (Distrust Priming): 3 block(s) detected
  ID 32 (Trust Priming): 3 block(s) detected
  ID 33 (Distrust Priming): 3 block(s) detected
  ID 34 (Trust Priming): 3 block(s) detected
  ID 35 (Distrust Priming): 3 block(s) detected
  ID 36 (Trust Priming): 3 block(s) detected
  ID 37 (Distrust Priming): 3 block(s) detected
  ID 38 (Trust Priming): 3 block(s) detected
  ID 39 (Distrust Priming): 3 block(s) detected
  ID 40 (Trust Priming): 3 block(s) detected
  ID 41 (Distrust Priming): 3 block(s) detected
  ID 42 (Trust Priming): 3 block(s) detected
  ID 43 (Distrust Priming): 3 block(s) detected
  ID 44 (Trust Priming): 3 block(s) detected
  ID 45 (Trust Priming): 3 block(s) detected
  ID 46 (Trust Priming): 3 block(s) detected  (9,081 row(s) tagged Restart, excluded)
  ID 47 (Distrust Priming): 3 block(s) detected
  ID 48 (Distrust Priming): 3 block(s) detected
  ID 49 (Trust Priming): 3 block(s) detected
  ID 50 (Distrust Priming): 3 block(s) detected
  ID 51 (Distrust Priming): 3 block(s) detected
  ID 52 (Trust Priming): 3 block(s) detected
  ID 53 (Distrust Priming): 3 block(s) detected
  ID 54 (Trust Priming): 3 block(s) detected
  ID 55 (Trust Priming): 3 block(s) detected
  ID 56 (Trust Priming): 3 block(s) detected
  ID 57 (Distrust Priming): 3 block(s) detected
  ID 58 (Distrust Priming): 3 block(s) detected
  ID 60 (Distrust Priming): 3 block(s) detected
  Rows with Commander data: 4,058,617 / 4,058,617
  Rows with Intelligence Support data: 4,058,577 / 4,058,617

---

## 6. Inspection & Export

### Inspect Participant

Loads a single participant and prints `DataSyncMarker` transitions to verify block labelling. Set `inspect_id` to the participant you want to check.

In [43]:
# --- Inspect a single participant ---
inspect_id = 13

df_inspect = pd.read_csv(physio_output_path)
df_inspect = df_inspect[df_inspect['ID'] == inspect_id].reset_index(drop=True)

print(f"ID={inspect_id}: {len(df_inspect)} rows")
print(f"DataSyncMarker unique values: {sorted(df_inspect['DataSyncMarker'].dropna().unique())}\n")

# Show every state transition with row index
print("DataSyncMarker transitions:")
prev = None
for i, val in df_inspect['DataSyncMarker'].items():
    val_int = int(float(val)) if pd.notna(val) else None
    if val_int != prev:
        print(f"  row {i:>6}: {prev} → {val_int}")
        prev = val_int

# Show rows around each occurrence of value 3
if 3 in df_inspect['DataSyncMarker'].values:
    rows_with_3 = df_inspect[df_inspect['DataSyncMarker'] == 3].index.tolist()
    print(f"\nValue=3 appears in {len(rows_with_3)} rows. Context around first occurrence:")
    first = rows_with_3[0]
    print(df_inspect.loc[max(0, first-3):first+3, ['DataSyncMarker', 'Reliability', 'timestamp']])

df_inspect

ID=13: 34792 rows
DataSyncMarker unique values: [np.float64(1.0), np.float64(2.0)]

DataSyncMarker transitions:
  row   3865: None → 1
  row  18979: 1 → 2
  row  27366: 2 → 1

,ID,Condition,Date,Time,timestamp,DataSyncMarker,DataSyncMarker_channel_1,Reliability,PPG_GRN_C,PPG_RED_C,...,Neon Companion_Neon Gaze_OpticalAxisX_right,Neon Companion_Neon Gaze_OpticalAxisY_right,Neon Companion_Neon Gaze_OpticalAxisZ_right,PPG_GRN_IS,PPG_RED_IS,PPG_IR_IS,EDA_IS,HR_IS,TEMP_IS,THERM_IS
0,13,Distrust Priming,2025-08-20,14:20:47.407,2924489.538,NaN,NaN,NaN,3574.0,85123.0,...,-0.126875,-0.136087,0.982503,1112.0,36615.0,127533.0,0.030147,NaN,33.880,NaN
1,13,Distrust Priming,2025-08-20,14:20:47.448,2924489.579,NaN,NaN,NaN,3605.0,85126.0,...,-0.124039,-0.133463,0.983231,1130.0,36587.0,127484.0,0.030147,NaN,33.880,30.865
2,13,Distrust Priming,2025-08-20,14:20:47.488,2924489.619,NaN,NaN,NaN,3603.0,85134.0,...,-0.126176,-0.128759,0.983579,1116.0,36584.0,127347.0,0.030147,NaN,33.880,30.865
3,13,Distrust Priming,2025-08-20,14:20:47.528,2924489.659,NaN,NaN,NaN,3592.0,85128.0,...,-0.114808,-0.126962,0.985227,1117.0,36633.0,127226.0,0.030147,NaN,33.880,30.865
4,13,Distrust Priming,2025-08-20,14:20:47.568,2924489.699,NaN,NaN,NaN,3591.0,85126.0,...,-0.127226,-0.123224,0.984158,1116.0,36647.0,127107.0,0.030147,NaN,33.948,30.975
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34787,13,Distrust Priming,2025-08-20,14:44:02.770,2925884.901,1.0,1.755715e+09,LL,3656.0,84783.0,...,0.167194,0.436725,0.883751,1062.0,41134.0,135898.0,0.030146,44.82,38.251,35.014
34788,13,Distrust Priming,2025-08-20,14:44:02.811,2925884.942,1.0,1.755715e+09,LL,3654.0,84770.0,...,0.167194,0.436725,0.883751,1047.0,41140.0,135898.0,0.030146,44.82,38.251,35.014
34789,13,Distrust Priming,2025-08-20,14:44:02.851,2925884.982,1.0,1.755715e+09,LL,3658.0,84795.0,...,0.167194,0.436725,0.883751,1061.0,41119.0,135898.0,0.030146,44.82,38.251,35.014
34790,13,Distrust Priming,2025-08-20,14:44:02.891,2925885.022,1.0,1.755715e+09,LL,3671.0,84807.0,...,0.167194,0.436725,0.883751,1064.0,41100.0,135898.0,0.030146,44.82,38.250,34.986
34791,13,Distrust Priming,2025-08-20,14:44:02.931,2925885.062,1.0,1.755715e+09,LL,3697.0,84809.0,...,0.167194,0.436725,0.883751,1064.0,41100.0,135898.0,0.030146,44.82,38.250,34.986

### Export Filtered Data

Filter `combined_df` by any column (`ID`, `Condition`, `Reliability`, etc.) and export to CSV. Uncomment the relevant example call below.

In [41]:
def export_merged_data_by_group(df, output_dir=".", **filters):
    """
    Export a filtered subset of merged_data to CSV.

    Parameters
    ----------
    df         : DataFrame  — the merged combined DataFrame (e.g. combined_df)
    output_dir : str        — directory for the exported CSV (created if needed)
    **filters  : column=value keyword filters; value may be a scalar or list
                 e.g. Condition="Trust Priming"
                      ID=[11, 23, 27]
                      Condition="Distrust Priming", ID=16
                      Reliability="HH"

    Returns
    -------
    Filtered DataFrame (also written to disk as merged_data_<filter_labels>.csv)
    """
    if not filters:
        print("No filters specified. Pass at least one keyword argument, e.g. Condition='Trust Priming'")
        return None

    mask = pd.Series(True, index=df.index)
    label_parts = []

    for col, value in filters.items():
        if col not in df.columns:
            available = [c for c in df.columns]
            print(f"WARNING: Column '{col}' not found. Available columns:\n  {available}")
            continue
        if isinstance(value, (list, tuple)):
            mask &= df[col].isin(value)
            label_parts.append(f"{col}_{'_'.join(str(v).replace(' ', '-') for v in value)}")
        else:
            mask &= df[col] == value
            label_parts.append(f"{col}_{str(value).replace(' ', '-')}")

    filtered = df[mask].reset_index(drop=True)

    if filtered.empty:
        print(f"No rows matched the specified filters: {filters}")
        return filtered

    os.makedirs(output_dir, exist_ok=True)
    filename = "merged_data_" + "__".join(label_parts) + ".csv"
    output_path = os.path.join(output_dir, filename)
    filtered.to_csv(output_path, index=False)

    print(f"Exported {len(filtered):,} rows x {len(filtered.columns)} columns")
    print(f"Filters applied : {filters}")
    if 'ID' in filtered.columns:
        ids = sorted(filtered['ID'].dropna().astype(int).unique().tolist())
        print(f"Participant IDs : {ids}")
    if 'Condition' in filtered.columns:
        print(f"Condition(s)    : {filtered['Condition'].unique().tolist()}")
    print(f"Saved to        : {output_path}")

    return filtered

In [45]:
# --- Export merged_data by group ---
# Load the combined data if not already in memory
#combined_df = pd.read_csv(output_path)

# Export a single condition
# export_merged_data_by_group(combined_df, output_dir=".", Condition="Trust Priming")
# export_merged_data_by_group(combined_df, output_dir=".", Condition="Distrust Priming")

# Export specific participant(s)
#export_merged_data_by_group(combined_df, output_dir=".", ID=13)
# export_merged_data_by_group(combined_df, output_dir=".", ID=[11, 23, 27])

# Export a condition + reliability block combo
# export_merged_data_by_group(combined_df, output_dir=".", Condition="Trust Priming", Reliability="HH")

# Export all conditions separately in a loop
# for cond in combined_df["Condition"].dropna().unique():
#     export_merged_data_by_group(combined_df, output_dir=".", Condition=cond)

Exported 34,792 rows x 69 columns
Filters applied : {'ID': 13}
Participant IDs : [13]
Condition(s)    : ['Distrust Priming']
Saved to        : ./merged_data_ID_13.csv

,ID,Condition,Date,Time,timestamp,DataSyncMarker,DataSyncMarker_channel_1,Video_Condition,Reliability,PPG_GRN_C,...,Neuroticism_IS,Openness_IS,Propensity_IS,NARS_IS,Cohesion_IS,NASA_TLX_IS,Prediction_IS,MDMT_North_IS,MDMT_South_IS,MDMT_Human_IS
0,13,Distrust Priming,2025-08-20,14:20:47.407,2924489.538,NaN,NaN,NaN,NaN,3574.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,13,Distrust Priming,2025-08-20,14:20:47.448,2924489.579,NaN,NaN,NaN,NaN,3605.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,13,Distrust Priming,2025-08-20,14:20:47.488,2924489.619,NaN,NaN,NaN,NaN,3603.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13,Distrust Priming,2025-08-20,14:20:47.528,2924489.659,NaN,NaN,NaN,NaN,3592.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,13,Distrust Priming,2025-08-20,14:20:47.568,2924489.699,NaN,NaN,NaN,NaN,3591.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34787,13,Distrust Priming,2025-08-20,14:44:02.770,2925884.901,1.0,1.755715e+09,NaN,LL,3656.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34788,13,Distrust Priming,2025-08-20,14:44:02.811,2925884.942,1.0,1.755715e+09,NaN,LL,3654.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34789,13,Distrust Priming,2025-08-20,14:44:02.851,2925884.982,1.0,1.755715e+09,NaN,LL,3658.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34790,13,Distrust Priming,2025-08-20,14:44:02.891,2925885.022,1.0,1.755715e+09,NaN,LL,3671.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34791,13,Distrust Priming,2025-08-20,14:44:02.931,2925885.062,1.0,1.755715e+09,NaN,LL,3697.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN